import { defineSpec } from '../../specs/define';
import { canvasSpecs } from '../../specs/canvasSpecs';
import { EVERYONE } from '../../auth/roles';

const pub = { roles: EVERYONE, integrations: [] as string[] };

/** Every site page renders through `useLayout(spec)`, so these arrays are the real section order. */
export const siteSpecs = {
  home: defineSpec({ ...pub, code: 'W-01', name: { es: 'Sitio · Inicio', en: 'Site · Home' },
    purpose: { es: 'La portada pública: "Muévete. Respira. Vive el presente.", Movimiento para todos, las siete clases como arcos con su título y sus palabras clave, las clases de hoy ("¿Cómo te quieres mover hoy?"), los profesores, los planes, reseñas y el primer paso (clase de prueba).', en: 'The public front page: “Move. Breathe. Live the present.”, Movement for everyone, the seven classes as arches with their title and keywords, today’s classes (“How do you want to move today?”), the teachers, the plans, reviews and the first step (a trial class).' },
    layout: ['Hero', 'Philosophy', 'Classes', 'TodayClasses', 'Teachers', 'ValueModel', 'Testimonials', 'FirstStep'],
    data: ['class_sessions', 'modalities', 'teachers', 'reviews'],
    logic: ['Sections render in the order stored by the layout editor (useLayout).', 'Today list shows only scheduled sessions for the current date.', 'Prose comes from src/tenant/brand.ts; prices from src/tenant/pricing.ts; facts from src/tenant/tenant.ts.', '0051: the class arches (ClassArch) are generated from brand.classOrder — seven, in the owner’s order, each in its D-01 tone; a real class photo uploaded in M-02d fills its arch.', 'Teachers show their initials in the tone of the class they guide until the portrait session (no generated portraits next to real names).', 'Testimonials read `reviews` with a comment and non-private visibility; the empty state says the space is pending.'],
    integrations: ['Supabase Realtime'], states: ['default', 'no classes today', 'no published reviews'] }),
  about: defineSpec({ ...pub, code: 'W-02', name: { es: 'Sitio · Sobre HOY', en: 'Site · About HOY' },
    purpose: { es: 'El texto completo de "Sobre HOY", los valores, "La filosofía de HOY" (nuestra filosofía y nuestro propósito) en panel oscuro y el tablero de marca.', en: 'The full “About HOY” text, the values, “The HOY philosophy” (our philosophy and our purpose) on a dark panel and the brand board.' },
    layout: ['Head', 'About', 'Media', 'Philosophy', 'BrandBoard'],
    data: [],
    logic: ['Every paragraph comes from src/tenant/brand.ts (transcribed from the owner’s brand manual).', 'The 4:3 media slot is a booked photograph: founders / studio interior.'],
    states: ['default'] }),
  modalities: defineSpec({ ...pub, code: 'W-03', name: { es: 'Sitio · Modalidades', en: 'Site · Modalities' },
    purpose: { es: 'Las filas del horario de las siete clases (Ligereza, Híbrido, Fuego, Sólido, Centro, Alineación, Pulso), con intensidad y duración, y el enlace a la página de cada clase.', en: 'The schedule rows of the seven classes (Ligereza, Híbrido, Fuego, Sólido, Centro, Alineación, Pulso), with intensity and duration, each linked to its class page.' },
    layout: ['PageHead', 'ModalityGrid', 'ClassLinks'], data: ['modalities'],
    logic: ['Grouped by class in brand.classOrder: the heading chip is the class name in its tone, the rows are the modalities in brand.classes[slug].modalitySlugs (one per class since 0051).', 'Each modality links to /site/classes/:slug through brand.classes[*].modalitySlugs.'],
    states: ['default'] }),
  schedule: defineSpec({ ...pub, code: 'W-04', name: { es: 'Sitio · Horario', en: 'Site · Schedule' }, checkedAt: [360, 390, 768, 1280, 1920, 3840],
    purpose: { es: 'Horario semanal público con cupos en vivo. Tocar una clase pide iniciar sesión y lleva a la app de clientes.', en: 'Public weekly schedule with live capacity. Tapping a class prompts sign-in and leads to the customer app.' },
    layout: ['PageHead', 'DayTabs', 'ClassList', 'Legend'],
    data: ['class_sessions', 'modalities', 'teachers', 'rooms'],
    logic: ['Shows 7 days starting today; Sundays show the empty state.', 'Capacity = capacity − booked_count from class_sessions.', 'Deep click → login prompt → /app (demo: switches to the customer demo user).'],
    integrations: ['Supabase Realtime', 'Supabase Auth'], states: ['default', 'day without classes', 'login prompt open'] }),
  teachers: defineSpec({ ...pub, code: 'W-05', name: { es: 'Sitio · Profesores', en: 'Site · Teachers' },
    purpose: { es: 'Los siete profesores del estudio, cada uno con la clase que guía. El retrato llega con la sesión de fotos; mientras tanto, sus iniciales en el tono de su clase.', en: 'The studio’s seven teachers, each with the class they guide. The portrait arrives with the photo session; until then, their initials in the tone of their class.' },
    layout: ['PageHead', 'TeacherGrid'], data: ['teachers', 'modalities'],
    logic: ['Only active teachers.', 'A teacher without photo_url renders the portrait-pending arch (initials in the class tone); 0051 retired the generated sample portraits, which must never stand next to a real name.', 'No star rating on the public page: a rating next to a real person is shown only where members left it (the app), never on the website.'],
    states: ['default', 'no portrait yet'] }),
  contact: defineSpec({ ...pub, code: 'W-06', name: { es: 'Sitio · Contacto', en: 'Site · Contact' },
    purpose: { es: 'WhatsApp, correo, dirección, Instagram y horario desde la configuración del tenant, el mapa del estudio y un formulario que abre WhatsApp con el mensaje listo.', en: 'WhatsApp, email, address, Instagram and hours from the tenant config, the studio map, and a form that opens WhatsApp with the message ready.' },
    layout: ['PageHead', 'ContactCards', 'Specials', 'Map', 'Form'], data: ['tenants'],
    logic: ['No hardcoded contact data: reads useContact() (M-08a, src/tenant/tenant.ts as the default) and labels only the fields not confirmed yet as pending (0051: all four confirmed — WhatsApp Business, the address with its landmark, info@humanclub.com and @hoyhumanclub).', 'MapSlot reads the contact location (address label + Google Maps link); provider stays "none" so the page makes no network request.', 'The form has no backend: it builds a wa.me deep link with the message prefilled.', 'Especiales (0017): private events, birthdays, team sessions and special requests are arranged directly with the studio — a card that opens WhatsApp with the request prefilled.'],
    integrations: ['WhatsApp'], states: ['default', 'form empty', 'form filled'] }),
  classes: defineSpec({ ...pub, code: 'W-07', name: { es: 'Sitio · Clases', en: 'Site · Classes' },
    purpose: { es: 'La introducción "Nuestras clases" (no venimos a entrenar cuerpos, venimos a despertar presencia) y una fila por cada una de las siete clases: concepto, intención, clave, mensajes y método, con su arco.', en: 'The “Our classes” introduction (we are not here to train bodies, we are here to awaken presence) and one row for each of the seven classes: concept, intention, keys, messages and method, with its arch.' },
    layout: ['PageHead', 'Intro', 'ClassList', 'CTA'], data: ['modalities'],
    logic: ['Cards are generated from brand.classOrder; nothing is written twice.', 'Each card links to /site/classes/:slug and carries its class tone.'],
    states: ['default'] }),
  classDetail: defineSpec({ ...pub, code: 'W-08', name: { es: 'Sitio · Clase', en: 'Site · Class' },
    purpose: { es: 'Una de las siete clases completa: frase, concepto, intención, clave, mensajes y método; los datos de su fila del horario, quién la guía, qué traer, el enlace al horario y la llamada a la clase de prueba.', en: 'One of the seven classes in full: line, concept, intention, keys, messages and method; the facts of its schedule row, who guides it, what to bring, the link into the schedule and the trial-class call to action.' },
    layout: ['Hero', 'Essay', 'Facts', 'Bring', 'Other', 'CTA'], data: ['modalities'],
    logic: ['Slug is validated against brand.classOrder; an unknown slug renders the not-found state with links to every class.', 'Facts (duration, intensity, heated) join `modalities` through brand.classes[slug].modalitySlugs — when no modality matches, the page says the practice lives inside the guided classes.', '"What to bring" is derived from the class’s bring keys (0051: the FAQ’s list — the studio provides mat and props; towel and bottle optional).'],
    states: ['default', 'no matching modality', 'unknown slug'] }),
  // 0019 — the public account-deletion request Google Play requires at a URL with no sign-in.
  deleteAccount: defineSpec({ ...pub, code: 'W-09', name: { es: 'Sitio · Eliminar cuenta', en: 'Site · Delete account' },
    purpose: { es: 'Pedir la eliminación de una cuenta sin iniciar sesión: correo o WhatsApp, motivo opcional, y la explicación en lenguaje llano de qué se conserva por ley y qué se elimina. Es la URL pública que exige Google Play; la app la ofrece también en Perfil → Cuenta y datos (C-26).', en: 'Request an account deletion with no sign-in: email or WhatsApp, optional reason, and a plain-words explanation of what is kept by law and what is removed. It is the public URL Google Play requires; the app also offers it under Profile → Account & data (C-26).' },
    layout: ['PageHead', 'WhatHappens', 'Form'],
    data: ['deletion_requests', 'audit_log', 'tenants'],
    logic: [
      'Submit inserts one deletion_requests row with user_id null, channel website, status requested, plus an audit_log row with actor null (role public). At least one contact (valid email or a 10-digit phone) is required; the "I understand" switch gates the button.',
      'Nothing is deleted here: admin matches the contact to a member in M-11 and the anonymisation runs server-side. The success state shows the last six characters of the row id as a reference.',
      'The controller name and the studio email come from M-08 (tenants.settings) with tenant.ts as fallback; the retention wording matches the privacy policy §6–§7 (A-06) without typing a number.',
    ],
    states: ['default', 'validation: no contact', 'validation: bad email / phone', 'switch off → button disabled', 'sent (reference shown)'] }),
  // 0051 — the public FAQ: the owner's verified questions, read from the same rows as the app's C-14 / C-15.
  faq: defineSpec({ ...pub, code: 'W-10', name: { es: 'Sitio · Preguntas frecuentes', en: 'Site · FAQ' },
    purpose: { es: 'Las preguntas frecuentes del estudio en cinco temas (clases y precios; reservas, cancelaciones y no-show; tarjetas de regalo; pagos; qué traer y el espacio), con búsqueda, índice de temas y tablas de precios en vivo.', en: 'The studio’s frequently asked questions in five topics (classes and prices; booking, cancellation and no-show; gift cards; payments; what to bring and the space), with search, a topic index and live price tables.' },
    layout: ['PageHead', 'Search', 'Groups', 'Contact'],
    data: ['faq_entries'],
    logic: [
      'Reads published faq_entries in sort order and groups them by group_key — the rows C-14 / C-15 read and M-02c edits, so the site and the app never disagree.',
      'A `{{pricing:<families>}}` line in an answer renders a live PriceTable from src/tenant/pricing.ts (FaqAnswer); numbers in sentences were filled from pricing.ts and the M-08 defaults at seed time.',
      'Search folds accents and case over the question and the answer (prices written out); matches open their answers; zero matches offer a WhatsApp handoff (support intent) with the search prefilled.',
      'The page publishes schema.org FAQPage JSON-LD in the reader’s language.',
    ],
    integrations: ['WhatsApp'], states: ['default', 'search: matches (answers open)', 'search: no matches', 'loading'] }),
  /** P-01 keeps its canvas code; only the layout, data and logic are brought up to what the page renders. */
  plans: defineSpec({
    ...canvasSpecs['P-01'],
    name: { es: 'Planes y precios', en: 'Plans & prices' },
    layout: ['PageHead', 'Families', 'Specials', 'Questions', 'Discipline', 'TaxNote'],
    data: [...new Set([...(canvasSpecs['P-01'].data ?? []), 'tenants'])],
    logic: [
      'Reads only src/tenant/pricing.ts for prices, names and the per-family rationale (FAMILY_RATIONALE). 0051: the verified launch list — trial and individual class, the 12-class package (and its Santa María Tennis Club price), private classes and gift cards; no memberships, no credits.',
      'The 12-class package cards (PackageCard) state the M-08 freeze rule (usePolicy: freezesPerPackage, freezeMaxDays) and the validity from pricing.ts.',
      'The studio rental and corporate experiences are on request (ON_REQUEST_FAMILIES): formats, no price, a WhatsApp handoff.',
      'The discipline band reads DISCIPLINE, whose numbers come from tenant.studio and the private-class rule.',
      'The IVA note reads the M-08 tax policy through usePolicy() (src/modules/admin/settings.ts), read-only.',
      'Especiales (0017): private events, birthdays, team sessions and special requests are not sold here — the Specials note sends the reader to WhatsApp (tenant.contact) and the desk prices them by hand in S-04.',
    ],
    states: ['default', 'IVA included', 'IVA added at checkout', 'freeze rule from M-08'],
  }),
};
