import { defineSpec } from '../../specs/define';
import { canvasSpecs } from '../../specs/canvasSpecs';
import { EVERYONE } from '../../auth/roles';

const pub = { roles: EVERYONE, integrations: [] as string[] };

/** Every site page renders through `useLayout(spec)`, so these arrays are the real section order. */
export const siteSpecs = {
  home: defineSpec({ ...pub, code: 'W-01', name: { es: 'Sitio · Inicio', en: 'Site · Home' },
    purpose: { es: 'La portada pública: el manifiesto de marca, los cuatro movimientos, las cinco clases, las clases de hoy, el modelo de valor, la filosofía, los profesores, reseñas reales y el primer paso (clase de prueba).', en: 'The public front page: the brand manifesto, the four movements, the five classes, today’s classes, the value model, the philosophy, the teachers, real reviews and the first step (a trial class).' },
    layout: ['Hero', 'Movements', 'Classes', 'TodayClasses', 'ValueModel', 'Philosophy', 'Teachers', 'Testimonials', 'FirstStep'],
    data: ['class_sessions', 'modalities', 'teachers', 'reviews'],
    logic: ['Sections render in the order stored by the layout editor (useLayout).', 'Today list shows only scheduled sessions for the current date.', 'Prose comes from src/tenant/brand.ts; prices from src/tenant/pricing.ts; facts from src/tenant/tenant.ts.', 'Testimonials read `reviews` with a comment and non-private visibility; the empty state says the space is pending.'],
    integrations: ['Supabase Realtime'], states: ['default', 'no classes today', 'no published reviews'] }),
  about: defineSpec({ ...pub, code: 'W-02', name: { es: 'Sitio · Sobre HOY', en: 'Site · About HOY' },
    purpose: { es: 'El texto completo de "Sobre HOY", los cuatro valores, la filosofía en panel oscuro y el tablero de marca.', en: 'The full “About HOY” text, the four values, the philosophy on a dark panel and the brand board.' },
    layout: ['Head', 'About', 'Values', 'Media', 'Philosophy', 'BrandBoard'],
    data: [],
    logic: ['Every paragraph comes from src/tenant/brand.ts (transcribed from the owner’s brand manual).', 'The 4:3 media slot is a booked photograph: founders / studio interior.'],
    states: ['default'] }),
  modalities: defineSpec({ ...pub, code: 'W-03', name: { es: 'Sitio · Modalidades', en: 'Site · Modalities' },
    purpose: { es: 'Las prácticas del horario agrupadas por movimiento, con intensidad, duración y sala caliente — y el enlace al ensayo de la clase a la que pertenece cada una.', en: 'The scheduled practices grouped by movement, with intensity, duration and heated room — each cross-linked to the class essay it belongs to.' },
    layout: ['PageHead', 'ModalityGrid', 'ClassLinks'], data: ['modalities'],
    logic: ['Groups by movement in the order Enraíza, Fluye, Arde, Libera.', 'Each modality links to /site/classes/:slug through brand.classes[*].modalitySlugs.'],
    states: ['default'] }),
  schedule: defineSpec({ ...pub, code: 'W-04', name: { es: 'Sitio · Horario', en: 'Site · Schedule' },
    purpose: { es: 'Horario semanal público con cupos en vivo. Tocar una clase pide iniciar sesión y lleva a la app de clientes.', en: 'Public weekly schedule with live capacity. Tapping a class prompts sign-in and leads to the customer app.' },
    layout: ['PageHead', 'DayTabs', 'ClassList', 'Legend'],
    data: ['class_sessions', 'modalities', 'teachers', 'rooms'],
    logic: ['Shows 7 days starting today; Sundays show the empty state.', 'Capacity = capacity − booked_count from class_sessions.', 'Deep click → login prompt → /app (demo: switches to the customer demo user).'],
    integrations: ['Supabase Realtime', 'Supabase Auth'], states: ['default', 'day without classes', 'login prompt open'] }),
  teachers: defineSpec({ ...pub, code: 'W-05', name: { es: 'Sitio · Profesores', en: 'Site · Teachers' },
    purpose: { es: 'Galería pública de profesores con retrato (hueco de foto reservado), bio y especialidades.', en: 'Public teacher gallery with a portrait (a booked photo slot), bio and specialties.' },
    layout: ['PageHead', 'TeacherGrid'], data: ['teachers', 'modalities'],
    logic: ['Only active teachers.', 'A teacher without photo_url renders a 4:3 MediaSlot instead of an empty avatar.'],
    states: ['default', 'no portrait yet'] }),
  contact: defineSpec({ ...pub, code: 'W-06', name: { es: 'Sitio · Contacto', en: 'Site · Contact' },
    purpose: { es: 'WhatsApp, correo, dirección, Instagram y horario desde la configuración del tenant, el mapa del estudio y un formulario que abre WhatsApp con el mensaje listo.', en: 'WhatsApp, email, address, Instagram and hours from the tenant config, the studio map, and a form that opens WhatsApp with the message ready.' },
    layout: ['PageHead', 'ContactCards', 'Specials', 'Map', 'Form'], data: ['tenants'],
    logic: ['No hardcoded contact data: reads src/tenant/tenant.ts and labels every placeholder as pending.', 'MapSlot reads tenant.location; provider stays "none" so the page makes no network request.', 'The form has no backend: it builds a wa.me deep link with the message prefilled.', 'Especiales (0017): private events, birthdays, team sessions and special requests are arranged directly with the studio — a card that opens WhatsApp with the request prefilled.'],
    integrations: ['WhatsApp'], states: ['default', 'form empty', 'form filled'] }),
  classes: defineSpec({ ...pub, code: 'W-07', name: { es: 'Sitio · Clases', en: 'Site · Classes' },
    purpose: { es: 'La introducción "Nuestras clases" y una tarjeta rica por clase (hot yoga, barre, pilates, meditación, respiración) con su hueco de foto 16:9.', en: 'The “Our classes” introduction and one rich card per class (hot yoga, barre, pilates, meditation, breathwork), each with its 16:9 photo slot.' },
    layout: ['PageHead', 'Intro', 'ClassList', 'CTA'], data: ['modalities'],
    logic: ['Cards are generated from brand.classOrder; nothing is written twice.', 'Each card links to /site/classes/:slug and carries its movement colour.'],
    states: ['default'] }),
  classDetail: defineSpec({ ...pub, code: 'W-08', name: { es: 'Sitio · Clase', en: 'Site · Class' },
    purpose: { es: 'El ensayo completo de una clase, los datos de la modalidad que le corresponde, qué traer, el enlace al horario y la llamada a la clase de prueba.', en: 'One class’s full essay, the facts of its matching modality, what to bring, the link into the schedule and the trial-class call to action.' },
    layout: ['Hero', 'Essay', 'Facts', 'Bring', 'Other', 'CTA'], data: ['modalities'],
    logic: ['Slug is validated against brand.classOrder; an unknown slug renders the not-found state with links to every class.', 'Facts (duration, intensity, heated) join `modalities` through brand.classes[slug].modalitySlugs — when no modality matches, the page says the practice lives inside the guided classes.', '"What to bring" is derived from the class’s bring keys; heated classes always list towel and water.'],
    states: ['default', 'no matching modality', 'unknown slug'] }),
  /** P-01 keeps its canvas code; only the layout, data and logic are brought up to what the page renders. */
  plans: defineSpec({
    ...canvasSpecs['P-01'],
    layout: ['PageHead', 'Families', 'Specials', 'Discipline', 'TaxNote'],
    data: [...new Set([...(canvasSpecs['P-01'].data ?? []), 'tenants'])],
    logic: [
      'Reads only src/tenant/pricing.ts for prices, names and the per-family rationale (FAMILY_RATIONALE).',
      'The discipline band reads DISCIPLINE, whose numbers come from tenant.studio and the number of plan families.',
      'The IVA note reads the M-08 tax policy through usePolicy() (src/modules/admin/settings.ts), read-only.',
      'Especiales (0017): private events, birthdays, team sessions and special requests are not sold here — the Specials note sends the reader to WhatsApp (tenant.contact) and the desk prices them by hand in S-04.',
    ],
    states: ['default', 'IVA included', 'IVA added at checkout'],
  }),
};
