import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'site.nav.home': { es: 'Inicio', en: 'Home' },
  'site.nav.about': { es: 'Filosofía', en: 'Philosophy' },
  'site.nav.modalities': { es: 'Modalidades', en: 'Modalities' },
  'site.nav.schedule': { es: 'Horario', en: 'Schedule' },
  'site.nav.teachers': { es: 'Profesores', en: 'Teachers' },
  'site.nav.plans': { es: 'Planes', en: 'Plans' },
  'site.nav.contact': { es: 'Contacto', en: 'Contact' },
  'site.nav.signin': { es: 'Entrar', en: 'Sign in' },
  'site.nav.book': { es: 'Reservar clase', en: 'Book a class' },
  'site.hero.eyebrow': { es: 'Human club · {city}', en: 'Human club · {city}' },
  'site.hero.title': { es: 'Hoy es un buen día para volver al cuerpo.', en: 'Today is a good day to come back to the body.' },
  'site.hero.body': { es: 'Un club de bienestar con {mats} mats, cuatro clases al día y cuatro formas de moverte: Enraíza, Fluye, Arde y Libera.', en: 'A wellness club with {mats} mats, four classes a day and four ways to move: Enraíza, Fluye, Arde and Libera.' },
  'site.hero.cta': { es: 'Clase de prueba', en: 'Trial class' },
  'site.hero.cta2': { es: 'Ver horario', en: 'See schedule' },
  'site.movements.title': { es: 'Cuatro movimientos', en: 'Four movements' },
  'site.movements.body': { es: 'Cada clase pertenece a un movimiento. Elige cómo quieres sentirte hoy y el horario se ordena para ti.', en: 'Every class belongs to a movement. Choose how you want to feel today and the schedule sorts itself for you.' },
  'site.mv.enraiza': { es: 'Fuerza, centro, control. Pilates y barre.', en: 'Strength, core, control. Pilates and barre.' },
  'site.mv.fluye': { es: 'Respiración y movimiento continuo. Flow.', en: 'Breath and continuous movement. Flow.' },
  'site.mv.arde': { es: 'Calor, sudor, foco. Hot yoga.', en: 'Heat, sweat, focus. Hot yoga.' },
  'site.mv.libera': { es: 'Soltar, quedarse quieto. Yin y meditación.', en: 'Let go, stay still. Yin and meditation.' },
  'site.today.title': { es: 'Hoy en el club', en: 'Today at the club' },
  'site.today.empty': { es: 'Hoy descansamos. Mira el horario de la semana.', en: 'We rest today. See the week’s schedule.' },
  'site.plans.title': { es: 'Planes claros', en: 'Clear plans' },
  'site.plans.body': { es: 'Una clase de prueba para empezar, paquetes para ir a tu ritmo o membresía para vivirlo completo.', en: 'A trial class to begin, packs to go at your pace, or a membership to live it fully.' },
  'site.plans.all': { es: 'Ver todos los planes', en: 'See all plans' },
  'site.teachers.title': { es: 'Profesores', en: 'Teachers' },
  'site.teachers.body': { es: 'Personas que enseñan desde la práctica, no desde el guion.', en: 'People who teach from practice, not from a script.' },
  'site.about.title': { es: 'Filosofía', en: 'Philosophy' },
  'site.about.p1': { es: 'HOY es un club humano. Un lugar para volver al cuerpo, sin prisa, sin ruido. Practicamos con humor y con rigor, en una sala que se siente como casa.', en: 'HOY is a human club. A place to come back to the body, without hurry, without noise. We practise with humour and rigour, in a room that feels like home.' },
  'site.about.p2': { es: 'Somos cercanos, sensoriales y contemporáneos. Hablamos directo y estamos presentes. Cada clase empieza con una pregunta: ¿cómo quieres sentirte hoy?', en: 'We are close, sensorial and contemporary. We speak directly and we are present. Every class begins with a question: how do you want to feel today?' },
  'site.about.values': { es: 'Humana · Cercana · Directa · Presente', en: 'Human · Close · Direct · Present' },
  'site.modalities.title': { es: 'Modalidades', en: 'Modalities' },
  'site.modalities.body': { es: 'Seis prácticas, cuatro movimientos, una sala.', en: 'Six practices, four movements, one room.' },
  'site.modalities.intensity': { es: 'Intensidad', en: 'Intensity' },
  'site.modalities.heated': { es: 'Sala caliente', en: 'Heated room' },
  'site.schedule.title': { es: 'Horario', en: 'Schedule' },
  'site.schedule.body': { es: 'Cuatro clases al día, {mats} mats, una clase por persona al día. Toca una clase para reservar.', en: 'Four classes a day, {mats} mats, one class per person per day. Tap a class to book.' },
  'site.schedule.loginTitle': { es: 'Para reservar, entra a tu cuenta', en: 'Sign in to book' },
  'site.schedule.loginBody': { es: 'Reservar y pagar ocurre dentro de la app. En esta demo, entrar te lleva a la app de clientes como {name}.', en: 'Booking and paying happen inside the app. In this demo, signing in takes you to the customer app as {name}.' },
  'site.schedule.loginCta': { es: 'Entrar y reservar', en: 'Sign in and book' },
  'site.schedule.legend': { es: 'Leyenda', en: 'Legend' },
  'site.contact.title': { es: 'Contacto', en: 'Contact' },
  'site.contact.body': { es: 'Escríbenos por WhatsApp o ven a conocer la sala.', en: 'Write to us on WhatsApp or come see the room.' },
  'site.contact.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'site.contact.email': { es: 'Correo', en: 'Email' },
  'site.contact.address': { es: 'Dirección', en: 'Address' },
  'site.contact.hours': { es: 'Horario de atención', en: 'Opening hours' },
  'site.legal.terms': { es: 'Términos y condiciones', en: 'Terms & conditions' },
  'site.legal.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },
  'site.legal.updated': { es: 'Última actualización: {date} · versión {v}', en: 'Last updated: {date} · version {v}' },
  'site.legal.draft': { es: 'Borrador. Este texto será reemplazado por el documento legal revisado. Incluye las secciones exigidas por la Ley 1581 de 2012 y el Decreto 1377 de 2013.', en: 'Draft. This text will be replaced by the reviewed legal document. It includes the sections required by Ley 1581 de 2012 and Decreto 1377 de 2013.' },
  'site.footer.rights': { es: '© {year} {name}. Todos los derechos reservados.', en: '© {year} {name}. All rights reserved.' },
  'site.footer.hub': { es: 'Hub de pruebas', en: 'Testing hub' },
};
