import type { StringTable } from '../../i18n/types';

/**
 * Website copy. Long-form brand prose (manifesto, "Sobre HOY", philosophy, class essays) lives in
 * `src/tenant/brand.ts`; this table holds the UI around it — labels, headings, CTAs and notes.
 * Namespaces: site.nav · site.hero · site.today · site.classes ·
 * site.value · site.philosophy · site.testimonials · site.first · site.about ·
 * site.modalities · site.schedule · site.teachers · site.plans · site.contact · site.legal · site.footer
 */
export const strings: StringTable = {
  'site.calendar.prev': { es: "Período anterior", en: "Previous period" },
  'site.calendar.next': { es: "Período siguiente", en: "Next period" },
  'site.calendar.view': { es: "Vista del calendario", en: "Calendar view" },
  'site.calendar.day': { es: "Día", en: "Day" },
  'site.calendar.week': { es: "Semana", en: "Week" },
  'site.calendar.month': { es: "Mes", en: "Month" },
  'site.calendar.date': { es: "Ir a una fecha", en: "Go to date" },
  'site.calendar.classes': { es: "{n} clases", en: "{n} classes" },
  'site.calendar.more': { es: "+ {n} más", en: "+ {n} more" },
  'site.calendar.noClasses': { es: "Sin clases", en: "No classes" },
  'site.calendar.empty': { es: "No hay clases publicadas para esta fecha. Explora otro día.", en: "No classes published for this date. Explore another day." },
  'site.calendar.note': { es: "Elige una clase para ver sus detalles.", en: "Choose a class to see its details." },
  'site.calendar.weekStrip': { es: "Días de la semana", en: "Days of the week" },
  'site.calendar.monthGrid': { es: "Días del mes", en: "Days of the month" },
  'site.mat.eyebrow': { es: "Tu lugar en el salón", en: "Your place in the room" },
  'site.mat.title': { es: "Elige tu mat", en: "Choose your mat" },
  'site.mat.layout': { es: "{n} mats · {rows} filas", en: "{n} mats · {rows} rows" },
  'site.mat.front': { es: "Frente · profesor", en: "Front · teacher" },
  'site.mat.row': { es: "Fila {n}", en: "Row {n}" },
  'site.mat.rowRange': { es: "mats {from}–{to}", en: "mats {from}–{to}" },
  'site.mat.entry': { es: "Entrada al salón", en: "Studio entrance" },
  'site.mat.room': { es: "Sala principal", en: "Main studio" },
  'site.mat.available': { es: "Disponible", en: "Available" },
  'site.mat.selected': { es: "Tu elección", en: "Your choice" },
  'site.mat.occupied': { es: "Ocupado", en: "Occupied" },
  'site.mat.number': { es: "Mat {n}", en: "Mat {n}" },
  'site.mat.occupiedLabel': { es: "Mat {n}, no disponible", en: "Mat {n}, unavailable" },
  'site.mat.chosen': { es: "Mat {n} seleccionado. Se reserva al confirmar.", en: "Mat {n} selected. Reserved when you confirm." },
  'site.mat.hint': { es: "Selecciona un mat disponible. Tu elección se confirma al finalizar la reserva.", en: "Select an available mat. Your choice is confirmed when you finish booking." },
  'site.mat.continue': { es: "Continuar con la reserva", en: "Continue booking" },
  'site.mat.error': { es: "Ese mat ya no está disponible. Elige otro para continuar.", en: "That mat is no longer available. Choose another to continue." },
  'site.mat.confirmed': { es: "Tu lugar: mat {n}", en: "Your place: mat {n}" },
  'site.plans.club': { es: "Membresía del club", en: "Club membership" },
  'site.plans.monthRitual': { es: "Un mes para ti", en: "A month for yourself" },
  'site.plans.yearRitual': { es: "Un año de bienestar", en: "A year of wellbeing" },
  'site.plans.save': { es: "Ahorras {amount} frente a 12 pagos mensuales.", en: "Save {amount} compared with 12 monthly payments." },
  'site.plans.monthlyNote': { es: "Pago mensual. Encuentra tu propio ritmo.", en: "Billed monthly. Find your own rhythm." },
  'site.plans.daily': { es: "Hasta {n} clase por día", en: "Up to {n} class per day" },
  'site.plans.practices': { es: "Acceso a todas las prácticas", en: "Access to every practice" },
  'site.plans.matBenefit': { es: "Elige tu mat al reservar yoga", en: "Choose your mat when booking yoga" },
  'site.plans.choose': { es: "Elegir {name}", en: "Choose {name}" },
  'site.plans.membershipTitle': { es: "Haz del bienestar tu ritual.", en: "Make wellbeing your ritual." },
  'site.plans.membershipBody': { es: "Dos formas de pertenecer. Todo el espacio para volver a ti.", en: "Two ways to belong. All the space to return to yourself." },
  'site.plans.passesTitle': { es: "A tu ritmo.", en: "At your own pace." },
  'site.plans.passesBody': { es: "Una primera visita o unas cuantas más. Tú eliges cómo empezar.", en: "A first visit or a few more. You choose how to begin." },
  'site.plans.classCount': { es: "{n} clase(s)", en: "{n} class(es)" },
  'site.plans.validity': { es: "Vigencia: {n} días · COP", en: "Valid for {n} days · COP" },
  'site.plans.select': { es: "Elegir pase", en: "Choose pass" },
  'site.plans.pausasBody': { es: "Un momento para bajar el ritmo y respirar.", en: "A moment to slow down and breathe." },
  'site.plans.regalosBody': { es: "Comparte un poco de bienestar con alguien.", en: "Share a little wellbeing with someone." },
  'site.plans.spaceTitle': { es: "Un espacio para tus ideas.", en: "Space for your ideas." },
  'site.plans.spaceBody': { es: "Producciones, encuentros y experiencias privadas. Coordinamos cada detalle contigo.", en: "Productions, gatherings and private experiences. We arrange every detail with you." },
  'site.plans.visitLabel': { es: "Tu próxima visita", en: "Your next visit" },
  'site.plans.visitTitle': { es: "Aquí hay un lugar para ti.", en: "There is a place for you here." },
  'site.plans.visitBody': { es: "Un salón con {n} mats. Encuentra tu clase y elige dónde quieres estar.", en: "A studio with {n} mats. Find your class and choose where you want to be." },

  'site.new.planLabel0': { es: 'Empieza aquí', en: 'Start here' },
  'site.new.planLabel1': { es: 'Tu ritual', en: 'Your ritual' },
  'site.new.planLabel2': { es: 'Una pausa', en: 'A pause' },
  "site.edition.label": { es: "Versiones", en: "Versions" },
  "site.edition.new": { es: "V2 · Santuario", en: "V2 · Sanctuary" },
  "site.edition.classic": { es: "V1 · Original", en: "V1 · Original" },
  "site.edition.history": { es: "Historia de versiones", en: "Version history" },
  "site.edition.release": { es: "25 sep 2026 · Arte y materiales", en: "25 Sep 2026 · Art & materials" },
  "site.new.eyebrow": { es: "LA VIDA ES {name}", en: "LIFE IS {name}" },
  "site.new.title": { es: "Tu espacio,", en: "Your space," },
  "site.new.title2": { es: "tu tiempo.", en: "your time." },
  "site.new.body": { es: "Un lugar para moverte, respirar, reconectar y sentir una vida más tuya.", en: "A place to move, breathe, reconnect, and feel more like yourself." },
  "site.new.book": { es: "Reserva tu clase", en: "Book your class" },
  "site.new.explore": { es: "Explora el club", en: "Explore the club" },
  "site.new.scroll": { es: "Un momento para ti", en: "A moment for yourself" },
  "site.new.ambient": { es: "Pausar movimiento", en: "Pause motion" },
  "site.new.static": { es: "Activar movimiento", en: "Enable motion" },
  "site.new.philosophyTitle": { es: "No tienes que ir más lejos.", en: "You don’t have to go further." },
  "site.new.philosophyEm": { es: "Solo volver a ti.", en: "Just back to yourself." },
  "site.new.philosophyBody": { es: "Entre todo lo que haces, también hay espacio para ti. Para respirar sin prisa, sentir tu cuerpo y encontrar tu propio ritmo.", en: "Among everything you do, there is room for you, too. To breathe without rushing, feel your body, and find your own rhythm." },
  "site.new.chapter2": { es: "01 / TU PRÁCTICA", en: "01 / YOUR PRACTICE" },
  "site.new.chapter3": { es: "02 / NOS ENCONTRAMOS", en: "02 / WE MEET" },
  "site.new.classesTitle": { es: "Muévete como te sientes.", en: "Move the way you feel." },
  "site.new.classesBody": { es: "Fuerza, fluidez o una pausa. No hay una sola forma de empezar.", en: "Strength, flow, or a pause. There is more than one way to begin." },
  "site.new.scheduleTitle": { es: "Hazle espacio a tu día.", en: "Make room in your day." },
  "site.new.scheduleBody": { es: "Tu próxima pausa empieza aquí.", en: "Your next pause starts here." },
  "site.new.teachersTitle": { es: "Personas que te acompañan.", en: "People who move with you." },
  "site.new.teachersBody": { es: "Cada práctica, una forma de conectar. Conoce a quienes te guían.", en: "Every practice is a way to connect. Meet the people who guide you." },
  "site.new.plansTitle": { es: "Un comienzo a tu medida.", en: "A beginning that fits you." },
  "site.new.plansBody": { es: "Empieza con una clase. Encuentra tu ritmo.", en: "Start with a class. Find your rhythm." },
  "site.new.philosophyLabel": { es: "NUESTRA FILOSOFÍA", en: "OUR PHILOSOPHY" },
  "site.new.community": { es: "Más que una práctica. Un lugar al que pertenecer.", en: "More than a practice. A place to belong." },
  "site.new.endTitle": { es: "Lo que necesitas", en: "What you need" },
  "site.new.endEm": { es: "empieza hoy.", en: "starts today." },
  "site.new.endBody": { es: "Ven tal como eres. Nosotros te acompañamos.", en: "Come as you are. We’ll be here with you." },
  "site.new.demo": { es: "Contenido e imágenes de concepto · horarios, equipo y precios de demostración.", en: "Concept content and imagery · demonstration schedules, team and pricing." },
  "site.new.portraitPending": { es: "Retrato por confirmar", en: "Portrait to be confirmed" },
  "site.new.artAlt": { es: "Concepto de un santuario de yoga con arcos y luz natural", en: "Concept yoga sanctuary with arches and natural light" },
  "site.new.philosophyAlt": { es: "Una pausa al sol frente a las montañas", en: "A pause in the sunlight facing the mountains" },
  "site.new.ritualAlt": { es: "Estudio tropical de yoga con jardín en Medellín", en: "Tropical yoga studio with a garden in Medellín" },
  "site.new.visit": { es: "Te esperamos.", en: "We’ll see you here." },
  "site.new.firstClass": { es: "Tu primera clase", en: "Your first class" },
  'site.nav.home': { es: 'Inicio', en: 'Home' },
  'site.nav.about': { es: 'Sobre HOY', en: 'About' },
  'site.nav.classes': { es: 'Clases', en: 'Classes' },
  'site.nav.modalities': { es: 'Modalidades', en: 'Modalities' },
  'site.nav.schedule': { es: 'Horario', en: 'Schedule' },
  'site.nav.teachers': { es: 'Profesores', en: 'Teachers' },
  'site.nav.plans': { es: 'Planes', en: 'Plans' },
  'site.nav.contact': { es: 'Contacto', en: 'Contact' },
  'site.nav.label': { es: 'Sitio', en: 'Site' },
  'site.nav.signin': { es: 'Entrar', en: 'Sign in' },
  'site.nav.book': { es: 'Reservar clase', en: 'Book a class' },

  'site.hero.eyebrow': { es: 'Human club · {city}', en: 'Human club · {city}' },
  'site.hero.body': { es: 'Un santuario urbano en {city}: {mats} tapetes, {classes} clases al día y cuatro formas de moverte. Sin experiencia previa, sin prisa.', en: 'An urban sanctuary in {city}: {mats} mats, {classes} classes a day and four ways to move. No previous experience, no hurry.' },
  'site.hero.cta': { es: 'Clase de prueba · {price}', en: 'Trial class · {price}' },
  'site.hero.cta2': { es: 'Ver horario', en: 'See schedule' },
  'site.hero.media': { es: 'Video de portada del estudio', en: 'Studio hero video' },


  'site.today.title': { es: 'Hoy en el club', en: 'Today at the club' },
  'site.today.empty': { es: 'Hoy descansamos. Mira el horario de la semana.', en: 'We rest today. See the week’s schedule.' },
  'site.today.done': { es: 'Las clases de hoy ya terminaron. Mañana seguimos: mira el horario.', en: 'Today’s classes are done. We continue tomorrow: see the schedule.' },
  'site.today.all': { es: 'Ver la semana completa', en: 'See the whole week' },

  'site.classes.title': { es: 'Nuestras clases', en: 'Our classes' },
  'site.classes.all': { es: 'Ver todas las clases', en: 'See all classes' },
  'site.classes.read': { es: 'Leer más', en: 'Read more' },
  'site.classes.media': { es: 'Foto de {name}', en: '{name} photograph' },
  'site.classes.facts': { es: 'La clase en datos', en: 'The class in numbers' },
  'site.classes.duration': { es: 'Duración', en: 'Duration' },
  'site.classes.intensity': { es: 'Intensidad', en: 'Intensity' },
  'site.classes.room': { es: 'Sala', en: 'Room' },
  'site.classes.roomHot': { es: 'Caliente, a propósito', en: 'Heated, on purpose' },
  'site.classes.roomTemperate': { es: 'Temperatura ambiente', en: 'Room temperature' },
  'site.classes.movement': { es: 'Movimiento', en: 'Movement' },
  'site.classes.factsPending': { es: 'Esta práctica todavía no tiene una modalidad propia en el horario: hoy se vive dentro de las clases guiadas.', en: 'This practice does not have its own modality in the schedule yet: today it lives inside the guided classes.' },
  'site.classes.bring': { es: 'Qué traer', en: 'What to bring' },
  'site.classes.bring.towel': { es: 'Toalla — la sala es caliente y vas a sudar.', en: 'A towel — the room is heated and you will sweat.' },
  'site.classes.bring.water': { es: 'Agua — hidrátate antes, durante y después.', en: 'Water — drink before, during and after.' },
  'site.classes.bring.socks': { es: 'Medias con agarre (las vendemos en recepción).', en: 'Grip socks (we sell them at the front desk).' },
  'site.classes.bring.comfy': { es: 'Ropa cómoda en la que puedas respirar.', en: 'Comfortable clothes you can breathe in.' },
  'site.classes.bring.layers': { es: 'Una capa extra: al quedarte quieto, el cuerpo se enfría.', en: 'An extra layer: the body cools down when you stay still.' },
  'site.classes.bring.nothing': { es: 'Nada más. Los tapetes y los props son del estudio.', en: 'Nothing else. Mats and props are the studio’s.' },
  'site.classes.schedule': { es: 'Ver esta clase en el horario', en: 'See this class in the schedule' },
  'site.classes.other': { es: 'Otras formas de moverte', en: 'Other ways to move' },
  'site.classes.back': { es: 'Todas las clases', en: 'All classes' },
  'site.classes.notFound': { es: 'No encontramos esa clase. Mira todas las formas de moverte en HOY.', en: 'We could not find that class. Take a look at every way to move at HOY.' },

  'site.value.title': { es: 'Cinco formas de vivirlo', en: 'Five ways to live it' },
  'site.value.body': { es: 'Un solo nivel de acceso, y puertas de entrada distintas según el momento en el que estés.', en: 'One level of access, with different ways in depending on where you are.' },
  'site.value.all': { es: 'Ver planes y precios', en: 'See plans and prices' },

  'site.philosophy.more': { es: 'Leer nuestra filosofía', en: 'Read our philosophy' },

  'site.testimonials.title': { es: 'Lo que dicen quienes ya vienen', en: 'What the people who come say' },
  'site.testimonials.body': { es: 'Reseñas reales dejadas en la app después de clase.', en: 'Real reviews left in the app after class.' },
  'site.testimonials.member': { es: 'Socio HOY', en: 'HOY member' },
  'site.testimonials.empty': { es: 'Todavía no hay reseñas publicadas. Este espacio se llena con las reseñas que dejan los socios después de clase.', en: 'No published reviews yet. This space fills up with the reviews members leave after class.' },

  'site.first.eyebrow': { es: 'El primer paso', en: 'The first step' },
  'site.first.title': { es: 'Decide con el cuerpo, no solo con la cabeza.', en: 'Decide with your body, not only with your head.' },
  'site.first.body': { es: 'Una clase de prueba por {price}, sin complicaciones y sin permanencia. Si te gusta, seguimos.', en: 'One trial class for {price}, no complications and no commitment. If it suits you, we carry on.' },
  'site.first.cta': { es: 'Reservar clase de prueba', en: 'Book a trial class' },
  'site.first.cta2': { es: 'Escríbenos por WhatsApp', en: 'Write to us on WhatsApp' },

  'site.about.values': { es: 'Así hablamos', en: 'How we speak' },
  'site.about.media': { es: 'Fundadores e interior del estudio', en: 'Founders and studio interior' },
  'site.about.board': { es: 'Tablero de marca', en: 'Brand board' },
  'site.about.boardNote': { es: 'Manual de marca 2026 — tipografía, color y wordmark.', en: 'Brand manual 2026 — type, colour and wordmark.' },
  'site.about.classes': { es: 'Conoce las clases', en: 'Meet the classes' },

  'site.modalities.title': { es: 'Modalidades', en: 'Modalities' },
  'site.modalities.body': { es: 'Seis prácticas, cuatro movimientos, una sala.', en: 'Six practices, four movements, one room.' },
  'site.modalities.intensity': { es: 'Intensidad', en: 'Intensity' },
  'site.modalities.heated': { es: 'Sala caliente', en: 'Heated room' },
  'site.modalities.classLink': { es: 'Leer sobre {name}', en: 'Read about {name}' },
  'site.modalities.essays': { es: 'Cada modalidad pertenece a una de nuestras clases. Lee de qué se trata antes de reservar.', en: 'Every modality belongs to one of our classes. Read what it is about before you book.' },

  'site.schedule.title': { es: 'Horario', en: 'Schedule' },
  'site.schedule.body': { es: '{classes} clases al día, {mats} tapetes, una clase por persona al día. Toca una clase para reservar.', en: '{classes} classes a day, {mats} mats, one class per person per day. Tap a class to book.' },
  'site.schedule.loginTitle': { es: 'Para reservar, entra a tu cuenta', en: 'Sign in to book' },
  'site.schedule.loginBody': { es: 'Reservar y pagar ocurre dentro de la app. Entra o crea tu cuenta y volverás a esta clase.', en: 'Booking and paying happen inside the app. Sign in or create an account and you will come back to this class.' },
  'site.schedule.loginCta': { es: 'Entrar y reservar', en: 'Sign in and book' },
  'site.schedule.legend': { es: 'Leyenda', en: 'Legend' },
  'site.schedule.legendBody': { es: 'El color de cada clase es su movimiento. El cupo que ves es en vivo: {mats} tapetes por sesión.', en: 'Each class’s colour is its movement. The capacity you see is live: {mats} mats per session.' },

  'site.teachers.title': { es: 'Profesores', en: 'Teachers' },
  'site.teachers.body': { es: 'Personas que enseñan desde la práctica, no desde el guion.', en: 'People who teach from practice, not from a script.' },
  'site.teachers.legend': { es: 'Los retratos están pendientes de la sesión de fotos; los chips indican qué enseña cada quien.', en: 'Portraits are pending the photo session; the chips show what each of them teaches.' },
  'site.teachers.portrait': { es: 'Retrato de {name}', en: 'Portrait of {name}' },

  'site.plans.title': { es: 'Planes', en: 'Plans' },
  'site.plans.body': { es: 'Encuentra tu forma de vivir el estudio. Membresías, clases y pequeñas pausas. Precios en COP.', en: 'Find your way to enjoy the studio. Memberships, classes and small pauses. Prices in COP.' },
  'site.plans.all': { es: 'Ver todos los planes', en: 'See all plans' },
  'site.plans.why': { es: 'Por qué existe', en: 'Why it exists' },
  'site.plans.discipline': { es: 'La disciplina detrás del modelo', en: 'The discipline behind the model' },
  'site.plans.taxTitle': { es: '¿Incluye IVA?', en: 'Does it include VAT?' },
  'site.plans.taxIncluded': { es: 'Sí: los precios mostrados ya incluyen IVA del {pct}%.', en: 'Yes: the prices shown already include {pct}% VAT.' },
  'site.plans.taxExcluded': { es: 'No: a los precios mostrados se les suma IVA del {pct}% al pagar.', en: 'No: {pct}% VAT is added to the prices shown at checkout.' },
  'site.plans.specials.eyebrow': { es: 'Especiales', en: 'Specials' },
  'site.plans.specials.title': { es: 'Lo que no cabe en un plan', en: 'What does not fit in a plan' },
  'site.plans.specials.body': { es: 'Un cumpleaños, una sesión para tu equipo, un evento privado o algo que todavía no tiene nombre. Esas cosas no se compran con un botón: se conversan. Escríbenos y lo armamos contigo.', en: 'A birthday, a session for your team, a private event or something that does not have a name yet. Those things are not bought with a button: they are talked through. Write to us and we will shape it with you.' },
  'site.plans.specials.cta': { es: 'Escribirnos por WhatsApp', en: 'Write to us on WhatsApp' },
  'site.plans.specials.wa': { es: 'Hola HOY, quiero preguntar por un especial: un evento privado o una sesión de grupo.', en: 'Hi HOY, I would like to ask about a special: a private event or a group session.' },
  'site.plans.taxSource': { es: 'Parámetro de operación (M-08). Si cambia en la configuración, cambia aquí.', en: 'An operating parameter (M-08). Change it in settings and it changes here.' },

  'site.contact.title': { es: 'Contacto', en: 'Contact' },
  'site.contact.body': { es: 'Escríbenos por WhatsApp o ven a conocer la sala.', en: 'Write to us on WhatsApp or come and see the room.' },
  'site.contact.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'site.contact.email': { es: 'Correo', en: 'Email' },
  'site.contact.address': { es: 'Dirección', en: 'Address' },
  'site.contact.hours': { es: 'Horario de atención', en: 'Opening hours' },
  'site.contact.instagram': { es: 'Instagram', en: 'Instagram' },
  'site.contact.pending': { es: 'Dato pendiente de confirmar', en: 'Detail pending confirmation' },
  'site.contact.waCta': { es: 'Abrir WhatsApp', en: 'Open WhatsApp' },
  'site.contact.map': { es: 'Dónde estamos', en: 'Where we are' },
  'site.contact.mapOpen': { es: 'Abrir en Google Maps', en: 'Open in Google Maps' },
  'site.contact.form': { es: 'Escríbenos', en: 'Write to us' },
  'site.contact.formBody': { es: 'Cuéntanos qué necesitas y te respondemos por WhatsApp. Este formulario abre tu WhatsApp con el mensaje listo — no guardamos nada.', en: 'Tell us what you need and we will answer on WhatsApp. This form opens WhatsApp with the message ready — nothing is stored.' },
  'site.contact.fName': { es: 'Tu nombre', en: 'Your name' },
  'site.contact.fPhone': { es: 'Tu WhatsApp', en: 'Your WhatsApp' },
  'site.contact.fMessage': { es: 'Mensaje', en: 'Message' },
  'site.contact.fMessagePh': { es: 'Quiero probar una clase…', en: 'I would like to try a class…' },
  'site.contact.fSend': { es: 'Enviar por WhatsApp', en: 'Send on WhatsApp' },
  'site.contact.specials': { es: 'Especiales', en: 'Specials' },
  'site.contact.specialsBody': { es: 'Eventos privados, cumpleaños, sesiones para equipos y pedidos especiales se arman directamente con el estudio. Cuéntanos qué tienes en mente y te respondemos por WhatsApp.', en: 'Private events, birthdays, team sessions and special requests are arranged directly with the studio. Tell us what you have in mind and we will answer on WhatsApp.' },
  'site.contact.fTemplate': { es: 'Hola HOY, soy {name} ({phone}). {message}', en: 'Hi HOY, I am {name} ({phone}). {message}' },

  'site.legal.terms': { es: 'Términos y condiciones', en: 'Terms & conditions' },
  'site.legal.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },

  'site.footer.rights': { es: '© {year} {name}. Todos los derechos reservados.', en: '© {year} {name}. All rights reserved.' },
  'site.footer.hub': { es: 'Hub de pruebas', en: 'Testing hub' },
  'site.footer.visit': { es: 'Visítanos', en: 'Visit us' },
  'site.footer.follow': { es: 'Síguenos', en: 'Follow us' },
  'site.footer.explore': { es: 'Explora', en: 'Explore' },
  'site.footer.lang': { es: 'Idioma', en: 'Language' },

  // W-09 delete account (0019)
  'site.delete.nav': { es: 'Eliminar mi cuenta', en: 'Delete my account' },
  'site.delete.title': { es: 'Eliminar tu cuenta', en: 'Delete your account' },
  'site.delete.body': { es: 'Puedes pedirle a {name} que elimine tu cuenta sin iniciar sesión. Te explicamos primero qué se conserva por ley y qué se elimina; después llenas dos campos.', en: 'You can ask {name} to delete your account without signing in. First we explain what is kept by law and what is removed; then you fill in two fields.' },
  'site.delete.kept': { es: 'Se conserva, sin tu nombre', en: 'Kept, without your name' },
  'site.delete.kept.invoices': { es: 'Las facturas y el historial de pagos, por el plazo de conservación contable que exige la ley, ligados a un identificador anónimo.', en: 'Invoices and payment history, for the accounting retention period the law requires, linked to an anonymous identifier.' },
  'site.delete.kept.waiver': { es: 'La exoneración firmada, por el plazo que fija la política de privacidad, como prueba de que la aceptaste.', en: 'The signed waiver, for the period the privacy policy sets, as proof that you accepted it.' },
  'site.delete.removed': { es: 'Se elimina', en: 'Removed' },
  'site.delete.removed.profile': { es: 'Tu perfil: nombre, foto, cumpleaños, contacto de emergencia, notas, preferencias y notificaciones.', en: 'Your profile: name, photo, birthday, emergency contact, notes, preferences and notifications.' },
  'site.delete.removed.access': { es: 'Tu acceso a la app, las reservas futuras, los créditos y la membresía vigente.', en: 'Your access to the app, future bookings, credits and any membership still running.' },
  'site.delete.time': { es: 'El estudio procesa la solicitud en máximo quince días hábiles y confirma por el contacto que dejes. Dudas: {email}.', en: 'The studio processes the request within fifteen business days at most and confirms through the contact you leave. Questions: {email}.' },
  'site.delete.form': { es: 'Solicitud', en: 'Request' },
  'site.delete.form.body': { es: 'Deja el correo o el WhatsApp con el que creaste la cuenta. Con uno basta; sirve para encontrarte y para confirmarte.', en: 'Leave the email or the WhatsApp you created the account with. One is enough; it is how we find you and how we confirm.' },
  'site.delete.oneOf': { es: 'Correo o WhatsApp: al menos uno', en: 'Email or WhatsApp: at least one' },
  'site.delete.err.contact': { es: 'Necesitamos un correo válido o un número de WhatsApp para encontrar tu cuenta.', en: 'We need a valid email or a WhatsApp number to find your account.' },
  'site.delete.inApp': { es: '¿Tienes la app? Hazlo desde Perfil → Cuenta y datos', en: 'Have the app? Do it from Profile → Account & data' },
  'site.delete.sent.title': { es: 'Solicitud recibida', en: 'Request received' },
  'site.delete.sent.body': { es: 'Referencia {ref}. Te escribimos al contacto que dejaste cuando esté hecha, en máximo quince días hábiles. Si tienes cuenta en la app, verás el estado en Perfil → Cuenta y datos.', en: 'Reference {ref}. We write to the contact you left once it is done, within fifteen business days at most. If you have an account in the app, the status shows under Profile → Account & data.' },
  'site.edition.video': { es: 'V2.3 · Video', en: 'V2.3 · Video' },
  'site.edition.still': { es: 'V2.3 · Sin video', en: 'V2.3 · Still' },
  'site.new.samplePortrait': { es: 'Retrato de muestra · generado', en: 'Sample portrait · generated' },
  'site.new.samplePortraits': { es: 'Retratos generados para ilustrar el diseño; no representan al equipo real.', en: 'Generated sample portraits illustrate the design; they do not depict the real team.' },
};
