import type { StringTable } from '../../i18n/types';

/**
 * Website copy. Long-form brand prose (manifesto, "Sobre HOY", philosophy, class essays) lives in
 * `src/tenant/brand.ts`; this table holds the UI around it — labels, headings, CTAs and notes.
 * Namespaces: site.nav · site.hero · site.movements · site.mv · site.today · site.classes ·
 * site.value · site.philosophy · site.testimonials · site.first · site.about ·
 * site.modalities · site.schedule · site.teachers · site.plans · site.contact · site.legal · site.footer
 */
export const strings: StringTable = {
  'site.nav.home': { es: 'Inicio', en: 'Home' },
  'site.nav.about': { es: 'Sobre HOY', en: 'About' },
  'site.nav.classes': { es: 'Clases', en: 'Classes' },
  'site.nav.modalities': { es: 'Modalidades', en: 'Modalities' },
  'site.nav.schedule': { es: 'Horario', en: 'Schedule' },
  'site.nav.teachers': { es: 'Profesores', en: 'Teachers' },
  'site.nav.plans': { es: 'Planes', en: 'Plans' },
  'site.nav.contact': { es: 'Contacto', en: 'Contact' },
  'site.nav.signin': { es: 'Entrar', en: 'Sign in' },
  'site.nav.book': { es: 'Reservar clase', en: 'Book a class' },

  'site.hero.eyebrow': { es: 'Human club · {city}', en: 'Human club · {city}' },
  'site.hero.body': { es: 'Un santuario urbano en {city}: {mats} tapetes, {classes} clases al día y cuatro formas de moverte. Sin experiencia previa, sin prisa.', en: 'An urban sanctuary in {city}: {mats} mats, {classes} classes a day and four ways to move. No previous experience, no hurry.' },
  'site.hero.cta': { es: 'Clase de prueba · {price}', en: 'Trial class · {price}' },
  'site.hero.cta2': { es: 'Ver horario', en: 'See schedule' },
  'site.hero.media': { es: 'Video de portada del estudio', en: 'Studio hero video' },

  'site.movements.title': { es: 'Cuatro movimientos', en: 'Four movements' },
  'site.movements.body': { es: 'Cada clase pertenece a un movimiento. Elige cómo quieres sentirte hoy y el horario se ordena para ti.', en: 'Every class belongs to a movement. Choose how you want to feel today and the schedule sorts itself for you.' },
  'site.mv.enraiza': { es: 'Fuerza, centro, control. Pilates y barre.', en: 'Strength, core, control. Pilates and barre.' },
  'site.mv.fluye': { es: 'Respiración y movimiento continuo. Flow.', en: 'Breath and continuous movement. Flow.' },
  'site.mv.arde': { es: 'Calor, sudor, foco. Hot yoga.', en: 'Heat, sweat, focus. Hot yoga.' },
  'site.mv.libera': { es: 'Soltar, quedarse quieto. Yin y meditación.', en: 'Let go, stay still. Yin and meditation.' },

  'site.today.title': { es: 'Hoy en el club', en: 'Today at the club' },
  'site.today.empty': { es: 'Hoy descansamos. Mira el horario de la semana.', en: 'We rest today. See the week’s schedule.' },
  'site.today.all': { es: 'Ver la semana completa', en: 'See the whole week' },

  'site.classes.title': { es: 'Nuestras clases', en: 'Our classes' },
  'site.classes.all': { es: 'Ver todas las clases', en: 'See all classes' },
  'site.classes.read': { es: 'Leer más', en: 'Read more' },
  'site.classes.media': { es: 'Foto de {name}', en: '{name} photograph' },
  'site.classes.facts': { es: 'La clase en datos', en: 'The class in numbers' },
  'site.classes.duration': { es: 'Duración', en: 'Duration' },
  'site.classes.intensity': { es: 'Intensidad', en: 'Intensity' },
  'site.classes.room': { es: 'Sala', en: 'Room' },
  'site.classes.roomHot': { es: 'Caliente, a propósito', en: 'Heated, on purpose' },
  'site.classes.roomTemperate': { es: 'Temperatura ambiente', en: 'Room temperature' },
  'site.classes.movement': { es: 'Movimiento', en: 'Movement' },
  'site.classes.factsPending': { es: 'Esta práctica todavía no tiene una modalidad propia en el horario: hoy se vive dentro de las clases guiadas.', en: 'This practice does not have its own modality in the schedule yet: today it lives inside the guided classes.' },
  'site.classes.bring': { es: 'Qué traer', en: 'What to bring' },
  'site.classes.bring.towel': { es: 'Toalla — la sala es caliente y vas a sudar.', en: 'A towel — the room is heated and you will sweat.' },
  'site.classes.bring.water': { es: 'Agua — hidrátate antes, durante y después.', en: 'Water — drink before, during and after.' },
  'site.classes.bring.socks': { es: 'Medias con agarre (las vendemos en recepción).', en: 'Grip socks (we sell them at the front desk).' },
  'site.classes.bring.comfy': { es: 'Ropa cómoda en la que puedas respirar.', en: 'Comfortable clothes you can breathe in.' },
  'site.classes.bring.layers': { es: 'Una capa extra: al quedarte quieto, el cuerpo se enfría.', en: 'An extra layer: the body cools down when you stay still.' },
  'site.classes.bring.nothing': { es: 'Nada más. Los tapetes y los props son del estudio.', en: 'Nothing else. Mats and props are the studio’s.' },
  'site.classes.schedule': { es: 'Ver esta clase en el horario', en: 'See this class in the schedule' },
  'site.classes.other': { es: 'Otras formas de moverte', en: 'Other ways to move' },
  'site.classes.back': { es: 'Todas las clases', en: 'All classes' },
  'site.classes.notFound': { es: 'No encontramos esa clase. Mira todas las formas de moverte en HOY.', en: 'We could not find that class. Take a look at every way to move at HOY.' },

  'site.value.title': { es: 'Cinco formas de vivirlo', en: 'Five ways to live it' },
  'site.value.body': { es: 'Un solo nivel de acceso, y puertas de entrada distintas según el momento en el que estés.', en: 'One level of access, with different ways in depending on where you are.' },
  'site.value.all': { es: 'Ver planes y precios', en: 'See plans and prices' },

  'site.philosophy.more': { es: 'Leer nuestra filosofía', en: 'Read our philosophy' },

  'site.testimonials.title': { es: 'Lo que dicen quienes ya vienen', en: 'What the people who come say' },
  'site.testimonials.body': { es: 'Reseñas reales dejadas en la app después de clase.', en: 'Real reviews left in the app after class.' },
  'site.testimonials.member': { es: 'Socio HOY', en: 'HOY member' },
  'site.testimonials.empty': { es: 'Todavía no hay reseñas publicadas. Este espacio se llena con las reseñas que dejan los socios después de clase.', en: 'No published reviews yet. This space fills up with the reviews members leave after class.' },

  'site.first.eyebrow': { es: 'El primer paso', en: 'The first step' },
  'site.first.title': { es: 'Decide con el cuerpo, no solo con la cabeza.', en: 'Decide with your body, not only with your head.' },
  'site.first.body': { es: 'Una clase de prueba por {price}, sin complicaciones y sin permanencia. Si te gusta, seguimos.', en: 'One trial class for {price}, no complications and no commitment. If it suits you, we carry on.' },
  'site.first.cta': { es: 'Reservar clase de prueba', en: 'Book a trial class' },
  'site.first.cta2': { es: 'Escríbenos por WhatsApp', en: 'Write to us on WhatsApp' },

  'site.about.values': { es: 'Así hablamos', en: 'How we speak' },
  'site.about.media': { es: 'Fundadores e interior del estudio', en: 'Founders and studio interior' },
  'site.about.board': { es: 'Tablero de marca', en: 'Brand board' },
  'site.about.boardNote': { es: 'Manual de marca 2026 — tipografía, color y wordmark.', en: 'Brand manual 2026 — type, colour and wordmark.' },
  'site.about.classes': { es: 'Conoce las clases', en: 'Meet the classes' },

  'site.modalities.title': { es: 'Modalidades', en: 'Modalities' },
  'site.modalities.body': { es: 'Seis prácticas, cuatro movimientos, una sala.', en: 'Six practices, four movements, one room.' },
  'site.modalities.intensity': { es: 'Intensidad', en: 'Intensity' },
  'site.modalities.heated': { es: 'Sala caliente', en: 'Heated room' },
  'site.modalities.classLink': { es: 'Leer sobre {name}', en: 'Read about {name}' },
  'site.modalities.essays': { es: 'Cada modalidad pertenece a una de nuestras clases. Lee de qué se trata antes de reservar.', en: 'Every modality belongs to one of our classes. Read what it is about before you book.' },

  'site.schedule.title': { es: 'Horario', en: 'Schedule' },
  'site.schedule.body': { es: '{classes} clases al día, {mats} tapetes, una clase por persona al día. Toca una clase para reservar.', en: '{classes} classes a day, {mats} mats, one class per person per day. Tap a class to book.' },
  'site.schedule.loginTitle': { es: 'Para reservar, entra a tu cuenta', en: 'Sign in to book' },
  'site.schedule.loginBody': { es: 'Reservar y pagar ocurre dentro de la app. Entra o crea tu cuenta y volverás a esta clase.', en: 'Booking and paying happen inside the app. Sign in or create an account and you will come back to this class.' },
  'site.schedule.loginCta': { es: 'Entrar y reservar', en: 'Sign in and book' },
  'site.schedule.legend': { es: 'Leyenda', en: 'Legend' },
  'site.schedule.legendBody': { es: 'El color de cada clase es su movimiento. El cupo que ves es en vivo: {mats} tapetes por sesión.', en: 'Each class’s colour is its movement. The capacity you see is live: {mats} mats per session.' },

  'site.teachers.title': { es: 'Profesores', en: 'Teachers' },
  'site.teachers.body': { es: 'Personas que enseñan desde la práctica, no desde el guion.', en: 'People who teach from practice, not from a script.' },
  'site.teachers.legend': { es: 'Los retratos están pendientes de la sesión de fotos; los chips indican qué enseña cada quien.', en: 'Portraits are pending the photo session; the chips show what each of them teaches.' },
  'site.teachers.portrait': { es: 'Retrato de {name}', en: 'Portrait of {name}' },

  'site.plans.title': { es: 'Planes', en: 'Plans' },
  'site.plans.body': { es: 'Precios en COP. Cinco líneas, un mismo estudio: {mats} tapetes y {classes} clases al día.', en: 'Prices in COP. Five lines, one studio: {mats} mats and {classes} classes a day.' },
  'site.plans.all': { es: 'Ver todos los planes', en: 'See all plans' },
  'site.plans.why': { es: 'Por qué existe', en: 'Why it exists' },
  'site.plans.discipline': { es: 'La disciplina detrás del modelo', en: 'The discipline behind the model' },
  'site.plans.taxTitle': { es: '¿Incluye IVA?', en: 'Does it include VAT?' },
  'site.plans.taxIncluded': { es: 'Sí: los precios mostrados ya incluyen IVA del {pct}%.', en: 'Yes: the prices shown already include {pct}% VAT.' },
  'site.plans.taxExcluded': { es: 'No: a los precios mostrados se les suma IVA del {pct}% al pagar.', en: 'No: {pct}% VAT is added to the prices shown at checkout.' },
  'site.plans.taxSource': { es: 'Parámetro de operación (M-08). Si cambia en la configuración, cambia aquí.', en: 'An operating parameter (M-08). Change it in settings and it changes here.' },

  'site.contact.title': { es: 'Contacto', en: 'Contact' },
  'site.contact.body': { es: 'Escríbenos por WhatsApp o ven a conocer la sala.', en: 'Write to us on WhatsApp or come and see the room.' },
  'site.contact.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'site.contact.email': { es: 'Correo', en: 'Email' },
  'site.contact.address': { es: 'Dirección', en: 'Address' },
  'site.contact.hours': { es: 'Horario de atención', en: 'Opening hours' },
  'site.contact.instagram': { es: 'Instagram', en: 'Instagram' },
  'site.contact.pending': { es: 'Dato pendiente de confirmar', en: 'Detail pending confirmation' },
  'site.contact.waCta': { es: 'Abrir WhatsApp', en: 'Open WhatsApp' },
  'site.contact.map': { es: 'Dónde estamos', en: 'Where we are' },
  'site.contact.mapOpen': { es: 'Abrir en Google Maps', en: 'Open in Google Maps' },
  'site.contact.form': { es: 'Escríbenos', en: 'Write to us' },
  'site.contact.formBody': { es: 'Cuéntanos qué necesitas y te respondemos por WhatsApp. Este formulario abre tu WhatsApp con el mensaje listo — no guardamos nada.', en: 'Tell us what you need and we will answer on WhatsApp. This form opens WhatsApp with the message ready — nothing is stored.' },
  'site.contact.fName': { es: 'Tu nombre', en: 'Your name' },
  'site.contact.fPhone': { es: 'Tu WhatsApp', en: 'Your WhatsApp' },
  'site.contact.fMessage': { es: 'Mensaje', en: 'Message' },
  'site.contact.fMessagePh': { es: 'Quiero probar una clase…', en: 'I would like to try a class…' },
  'site.contact.fSend': { es: 'Enviar por WhatsApp', en: 'Send on WhatsApp' },
  'site.contact.fTemplate': { es: 'Hola HOY, soy {name} ({phone}). {message}', en: 'Hi HOY, I am {name} ({phone}). {message}' },

  'site.legal.terms': { es: 'Términos y condiciones', en: 'Terms & conditions' },
  'site.legal.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },
  'site.legal.updated': { es: 'Última actualización: {date} · versión {v}', en: 'Last updated: {date} · version {v}' },
  'site.legal.draft': { es: 'Borrador. Este texto será reemplazado por el documento legal revisado. Incluye las secciones exigidas por la Ley 1581 de 2012 y el Decreto 1377 de 2013.', en: 'Draft. This text will be replaced by the reviewed legal document. It includes the sections required by Ley 1581 de 2012 and Decreto 1377 de 2013.' },

  'site.footer.rights': { es: '© {year} {name}. Todos los derechos reservados.', en: '© {year} {name}. All rights reserved.' },
  'site.footer.hub': { es: 'Hub de pruebas', en: 'Testing hub' },
  'site.footer.visit': { es: 'Visítanos', en: 'Visit us' },
  'site.footer.follow': { es: 'Síguenos', en: 'Follow us' },
  'site.footer.explore': { es: 'Explora', en: 'Explore' },
  'site.footer.lang': { es: 'Idioma', en: 'Language' },
};
