import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'dev.tokens.title': { es: 'Tokens de diseño (D-01)', en: 'Design tokens (D-01)' },
  'dev.tokens.body': { es: 'La única fuente de verdad es src/design/tokens.ts. Todo lo que ves aquí se lee en vivo de las variables CSS.', en: 'The single source of truth is src/design/tokens.ts. Everything here reads live from the CSS variables.' },
  'dev.tokens.brand': { es: 'Marca', en: 'Brand' },
  'dev.tokens.semantic': { es: 'Roles semánticos ({theme})', en: 'Semantic roles ({theme})' },
  'dev.tokens.tones': { es: 'Tonos de clase', en: 'Class tones' },
  'dev.tokens.type': { es: 'Tipografía', en: 'Typography' },
  'dev.tokens.spacing': { es: 'Escala de espaciado (base 4 px)', en: 'Spacing scale (4 px base)' },
  'dev.tokens.spacingSemantic': { es: 'Espaciado semántico', en: 'Semantic spacing' },
  'dev.tokens.spacingSemantic.eyebrow': { es: 'lo que usan las páginas · valor en vivo a este ancho', en: 'what pages use · live value at this width' },
  'dev.tokens.radii': { es: 'Radios', en: 'Radii' },
  'dev.tokens.shadows': { es: 'Escala de sombra física', en: 'Physical shadow scale' },
  'dev.tokens.shadows.eyebrow': { es: 'Capa Depth del canvas · realce interior + contacto + ambiente suave', en: 'Canvas Depth layer · inset highlight + contact + soft ambient' },
  'dev.tokens.palette': { es: 'Paleta del canvas', en: 'Canvas palette' },
  'dev.tokens.rgb': { es: 'Tripletas RGB (sombras y texturas)', en: 'RGB triplets (shadows and textures)' },
  'dev.tokens.surfaces': { es: 'Escala de superficies', en: 'Surface scale' },
  'dev.tokens.surfaces.eyebrow': { es: 'card · elevated · pressed · soft · inverse · marco', en: 'card · elevated · pressed · soft · inverse · frame' },
  'dev.tokens.frame': { es: 'Marco del teléfono (34 px)', en: 'Phone frame (34 px)' },
  'dev.tokens.textures': { es: 'Texturas', en: 'Textures' },
  'dev.tokens.textures.eyebrow': { es: 'Grano de ante del manual de marca, en CSS puro', en: 'Suede grain from the brand manual, in pure CSS' },
  'dev.tokens.textures.note': { es: 'Dos degradados repetidos de una línea más un charco de luz radial. Sin archivos de imagen: se aplican como background-image sobre el color de la superficie. El tema oscuro y el wireframe los apagan (--tex-*-on).', en: 'Two one-pixel repeating gradients plus a radial light pool. No image files: applied as background-image over the surface colour. Dark theme and wireframe switch them off (--tex-*-on).' },
  'dev.tokens.materials': { es: 'Materiales', en: 'Materials' },
  'dev.tokens.materials.eyebrow': { es: 'Rellenos decorativos del D-01 del canvas · arte del hero, gift cards, vacíos', en: 'Decorative fills from the canvas D-01 · hero art, gift cards, empty art' },
  'dev.tokens.motion': { es: 'Movimiento', en: 'Motion' },
  'dev.tokens.icons': { es: 'Iconos', en: 'Icons' },
  'dev.tokens.icons.eyebrow': { es: 'Tamaños en rem (crecen con --ui) · trazo 1,75 / 2,25 activo · cuadro de 36 px', en: 'Sizes in rem (grow with --ui) · stroke 1.75 / 2.25 active · 36 px tile' },
  'dev.components.title': { es: 'Biblioteca de componentes (D-02)', en: 'Component library (D-02)' },
  'dev.components.body': { es: 'Cada componente vive en src/components/<nivel>/<Nombre>/ con su .meta.ts. Sin meta no hay componente; sin uso no hay meta.', en: 'Every component lives in src/components/<tier>/<Name>/ with its .meta.ts. No meta, no component; no usage, no meta.' },
  'dev.components.props': { es: 'Props', en: 'Props' },
  'dev.components.states': { es: 'Estados', en: 'States' },
  'dev.components.a11y': { es: 'Accesibilidad', en: 'Accessibility' },
  'dev.components.count': { es: '{n} componentes', en: '{n} components' },
  'dev.specs.title': { es: 'Specs de página', en: 'Page specs' },
  'dev.specs.body': { es: 'Todas las specs del canvas y las nuevas. El porcentaje mide completitud (propósito, layout, datos, roles, lógica, integraciones, estados). Las rutas indican dónde vive cada pantalla.', en: 'Every canvas spec plus new ones. The percentage measures completeness (purpose, layout, data, roles, logic, integrations, states). Routes show where each screen lives.' },
  'dev.specs.route': { es: 'Ruta', en: 'Route' },
  'dev.specs.noRoute': { es: 'sin ruta', en: 'no route' },
  'dev.specs.stub': { es: 'stub', en: 'stub' },
  'dev.specs.built': { es: 'construida', en: 'built' },
  'dev.layout.title': { es: 'Editor de layout', en: 'Layout editor' },
  'dev.layout.body': { es: 'Arrastra para reordenar las secciones de {code}. El orden se guarda en page_layouts y la página lo lee con useLayout.', en: 'Drag to reorder the sections of {code}. The order persists to page_layouts and the page reads it with useLayout.' },
  'dev.layout.pick': { es: 'Página', en: 'Page' },
  'dev.layout.hidden': { es: 'Oculta', en: 'Hidden' },
  'dev.layout.visible': { es: 'Visible', en: 'Visible' },
  'dev.layout.reset': { es: 'Volver al orden del spec', en: 'Reset to spec order' },
  'dev.layout.custom': { es: 'Orden personalizado guardado', en: 'Custom order saved' },
  'dev.layout.default': { es: 'Orden por defecto (spec)', en: 'Default order (spec)' },
  'dev.layout.wired': { es: 'Esta página lee useLayout', en: 'This page reads useLayout' },
  'dev.layout.notWired': { es: 'Esta página aún no lee useLayout; el orden se guarda igual.', en: 'This page does not read useLayout yet; the order is saved anyway.' },
  'dev.layout.preview': { es: 'Ver página', en: 'View page' },
  'dev.canvas.title': { es: 'Lienzo de páginas (D-05)', en: 'Page canvas (D-05)' },
  'dev.canvas.body': { es: '{n} páginas, agrupadas por superficie, con su captura real. Clic o Enter abre la página. Las capturas salen de npm run screenshots; una página sin captura muestra su mosaico.', en: '{n} pages, grouped by surface, each with its real capture. Click or Enter opens the page. Captures come from npm run screenshots; a page without one shows its idle tile.' },
  'dev.canvas.zoom': { es: 'Zoom', en: 'Zoom' },
  'dev.sim.title': { es: 'Simulador de dispositivos (D-06)', en: 'Device simulator (D-06)' },
  'dev.sim.body': { es: 'Cualquier ruta, en cualquier dispositivo, como cualquier persona. Todo el estado va en la URL, así que esta vista es un enlace que puedes compartir.', en: 'Any route, on any device, as anyone. All the state lives in the URL, so this view is a link you can share.' },
  'dev.sim.device': { es: 'Dispositivo', en: 'Device' },
  'dev.sim.route': { es: 'Ruta', en: 'Route' },
  'dev.sim.as': { es: 'Entrar como', en: 'Enter as' },
  'dev.sim.openTab': { es: 'Abrir en pestaña', en: 'Open in a tab' },
  'dev.kb.title': { es: 'Knowledgebase (K-01)', en: 'Knowledgebase (K-01)' },
  'dev.kb.kanban': { es: 'Kanban', en: 'Kanban' },
  'dev.kb.changelog': { es: 'Changelog', en: 'Changelog' },
  'dev.kb.prompts': { es: 'Prompts', en: 'Prompts' },
  // ---- 0040 · D-07 developer API keys ----
  'dev.apiKeys.nav': { es: 'Llaves de API', en: 'API keys' },
  'dev.apiKeys.title': { es: 'Llaves de API', en: 'API keys' },
  'dev.apiKeys.subtitle': { es: 'Llaves que HoyOS entrega a desarrolladores para leer clases y horarios, o escribir reservas, desde otra app. Se guarda un hash; la llave completa se ve una sola vez.', en: 'Keys HoyOS issues to developers to read classes and hours, or write bookings, from another app. A hash is stored; the full key is seen only once.' },
  'dev.apiKeys.readonly': { es: 'Solo lectura', en: 'Read-only' },
  'dev.apiKeys.create': { es: 'Crear llave', en: 'Create key' },
  'dev.apiKeys.create.submit': { es: 'Crear y mostrar una vez', en: 'Create and show once' },
  'dev.apiKeys.intro.title': { es: 'Para qué son y qué falta', en: 'What they are for and what is missing' },
  'dev.apiKeys.intro.body': { es: 'Cada llave tiene un entorno (prueba o producción), permisos y, si quieres, un vencimiento. La verificación la hace el servidor de HoyOS, que todavía no existe: hoy las llaves se crean y se administran, pero nada las acepta. Encabezado:', en: 'Each key has an environment (test or live), scopes and, optionally, an expiry. The HoyOS server does the verification and it does not exist yet: today keys are created and managed, but nothing accepts them. Header:' },
  'dev.apiKeys.intro.outbound': { es: 'Secretos de salida: Integraciones (M-10)', en: 'Outbound secrets: Integrations (M-10)' },
  'dev.apiKeys.list': { es: 'Llaves emitidas', en: 'Issued keys' },
  'dev.apiKeys.list.count': { es: '{n} llaves · {active} activas', en: '{n} keys · {active} active' },
  'dev.apiKeys.empty': { es: 'Sin llaves todavía', en: 'No keys yet' },
  'dev.apiKeys.empty.body': { es: 'Crea una llave de prueba para empezar.', en: 'Create a test key to start.' },
  'dev.apiKeys.col.name': { es: 'Nombre', en: 'Name' },
  'dev.apiKeys.col.prefix': { es: 'Llave', en: 'Key' },
  'dev.apiKeys.col.env': { es: 'Entorno', en: 'Environment' },
  'dev.apiKeys.col.scopes': { es: 'Permisos', en: 'Scopes' },
  'dev.apiKeys.col.created': { es: 'Creada', en: 'Created' },
  'dev.apiKeys.col.lastUsed': { es: 'Último uso', en: 'Last used' },
  'dev.apiKeys.col.status': { es: 'Estado', en: 'Status' },
  'dev.apiKeys.col.actions': { es: 'Acciones', en: 'Actions' },
  'dev.apiKeys.never': { es: 'Nunca', en: 'Never' },
  'dev.apiKeys.replaces': { es: 'reemplaza {prefix}…', en: 'replaces {prefix}…' },
  'dev.apiKeys.env.live': { es: 'Producción', en: 'Live' },
  'dev.apiKeys.env.test': { es: 'Prueba', en: 'Test' },
  'dev.apiKeys.status.active': { es: 'Activa', en: 'Active' },
  'dev.apiKeys.status.expiring': { es: 'Por vencer', en: 'Expiring' },
  'dev.apiKeys.status.expired': { es: 'Vencida', en: 'Expired' },
  'dev.apiKeys.status.revoked': { es: 'Revocada', en: 'Revoked' },
  'dev.apiKeys.rotate': { es: 'Rotar', en: 'Rotate' },
  'dev.apiKeys.revoke': { es: 'Revocar', en: 'Revoke' },
  'dev.apiKeys.revoke.confirm': { es: '¿Revocar ya?', en: 'Revoke now?' },
  'dev.apiKeys.revoked': { es: 'Llave {prefix}… revocada', en: 'Key {prefix}… revoked' },
  'dev.apiKeys.f.name': { es: 'Nombre', en: 'Name' },
  'dev.apiKeys.f.name.hint': { es: 'Para quién o para qué app es.', en: 'Who or which app it is for.' },
  'dev.apiKeys.f.name.ph': { es: 'Widget de horario', en: 'Schedule widget' },
  'dev.apiKeys.f.env': { es: 'Entorno', en: 'Environment' },
  'dev.apiKeys.f.env.hint': { es: 'Las de prueba solo tocan datos de prueba.', en: 'Test keys only touch test data.' },
  'dev.apiKeys.f.expiry': { es: 'Vence', en: 'Expires' },
  'dev.apiKeys.f.expiry.days': { es: 'En {n} días', en: 'In {n} days' },
  'dev.apiKeys.f.expiry.never': { es: 'Nunca', en: 'Never' },
  'dev.apiKeys.f.scopes': { es: 'Permisos', en: 'Scopes' },
  'dev.apiKeys.scope.classes.read': { es: 'leer clases y horario', en: 'read classes and schedule' },
  'dev.apiKeys.scope.bookings.read': { es: 'leer reservas', en: 'read bookings' },
  'dev.apiKeys.scope.bookings.write': { es: 'crear y cancelar reservas', en: 'create and cancel bookings' },
  'dev.apiKeys.scope.customers.read': { es: 'leer clientes', en: 'read customers' },
  'dev.apiKeys.scope.hours.read': { es: 'leer horario y festivos', en: 'read hours and holidays' },
  'dev.apiKeys.scope.hours.write': { es: 'cambiar festivos y horarios especiales', en: 'change holidays and special hours' },
  'dev.apiKeys.scope.webhooks.receive': { es: 'recibir webhooks', en: 'receive webhooks' },
  'dev.apiKeys.err.name': { es: 'Ponle un nombre a la llave.', en: 'Give the key a name.' },
  'dev.apiKeys.err.scopes': { es: 'Elige al menos un permiso.', en: 'Pick at least one scope.' },
  'dev.apiKeys.err.rotateDead': { es: 'Una llave revocada o vencida no se rota; crea una nueva.', en: 'A revoked or expired key cannot be rotated; create a new one.' },
  'dev.apiKeys.shown.title': { es: 'Tu nueva llave', en: 'Your new key' },
  'dev.apiKeys.shown.rotated': { es: 'La llave de reemplazo', en: 'The replacement key' },
  'dev.apiKeys.shown.once': { es: 'Solo se muestra esta vez', en: 'Shown this one time only' },
  'dev.apiKeys.shown.once.body': { es: 'Cópiala ahora y guárdala en el gestor de secretos de tu app. HoyOS guarda solo un hash: si la pierdes, rótala.', en: 'Copy it now and keep it in your app’s secret manager. HoyOS keeps only a hash: if you lose it, rotate it.' },
  'dev.apiKeys.shown.meta': { es: '{name} · {prefix}… · {env}', en: '{name} · {prefix}… · {env}' },
  'dev.apiKeys.shown.grace': { es: 'La llave anterior ({prefix}…) sigue funcionando 24 horas para que despliegues la nueva.', en: 'The previous key ({prefix}…) keeps working for 24 hours so you can deploy the new one.' },
  'dev.apiKeys.shown.done': { es: 'Ya la guardé', en: 'I saved it' },
  'dev.apiKeys.copy': { es: 'Copiar llave', en: 'Copy key' },
  'dev.apiKeys.copied': { es: 'Llave copiada', en: 'Key copied' },
  'dev.apiKeys.copyFailed': { es: 'No se pudo copiar; selecciónala a mano.', en: 'Could not copy; select it by hand.' },
  'dev.apiKeys.try': { es: 'Probar una petición', en: 'Try a request' },
  'dev.apiKeys.try.body': { es: 'Cuando exista el servidor, esto enviará una petición firmada con la llave que elijas y mostrará la respuesta.', en: 'Once the server exists, this will send a request signed with the key you pick and show the response.' },
  'dev.apiKeys.try.cta': { es: 'Probar una petición', en: 'Try a request' },
};
