import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'dev.tokens.title': { es: 'Tokens de diseño (D-01)', en: 'Design tokens (D-01)' },
  'dev.tokens.body': { es: 'La única fuente de verdad es src/design/tokens.ts. Todo lo que ves aquí se lee en vivo de las variables CSS.', en: 'The single source of truth is src/design/tokens.ts. Everything here reads live from the CSS variables.' },
  'dev.tokens.brand': { es: 'Marca', en: 'Brand' },
  'dev.tokens.semantic': { es: 'Roles semánticos ({theme})', en: 'Semantic roles ({theme})' },
  'dev.tokens.movements': { es: 'Movimientos', en: 'Movements' },
  'dev.tokens.type': { es: 'Tipografía', en: 'Typography' },
  'dev.tokens.spacing': { es: 'Espaciado (4 pt)', en: 'Spacing (4 pt)' },
  'dev.tokens.radii': { es: 'Radios', en: 'Radii' },
  'dev.tokens.shadows': { es: 'Sombra física (3 capas)', en: 'Physical shadow (3 layers)' },
  'dev.tokens.motion': { es: 'Movimiento', en: 'Motion' },
  'dev.components.title': { es: 'Biblioteca de componentes (D-02)', en: 'Component library (D-02)' },
  'dev.components.body': { es: 'Cada componente vive en src/components/<nivel>/<Nombre>/ con su .meta.ts. Sin meta no hay componente; sin uso no hay meta.', en: 'Every component lives in src/components/<tier>/<Name>/ with its .meta.ts. No meta, no component; no usage, no meta.' },
  'dev.components.props': { es: 'Props', en: 'Props' },
  'dev.components.states': { es: 'Estados', en: 'States' },
  'dev.components.a11y': { es: 'Accesibilidad', en: 'Accessibility' },
  'dev.components.usedBy': { es: 'Usado en', en: 'Used by' },
  'dev.components.count': { es: '{n} componentes', en: '{n} components' },
  'dev.specs.title': { es: 'Specs de página', en: 'Page specs' },
  'dev.specs.body': { es: 'Todas las specs del canvas y las nuevas. El porcentaje mide completitud (propósito, layout, datos, roles, lógica, integraciones, estados). Las rutas indican dónde vive cada pantalla.', en: 'Every canvas spec plus new ones. The percentage measures completeness (purpose, layout, data, roles, logic, integrations, states). Routes show where each screen lives.' },
  'dev.specs.route': { es: 'Ruta', en: 'Route' },
  'dev.specs.noRoute': { es: 'sin ruta', en: 'no route' },
  'dev.specs.stub': { es: 'stub', en: 'stub' },
  'dev.specs.built': { es: 'construida', en: 'built' },
  'dev.specs.open': { es: 'Abrir', en: 'Open' },
  'dev.layout.title': { es: 'Editor de layout', en: 'Layout editor' },
  'dev.layout.body': { es: 'Arrastra para reordenar las secciones de {code}. El orden se guarda en page_layouts y la página lo lee con useLayout.', en: 'Drag to reorder the sections of {code}. The order persists to page_layouts and the page reads it with useLayout.' },
  'dev.layout.pick': { es: 'Página', en: 'Page' },
  'dev.layout.hidden': { es: 'Oculta', en: 'Hidden' },
  'dev.layout.visible': { es: 'Visible', en: 'Visible' },
  'dev.layout.reset': { es: 'Volver al orden del spec', en: 'Reset to spec order' },
  'dev.layout.custom': { es: 'Orden personalizado guardado', en: 'Custom order saved' },
  'dev.layout.default': { es: 'Orden por defecto (spec)', en: 'Default order (spec)' },
  'dev.layout.wired': { es: 'Esta página lee useLayout', en: 'This page reads useLayout' },
  'dev.layout.notWired': { es: 'Esta página aún no lee useLayout; el orden se guarda igual.', en: 'This page does not read useLayout yet; the order is saved anyway.' },
  'dev.layout.preview': { es: 'Ver página', en: 'View page' },
  'dev.kb.title': { es: 'Knowledgebase (K-01)', en: 'Knowledgebase (K-01)' },
  'dev.kb.kanban': { es: 'Kanban', en: 'Kanban' },
  'dev.kb.changelog': { es: 'Changelog', en: 'Changelog' },
  'dev.kb.prompts': { es: 'Prompts', en: 'Prompts' },
};
