import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  // M-03 tables
  'admin.tables.title': { es: 'Tablas', en: 'Tables' },
  'admin.tables.subtitle': { es: 'Todas las tablas del sistema, tal como vivirán en Supabase. Edita filas, filtra y exporta.', en: 'Every table in the system, as it will live in Supabase. Edit rows, filter and export.' },
  'admin.tables.pick': { es: 'Elige una tabla en la barra lateral.', en: 'Pick a table in the sidebar.' },
  'admin.tables.search': { es: 'Buscar en {table}…', en: 'Search {table}…' },
  'admin.tables.columns': { es: '{n} columnas', en: '{n} columns' },
  'admin.tables.row': { es: 'Fila', en: 'Row' },
  'admin.tables.references': { es: 'referencia a', en: 'references' },
  'admin.tables.provider': { es: 'Proveedor: {name}', en: 'Provider: {name}' },
  'admin.tables.resetSeed': { es: 'Reiniciar datos demo', en: 'Reset demo data' },
  'admin.tables.resetConfirm': { es: '¿Borrar todos los cambios y volver a los datos demo?', en: 'Discard all changes and return to demo data?' },
  'admin.tables.addRow': { es: 'Nueva fila', en: 'New row' },
  'admin.tables.deleteConfirm': { es: '¿Eliminar esta fila?', en: 'Delete this row?' },
  'admin.tables.saved': { es: 'Guardado', en: 'Saved' },
  'admin.tables.readonly': { es: 'Solo lectura (generado)', en: 'Read only (generated)' },
  'admin.tables.groups': { es: 'Grupos', en: 'Groups' },
  'admin.tables.schema': { es: 'Esquema', en: 'Schema' },
  'admin.tables.data': { es: 'Datos', en: 'Data' },

  // M-01 dashboard
  'admin.dashboard.title': { es: 'Panel', en: 'Dashboard' },
  'admin.dashboard.members': { es: 'Miembros activos', en: 'Active members' },
  'admin.dashboard.revenue': { es: 'Ingresos 30 días', en: 'Revenue 30 days' },
  'admin.dashboard.occupancy': { es: 'Ocupación 7 días', en: 'Occupancy 7 days' },
  'admin.dashboard.arrivals': { es: 'Llegadas hoy', en: 'Arrivals today' },
  'admin.dashboard.arrivals.hint': { es: 'en {n} clases', en: 'across {n} classes' },
  'admin.dashboard.occChart': { es: 'Ocupación por día', en: 'Occupancy by day' },
  'admin.dashboard.occChart.eyebrow': { es: 'Reservas / cupos · 7 días', en: 'Bookings / capacity · 7 days' },
  'admin.dashboard.flags': { es: 'Interruptores de funciones', en: 'Feature switches' },
  'admin.dashboard.flags.body': { es: 'Cada bloque de cada pantalla se puede apagar aquí. Cada cambio queda en el registro de actividad.', en: 'Every block of every screen can be turned off here. Every change is written to the activity log.' },
  'admin.dashboard.flags.readonly': { es: 'Tu rol ve los interruptores pero no los cambia.', en: 'Your role sees the switches but cannot change them.' },
  'admin.dashboard.audit': { es: 'Actividad reciente', en: 'Recent activity' },
  'admin.dashboard.system': { es: 'Sistema', en: 'System' },

  // M-02 content
  'admin.content.title': { es: 'Contenido', en: 'Content' },
  'admin.content.subtitle': { es: 'Clases, profesores, modalidades y salas: la fuente de la app, el sitio y recepción.', en: 'Classes, teachers, modalities and rooms: the source for the app, the website and the desk.' },
  'admin.content.tab.class_templates': { es: 'Clases (plantillas)', en: 'Classes (templates)' },
  'admin.content.tab.teachers': { es: 'Profesores', en: 'Teachers' },
  'admin.content.tab.modalities': { es: 'Modalidades', en: 'Modalities' },
  'admin.content.tab.rooms': { es: 'Salas', en: 'Rooms' },
  'admin.content.pricingNote': { es: 'Los precios viven en el Modelo de Valor (P-01) y no se editan aquí.', en: 'Prices live in the value model (P-01) and are not edited here.' },
  'admin.content.add': { es: 'Crear', en: 'Create' },
  'admin.content.published': { es: 'Publicado', en: 'Published' },
  'admin.content.draft': { es: 'Borrador', en: 'Draft' },
  'admin.content.empty': { es: 'Crea el primer elemento', en: 'Create the first item' },
  'admin.content.empty.body': { es: 'Empieza en borrador y publica cuando el español esté listo.', en: 'Start as a draft and publish once the Spanish is ready.' },
  'admin.content.deleteConfirm': { es: '¿Eliminar este elemento? Las sesiones ya generadas no cambian.', en: 'Delete this item? Already generated sessions do not change.' },
  'admin.content.required': { es: 'Obligatorio (español)', en: 'Required (Spanish)' },
  'admin.content.unsaved': { es: 'Cambios sin guardar', en: 'Unsaved changes' },
  'admin.content.upToDate': { es: 'Al día', en: 'Up to date' },
  'admin.content.preview': { es: 'Vista previa · app / web', en: 'Preview · app / web' },
  'admin.content.intensity': { es: 'intensidad', en: 'intensity' },

  // M-04 emails
  'admin.emails.title': { es: 'Emails transaccionales', en: 'Transactional emails' },
  'admin.emails.subtitle': { es: 'Cada email automático como diseño real, en dos idiomas, con su disparador y enlace profundo.', en: 'Every automated email as a real design, in both languages, with its trigger and deep link.' },
  'admin.emails.createMissing': { es: 'Crear {n} plantillas estándar', en: 'Create {n} standard templates' },
  'admin.emails.empty': { es: 'Sin plantillas todavía', en: 'No templates yet' },
  'admin.emails.empty.body': { es: 'Crea el set estándar: reserva, recibo, cancelación, lista de espera, recordatorio, preparación, cumpleaños, renovación, pago fallido, regalo, invitación.', en: 'Create the standard set: booking, receipt, cancellation, waitlist, reminder, preparation, birthday, renewal, failed payment, gift, invite.' },
  'admin.emails.draft': { es: 'Borrador', en: 'Draft' },
  'admin.emails.deepLink': { es: 'El botón enlaza a la pantalla correspondiente en la app o el sitio.', en: 'The button deep-links into the matching app screen or website page.' },
  'admin.emails.dianNote': { es: 'Los recibos incluyen la referencia DIAN cuando exista.', en: 'Receipts include the DIAN reference once it exists.' },
  'admin.emails.versions': { es: 'Versiones', en: 'Versions' },
  'admin.emails.versions.empty': { es: 'Sin cambios registrados todavía.', en: 'No changes recorded yet.' },
  'admin.emails.rollback': { es: 'Restaurar', en: 'Roll back' },
  'admin.emails.log': { es: 'Envíos', en: 'Send log' },
  'admin.emails.log.when': { es: 'Cuándo', en: 'When' },
  'admin.emails.log.to': { es: 'Para', en: 'To' },
  'admin.emails.log.template': { es: 'Plantilla', en: 'Template' },
  'admin.emails.log.status': { es: 'Estado', en: 'Status' },
  'admin.emails.log.empty': { es: 'Sin envíos todavía.', en: 'Nothing sent yet.' },
  'admin.emails.f.name': { es: 'Nombre', en: 'Name' },
  'admin.emails.f.trigger': { es: 'Disparador', en: 'Trigger' },
  'admin.emails.f.trigger.hint': { es: 'Evento del sistema, p. ej. booking.created', en: 'System event, e.g. booking.created' },
  'admin.emails.f.subject': { es: 'Asunto', en: 'Subject' },
  'admin.emails.f.body': { es: 'Cuerpo', en: 'Body' },
  'admin.emails.f.cta': { es: 'Botón', en: 'Button' },
  'admin.emails.f.deepLink': { es: 'Enlace profundo', en: 'Deep link' },
  'admin.emails.f.active': { es: 'Activo', en: 'Active' },
  'admin.emails.vars': { es: 'Variables', en: 'Variables' },
  'admin.emails.missingEn': { es: 'Falta la traducción al inglés: no se puede activar.', en: 'English translation missing: cannot activate.' },
  'admin.emails.test': { es: 'Enviarme una prueba', en: 'Send me a test' },
  'admin.emails.saveVersion': { es: 'Guardar v{v}', en: 'Save v{v}' },
  'admin.emails.unsaved': { es: 'Cambios sin guardar.', en: 'Unsaved changes.' },

  // M-05 whatsapp
  'admin.wa.title': { es: 'Automatizaciones de WhatsApp', en: 'WhatsApp automations' },
  'admin.wa.subtitle': { es: 'Plantillas aprobadas por Meta, sus disparadores, tiempos y horas de silencio.', en: 'Meta-approved templates, their triggers, timing and quiet hours.' },
  'admin.wa.createMissing': { es: 'Crear {n} automatizaciones estándar', en: 'Create {n} standard automations' },
  'admin.wa.empty': { es: 'Sin automatizaciones todavía', en: 'No automations yet' },
  'admin.wa.empty.body': { es: 'Crea el set estándar: reserva, recordatorio, cancelación, lista de espera, cumpleaños, recibo, membresía, feedback, invitación.', en: 'Create the standard set: booking, reminder, cancellation, waitlist, birthday, receipt, membership, feedback, invite.' },
  'admin.wa.quiet': { es: 'Horas de silencio', en: 'Quiet hours' },
  'admin.wa.quiet.body': { es: 'Los mensajes no urgentes esperan hasta la mañana. Las cancelaciones pasan.', en: 'Non-urgent messages wait until morning. Cancellations go through.' },
  'admin.wa.quiet.now': { es: 'Ahora mismo estamos en silencio: los envíos quedan en cola.', en: 'Quiet hours are on right now: sends are queued.' },
  'admin.wa.optin': { es: 'Opt-in', en: 'Opt-in' },
  'admin.wa.optin.body': { es: 'Solo números verificados con opt-in reciben automatizaciones. El opt-out es inmediato y permanente.', en: 'Only verified, opted-in numbers get automations. Opt-out is immediate and permanent.' },
  'admin.wa.meta': { es: 'Aprobadas por Meta', en: 'Meta approved' },
  'admin.wa.meta.body': { es: 'Una automatización no se activa hasta que su plantilla esté aprobada.', en: 'An automation cannot be enabled until its template is approved.' },
  'admin.wa.col.automation': { es: 'Automatización', en: 'Automation' },
  'admin.wa.col.trigger': { es: 'Disparador', en: 'Trigger' },
  'admin.wa.col.delay': { es: 'Cuándo', en: 'When' },
  'admin.wa.col.status': { es: 'Meta', en: 'Meta' },
  'admin.wa.approval.draft': { es: 'Borrador', en: 'Draft' },
  'admin.wa.approval.pending': { es: 'Pendiente', en: 'Pending' },
  'admin.wa.approval.approved': { es: 'Aprobada', en: 'Approved' },
  'admin.wa.approval.rejected': { es: 'Rechazada', en: 'Rejected' },
  'admin.wa.noTemplate': { es: 'Sin plantilla', en: 'No template' },
  'admin.wa.blocked': { es: 'Plantilla pendiente de aprobación en Meta', en: 'Template pending Meta approval' },
  'admin.wa.preview': { es: 'Vista previa', en: 'Preview' },
  'admin.wa.cta': { es: 'Abrir en la app', en: 'Open in app' },
  'admin.wa.editTemplate': { es: 'Editar plantilla', en: 'Edit template' },
  'admin.wa.test': { es: 'Enviarme una prueba', en: 'Send me a test' },
  'admin.wa.test.queue': { es: 'Poner prueba en cola', en: 'Queue a test' },
  'admin.wa.respectsQuiet': { es: 'Respeta las horas de silencio.', en: 'Respects quiet hours.' },
  'admin.wa.overridesQuiet': { es: 'Urgente: ignora las horas de silencio.', en: 'Urgent: overrides quiet hours.' },
  'admin.wa.log': { es: 'Registro de envíos', en: 'Message log' },
  'admin.wa.log.when': { es: 'Cuándo', en: 'When' },
  'admin.wa.log.to': { es: 'Para', en: 'To' },
  'admin.wa.log.template': { es: 'Plantilla', en: 'Template' },
  'admin.wa.log.status': { es: 'Estado', en: 'Status' },
  'admin.wa.log.empty': { es: 'Sin envíos todavía.', en: 'Nothing sent yet.' },
  'admin.wa.f.name': { es: 'Nombre', en: 'Name' },
  'admin.wa.f.category': { es: 'Categoría Meta', en: 'Meta category' },
  'admin.wa.f.body': { es: 'Cuerpo', en: 'Body' },
  'admin.wa.f.body.hint': { es: 'Variables numeradas {{1}}, {{2}}… como exige Meta.', en: 'Numbered variables {{1}}, {{2}}… as Meta requires.' },
  'admin.wa.f.approval': { es: 'Estado en Meta', en: 'Meta status' },
  'admin.wa.f.approval.hint': { es: 'Simulado hasta conectar la API de WhatsApp Business.', en: 'Simulated until the WhatsApp Business API is connected.' },

  // M-06 crm
  'admin.crm.title': { es: 'CRM', en: 'CRM' },
  'admin.crm.subtitle': { es: 'Una ficha por persona en la que todo el estudio confía.', en: 'One record per person the whole studio trusts.' },
  'admin.crm.search': { es: 'Buscar nombre, WhatsApp o email…', en: 'Search name, WhatsApp or email…' },
  'admin.crm.seg.all': { es: 'Todos', en: 'All' },
  'admin.crm.seg.all.body': { es: 'Todavía no hay clientes.', en: 'No customers yet.' },
  'admin.crm.seg.at_risk': { es: 'En riesgo', en: 'At risk' },
  'admin.crm.seg.at_risk.body': { es: 'Nadie ha bajado su ritmo de visitas.', en: 'Nobody has dropped their visit cadence.' },
  'admin.crm.seg.new': { es: 'Nuevos este mes', en: 'New this month' },
  'admin.crm.seg.new.body': { es: 'Nadie se registró este mes todavía.', en: 'Nobody signed up this month yet.' },
  'admin.crm.seg.no_membership': { es: 'Sin membresía', en: 'No membership' },
  'admin.crm.seg.no_membership.body': { es: 'Todos tienen membresía activa.', en: 'Everyone has an active membership.' },
  'admin.crm.seg.birthdays': { es: 'Cumpleaños', en: 'Birthdays' },
  'admin.crm.seg.birthdays.body': { es: 'Nadie cumple años este mes (o falta la fecha en el perfil).', en: 'No birthdays this month (or the date is missing on the profile).' },
  'admin.crm.emptySeg': { es: 'Nadie coincide todavía', en: 'Nobody matches yet' },
  'admin.crm.noPlan': { es: 'Sin plan', en: 'No plan' },
  'admin.crm.col.member': { es: 'Miembro', en: 'Member' },
  'admin.crm.col.plan': { es: 'Plan', en: 'Plan' },
  'admin.crm.col.visits': { es: 'Visitas', en: 'Visits' },
  'admin.crm.col.last': { es: 'Última visita', en: 'Last visit' },
  'admin.crm.col.risk': { es: 'Riesgo', en: 'Risk' },
  'admin.crm.col.since': { es: 'Desde', en: 'Since' },
  'admin.crm.risk.low': { es: 'Bajo', en: 'Low' },
  'admin.crm.risk.medium': { es: 'Medio', en: 'Medium' },
  'admin.crm.risk.high': { es: 'Alto', en: 'High' },

  'admin.member.notFound': { es: 'Miembro no encontrado', en: 'Member not found' },
  'admin.member.notFound.body': { es: 'El enlace es antiguo o la persona fue eliminada.', en: 'The link is old or the person was removed.' },
  'admin.member.since': { es: 'Desde {date}', en: 'Since {date}' },
  'admin.member.optin': { es: 'Marketing', en: 'Marketing' },
  'admin.member.consent': { es: '{n} consentimientos', en: '{n} consents' },
  'admin.member.ltv': { es: 'Valor total (LTV)', en: 'Lifetime value' },
  'admin.member.visits': { es: 'Visitas', en: 'Visits' },
  'admin.member.credits': { es: '{n} créditos', en: '{n} credits' },
  'admin.member.lastVisit': { es: 'Última visita', en: 'Last visit' },
  'admin.member.risk.hint': { es: 'según su propio ritmo', en: 'against own cadence' },
  'admin.member.tab.timeline': { es: 'Línea de tiempo', en: 'Timeline' },
  'admin.member.tab.bookings': { es: 'Reservas', en: 'Bookings' },
  'admin.member.tab.payments': { es: 'Pagos', en: 'Payments' },
  'admin.member.tab.notes': { es: 'Notas', en: 'Notes' },
  'admin.member.timeline.empty': { es: 'Sin eventos todavía.', en: 'No events yet.' },
  'admin.member.bookings.empty': { es: 'Sin reservas.', en: 'No bookings.' },
  'admin.member.payments.empty': { es: 'Sin pagos.', en: 'No payments.' },
  'admin.member.automation': { es: 'automatización', en: 'automation' },
  'admin.member.payment': { es: 'Pago', en: 'Payment' },
  'admin.member.note': { es: 'Nota interna', en: 'Staff note' },
  'admin.member.booking.booked': { es: 'Reserva', en: 'Booking' },
  'admin.member.booking.checked_in': { es: 'Check-in', en: 'Check-in' },
  'admin.member.booking.no_show': { es: 'No vino', en: 'No-show' },
  'admin.member.booking.late_cancel': { es: 'Cancelación tardía', en: 'Late cancel' },
  'admin.member.booking.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'admin.member.col.when': { es: 'Cuándo', en: 'When' },
  'admin.member.col.class': { es: 'Clase', en: 'Class' },
  'admin.member.col.status': { es: 'Estado', en: 'Status' },
  'admin.member.col.paidWith': { es: 'Pagado con', en: 'Paid with' },
  'admin.member.col.product': { es: 'Producto', en: 'Product' },
  'admin.member.col.amount': { es: 'Importe', en: 'Amount' },
  'admin.member.col.method': { es: 'Método', en: 'Method' },
  'admin.member.notes.rule': { es: 'Internas: la persona nunca las ve. Las señales de salud aparecen al profesor solo como marcador.', en: 'Internal: the member never sees them. Health flags surface to teachers as a marker only.' },
  'admin.member.notes.ph': { es: 'Preguntó por pase de invitado. Mencionó molestia en la rodilla…', en: 'Asked about a guest pass. Mentioned a knee issue…' },
  'admin.member.notes.add': { es: 'Guardar nota', en: 'Save note' },
  'admin.member.notes.empty': { es: 'Sin notas todavía.', en: 'No notes yet.' },
  'admin.member.compose.wa': { es: 'Mensaje manual desde el número de {studio}. Queda en el registro de mensajes.', en: 'Manual message from the {studio} number. Logged in the message log.' },
  'admin.member.compose.email': { es: 'Email manual desde el estudio. Queda en el registro de mensajes.', en: 'Manual email from the studio. Logged in the message log.' },
  'admin.member.compose.text': { es: 'Mensaje', en: 'Message' },
  'admin.member.compose.unverified': { es: 'Número sin verificar: podría no entregarse', en: 'Unverified number: may not deliver' },
  'admin.member.compose.send': { es: 'Enviar', en: 'Send' },
  'admin.member.viewLogged': { es: 'Abrir esta ficha quedó registrado en el log de actividad (Ley 1581).', en: 'Opening this record was written to the activity log (Ley 1581).' },

  // M-07 activity
  'admin.activity.title': { es: 'Registro de actividad', en: 'Activity log' },
  'admin.activity.subtitle': { es: 'Quién hizo qué, sobre qué y cuándo. Nada aquí se edita ni se borra.', en: 'Who did what, on what and when. Nothing here is edited or deleted.' },
  'admin.activity.export': { es: 'Exportar CSV', en: 'Export CSV' },
  'admin.activity.range': { es: 'Rango', en: 'Range' },
  'admin.activity.range.today': { es: 'Hoy', en: 'Today' },
  'admin.activity.range.7d': { es: 'Últimos 7 días', en: 'Last 7 days' },
  'admin.activity.range.30d': { es: 'Últimos 30 días', en: 'Last 30 days' },
  'admin.activity.range.all': { es: 'Todo', en: 'All time' },
  'admin.activity.anyone': { es: 'Cualquier persona', en: 'Anyone' },
  'admin.activity.anyArea': { es: 'Cualquier área', en: 'Any area' },
  'admin.activity.searchAction': { es: 'Buscar acción…', en: 'Search action…' },
  'admin.activity.col.when': { es: 'Cuándo', en: 'When' },
  'admin.activity.col.who': { es: 'Quién', en: 'Who' },
  'admin.activity.col.action': { es: 'Acción', en: 'Action' },
  'admin.activity.col.object': { es: 'Objeto', en: 'Object' },
  'admin.activity.col.source': { es: 'Origen', en: 'Source' },
  'admin.activity.automation': { es: 'Automatización', en: 'Automation' },
  'admin.activity.system': { es: 'Sistema', en: 'System' },
  'admin.activity.empty': { es: 'Sin actividad en este rango', en: 'No activity in this range' },
  'admin.activity.empty.body': { es: 'Amplía el rango o quita filtros.', en: 'Widen the range or remove filters.' },
  'admin.activity.retention': { es: 'Solo anexar: ningún rol puede editar o borrar filas. Se conservan 24 meses y luego pasan a archivo frío.', en: 'Append-only: no role can edit or delete rows. Retained 24 months, then archived to cold storage.' },
  'admin.activity.before': { es: 'Antes', en: 'Before' },
  'admin.activity.after': { es: 'Después', en: 'After' },
  'admin.activity.raw': { es: 'Detalle', en: 'Detail' },
  'admin.activity.immutable': { es: 'Esta fila es inmutable.', en: 'This row is immutable.' },

  // M-08 settings
  'admin.settings.title': { es: 'Ajustes y políticas', en: 'Settings & policies' },
  'admin.settings.subtitle': { es: 'Los parámetros que leen todas las demás pantallas. Cambia uno aquí y cambia en todas partes.', en: 'The parameters every other screen reads. Change one here and it changes everywhere.' },
  'admin.settings.readonly': { es: 'Solo lectura para tu rol', en: 'Read-only for your role' },
  'admin.settings.saved': { es: 'Guardado', en: 'Saved' },
  'admin.settings.unsaved': { es: 'Sin guardar', en: 'Unsaved' },
  'admin.settings.sec.profile': { es: 'Estudio', en: 'Studio' },
  'admin.settings.sec.openingHours': { es: 'Horarios', en: 'Opening hours' },
  'admin.settings.sec.studio': { es: 'Capacidad', en: 'Capacity' },
  'admin.settings.sec.policies': { es: 'Políticas', en: 'Policies' },
  'admin.settings.sec.quietHours': { es: 'Horas de silencio', en: 'Quiet hours' },
  'admin.settings.sec.tax': { es: 'Impuestos y facturación', en: 'Tax & invoicing' },
  'admin.settings.sec.features': { es: 'Funciones', en: 'Features' },
  'admin.settings.sec.integrations': { es: 'Integraciones', en: 'Integrations' },
  'admin.settings.f.name': { es: 'Nombre', en: 'Name' },
  'admin.settings.f.name.hint': { es: 'Identidad en src/tenant/tenant.ts', en: 'Identity lives in src/tenant/tenant.ts' },
  'admin.settings.f.legal': { es: 'Razón social', en: 'Legal name' },
  'admin.settings.f.address': { es: 'Dirección', en: 'Address' },
  'admin.settings.open': { es: 'Abierto', en: 'Open' },
  'admin.settings.closed': { es: 'Cerrado', en: 'Closed' },
  'admin.settings.hours.note': { es: 'El calendario de festivos llega con la función “Calendario de festivos”.', en: 'The holiday calendar arrives with the “Holiday calendar” feature.' },
  'admin.settings.f.mats': { es: 'Mats por clase', en: 'Mats per class' },
  'admin.settings.f.mats.hint': { es: 'Lo citan lista de espera, medidor de cupos y checkout', en: 'Quoted by waitlist, capacity meter and checkout' },
  'admin.settings.f.classesPerDay': { es: 'Clases por día', en: 'Classes per day' },
  'admin.settings.f.perPerson': { es: 'Clases por persona y día', en: 'Classes per person per day' },
  'admin.settings.f.perPerson.hint': { es: 'C-01 · C-04', en: 'C-01 · C-04' },
  'admin.settings.rooms': { es: 'Salas', en: 'Rooms' },
  'admin.settings.rooms.edit': { es: 'Editar salas en Contenido →', en: 'Edit rooms in Content →' },
  'admin.settings.f.cancellation': { es: 'Ventana de cancelación (h)', en: 'Cancellation window (h)' },
  'admin.settings.f.waitlistClaim': { es: 'Reclamo de lista de espera (min)', en: 'Waitlist claim window (min)' },
  'admin.settings.f.lateGrace': { es: 'Gracia de llegada tarde (min)', en: 'Late check-in grace (min)' },
  'admin.settings.f.noShowFee': { es: 'Cargo por no asistir', en: 'No-show fee' },
  'admin.settings.f.noShowFee.off': { es: 'Apagado en Funciones', en: 'Off in Features' },
  'admin.settings.f.pauseDays': { es: 'Días de pausa al año', en: 'Pause days per year' },
  'admin.settings.f.maxPauses': { es: 'Pausas al año', en: 'Pauses per year' },
  'admin.settings.policies.note': { es: 'Un cambio de política aplica solo a reservas futuras; las existentes conservan sus términos.', en: 'A policy change applies to future bookings only; existing ones keep their terms.' },
  'admin.settings.f.from': { es: 'Desde', en: 'From' },
  'admin.settings.f.to': { es: 'Hasta', en: 'To' },
  'admin.settings.quiet.note': { es: 'Los mensajes no urgentes de WhatsApp esperan hasta que termine el silencio. Las cancelaciones pasan siempre.', en: 'Non-urgent WhatsApp messages wait until quiet hours end. Cancellations always go through.' },
  'admin.settings.f.iva': { es: 'IVA (%)', en: 'IVA (%)' },
  'admin.settings.f.dian': { es: 'Resolución DIAN', en: 'DIAN resolution' },
  'admin.settings.f.dian.hint': { es: 'Número y rango autorizado', en: 'Number and authorised range' },
  'admin.settings.f.included': { es: 'Los precios publicados incluyen IVA', en: 'Published prices include IVA' },
  'admin.settings.f.eInvoicing': { es: 'Facturación electrónica activa', en: 'Electronic invoicing on' },
  'admin.settings.tax.needsDian': { es: 'La facturación electrónica necesita la resolución DIAN antes de encenderse.', en: 'Electronic invoicing needs the DIAN resolution before it can be switched on.' },
  'admin.settings.feat.multipleLocations': { es: 'Varias sedes', en: 'Multiple locations' },
  'admin.settings.feat.noShowFee': { es: 'Cargo por no asistir', en: 'No-show fee' },
  'admin.settings.feat.holidayCalendar': { es: 'Calendario de festivos', en: 'Holiday calendar' },
  'admin.settings.feat.walkInRegistration': { es: 'Registro walk-in en recepción', en: 'Walk-in registration at the desk' },
  'admin.settings.feat.autoCheckinOnSale': { es: 'Check-in automático al vender', en: 'Auto check-in on sale' },
  'admin.settings.features.note': { es: 'Los interruptores por pantalla ({on} de {n} activos) viven en el panel:', en: 'Per-screen switches ({on} of {n} on) live on the dashboard:' },
  'admin.settings.int.wompi': { es: 'Wompi', en: 'Wompi' },
  'admin.settings.int.wompi.body': { es: 'Pagos con tarjeta, PSE, Nequi y nómina.', en: 'Card, PSE, Nequi payments and payroll.' },
  'admin.settings.int.whatsapp': { es: 'WhatsApp Business API', en: 'WhatsApp Business API' },
  'admin.settings.int.whatsapp.body': { es: 'Plantillas, OTP y automatizaciones.', en: 'Templates, OTP and automations.' },
  'admin.settings.int.email': { es: 'Email transaccional', en: 'Transactional email' },
  'admin.settings.int.email.body': { es: 'Recibos, recordatorios, reportes.', en: 'Receipts, reminders, reports.' },
  'admin.settings.int.calendar': { es: 'Calendario', en: 'Calendar' },
  'admin.settings.int.calendar.body': { es: 'Sincronización de clases con Google / Apple.', en: 'Class sync with Google / Apple.' },
  'admin.settings.int.status.pending': { es: 'Pendiente', en: 'Pending' },
  'admin.settings.int.status.connected': { es: 'Conectado', en: 'Connected' },
  'admin.settings.int.status.error': { es: 'Con error', en: 'Error' },
  'admin.settings.int.note': { es: 'Las credenciales se escriben una vez y nunca se muestran. El estado aquí es un marcador hasta conectar cada servicio.', en: 'Credentials are write-only and never displayed. The status here is a placeholder until each service is connected.' },

  // M-09 finance
  'admin.finance.nav': { es: 'Finanzas', en: 'Finance' },
  'admin.finance.title': { es: 'Finanzas', en: 'Finance' },
  'admin.finance.subtitle': { es: 'Ingresos por producto y método, pendientes, reembolsos y facturas con referencia DIAN.', en: 'Revenue by product and method, pending, refunds and invoices with the DIAN reference.' },
  'admin.finance.range.7d': { es: '7 días', en: '7 days' },
  'admin.finance.range.30d': { es: '30 días', en: '30 days' },
  'admin.finance.range.90d': { es: '90 días', en: '90 days' },
  'admin.finance.range.all': { es: 'Todo', en: 'All' },
  'admin.finance.revenue': { es: 'Ingresos', en: 'Revenue' },
  'admin.finance.revenue.hint': { es: '{n} pagos aprobados', en: '{n} approved payments' },
  'admin.finance.pending': { es: 'Pendientes', en: 'Pending' },
  'admin.finance.pending.hint': { es: '{n} links / transferencias sin confirmar', en: '{n} unconfirmed links / transfers' },
  'admin.finance.refunded': { es: 'Reembolsado', en: 'Refunded' },
  'admin.finance.refunded.hint': { es: '{n} reembolsos', en: '{n} refunds' },
  'admin.finance.wompiShare': { es: 'Vía Wompi', en: 'Via Wompi' },
  'admin.finance.wompiShare.hint': { es: 'resto: efectivo / manual', en: 'rest: cash / manual' },
  'admin.finance.byProduct': { es: 'Ingresos por producto', en: 'Revenue by product' },
  'admin.finance.byMethod': { es: 'Ingresos por método', en: 'Revenue by method' },
  'admin.finance.emptyRange': { es: 'Sin movimientos en este rango.', en: 'No activity in this range.' },
  'admin.finance.method.card': { es: 'Tarjeta', en: 'Card' },
  'admin.finance.method.pse': { es: 'PSE', en: 'PSE' },
  'admin.finance.method.nequi': { es: 'Nequi', en: 'Nequi' },
  'admin.finance.method.cash': { es: 'Efectivo', en: 'Cash' },
  'admin.finance.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'admin.finance.method.gift_card': { es: 'Bono regalo', en: 'Gift card' },
  'admin.finance.payouts': { es: 'Liquidaciones (payouts)', en: 'Payouts' },
  'admin.finance.payouts.next': { es: 'Próxima liquidación', en: 'Next payout' },
  'admin.finance.payouts.placeholder': { es: 'marcador hasta conectar Wompi', en: 'placeholder until Wompi is connected' },
  'admin.finance.payouts.settled': { es: 'Cobrado vía Wompi', en: 'Collected via Wompi' },
  'admin.finance.payouts.settled.hint': { es: 'en el rango', en: 'in range' },
  'admin.finance.payouts.manual': { es: 'Cobrado en mostrador', en: 'Collected at the desk' },
  'admin.finance.payouts.manual.hint': { es: 'efectivo, datáfono, transferencia', en: 'cash, terminal, transfer' },
  'admin.finance.payouts.body': { es: 'Cuando Wompi esté conectado, aquí aparecen las liquidaciones a la cuenta del estudio y la nómina de profesores.', en: 'Once Wompi is connected, payouts to the studio account and teacher payroll show here.' },
  'admin.finance.payments': { es: 'Pagos', en: 'Payments' },
  'admin.finance.refund': { es: 'Reembolsar', en: 'Refund' },
  'admin.finance.refund.confirm': { es: '¿Reembolsar {amount}? El pago pasa a “refunded” y queda en el registro.', en: 'Refund {amount}? The payment becomes “refunded” and is logged.' },
  'admin.finance.refund.noPermission': { es: 'Solo finanzas y administración reembolsan.', en: 'Only finance and admin can refund.' },
  'admin.finance.col.when': { es: 'Cuándo', en: 'When' },
  'admin.finance.col.member': { es: 'Miembro', en: 'Member' },
  'admin.finance.col.product': { es: 'Producto', en: 'Product' },
  'admin.finance.col.amount': { es: 'Importe', en: 'Amount' },
  'admin.finance.col.method': { es: 'Método', en: 'Method' },
  'admin.finance.col.status': { es: 'Estado', en: 'Status' },
  'admin.finance.col.invoice': { es: 'Factura', en: 'Invoice' },
  'admin.finance.col.cufe': { es: 'CUFE (DIAN)', en: 'CUFE (DIAN)' },
  'admin.finance.noCufe': { es: 'sin CUFE', en: 'no CUFE' },
  'admin.finance.cufe.pending': { es: 'Pendiente de emitir', en: 'Pending issue' },
  'admin.finance.cufe.off': { es: 'Facturación electrónica apagada', en: 'E-invoicing off' },
  'admin.finance.invoices': { es: 'Facturas', en: 'Invoices' },
  'admin.finance.einv.on': { es: 'Facturación electrónica activa: el CUFE se asigna al emitir en DIAN.', en: 'E-invoicing on: the CUFE is assigned when issued at DIAN.' },
  'admin.finance.einv.off': { es: 'Activa la facturación electrónica en Ajustes → Impuestos cuando tengas la resolución DIAN.', en: 'Turn on e-invoicing in Settings → Tax once you have the DIAN resolution.' },
};
