import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  // M-03 tables
  'admin.tables.title': { es: 'Tablas', en: 'Tables' },
  'admin.tables.subtitle': { es: 'Todas las tablas del sistema, tal como vivirán en Supabase. Edita filas, filtra y exporta.', en: 'Every table in the system, as it will live in Supabase. Edit rows, filter and export.' },
  'admin.tables.pick': { es: 'Elige una tabla en la barra lateral.', en: 'Pick a table in the sidebar.' },
  'admin.tables.search': { es: 'Buscar en {table}…', en: 'Search {table}…' },
  'admin.tables.columns': { es: '{n} columnas', en: '{n} columns' },
  'admin.tables.row': { es: 'Fila', en: 'Row' },
  'admin.tables.references': { es: 'referencia a', en: 'references' },
  'admin.tables.provider': { es: 'Proveedor: {name}', en: 'Provider: {name}' },
  'admin.tables.resetSeed': { es: 'Reiniciar datos demo', en: 'Reset demo data' },
  'admin.tables.resetConfirm': { es: '¿Borrar todos los cambios y volver a los datos demo?', en: 'Discard all changes and return to demo data?' },
  'admin.tables.addRow': { es: 'Nueva fila', en: 'New row' },
  'admin.tables.deleteConfirm': { es: '¿Eliminar esta fila?', en: 'Delete this row?' },
  'admin.tables.saved': { es: 'Guardado', en: 'Saved' },
  'admin.tables.readonly': { es: 'Solo lectura (generado)', en: 'Read only (generated)' },
  'admin.tables.groups': { es: 'Grupos', en: 'Groups' },
  'admin.tables.schema': { es: 'Esquema', en: 'Schema' },
  'admin.tables.data': { es: 'Datos', en: 'Data' },

  // M-01 dashboard
  'admin.dashboard.title': { es: 'Panel', en: 'Dashboard' },
  'admin.dashboard.members': { es: 'Miembros activos', en: 'Active members' },
  'admin.dashboard.revenue': { es: 'Ingresos 30 días', en: 'Revenue 30 days' },
  'admin.dashboard.occupancy': { es: 'Ocupación 7 días', en: 'Occupancy 7 days' },
  'admin.dashboard.arrivals': { es: 'Llegadas hoy', en: 'Arrivals today' },
  'admin.dashboard.arrivals.hint': { es: 'en {n} clases', en: 'across {n} classes' },
  'admin.dashboard.occChart': { es: 'Ocupación por día', en: 'Occupancy by day' },
  'admin.dashboard.occChart.eyebrow': { es: 'Reservas / cupos · 7 días', en: 'Bookings / capacity · 7 days' },
  'admin.dashboard.today': { es: 'Hoy en un vistazo', en: 'Today at a glance' },
  'admin.dashboard.today.eyebrow': { es: 'Clases de hoy · ocupación y quién ya está en sala', en: 'Today’s classes · occupancy and who is already in the room' },
  'admin.dashboard.today.empty': { es: 'Hoy no hay clases programadas', en: 'No classes scheduled today' },
  'admin.dashboard.today.inRoom': { es: '{n} en sala', en: '{n} in the room' },
  'admin.dashboard.audit': { es: 'Actividad reciente', en: 'Recent activity' },
  'admin.dashboard.system': { es: 'Sistema', en: 'System' },

  // M-02 content
  'admin.content.title': { es: 'Contenido', en: 'Content' },
  'admin.content.subtitle': { es: 'Clases, profesores, modalidades y salas: la fuente de la app, el sitio y recepción.', en: 'Classes, teachers, modalities and rooms: the source for the app, the website and the desk.' },
  'admin.content.tab.class_templates': { es: 'Clases (plantillas)', en: 'Classes (templates)' },
  'admin.content.tab.teachers': { es: 'Profesores', en: 'Teachers' },
  'admin.content.tab.modalities': { es: 'Modalidades', en: 'Modalities' },
  'admin.content.tab.rooms': { es: 'Salas', en: 'Rooms' },
  'admin.content.pricingNote': { es: 'Los precios viven en el Modelo de Valor (P-01) y no se editan aquí.', en: 'Prices live in the value model (P-01) and are not edited here.' },
  'admin.content.add': { es: 'Crear', en: 'Create' },
  'admin.content.published': { es: 'Publicado', en: 'Published' },
  'admin.content.draft': { es: 'Borrador', en: 'Draft' },
  'admin.content.empty': { es: 'Crea el primer elemento', en: 'Create the first item' },
  'admin.content.empty.body': { es: 'Empieza en borrador y publica cuando el español esté listo.', en: 'Start as a draft and publish once the Spanish is ready.' },
  'admin.content.deleteConfirm': { es: '¿Eliminar este elemento? Las sesiones ya generadas no cambian.', en: 'Delete this item? Already generated sessions do not change.' },
  'admin.content.required': { es: 'Obligatorio (español)', en: 'Required (Spanish)' },
  'admin.content.unsaved': { es: 'Cambios sin guardar', en: 'Unsaved changes' },
  'admin.content.upToDate': { es: 'Al día', en: 'Up to date' },
  'admin.content.preview': { es: 'Vista previa · app / web', en: 'Preview · app / web' },
  'admin.content.intensity': { es: 'intensidad', en: 'intensity' },

  // M-04 emails
  'admin.emails.title': { es: 'Emails transaccionales', en: 'Transactional emails' },
  'admin.emails.subtitle': { es: 'Cada email automático como diseño real, en dos idiomas, con su disparador y enlace profundo.', en: 'Every automated email as a real design, in both languages, with its trigger and deep link.' },
  'admin.emails.createMissing': { es: 'Crear {n} plantillas estándar', en: 'Create {n} standard templates' },
  'admin.emails.empty': { es: 'Sin plantillas todavía', en: 'No templates yet' },
  'admin.emails.empty.body': { es: 'Crea el set estándar: reserva, recibo, cancelación, lista de espera, recordatorio, preparación, cumpleaños, renovación, pago fallido, regalo, invitación.', en: 'Create the standard set: booking, receipt, cancellation, waitlist, reminder, preparation, birthday, renewal, failed payment, gift, invite.' },
  'admin.emails.draft': { es: 'Borrador', en: 'Draft' },
  'admin.emails.deepLink': { es: 'El botón enlaza a la pantalla correspondiente en la app o el sitio.', en: 'The button deep-links into the matching app screen or website page.' },
  'admin.emails.dianNote': { es: 'Los recibos incluyen la referencia DIAN cuando exista.', en: 'Receipts include the DIAN reference once it exists.' },
  'admin.emails.versions': { es: 'Versiones', en: 'Versions' },
  'admin.emails.versions.empty': { es: 'Sin cambios registrados todavía.', en: 'No changes recorded yet.' },
  'admin.emails.rollback': { es: 'Restaurar', en: 'Roll back' },
  'admin.emails.log': { es: 'Envíos', en: 'Send log' },
  'admin.emails.log.when': { es: 'Cuándo', en: 'When' },
  'admin.emails.log.to': { es: 'Para', en: 'To' },
  'admin.emails.log.template': { es: 'Plantilla', en: 'Template' },
  'admin.emails.log.status': { es: 'Estado', en: 'Status' },
  'admin.emails.log.empty': { es: 'Sin envíos todavía.', en: 'Nothing sent yet.' },
  'admin.emails.f.name': { es: 'Nombre', en: 'Name' },
  'admin.emails.f.trigger': { es: 'Disparador', en: 'Trigger' },
  'admin.emails.f.trigger.hint': { es: 'Evento del sistema, p. ej. booking.created', en: 'System event, e.g. booking.created' },
  'admin.emails.f.subject': { es: 'Asunto', en: 'Subject' },
  'admin.emails.f.body': { es: 'Cuerpo', en: 'Body' },
  'admin.emails.f.cta': { es: 'Botón', en: 'Button' },
  'admin.emails.f.deepLink': { es: 'Enlace profundo', en: 'Deep link' },
  'admin.emails.f.active': { es: 'Activo', en: 'Active' },
  'admin.emails.vars': { es: 'Variables', en: 'Variables' },
  'admin.emails.missingEn': { es: 'Falta la traducción al inglés: no se puede activar.', en: 'English translation missing: cannot activate.' },
  'admin.emails.test': { es: 'Enviarme una prueba', en: 'Send me a test' },
  'admin.emails.saveVersion': { es: 'Guardar v{v}', en: 'Save v{v}' },
  'admin.emails.unsaved': { es: 'Cambios sin guardar.', en: 'Unsaved changes.' },

  // M-05 whatsapp
  'admin.wa.title': { es: 'Automatizaciones de WhatsApp', en: 'WhatsApp automations' },
  'admin.wa.subtitle': { es: 'Plantillas aprobadas por Meta, sus disparadores, tiempos y horas de silencio.', en: 'Meta-approved templates, their triggers, timing and quiet hours.' },
  'admin.wa.createMissing': { es: 'Crear {n} automatizaciones estándar', en: 'Create {n} standard automations' },
  'admin.wa.empty': { es: 'Sin automatizaciones todavía', en: 'No automations yet' },
  'admin.wa.empty.body': { es: 'Crea el set estándar: reserva, recordatorio, cancelación, lista de espera, cumpleaños, recibo, membresía, feedback, invitación.', en: 'Create the standard set: booking, reminder, cancellation, waitlist, birthday, receipt, membership, feedback, invite.' },
  'admin.wa.quiet': { es: 'Horas de silencio', en: 'Quiet hours' },
  'admin.wa.quiet.body': { es: 'Los mensajes no urgentes esperan hasta la mañana. Las cancelaciones pasan.', en: 'Non-urgent messages wait until morning. Cancellations go through.' },
  'admin.wa.quiet.now': { es: 'Ahora mismo estamos en silencio: los envíos quedan en cola.', en: 'Quiet hours are on right now: sends are queued.' },
  'admin.wa.optin': { es: 'Opt-in', en: 'Opt-in' },
  'admin.wa.optin.body': { es: 'Solo números verificados con opt-in reciben automatizaciones. El opt-out es inmediato y permanente.', en: 'Only verified, opted-in numbers get automations. Opt-out is immediate and permanent.' },
  'admin.wa.meta': { es: 'Aprobadas por Meta', en: 'Meta approved' },
  'admin.wa.meta.body': { es: 'Una automatización no se activa hasta que su plantilla esté aprobada.', en: 'An automation cannot be enabled until its template is approved.' },
  'admin.wa.col.automation': { es: 'Automatización', en: 'Automation' },
  'admin.wa.col.trigger': { es: 'Disparador', en: 'Trigger' },
  'admin.wa.col.delay': { es: 'Cuándo', en: 'When' },
  'admin.wa.col.status': { es: 'Meta', en: 'Meta' },
  'admin.wa.approval.draft': { es: 'Borrador', en: 'Draft' },
  'admin.wa.approval.pending': { es: 'Pendiente', en: 'Pending' },
  'admin.wa.approval.approved': { es: 'Aprobada', en: 'Approved' },
  'admin.wa.approval.rejected': { es: 'Rechazada', en: 'Rejected' },
  'admin.wa.noTemplate': { es: 'Sin plantilla', en: 'No template' },
  'admin.wa.blocked': { es: 'Plantilla pendiente de aprobación en Meta', en: 'Template pending Meta approval' },
  'admin.wa.preview': { es: 'Vista previa', en: 'Preview' },
  'admin.wa.cta': { es: 'Abrir en la app', en: 'Open in app' },
  'admin.wa.editTemplate': { es: 'Editar plantilla', en: 'Edit template' },
  'admin.wa.test': { es: 'Enviarme una prueba', en: 'Send me a test' },
  'admin.wa.test.queue': { es: 'Poner prueba en cola', en: 'Queue a test' },
  'admin.wa.respectsQuiet': { es: 'Respeta las horas de silencio.', en: 'Respects quiet hours.' },
  'admin.wa.overridesQuiet': { es: 'Urgente: ignora las horas de silencio.', en: 'Urgent: overrides quiet hours.' },
  'admin.wa.log': { es: 'Registro de envíos', en: 'Message log' },
  'admin.wa.log.when': { es: 'Cuándo', en: 'When' },
  'admin.wa.log.to': { es: 'Para', en: 'To' },
  'admin.wa.log.template': { es: 'Plantilla', en: 'Template' },
  'admin.wa.log.status': { es: 'Estado', en: 'Status' },
  'admin.wa.log.empty': { es: 'Sin envíos todavía.', en: 'Nothing sent yet.' },
  'admin.wa.f.name': { es: 'Nombre', en: 'Name' },
  'admin.wa.f.category': { es: 'Categoría Meta', en: 'Meta category' },
  'admin.wa.f.body': { es: 'Cuerpo', en: 'Body' },
  'admin.wa.f.body.hint': { es: 'Variables numeradas {{1}}, {{2}}… como exige Meta.', en: 'Numbered variables {{1}}, {{2}}… as Meta requires.' },
  'admin.wa.f.approval': { es: 'Estado en Meta', en: 'Meta status' },
  'admin.wa.f.approval.hint': { es: 'Simulado hasta conectar la API de WhatsApp Business.', en: 'Simulated until the WhatsApp Business API is connected.' },

  // M-06 crm
  'admin.crm.title': { es: 'CRM', en: 'CRM' },
  'admin.crm.subtitle': { es: 'Una ficha por persona en la que todo el estudio confía.', en: 'One record per person the whole studio trusts.' },
  'admin.crm.search': { es: 'Buscar nombre, WhatsApp o email…', en: 'Search name, WhatsApp or email…' },
  'admin.crm.seg.all': { es: 'Todos', en: 'All' },
  'admin.crm.seg.all.body': { es: 'Todavía no hay clientes.', en: 'No customers yet.' },
  'admin.crm.seg.at_risk': { es: 'En riesgo', en: 'At risk' },
  'admin.crm.seg.at_risk.body': { es: 'Nadie ha bajado su ritmo de visitas.', en: 'Nobody has dropped their visit cadence.' },
  'admin.crm.seg.new': { es: 'Nuevos este mes', en: 'New this month' },
  'admin.crm.seg.new.body': { es: 'Nadie se registró este mes todavía.', en: 'Nobody signed up this month yet.' },
  'admin.crm.seg.no_membership': { es: 'Sin membresía', en: 'No membership' },
  'admin.crm.seg.no_membership.body': { es: 'Todos tienen membresía activa.', en: 'Everyone has an active membership.' },
  'admin.crm.seg.birthdays': { es: 'Cumpleaños', en: 'Birthdays' },
  'admin.crm.seg.birthdays.body': { es: 'Nadie cumple años este mes (o falta la fecha en el perfil).', en: 'No birthdays this month (or the date is missing on the profile).' },
  'admin.crm.emptySeg': { es: 'Nadie coincide todavía', en: 'Nobody matches yet' },
  'admin.crm.noPlan': { es: 'Sin plan', en: 'No plan' },
  'admin.crm.col.member': { es: 'Miembro', en: 'Member' },
  'admin.crm.col.plan': { es: 'Plan', en: 'Plan' },
  'admin.crm.col.visits': { es: 'Visitas', en: 'Visits' },
  'admin.crm.col.last': { es: 'Última visita', en: 'Last visit' },
  'admin.crm.col.risk': { es: 'Riesgo', en: 'Risk' },
  'admin.crm.col.since': { es: 'Desde', en: 'Since' },
  'admin.crm.risk.low': { es: 'Bajo', en: 'Low' },
  'admin.crm.risk.medium': { es: 'Medio', en: 'Medium' },
  'admin.crm.risk.high': { es: 'Alto', en: 'High' },

  'admin.member.notFound': { es: 'Miembro no encontrado', en: 'Member not found' },
  'admin.member.notFound.body': { es: 'El enlace es antiguo o la persona fue eliminada.', en: 'The link is old or the person was removed.' },
  'admin.member.since': { es: 'Desde {date}', en: 'Since {date}' },
  'admin.member.optin': { es: 'Marketing', en: 'Marketing' },
  'admin.member.consent': { es: '{n} consentimientos', en: '{n} consents' },
  'admin.member.ltv': { es: 'Valor total (LTV)', en: 'Lifetime value' },
  'admin.member.visits': { es: 'Visitas', en: 'Visits' },
  'admin.member.credits': { es: '{n} créditos', en: '{n} credits' },
  'admin.member.lastVisit': { es: 'Última visita', en: 'Last visit' },
  'admin.member.risk.hint': { es: 'según su propio ritmo', en: 'against own cadence' },
  'admin.member.tab.timeline': { es: 'Línea de tiempo', en: 'Timeline' },
  'admin.member.tab.bookings': { es: 'Reservas', en: 'Bookings' },
  'admin.member.tab.payments': { es: 'Pagos', en: 'Payments' },
  'admin.member.tab.notes': { es: 'Notas', en: 'Notes' },
  'admin.member.timeline.empty': { es: 'Sin eventos todavía.', en: 'No events yet.' },
  'admin.member.bookings.empty': { es: 'Sin reservas.', en: 'No bookings.' },
  'admin.member.payments.empty': { es: 'Sin pagos.', en: 'No payments.' },
  'admin.member.automation': { es: 'automatización', en: 'automation' },
  'admin.member.payment': { es: 'Pago', en: 'Payment' },
  'admin.member.note': { es: 'Nota interna', en: 'Staff note' },
  'admin.member.booking.booked': { es: 'Reserva', en: 'Booking' },
  'admin.member.booking.checked_in': { es: 'Check-in', en: 'Check-in' },
  'admin.member.booking.no_show': { es: 'No vino', en: 'No-show' },
  'admin.member.booking.late_cancel': { es: 'Cancelación tardía', en: 'Late cancel' },
  'admin.member.booking.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'admin.member.col.when': { es: 'Cuándo', en: 'When' },
  'admin.member.col.class': { es: 'Clase', en: 'Class' },
  'admin.member.col.status': { es: 'Estado', en: 'Status' },
  'admin.member.col.paidWith': { es: 'Pagado con', en: 'Paid with' },
  'admin.member.col.product': { es: 'Producto', en: 'Product' },
  'admin.member.col.amount': { es: 'Importe', en: 'Amount' },
  'admin.member.col.method': { es: 'Método', en: 'Method' },
  'admin.member.notes.rule': { es: 'Internas: la persona nunca las ve. Las señales de salud aparecen al profesor solo como marcador.', en: 'Internal: the member never sees them. Health flags surface to teachers as a marker only.' },
  'admin.member.notes.ph': { es: 'Preguntó por pase de invitado. Mencionó molestia en la rodilla…', en: 'Asked about a guest pass. Mentioned a knee issue…' },
  'admin.member.notes.add': { es: 'Guardar nota', en: 'Save note' },
  'admin.member.notes.empty': { es: 'Sin notas todavía.', en: 'No notes yet.' },
  'admin.member.compose.wa': { es: 'Mensaje manual desde el número de {studio}. Queda en el registro de mensajes.', en: 'Manual message from the {studio} number. Logged in the message log.' },
  'admin.member.compose.email': { es: 'Email manual desde el estudio. Queda en el registro de mensajes.', en: 'Manual email from the studio. Logged in the message log.' },
  'admin.member.compose.text': { es: 'Mensaje', en: 'Message' },
  'admin.member.compose.unverified': { es: 'Número sin verificar: podría no entregarse', en: 'Unverified number: may not deliver' },
  'admin.member.compose.send': { es: 'Enviar', en: 'Send' },
  'admin.member.viewLogged': { es: 'Abrir esta ficha quedó registrado en el log de actividad (Ley 1581).', en: 'Opening this record was written to the activity log (Ley 1581).' },

  // M-07 activity
  'admin.activity.title': { es: 'Registro de actividad', en: 'Activity log' },
  'admin.activity.subtitle': { es: 'Quién hizo qué, sobre qué y cuándo. Nada aquí se edita ni se borra.', en: 'Who did what, on what and when. Nothing here is edited or deleted.' },
  'admin.activity.export': { es: 'Exportar CSV', en: 'Export CSV' },
  'admin.activity.range': { es: 'Rango', en: 'Range' },
  'admin.activity.range.today': { es: 'Hoy', en: 'Today' },
  'admin.activity.range.7d': { es: 'Últimos 7 días', en: 'Last 7 days' },
  'admin.activity.range.30d': { es: 'Últimos 30 días', en: 'Last 30 days' },
  'admin.activity.range.all': { es: 'Todo', en: 'All time' },
  'admin.activity.anyone': { es: 'Cualquier persona', en: 'Anyone' },
  'admin.activity.anyArea': { es: 'Cualquier área', en: 'Any area' },
  'admin.activity.searchAction': { es: 'Buscar acción…', en: 'Search action…' },
  'admin.activity.col.when': { es: 'Cuándo', en: 'When' },
  'admin.activity.col.who': { es: 'Quién', en: 'Who' },
  'admin.activity.col.action': { es: 'Acción', en: 'Action' },
  'admin.activity.col.object': { es: 'Objeto', en: 'Object' },
  'admin.activity.col.source': { es: 'Origen', en: 'Source' },
  'admin.activity.automation': { es: 'Automatización', en: 'Automation' },
  'admin.activity.system': { es: 'Sistema', en: 'System' },
  'admin.activity.empty': { es: 'Sin actividad en este rango', en: 'No activity in this range' },
  'admin.activity.empty.body': { es: 'Amplía el rango o quita filtros.', en: 'Widen the range or remove filters.' },
  'admin.activity.retention': { es: 'Solo anexar: ningún rol puede editar o borrar filas. Se conservan 24 meses y luego pasan a archivo frío.', en: 'Append-only: no role can edit or delete rows. Retained 24 months, then archived to cold storage.' },
  'admin.activity.before': { es: 'Antes', en: 'Before' },
  'admin.activity.after': { es: 'Después', en: 'After' },
  'admin.activity.raw': { es: 'Detalle', en: 'Detail' },
  'admin.activity.immutable': { es: 'Esta fila es inmutable.', en: 'This row is immutable.' },

  // M-08 settings
  'admin.settings.title': { es: 'Ajustes y políticas', en: 'Settings & policies' },
  'admin.settings.group.general': { es: 'General', en: 'General' },
  'admin.settings.group.general.body': { es: 'Contacto, horarios, aforo y políticas: los números que leen todas las demás pantallas.', en: 'Contact, opening hours, capacity and policies: the numbers every other screen reads.' },
  'admin.settings.group.features': { es: 'Funciones', en: 'Features' },
  'admin.settings.group.features.body': { es: 'Interruptores del estudio y de cada pantalla. Cada cambio queda en el registro de actividad.', en: 'Studio-wide and per-screen switches. Every change is written to the activity log.' },
  'admin.settings.group.payments': { es: 'Pagos', en: 'Payments' },
  'admin.settings.group.payments.body': { es: 'Cuenta de consignación, NIT, IVA y resolución DIAN, y el entorno de Wompi.', en: 'Payout account, NIT, IVA and DIAN resolution, and the Wompi environment.' },
  'admin.settings.group.communications': { es: 'Comunicaciones', en: 'Communications' },
  'admin.settings.group.communications.body': { es: 'Horas de silencio y los nombres con los que salen WhatsApp y email.', en: 'Quiet hours and the names WhatsApp and email go out with.' },
  'admin.settings.group.branding': { es: 'Marca', en: 'Branding' },
  'admin.settings.group.branding.body': { es: 'Nombre visible, variante del wordmark e idioma por defecto.', en: 'Display name, wordmark variant and default language.' },
  'admin.settings.sec.payments': { es: 'Cuenta de consignación', en: 'Payout account' },
  'admin.settings.sec.fiscal': { es: 'Identidad fiscal', en: 'Fiscal identity' },
  'admin.settings.sec.senders': { es: 'Remitentes', en: 'Senders' },
  'admin.settings.sec.branding': { es: 'Marca', en: 'Branding' },
  'admin.settings.f.nit.hint': { es: 'Aparece en facturas y recibos', en: 'Printed on invoices and receipts' },
  'admin.settings.f.bank': { es: 'Banco', en: 'Bank' },
  'admin.settings.f.accountType': { es: 'Tipo de cuenta', en: 'Account type' },
  'admin.settings.f.savings': { es: 'Ahorros', en: 'Savings' },
  'admin.settings.f.checking': { es: 'Corriente', en: 'Checking' },
  'admin.settings.f.accountNumber': { es: 'Número de cuenta', en: 'Account number' },
  'admin.settings.f.accountHolder': { es: 'Titular', en: 'Account holder' },
  'admin.settings.f.wompiEnv': { es: 'Entorno', en: 'Environment' },
  'admin.settings.f.production': { es: 'Producción', en: 'Production' },
  'admin.settings.pay.keys.title': { es: 'Llaves de Wompi: nunca se guardan aquí', en: 'Wompi keys: never stored here' },
  'admin.settings.pay.keys.body': { es: 'La llave privada y el secreto de eventos viven en variables de entorno del servidor. HoyOS no las guarda en la base de datos ni las muestra en el navegador; este panel solo elige el entorno.', en: 'The private key and the events secret live in server environment variables. HoyOS never stores them in the database nor shows them in the browser; this panel only picks the environment.' },
  'admin.settings.f.waSender': { es: 'Nombre en WhatsApp', en: 'WhatsApp sender name' },
  'admin.settings.f.waSender.hint': { es: 'Debe coincidir con el perfil aprobado por Meta', en: 'Must match the Meta-approved profile' },
  'admin.settings.f.emailSender': { es: 'Nombre del remitente de email', en: 'Email sender name' },
  'admin.settings.f.replyTo': { es: 'Responder a', en: 'Reply-to' },
  'admin.settings.senders.note': { es: 'M-04 y M-05 usan estos nombres al enviar:', en: 'M-04 and M-05 use these names when sending:' },
  'admin.settings.f.displayName': { es: 'Nombre visible', en: 'Display name' },
  'admin.settings.f.displayName.hint': { es: 'Vacío usa el nombre de src/tenant/tenant.ts', en: 'Empty falls back to src/tenant/tenant.ts' },
  'admin.settings.f.wordmark': { es: 'Variante del wordmark', en: 'Wordmark variant' },
  'admin.settings.f.wordmark.auto': { es: 'Automático (según tema)', en: 'Auto (follows the theme)' },
  'admin.settings.f.wordmark.blue': { es: 'Azul', en: 'Blue' },
  'admin.settings.f.wordmark.cream': { es: 'Crema', en: 'Cream' },
  'admin.settings.f.wordmark.yellow': { es: 'Amarillo', en: 'Yellow' },
  'admin.settings.f.defaultLang': { es: 'Idioma por defecto', en: 'Default language' },
  'admin.settings.f.defaultLang.hint': { es: 'El español es obligatorio; el inglés cae al español', en: 'Spanish is required; English falls back to Spanish' },
  'admin.settings.f.preview': { es: 'Vista previa', en: 'Preview' },
  'admin.settings.flags.title': { es: 'Interruptores por pantalla', en: 'Per-screen switches' },
  'admin.settings.flags.eyebrow': { es: 'feature_flags · escritura auditada', en: 'feature_flags · audited writes' },
  'admin.settings.flags.body': { es: 'Cada bloque de cada pantalla se puede apagar aquí. Cada cambio queda en el registro de actividad.', en: 'Every block of every screen can be turned off here. Every change is written to the activity log.' },
  'admin.settings.flags.readonly': { es: 'Tu rol ve los interruptores pero no los cambia.', en: 'Your role sees the switches but cannot change them.' },
  'admin.settings.flags.count': { es: '{on} de {n} activos. Historial en:', en: '{on} of {n} on. History in:' },
  'admin.settings.subtitle': { es: 'Los parámetros que leen todas las demás pantallas. Cambia uno aquí y cambia en todas partes.', en: 'The parameters every other screen reads. Change one here and it changes everywhere.' },
  'admin.settings.readonly': { es: 'Solo lectura para tu rol', en: 'Read-only for your role' },
  'admin.settings.saved': { es: 'Guardado', en: 'Saved' },
  'admin.settings.unsaved': { es: 'Sin guardar', en: 'Unsaved' },
  'admin.settings.sec.profile': { es: 'Estudio', en: 'Studio' },
  'admin.settings.sec.openingHours': { es: 'Horarios', en: 'Opening hours' },
  'admin.settings.sec.studio': { es: 'Capacidad', en: 'Capacity' },
  'admin.settings.sec.policies': { es: 'Políticas', en: 'Policies' },
  'admin.settings.sec.quietHours': { es: 'Horas de silencio', en: 'Quiet hours' },
  'admin.settings.sec.tax': { es: 'Impuestos y facturación', en: 'Tax & invoicing' },
  'admin.settings.sec.features': { es: 'Funciones', en: 'Features' },
  'admin.settings.sec.integrations': { es: 'Integraciones', en: 'Integrations' },
  'admin.settings.f.name': { es: 'Nombre', en: 'Name' },
  'admin.settings.f.name.hint': { es: 'Identidad en src/tenant/tenant.ts', en: 'Identity lives in src/tenant/tenant.ts' },
  'admin.settings.f.legal': { es: 'Razón social', en: 'Legal name' },
  'admin.settings.f.address': { es: 'Dirección', en: 'Address' },
  'admin.settings.open': { es: 'Abierto', en: 'Open' },
  'admin.settings.closed': { es: 'Cerrado', en: 'Closed' },
  'admin.settings.hours.note': { es: 'El calendario de festivos llega con la función “Calendario de festivos”.', en: 'The holiday calendar arrives with the “Holiday calendar” feature.' },
  'admin.settings.f.mats': { es: 'Mats por clase', en: 'Mats per class' },
  'admin.settings.f.mats.hint': { es: 'Lo citan lista de espera, medidor de cupos y checkout', en: 'Quoted by waitlist, capacity meter and checkout' },
  'admin.settings.f.classesPerDay': { es: 'Clases por día', en: 'Classes per day' },
  'admin.settings.f.perPerson': { es: 'Clases por persona y día', en: 'Classes per person per day' },
  'admin.settings.f.perPerson.hint': { es: 'C-01 · C-04', en: 'C-01 · C-04' },
  'admin.settings.rooms': { es: 'Salas', en: 'Rooms' },
  'admin.settings.rooms.edit': { es: 'Editar salas en Contenido →', en: 'Edit rooms in Content →' },
  'admin.settings.f.cancellation': { es: 'Ventana de cancelación (h)', en: 'Cancellation window (h)' },
  'admin.settings.f.waitlistClaim': { es: 'Reclamo de lista de espera (min)', en: 'Waitlist claim window (min)' },
  'admin.settings.f.lateGrace': { es: 'Gracia de llegada tarde (min)', en: 'Late check-in grace (min)' },
  'admin.settings.f.noShowFee': { es: 'Cargo por no asistir', en: 'No-show fee' },
  'admin.settings.f.noShowFee.off': { es: 'Apagado en Funciones', en: 'Off in Features' },
  'admin.settings.f.pauseDays': { es: 'Días de pausa al año', en: 'Pause days per year' },
  'admin.settings.f.maxPauses': { es: 'Pausas al año', en: 'Pauses per year' },
  'admin.settings.f.paymentHold': { es: 'Cupo retenido tras pago rechazado (min)', en: 'Spot held after a declined payment (min)' },
  'admin.settings.f.chargeNotice': { es: 'Aviso antes del cobro de renovación (días)', en: 'Notice before a renewal charge (days)' },
  'admin.settings.f.lockoutAttempts': { es: 'Intentos de acceso antes del bloqueo', en: 'Sign-in attempts before lockout' },
  'admin.settings.f.lockoutMinutes': { es: 'Duración del bloqueo (min)', en: 'Lockout duration (min)' },
  'admin.settings.policies.note': { es: 'La app de clientes lee estos valores (ventana de cancelación, reclamo, retención, pausa, bloqueo). Un cambio aplica solo a reservas futuras; las existentes conservan sus términos.', en: 'The customer app reads these values (cancellation window, claim, hold, pause, lockout). A change applies to future bookings only; existing ones keep their terms.' },
  'admin.settings.f.from': { es: 'Desde', en: 'From' },
  'admin.settings.f.to': { es: 'Hasta', en: 'To' },
  'admin.settings.quiet.note': { es: 'Los mensajes no urgentes de WhatsApp esperan hasta que termine el silencio. Las cancelaciones pasan siempre.', en: 'Non-urgent WhatsApp messages wait until quiet hours end. Cancellations always go through.' },
  'admin.settings.f.iva': { es: 'IVA (%)', en: 'IVA (%)' },
  'admin.settings.f.dian': { es: 'Resolución DIAN', en: 'DIAN resolution' },
  'admin.settings.f.dian.hint': { es: 'Número y rango autorizado', en: 'Number and authorised range' },
  'admin.settings.f.included': { es: 'Los precios publicados incluyen IVA', en: 'Published prices include IVA' },
  'admin.settings.f.eInvoicing': { es: 'Facturación electrónica activa', en: 'Electronic invoicing on' },
  'admin.settings.tax.needsDian': { es: 'La facturación electrónica necesita la resolución DIAN antes de encenderse.', en: 'Electronic invoicing needs the DIAN resolution before it can be switched on.' },
  'admin.settings.feat.multipleLocations': { es: 'Varias sedes', en: 'Multiple locations' },
  'admin.settings.feat.noShowFee': { es: 'Cargo por no asistir', en: 'No-show fee' },
  'admin.settings.feat.holidayCalendar': { es: 'Calendario de festivos', en: 'Holiday calendar' },
  'admin.settings.feat.walkInRegistration': { es: 'Registro walk-in en recepción', en: 'Walk-in registration at the desk' },
  'admin.settings.feat.autoCheckinOnSale': { es: 'Check-in automático al vender', en: 'Auto check-in on sale' },
  'admin.settings.features.note': { es: 'Estos interruptores son del estudio completo. Los de cada pantalla están abajo.', en: 'These switches are studio-wide. The per-screen ones are below.' },
  'admin.settings.int.wompi': { es: 'Wompi', en: 'Wompi' },
  'admin.settings.int.wompi.body': { es: 'Pagos con tarjeta, PSE, Nequi y nómina.', en: 'Card, PSE, Nequi payments and payroll.' },
  'admin.settings.int.whatsapp': { es: 'WhatsApp Business API', en: 'WhatsApp Business API' },
  'admin.settings.int.whatsapp.body': { es: 'Plantillas, OTP y automatizaciones.', en: 'Templates, OTP and automations.' },
  'admin.settings.int.email': { es: 'Email transaccional', en: 'Transactional email' },
  'admin.settings.int.email.body': { es: 'Recibos, recordatorios, reportes.', en: 'Receipts, reminders, reports.' },
  'admin.settings.int.calendar': { es: 'Calendario', en: 'Calendar' },
  'admin.settings.int.calendar.body': { es: 'Sincronización de clases con Google / Apple.', en: 'Class sync with Google / Apple.' },
  'admin.settings.int.status.pending': { es: 'Pendiente', en: 'Pending' },
  'admin.settings.int.status.connected': { es: 'Conectado', en: 'Connected' },
  'admin.settings.int.status.error': { es: 'Con error', en: 'Error' },
  'admin.settings.int.note': { es: 'Las credenciales se escriben una vez y nunca se muestran. El estado aquí es un marcador hasta conectar cada servicio.', en: 'Credentials are write-only and never displayed. The status here is a placeholder until each service is connected.' },

  // M-09 finance
  'admin.finance.nav': { es: 'Finanzas', en: 'Finance' },
  'admin.finance.title': { es: 'Finanzas', en: 'Finance' },
  'admin.finance.subtitle': { es: 'Ingresos por producto y método, pendientes, reembolsos y facturas con referencia DIAN.', en: 'Revenue by product and method, pending, refunds and invoices with the DIAN reference.' },
  'admin.finance.range.7d': { es: '7 días', en: '7 days' },
  'admin.finance.range.15d': { es: '15 días', en: '15 days' },
  'admin.finance.range.30d': { es: '30 días', en: '30 days' },
  'admin.finance.range.90d': { es: '90 días', en: '90 days' },
  'admin.finance.range.all': { es: 'Todo', en: 'All' },
  'admin.finance.revenue': { es: 'Ingresos', en: 'Revenue' },
  'admin.finance.revenue.hint': { es: '{n} pagos aprobados', en: '{n} approved payments' },
  'admin.finance.pending': { es: 'Pendientes', en: 'Pending' },
  'admin.finance.pending.hint': { es: '{n} links / transferencias sin confirmar', en: '{n} unconfirmed links / transfers' },
  'admin.finance.refunded': { es: 'Reembolsado', en: 'Refunded' },
  'admin.finance.refunded.hint': { es: '{n} reembolsos', en: '{n} refunds' },
  'admin.finance.wompiShare': { es: 'Vía Wompi', en: 'Via Wompi' },
  'admin.finance.wompiShare.hint': { es: 'resto: efectivo / manual', en: 'rest: cash / manual' },
  'admin.finance.byProduct': { es: 'Ingresos por producto', en: 'Revenue by product' },
  'admin.finance.byMethod': { es: 'Ingresos por método', en: 'Revenue by method' },
  'admin.finance.emptyRange': { es: 'Sin movimientos en este rango.', en: 'No activity in this range.' },
  'admin.finance.method.card': { es: 'Tarjeta', en: 'Card' },
  'admin.finance.method.pse': { es: 'PSE', en: 'PSE' },
  'admin.finance.method.nequi': { es: 'Nequi', en: 'Nequi' },
  'admin.finance.method.cash': { es: 'Efectivo', en: 'Cash' },
  'admin.finance.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'admin.finance.method.gift_card': { es: 'Bono regalo', en: 'Gift card' },
  'admin.finance.payouts': { es: 'Nómina de profesores', en: 'Teacher payroll' },
  'admin.finance.payouts.next': { es: 'Próxima corrida', en: 'Next run' },
  'admin.finance.payouts.placeholder': { es: 'marcador hasta conectar Wompi', en: 'placeholder until Wompi is connected' },
  'admin.finance.payouts.settled': { es: 'Cobrado vía Wompi', en: 'Collected via Wompi' },
  'admin.finance.payouts.settled.hint': { es: 'en el rango', en: 'in range' },
  'admin.finance.payouts.manual': { es: 'Cobrado en mostrador', en: 'Collected at the desk' },
  'admin.finance.payouts.manual.hint': { es: 'efectivo, datáfono, transferencia', en: 'cash, terminal, transfer' },
  'admin.finance.payouts.body': { es: 'Las corridas se aprueban y se pagan en Nómina (M-09a). La cuenta de dispersión y el entorno de Wompi viven en', en: 'Runs are approved and paid in Payroll (M-09a). The dispersion account and the Wompi environment live in' },
  'admin.finance.payments': { es: 'Pagos', en: 'Payments' },
  'admin.finance.refund': { es: 'Reembolsar', en: 'Refund' },
  'admin.finance.refund.confirm': { es: '¿Reembolsar {amount}? El pago pasa a “refunded” y queda en el registro.', en: 'Refund {amount}? The payment becomes “refunded” and is logged.' },
  'admin.finance.refund.noPermission': { es: 'Solo finanzas y administración reembolsan.', en: 'Only finance and admin can refund.' },
  'admin.finance.col.when': { es: 'Cuándo', en: 'When' },
  'admin.finance.col.member': { es: 'Miembro', en: 'Member' },
  'admin.finance.col.product': { es: 'Producto', en: 'Product' },
  'admin.finance.col.amount': { es: 'Importe', en: 'Amount' },
  'admin.finance.col.method': { es: 'Método', en: 'Method' },
  'admin.finance.col.status': { es: 'Estado', en: 'Status' },
  'admin.finance.col.invoice': { es: 'Factura', en: 'Invoice' },
  'admin.finance.col.cufe': { es: 'CUFE (DIAN)', en: 'CUFE (DIAN)' },
  'admin.finance.noCufe': { es: 'sin CUFE', en: 'no CUFE' },
  'admin.finance.cufe.pending': { es: 'Pendiente de emitir', en: 'Pending issue' },
  'admin.finance.cufe.off': { es: 'Facturación electrónica apagada', en: 'E-invoicing off' },
  'admin.finance.invoices': { es: 'Facturas', en: 'Invoices' },
  'admin.finance.einv.on': { es: 'Facturación electrónica activa: el CUFE se asigna al emitir en DIAN.', en: 'E-invoicing on: the CUFE is assigned when issued at DIAN.' },
  'admin.finance.einv.off': { es: 'Activa la facturación electrónica en Ajustes → Impuestos cuando tengas la resolución DIAN.', en: 'Turn on e-invoicing in Settings → Tax once you have the DIAN resolution.' },
  // ---- 0012 · M-02 content family (M-02a…M-02d) ----
  'admin.content.nav.entities': { es: 'Catálogo', en: 'Catalogue' },
  'admin.content.nav.articles': { es: 'Artículos', en: 'Articles' },
  'admin.content.nav.faq': { es: 'Preguntas frecuentes', en: 'FAQ' },
  'admin.content.nav.events': { es: 'Eventos', en: 'Events' },
  'admin.content.nav.media': { es: 'Medios', en: 'Media' },
  'admin.content.bi.hint': { es: 'Español arriba, inglés abajo. Si el inglés queda vacío se usa el español.', en: 'Spanish above, English below. An empty English falls back to Spanish.' },

  'admin.articles.title': { es: 'Artículos', en: 'Articles' },
  'admin.articles.subtitle': { es: 'Reglas del club, textos “sobre HOY” y guías. Se publican sin deploy y los lee la app (C-13, C-14/C-15).', en: 'Club rules, about-the-studio copy and guides. They publish without a deploy and the app reads them (C-13, C-14/C-15).' },
  'admin.articles.add': { es: 'Nuevo artículo', en: 'New article' },
  'admin.articles.editor': { es: 'Artículo', en: 'Article' },
  'admin.articles.untitled': { es: 'Sin título', en: 'Untitled' },
  'admin.articles.col.title': { es: 'Título', en: 'Title' },
  'admin.articles.col.section': { es: 'Categoría', en: 'Category' },
  'admin.articles.col.status': { es: 'Estado', en: 'Status' },
  'admin.articles.col.when': { es: 'Programado', en: 'Scheduled' },
  'admin.articles.col.sort': { es: 'Orden', en: 'Order' },
  'admin.articles.filter.all': { es: 'Todos', en: 'All' },
  'admin.articles.status.draft': { es: 'Borrador', en: 'Draft' },
  'admin.articles.status.scheduled': { es: 'Programado', en: 'Scheduled' },
  'admin.articles.status.published': { es: 'Publicado', en: 'Published' },
  'admin.articles.section.rules': { es: 'Reglas del club', en: 'Club rules' },
  'admin.articles.section.about': { es: 'Sobre el estudio', en: 'About the studio' },
  'admin.articles.section.faq': { es: 'Ayuda', en: 'Help' },
  'admin.articles.section.hint': { es: 'Define dónde aparece: reglas en C-13, “sobre” en la web, ayuda junto a las FAQ.', en: 'Decides where it shows: rules in C-13, “about” on the site, help next to the FAQ.' },
  'admin.articles.slug': { es: 'Slug', en: 'Slug' },
  'admin.articles.slug.hint': { es: 'Minúsculas, números y guiones. Es el enlace permanente del artículo.', en: 'Lowercase, digits and hyphens. It is the article’s permanent link.' },
  'admin.articles.slugRule': { es: 'Solo minúsculas, números y guiones.', en: 'Lowercase, digits and hyphens only.' },
  'admin.articles.titleField': { es: 'Título', en: 'Title' },
  'admin.articles.summary': { es: 'Resumen', en: 'Summary' },
  'admin.articles.body': { es: 'Cuerpo', en: 'Body' },
  'admin.articles.body.ph': { es: 'Escribe en markdown: ## títulos, **negrita**, listas con -', en: 'Write in markdown: ## headings, **bold**, lists with -' },
  'admin.articles.body.empty': { es: 'La vista previa aparece mientras escribes, tal como lo verá el socio.', en: 'The preview appears as you type, exactly as the member will see it.' },
  'admin.articles.publishAt': { es: 'Publicar el', en: 'Publish on' },
  'admin.articles.publishAt.hint': { es: 'Con fecha futura y publicado activo, queda programado. Vacío = se publica al activarlo.', en: 'A future date with published on means scheduled. Empty = live as soon as you publish.' },
  'admin.articles.publishNow': { es: 'Publicar ahora', en: 'Publish now' },
  'admin.articles.unpublish': { es: 'Despublicar', en: 'Unpublish' },
  'admin.articles.empty': { es: 'Sin artículos', en: 'No articles' },
  'admin.articles.empty.body': { es: 'Crea el primero: las reglas de la sala son un buen comienzo.', en: 'Create the first one: the room rules are a good start.' },
  'admin.articles.emptyFilter': { es: 'Ningún artículo en este estado.', en: 'No article in this state.' },

  'admin.faq.title': { es: 'Preguntas frecuentes', en: 'FAQ' },
  'admin.faq.subtitle': { es: 'Las secciones y preguntas que leen C-14 y C-15. El orden se mueve con ↑ y ↓.', en: 'The sections and questions C-14 and C-15 read. Order moves with ↑ and ↓.' },
  'admin.faq.addGroup': { es: 'Nueva sección', en: 'New section' },
  'admin.faq.addEntry': { es: 'Nueva pregunta', en: 'New question' },
  'admin.faq.addHere': { es: 'Añadir aquí', en: 'Add here' },
  'admin.faq.editor': { es: 'Pregunta', en: 'Question' },
  'admin.faq.question': { es: 'Pregunta', en: 'Question' },
  'admin.faq.answer': { es: 'Respuesta', en: 'Answer' },
  'admin.faq.groupKey': { es: 'Clave de sección', en: 'Section key' },
  'admin.faq.groupKey.hint': { es: 'Mueve la pregunta a otra sección; las preguntas con la misma clave se agrupan.', en: 'Moves the question to another section; questions sharing a key group together.' },
  'admin.faq.groupTitle': { es: 'Título de la sección', en: 'Section title' },
  'admin.faq.groupTitle.hint': { es: 'Se guarda en todas las preguntas de la sección.', en: 'Saved on every question of the section.' },
  'admin.faq.groupLead': { es: 'Entrada de la sección', en: 'Section lead' },
  'admin.faq.page': { es: 'Página', en: 'Page' },
  'admin.faq.page.all': { es: 'Las dos páginas', en: 'Both pages' },
  'admin.faq.page.n': { es: 'Página {n}', en: 'Page {n}' },
  'admin.faq.page.hint': { es: 'Página 1 = C-14, página 2 = C-15.', en: 'Page 1 = C-14, page 2 = C-15.' },
  'admin.faq.up': { es: 'Subir', en: 'Move up' },
  'admin.faq.down': { es: 'Bajar', en: 'Move down' },
  'admin.faq.count': { es: '{n} preguntas · {published} publicadas', en: '{n} questions · {published} published' },
  'admin.faq.untitled': { es: 'Pregunta sin escribir', en: 'Question not written yet' },
  'admin.faq.noAnswer': { es: 'Sin respuesta todavía', en: 'No answer yet' },
  'admin.faq.empty': { es: 'Sin preguntas', en: 'No questions' },
  'admin.faq.empty.body': { es: 'Empieza por una sección: “Tu primera vez”, por ejemplo.', en: 'Start with a section: “Your first time”, for instance.' },

  'admin.events.title': { es: 'Eventos', en: 'Events' },
  'admin.events.subtitle': { es: 'Talleres, baños de sonido y eventos especiales. Publicados aparecen en C-23 y en la web.', en: 'Workshops, sound baths and special events. Published ones appear in C-23 and on the site.' },
  'admin.events.add': { es: 'Nuevo evento', en: 'New event' },
  'admin.events.editor': { es: 'Evento', en: 'Event' },
  'admin.events.untitled': { es: 'Sin título', en: 'Untitled' },
  'admin.events.col.title': { es: 'Evento', en: 'Event' },
  'admin.events.col.when': { es: 'Cuándo', en: 'When' },
  'admin.events.col.rsvps': { es: 'Inscritos', en: 'RSVPs' },
  'admin.events.col.price': { es: 'Precio', en: 'Price' },
  'admin.events.col.memberPrice': { es: 'Precio socio', en: 'Member price' },
  'admin.events.col.status': { es: 'Estado', en: 'Status' },
  'admin.events.status.draft': { es: 'Borrador', en: 'Draft' },
  'admin.events.status.published': { es: 'Publicado', en: 'Published' },
  'admin.events.status.cancelled': { es: 'Cancelado', en: 'Cancelled' },
  'admin.events.included': { es: 'Incluido', en: 'Included' },
  'admin.events.publish': { es: 'Publicar', en: 'Publish' },
  'admin.events.unpublish': { es: 'Despublicar', en: 'Unpublish' },
  'admin.events.cancel': { es: 'Cancelar evento', en: 'Cancel event' },
  'admin.events.titleField': { es: 'Título', en: 'Title' },
  'admin.events.kind': { es: 'Tipo', en: 'Kind' },
  'admin.events.kind.hint': { es: 'Taller, baño de sonido, círculo… se muestra sobre el título.', en: 'Workshop, sound bath, circle… it shows above the title.' },
  'admin.events.description': { es: 'Descripción', en: 'Description' },
  'admin.events.starts': { es: 'Empieza', en: 'Starts' },
  'admin.events.ends': { es: 'Termina', en: 'Ends' },
  'admin.events.room': { es: 'Sala', en: 'Room' },
  'admin.events.host': { es: 'Anfitrión', en: 'Host' },
  'admin.events.capacity': { es: 'Aforo', en: 'Capacity' },
  'admin.events.capacity.hint': { es: 'Máximo {n} (mats de la sala).', en: 'Maximum {n} (studio mats).' },
  'admin.events.capBelowRsvps': { es: 'Ya hay {n} inscritos: el aforo no puede ser menor.', en: '{n} people are already in: capacity cannot be lower.' },
  'admin.events.capOverMats': { es: 'La sala tiene {n} mats.', en: 'The room has {n} mats.' },
  'admin.events.endBeforeStart': { es: 'La hora de fin debe ser posterior al inicio.', en: 'The end time must be after the start.' },
  'admin.events.price.hint': { es: 'COP, precio público. Por defecto, el de talleres en pricing.ts.', en: 'COP, public price. Defaults to the workshop price in pricing.ts.' },
  'admin.events.memberPrice.hint': { es: 'COP. 0 = incluido para socios de Membresía.', en: 'COP. 0 = included for Membership members.' },
  'admin.events.rsvpCount': { es: '{n} inscritos de {cap} cupos. Las inscripciones se leen de event_rsvps, no se escriben aquí.', en: '{n} RSVPs of {cap} spots. RSVPs are read from event_rsvps, never written here.' },
  'admin.events.rsvpNote': { es: 'Inscritos = event_rsvps (going + asistidos, con invitados).', en: 'RSVPs = event_rsvps (going + attended, guests included).' },
  'admin.events.hasRsvps': { es: 'Este evento ya tiene inscritos: cancélalo en vez de borrarlo.', en: 'This event already has RSVPs: cancel it instead of deleting it.' },
  'admin.events.preview': { es: 'En la app: {title} · {price}', en: 'In the app: {title} · {price}' },
  'admin.events.empty': { es: 'Sin eventos', en: 'No events' },
  'admin.events.empty.body': { es: 'Crea uno y publícalo para que aparezca en la agenda del socio.', en: 'Create one and publish it so it shows on the member’s calendar.' },

  'admin.media.title': { es: 'Biblioteca de medios', en: 'Media library' },
  'admin.media.subtitle': { es: 'Un cupo por cada lugar donde la app y la web muestran arte: qué falta, en qué proporción y con qué encargo. Pega la URL y aparece en todas partes.', en: 'One slot per place the app and the site show art: what is missing, in which ratio and with which brief. Paste the URL and it appears everywhere.' },
  'admin.media.add': { es: 'Nuevo cupo', en: 'New slot' },
  'admin.media.note': { es: 'HoyOS guarda la URL, nunca el archivo: la subida llega con Supabase Storage.', en: 'HoyOS stores the URL, never the file: uploads arrive with Supabase Storage.' },
  'admin.media.status.pending': { es: 'Pendiente', en: 'Pending' },
  'admin.media.status.ready': { es: 'Lista', en: 'Ready' },
  'admin.media.kind.photo': { es: 'Foto', en: 'Photo' },
  'admin.media.kind.video': { es: 'Video', en: 'Video' },
  'admin.media.kind.illustration': { es: 'Ilustración', en: 'Illustration' },
  'admin.media.kindField': { es: 'Tipo', en: 'Kind' },
  'admin.media.kpi.ready': { es: 'Piezas listas', en: 'Assets ready' },
  'admin.media.kpi.ready.hint': { es: 'de los cupos que la app conoce', en: 'of the slots the app knows about' },
  'admin.media.kpi.pending': { es: 'Por producir', en: 'Still to shoot' },
  'admin.media.kpi.pending.hint': { es: 'mientras tanto se ve el marco con su proporción', en: 'meanwhile the framed empty slot shows its ratio' },
  'admin.media.kpi.video': { es: 'Cupos de video', en: 'Video slots' },
  'admin.media.kpi.video.hint': { es: 'recorrido del estudio y similares', en: 'the studio tour and the like' },
  'admin.media.url': { es: 'URL de la pieza', en: 'Asset URL' },
  'admin.media.url.hint': { es: 'Enlace público (https://…) o ruta dentro del sitio.', en: 'A public link (https://…) or a path inside the site.' },
  'admin.media.url.bad': { es: 'Debe empezar por https://, / o ./', en: 'It must start with https://, / or ./' },
  'admin.media.markReady': { es: 'Marcar lista', en: 'Mark ready' },
  'admin.media.markPending': { es: 'Volver a pendiente', en: 'Back to pending' },
  'admin.media.more': { es: 'Más campos', en: 'More fields' },
  'admin.media.less': { es: 'Menos campos', en: 'Fewer fields' },
  'admin.media.slotKey': { es: 'Clave del cupo', en: 'Slot key' },
  'admin.media.slotKey.hint': { es: 'La pide el componente: class.hero, teacher.portrait… no la cambies sin avisar.', en: 'The component asks for it: class.hero, teacher.portrait… do not change it lightly.' },
  'admin.media.ratio': { es: 'Proporción', en: 'Ratio' },
  'admin.media.label': { es: 'Dónde se usa', en: 'Where it shows' },
  'admin.media.alt': { es: 'Texto alternativo', en: 'Alternative text' },
  'admin.media.alt.hint': { es: 'Lo lee quien no ve la imagen. Describe la escena, no repitas el título.', en: 'Read by anyone who cannot see the image. Describe the scene, do not repeat the title.' },
  'admin.media.brief': { es: 'Encargo', en: 'Brief' },
  'admin.media.credit': { es: 'Crédito', en: 'Credit' },
  'admin.media.credit.hint': { es: 'Fotógrafo o licencia.', en: 'Photographer or licence.' },
  'admin.media.noKey': { es: 'sin clave', en: 'no key' },
  'admin.media.noBrief': { es: 'Sin encargo escrito todavía.', en: 'No brief written yet.' },
  'admin.media.untitled': { es: 'Cupo sin nombre', en: 'Unnamed slot' },
  'admin.media.empty': { es: 'Sin cupos de medios', en: 'No media slots' },
  'admin.media.empty.body': { es: 'Crea un cupo por cada foto o video que la app deba mostrar.', en: 'Create one slot per photo or video the app should show.' },

  // ---- 0012 · M-09a / M-09b teacher payouts ----
  'admin.payouts.nav': { es: 'Nómina', en: 'Payroll' },
  'admin.payouts.title': { es: 'Nómina de profesores', en: 'Teacher payroll' },
  'admin.payouts.subtitle': { es: 'Una corrida por mes: clases dictadas × tarifa, aprobación y pago. Los montos salen de las clases cerradas, no de una estimación.', en: 'One run per month: classes taught × rate, approval and payment. The amounts come from closed classes, not from an estimate.' },
  'admin.payouts.simulated': { es: 'Wompi simulado', en: 'Wompi simulated' },
  'admin.payouts.backToFinance': { es: 'Volver a Finanzas', en: 'Back to Finance' },
  'admin.payouts.status.draft': { es: 'Borrador', en: 'Draft' },
  'admin.payouts.status.approved': { es: 'Aprobada', en: 'Approved' },
  'admin.payouts.status.paid': { es: 'Pagada', en: 'Paid' },
  'admin.payouts.method.wompi': { es: 'Wompi', en: 'Wompi' },
  'admin.payouts.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'admin.payouts.method.cash': { es: 'Efectivo', en: 'Cash' },
  'admin.payouts.method.hint': { es: 'se decide al pagar', en: 'decided when paying' },
  'admin.payouts.kind.class': { es: 'Clase', en: 'Class' },
  'admin.payouts.kind.bonus': { es: 'Bono', en: 'Bonus' },
  'admin.payouts.kind.adjustment': { es: 'Ajuste', en: 'Adjustment' },
  'admin.payouts.kind.manual': { es: 'Especial', en: 'Special' },
  'admin.payouts.manualHint': { es: 'Las líneas "Especial" son pagos acordados a mano en recepción (S-04) y entran al borrador junto con las clases; recalcular no las duplica.', en: '"Especial" lines are payouts agreed by hand at the desk (S-04); they enter the draft with the classes and recomputing never duplicates them.' },
  'admin.payouts.runOf.manual': { es: '{n} especiales', en: '{n} specials' },
  'admin.finance.col.contact': { es: 'contacto (Especial)', en: 'contact (Special)' },
  'admin.payouts.col.period': { es: 'Periodo', en: 'Period' },
  'admin.payouts.col.status': { es: 'Estado', en: 'Status' },
  'admin.payouts.col.teachers': { es: 'Profesores', en: 'Teachers' },
  'admin.payouts.col.classes': { es: 'Clases', en: 'Classes' },
  'admin.payouts.col.total': { es: 'Total', en: 'Total' },
  'admin.payouts.col.method': { es: 'Medio', en: 'Method' },
  'admin.payouts.col.settled': { es: 'Liquidada', en: 'Settled' },
  'admin.payouts.awaitingPayment': { es: 'aprobada, sin pagar', en: 'approved, unpaid' },
  'admin.payouts.kpi.next': { es: 'Próxima corrida', en: 'Next run' },
  'admin.payouts.kpi.next.hint': { es: '{period} · {n} profesores', en: '{period} · {n} teachers' },
  'admin.payouts.kpi.next.none': { es: 'sin borrador todavía: genera el periodo', en: 'no draft yet: generate the period' },
  'admin.payouts.kpi.pending': { es: 'Por pagar', en: 'Awaiting payment' },
  'admin.payouts.kpi.pending.hint': { es: '{n} corridas aprobadas', en: '{n} approved runs' },
  'admin.payouts.kpi.quarter': { es: 'Pagado en el trimestre', en: 'Paid this quarter' },
  'admin.payouts.kpi.quarter.hint': { es: '{n} corridas liquidadas', en: '{n} settled runs' },
  'admin.payouts.kpi.runTotal': { es: 'Total de la corrida', en: 'Run total' },
  'admin.payouts.kpi.runTotal.hint': { es: '{n} líneas', en: '{n} lines' },
  'admin.payouts.kpi.state': { es: 'Estado', en: 'State' },
  'admin.payouts.generate': { es: 'Generar borrador del periodo', en: 'Generate the period’s draft' },
  'admin.payouts.generate.period': { es: 'Periodo', en: 'Period' },
  'admin.payouts.generate.action': { es: 'Generar borrador', en: 'Generate draft' },
  'admin.payouts.generate.hint': { es: 'Se puede repetir: vuelve a calcular el borrador desde las clases cerradas, no suma dos veces.', en: 'Safe to repeat: it recomputes the draft from the closed classes instead of paying twice.' },
  'admin.payouts.generate.done': { es: '{n} líneas · {total}', en: '{n} lines · {total}' },
  'admin.payouts.generate.blocked': { es: 'Ese periodo ya tiene una corrida {status}: las correcciones van como ajuste en la siguiente.', en: 'That period already has a run in {status}: corrections go as an adjustment in the next one.' },
  'admin.payouts.noPermission': { es: 'Necesitas el permiso payroll.write para generar, aprobar o pagar.', en: 'You need the payroll.write permission to generate, approve or pay.' },
  'admin.payouts.empty': { es: 'Sin corridas de nómina', en: 'No payroll runs' },
  'admin.payouts.empty.body': { es: 'Genera el borrador del mes en curso y revisa el extracto por profesor.', en: 'Generate this month’s draft and review the statement per teacher.' },
  'admin.payouts.seamNote': { es: 'La dispersión por Wompi está simulada (wompiPayout). La corrida, las líneas y el registro de auditoría ya son reales; el efectivo y la transferencia no pasan por Wompi nunca.', en: 'The Wompi dispersion is simulated (wompiPayout). The run, the lines and the audit trail are already real; cash and transfer never go through Wompi.' },
  'admin.payouts.notFound': { es: 'Corrida no encontrada', en: 'Run not found' },
  'admin.payouts.runOf': { es: '{n} profesores · {classes} clases', en: '{n} teachers · {classes} classes' },
  'admin.payouts.actions': { es: 'Acciones', en: 'Actions' },
  'admin.payouts.action.regenerate': { es: 'Recalcular borrador', en: 'Recompute draft' },
  'admin.payouts.action.approve': { es: 'Aprobar', en: 'Approve' },
  'admin.payouts.action.wompi': { es: 'Enviar por Wompi', en: 'Send via Wompi' },
  'admin.payouts.action.transfer': { es: 'Marcar pagada · transferencia', en: 'Mark paid · transfer' },
  'admin.payouts.action.cash': { es: 'Marcar pagada · efectivo', en: 'Mark paid · cash' },
  'admin.payouts.action.csv': { es: 'Exportar CSV', en: 'Export CSV' },
  'admin.payouts.action.print': { es: 'Imprimir', en: 'Print' },
  'admin.payouts.flow': { es: 'Borrador → aprobada → pagada. Aprobar congela las líneas; pagar cierra la corrida.', en: 'Draft → approved → paid. Approving freezes the lines; paying closes the run.' },
  'admin.payouts.locked': { es: 'Corrida pagada: no se edita. Una corrección va como ajuste en la siguiente.', en: 'Paid run: not editable. A correction goes as an adjustment in the next one.' },
  'admin.payouts.approvedOn': { es: 'aprobada el {date}', en: 'approved {date}' },
  'admin.payouts.notApproved': { es: 'sin aprobar', en: 'not approved' },
  'admin.payouts.statement': { es: 'Extracto por profesor', en: 'Statement per teacher' },
  'admin.payouts.teacherSummary': { es: '{classes} clases · pago por {method}', en: '{classes} classes · paid by {method}' },
  'admin.payouts.attendees': { es: '{n} asistentes', en: '{n} attended' },
  'admin.payouts.noLines': { es: 'Corrida sin líneas', en: 'Run with no lines' },
  'admin.payouts.noLines.body': { es: 'No hubo clases cerradas en el periodo, o el borrador se generó antes de cerrarlas.', en: 'No classes were closed in the period, or the draft was generated before they were.' },
  'admin.payouts.msg.approved': { es: 'Corrida aprobada por {total}. Ya se puede pagar.', en: 'Run approved for {total}. It can be paid now.' },
  'admin.payouts.msg.paid': { es: 'Marcada como pagada por {method}.', en: 'Marked paid by {method}.' },
  'admin.payouts.msg.sent': { es: 'Dispersión simulada aceptada · referencia {ref}. Con Wompi real, el webhook confirmaría este estado.', en: 'Simulated dispersion accepted · reference {ref}. With real Wompi, the webhook would confirm this state.' },
  'admin.payouts.msg.rejected': { es: 'La dispersión fue rechazada y la corrida sigue aprobada.', en: 'The dispersion was rejected and the run stays approved.' },

  // M-09 payouts summary card (replaces the em-dash placeholder)
  'admin.finance.payouts.open': { es: 'Abrir nómina', en: 'Open payroll' },
  'admin.finance.payouts.next.hint': { es: '{period} · {n} profesores', en: '{period} · {n} teachers' },
  'admin.finance.payouts.next.none': { es: 'sin borrador: genera el periodo en M-09a', en: 'no draft: generate the period in M-09a' },
  'admin.finance.payouts.pending': { es: 'Aprobado por pagar', en: 'Approved, unpaid' },
  'admin.finance.payouts.pending.hint': { es: '{n} corridas', en: '{n} runs' },
  'admin.finance.payouts.quarter': { es: 'Pagado en el trimestre', en: 'Paid this quarter' },
  'admin.finance.payouts.quarter.hint': { es: '{n} corridas liquidadas', en: '{n} settled runs' },
  'admin.finance.invFilter': { es: 'Filtrar facturas por estado del pago', en: 'Filter invoices by payment status' },
  'admin.finance.invFilter.all': { es: 'Todas', en: 'All' },
  'admin.finance.invFilter.approved': { es: 'Pagadas', en: 'Paid' },
  'admin.finance.invFilter.pending': { es: 'Pendientes', en: 'Pending' },
  'admin.finance.invFilter.refunded': { es: 'Reembolsadas', en: 'Refunded' },
  // per-teacher settlement inside a run (M-09b)
  'admin.payouts.payTeacher': { es: 'Marcar como pagado', en: 'Mark as paid' },
  'admin.payouts.teacherPaid': { es: 'Pagado el {date} por {method}', en: 'Paid {date} by {method}' },
  'admin.payouts.teacherUnpaid': { es: 'Sin pagar · se liquida por {method}', en: 'Unpaid · settles by {method}' },
  'admin.payouts.teacherPartial': { es: 'Pago parcial: {n} de {total} líneas', en: 'Partly paid: {n} of {total} lines' },
  'admin.payouts.msg.teacherPaid': { es: '{name}: {total} marcado como pagado por {method}.', en: '{name}: {total} marked paid by {method}.' },
  'admin.payouts.msg.allPaid': { es: 'Todos los profesores quedaron pagados, así que la corrida se cerró como pagada.', en: 'Every teacher is paid, so the run closed as paid.' },
  'admin.payouts.perTeacherHint': { es: 'Puedes liquidar profesor por profesor: la corrida se cierra sola cuando todos quedan pagados.', en: 'You can settle teacher by teacher: the run closes itself once everybody is paid.' },

  // M-09c expenses ledger + M-09 balance
  'admin.expenses.nav': { es: 'Gastos', en: 'Expenses' },
  'admin.expenses.title': { es: 'Gastos', en: 'Expenses' },
  'admin.expenses.subtitle': { es: 'Gastos fijos recurrentes generados de sus plantillas y gastos variables registrados a mano; pagado y por pagar, por categoría. Restan en el balance de Finanzas.', en: 'Recurring fixed costs generated from their templates and variable costs recorded by hand; paid and to pay, by category. They subtract in the Finance balance.' },
  'admin.expenses.rangeLabel': { es: 'Rango de fechas', en: 'Date range' },
  'admin.expenses.filterLabel': { es: 'Filtrar gastos', en: 'Filter expenses' },
  'admin.expenses.kpi.fixed': { es: 'Gastos fijos', en: 'Fixed expenses' },
  'admin.expenses.kpi.fixed.hint': { es: '{n} filas generadas de plantillas', en: '{n} rows generated from templates' },
  'admin.expenses.kpi.variable': { es: 'Gastos variables', en: 'Variable expenses' },
  'admin.expenses.kpi.variable.hint': { es: '{n} registrados a mano', en: '{n} recorded by hand' },
  'admin.expenses.kpi.paid': { es: 'Pagado', en: 'Paid' },
  'admin.expenses.kpi.paid.hint': { es: '{n} gastos con fecha de pago', en: '{n} expenses with a payment date' },
  'admin.expenses.kpi.unpaid': { es: 'Por pagar', en: 'To pay' },
  'admin.expenses.kpi.unpaid.hint': { es: '{n} pendientes en el rango', en: '{n} pending in the range' },
  'admin.expenses.byCategory': { es: 'Gastos por categoría', en: 'Expenses by category' },
  'admin.expenses.byCategory.hint': { es: 'Total del rango: {total}. Fijos y variables juntos.', en: 'Range total: {total}. Fixed and variable together.' },
  'admin.expenses.add': { es: 'Registrar un gasto', en: 'Record an expense' },
  'admin.expenses.noPermission': { es: 'Solo finanzas y administración registran gastos. Puedes consultar.', en: 'Only finance and admin record expenses. You can look.' },
  'admin.expenses.required': { es: 'Obligatorio', en: 'Required' },
  'admin.expenses.amount.positive': { es: 'Debe ser mayor que cero', en: 'Must be greater than zero' },
  'admin.expenses.amount.hint': { es: 'COP, sin decimales', en: 'COP, no decimals' },
  'admin.expenses.concept.placeholder': { es: 'p. ej. Reposición de mats', en: 'e.g. Mat replacement' },
  'admin.expenses.form.paidToday': { es: 'Pagado hoy', en: 'Paid today' },
  'admin.expenses.form.hint': { es: 'Queda en el registro de actividad con tu nombre.', en: 'It lands in the activity log under your name.' },
  'admin.expenses.form.save': { es: 'Guardar gasto', en: 'Save expense' },
  'admin.expenses.msg.added': { es: 'Gasto guardado: {concept} · {amount}.', en: 'Expense saved: {concept} · {amount}.' },
  'admin.expenses.msg.templateAdded': { es: 'Plantilla creada: {concept}. Genera el periodo para crear sus gastos.', en: 'Template created: {concept}. Generate the period to create its expenses.' },
  'admin.expenses.templates': { es: 'Gastos fijos recurrentes', en: 'Recurring fixed costs' },
  'admin.expenses.templates.eyebrow': { es: 'Plantillas · quincenales y mensuales', en: 'Templates · biweekly and monthly' },
  'admin.expenses.templates.new': { es: 'Nueva plantilla', en: 'New template' },
  'admin.expenses.templates.save': { es: 'Guardar plantilla', en: 'Save template' },
  'admin.expenses.templates.empty': { es: 'Sin plantillas todavía', en: 'No templates yet' },
  'admin.expenses.templates.empty.body': { es: 'Crea el arriendo, los servicios y el aseo como plantillas y genera cada periodo con un botón.', en: 'Create rent, utilities and cleaning as templates and generate every period with one button.' },
  'admin.expenses.template.amount.hint': { es: 'por vencimiento (una quincena o un mes)', en: 'per due date (one fortnight or one month)' },
  'admin.expenses.generate.action': { es: 'Generar gastos fijos del periodo', en: 'Generate the period’s fixed expenses' },
  'admin.expenses.generate.hint': { es: '{n} plantillas activas · {total} en el periodo', en: '{n} active templates · {total} in the period' },
  'admin.expenses.generate.idempotent': { es: 'Se puede repetir: un vencimiento que ya tiene su fila se salta, nunca se duplica, y un gasto pagado nunca se borra. Las plantillas inactivas no generan nada.', en: 'Safe to repeat: a due date that already has its row is skipped, never duplicated, and a paid expense is never deleted. Inactive templates generate nothing.' },
  'admin.expenses.generate.done': { es: '{n} gastos fijos creados · {total} ({skipped} ya existían)', en: '{n} fixed expenses created · {total} ({skipped} already existed)' },
  'admin.expenses.generate.nothing': { es: 'Nada nuevo: los {skipped} vencimientos del periodo ya tenían su fila.', en: 'Nothing new: the period’s {skipped} due dates already had their row.' },
  'admin.expenses.list': { es: 'Gastos del rango', en: 'Expenses in range' },
  'admin.expenses.filter.all': { es: 'Todos', en: 'All' },
  'admin.expenses.filter.fixed': { es: 'Fijos', en: 'Fixed' },
  'admin.expenses.filter.variable': { es: 'Variables', en: 'Variable' },
  'admin.expenses.filter.unpaid': { es: 'Por pagar', en: 'To pay' },
  'admin.expenses.empty': { es: 'Sin gastos en este rango', en: 'No expenses in this range' },
  'admin.expenses.empty.body': { es: 'Registra uno arriba o genera los fijos del periodo.', en: 'Record one above or generate the period’s fixed costs.' },
  'admin.expenses.footnote': { es: 'Un gasto no es un pago de socio ni una nómina: vive en su propia tabla y resta en el balance de M-09. {n} plantillas definen los fijos.', en: 'An expense is neither a member payment nor payroll: it lives in its own table and subtracts in the M-09 balance. {n} templates define the fixed ones.' },
  'admin.expenses.markPaid': { es: 'Marcar pagado', en: 'Mark paid' },
  'admin.expenses.paidOn': { es: 'Pagado {date}', en: 'Paid {date}' },
  'admin.expenses.unpaid': { es: 'Por pagar', en: 'To pay' },
  'admin.expenses.remove.confirm': { es: '¿Eliminar “{concept}” ({amount})? Solo se pueden borrar gastos sin pagar.', en: 'Delete “{concept}” ({amount})? Only unpaid expenses can be deleted.' },
  'admin.expenses.active': { es: 'Activa', en: 'Active' },
  'admin.expenses.inactive': { es: 'Inactiva', en: 'Inactive' },
  'admin.expenses.activate': { es: 'Activar', en: 'Activate' },
  'admin.expenses.deactivate': { es: 'Desactivar', en: 'Deactivate' },
  'admin.expenses.dueOnce': { es: 'día {d}', en: 'day {d}' },
  'admin.expenses.dueTwice': { es: 'días {d} y {d2}', en: 'days {d} and {d2}' },
  'admin.expenses.col.date': { es: 'Fecha', en: 'Date' },
  'admin.expenses.col.concept': { es: 'Concepto', en: 'Concept' },
  'admin.expenses.col.category': { es: 'Categoría', en: 'Category' },
  'admin.expenses.col.kind': { es: 'Tipo', en: 'Kind' },
  'admin.expenses.col.method': { es: 'Método', en: 'Method' },
  'admin.expenses.col.amount': { es: 'Valor', en: 'Amount' },
  'admin.expenses.col.status': { es: 'Estado', en: 'Status' },
  'admin.expenses.col.vendor': { es: 'Proveedor', en: 'Vendor' },
  'admin.expenses.col.note': { es: 'Nota', en: 'Note' },
  'admin.expenses.col.cadence': { es: 'Cadencia', en: 'Cadence' },
  'admin.expenses.col.anchorDay': { es: 'Día de vencimiento', en: 'Due day' },
  'admin.expenses.anchorDay.hint': { es: '1–28; quincenal vence también 15 días después', en: '1–28; biweekly also falls due 15 days later' },
  'admin.expenses.col.monthly': { es: 'Al mes', en: 'Per month' },
  'admin.expenses.col.active': { es: 'Estado', en: 'Status' },
  'admin.expenses.kind.fixed': { es: 'Fijo', en: 'Fixed' },
  'admin.expenses.kind.variable': { es: 'Variable', en: 'Variable' },
  'admin.expenses.cadence.monthly': { es: 'Mensual', en: 'Monthly' },
  'admin.expenses.cadence.biweekly': { es: 'Quincenal', en: 'Biweekly' },
  'admin.expenses.method.cash': { es: 'Efectivo', en: 'Cash' },
  'admin.expenses.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'admin.expenses.method.card': { es: 'Tarjeta', en: 'Card' },
  'admin.expenses.cat.rent': { es: 'Arriendo', en: 'Rent' },
  'admin.expenses.cat.utilities': { es: 'Servicios públicos', en: 'Utilities' },
  'admin.expenses.cat.internet': { es: 'Internet y telefonía', en: 'Internet and phone' },
  'admin.expenses.cat.cleaning': { es: 'Aseo', en: 'Cleaning' },
  'admin.expenses.cat.software': { es: 'Software', en: 'Software' },
  'admin.expenses.cat.insurance': { es: 'Seguros', en: 'Insurance' },
  'admin.expenses.cat.supplies': { es: 'Insumos', en: 'Supplies' },
  'admin.expenses.cat.maintenance': { es: 'Mantenimiento', en: 'Maintenance' },
  'admin.expenses.cat.marketing': { es: 'Marketing', en: 'Marketing' },
  'admin.expenses.cat.fees': { es: 'Honorarios y comisiones', en: 'Fees and commissions' },
  'admin.expenses.cat.other': { es: 'Otros', en: 'Other' },
  'admin.finance.balance': { es: 'Balance del periodo', en: 'Period balance' },
  'admin.finance.balance.eyebrow': { es: 'Ingresos − Nómina − Gastos', en: 'Revenue − Payroll − Expenses' },
  'admin.finance.balance.revenue': { es: 'Ingresos', en: 'Revenue' },
  'admin.finance.balance.revenue.hint': { es: '{n} pagos aprobados', en: '{n} approved payments' },
  'admin.finance.balance.payroll': { es: 'Nómina', en: 'Payroll' },
  'admin.finance.balance.payroll.hint': { es: '{n} corridas cuyo periodo cruza el rango', en: '{n} runs whose period overlaps the range' },
  'admin.finance.balance.payroll.none': { es: 'sin corridas en el rango', en: 'no runs in the range' },
  'admin.finance.balance.expenses': { es: 'Gastos', en: 'Expenses' },
  'admin.finance.balance.expenses.hint': { es: 'fijos {fixed} · variables {variable}', en: 'fixed {fixed} · variable {variable}' },
  'admin.finance.balance.result': { es: 'Balance', en: 'Balance' },
  'admin.finance.balance.margin': { es: 'margen {pct} % sobre ingresos', en: '{pct} % margin on revenue' },
  'admin.finance.balance.noRevenue': { es: 'sin ingresos en el rango', en: 'no revenue in the range' },
  'admin.finance.balance.openPayroll': { es: 'Nómina (M-09a)', en: 'Payroll (M-09a)' },
  'admin.finance.balance.openExpenses': { es: 'Gastos (M-09c)', en: 'Expenses (M-09c)' },
  'admin.finance.balance.body': { es: 'Ingresos son los pagos aprobados del rango. Nómina toma cada corrida cuyo periodo mensual cruza el rango, al total actual (el borrador cuenta: las clases ya se dictaron). Gastos son los fijos y variables con fecha en el rango, pagados o no.', en: 'Revenue is the approved payments in the range. Payroll takes every run whose monthly period overlaps the range, at its current total (a draft counts: the classes were taught). Expenses are the fixed and variable rows dated in the range, paid or not.' },
};
