import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'admin.tables.title': { es: 'Tablas', en: 'Tables' },
  'admin.tables.subtitle': { es: 'Todas las tablas del sistema, tal como vivirán en Supabase. Edita filas, filtra y exporta.', en: 'Every table in the system, as it will live in Supabase. Edit rows, filter and export.' },
  'admin.tables.pick': { es: 'Elige una tabla en la barra lateral.', en: 'Pick a table in the sidebar.' },
  'admin.tables.search': { es: 'Buscar en {table}…', en: 'Search {table}…' },
  'admin.tables.columns': { es: '{n} columnas', en: '{n} columns' },
  'admin.tables.row': { es: 'Fila', en: 'Row' },
  'admin.tables.references': { es: 'referencia a', en: 'references' },
  'admin.tables.provider': { es: 'Proveedor: {name}', en: 'Provider: {name}' },
  'admin.tables.resetSeed': { es: 'Reiniciar datos demo', en: 'Reset demo data' },
  'admin.tables.resetConfirm': { es: '¿Borrar todos los cambios y volver a los datos demo?', en: 'Discard all changes and return to demo data?' },
  'admin.tables.addRow': { es: 'Nueva fila', en: 'New row' },
  'admin.tables.deleteConfirm': { es: '¿Eliminar esta fila?', en: 'Delete this row?' },
  'admin.tables.saved': { es: 'Guardado', en: 'Saved' },
  'admin.tables.readonly': { es: 'Solo lectura (generado)', en: 'Read only (generated)' },
  'admin.tables.groups': { es: 'Grupos', en: 'Groups' },
  'admin.tables.schema': { es: 'Esquema', en: 'Schema' },
  'admin.tables.data': { es: 'Datos', en: 'Data' },
  'admin.dashboard.title': { es: 'Panel', en: 'Dashboard' },
  'admin.dashboard.members': { es: 'Miembros activos', en: 'Active members' },
  'admin.dashboard.revenue': { es: 'Ingresos 30 días', en: 'Revenue 30 days' },
  'admin.dashboard.occupancy': { es: 'Ocupación 7 días', en: 'Occupancy 7 days' },
  'admin.dashboard.flags': { es: 'Interruptores de funciones', en: 'Feature switches' },
  'admin.dashboard.flags.body': { es: 'Cada bloque de cada pantalla se puede apagar aquí. Los valores vienen de la tabla feature_flags.', en: 'Every block of every screen can be turned off here. Values come from the feature_flags table.' },
};
