import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  // S-01
  'staff.home.title': { es: 'Hoy en recepción', en: 'Front desk today' },
  'staff.home.role': { es: 'Estás viendo el inicio de {role}.', en: 'You are viewing the {role} home.' },
  'staff.home.todayClasses': { es: 'Clases de hoy', en: 'Today’s classes' },
  'staff.home.arrivals': { es: 'Llegadas hoy', en: 'Arrivals today' },
  'staff.home.arrivals.hint': { es: '{n} por llegar', en: '{n} still expected' },
  'staff.home.openShifts': { es: 'Turnos pendientes', en: 'Open shifts' },
  'staff.home.openShifts.hint': { es: 'de {n} clases hoy', en: 'of {n} classes today' },
  'staff.home.waitlist': { es: 'En lista de espera', en: 'On waitlist' },
  'staff.home.payments': { es: 'Cobros hoy', en: 'Payments today' },
  'staff.home.pending': { es: '{n} pendientes', en: '{n} pending' },
  'staff.home.next': { es: 'Próxima clase', en: 'Next class' },
  'staff.home.next.empty': { es: 'No quedan clases hoy.', en: 'No classes left today.' },
  'staff.home.quick': { es: 'Acciones rápidas', en: 'Quick actions' },
  'staff.home.openCheckin': { es: 'Abrir check-in', en: 'Open check-in' },
  'staff.home.openRegister': { es: 'Registrar y cobrar', en: 'Register & pay' },
  'staff.home.openCrm': { es: 'Buscar miembro (CRM)', en: 'Find a member (CRM)' },
  'staff.home.openTables': { es: 'Ver tablas', en: 'View tables' },
  'staff.home.activity': { es: 'Actividad reciente', en: 'Recent activity' },
  'staff.home.activity.note': { es: 'Cada acción del equipo queda en el registro con nombre y hora.', en: 'Every staff action is logged with name and time.' },
  'staff.home.system': { es: 'Sistema', en: 'System' },

  // S-02
  'staff.checkin.title': { es: 'Check-in', en: 'Check-in' },
  'staff.checkin.subtitle': { es: 'Quién se espera, quién llegó, y vender un cupo en el momento.', en: 'Who is expected, who arrived, and sell a drop-in on the spot.' },
  'staff.checkin.today': { es: 'Clases de hoy', en: 'Today’s classes' },
  'staff.checkin.strip.hint': { es: 'Toca una clase para ver su lista', en: 'Tap a class to see its roster' },
  'staff.checkin.phase.now': { es: 'Ahora', en: 'Now' },
  'staff.checkin.phase.next': { es: 'Después', en: 'Later' },
  'staff.checkin.phase.past': { es: 'Terminó', en: 'Done' },
  'staff.checkin.noClasses': { es: 'Hoy no hay clases programadas', en: 'No classes scheduled today' },
  'staff.checkin.noClasses.body': { es: 'El horario se genera desde las plantillas de clase en Contenido.', en: 'The schedule is generated from class templates in Content.' },
  'staff.checkin.arrivals': { es: '{n} de {total} llegaron', en: '{n} of {total} arrived' },
  'staff.checkin.grace': { es: 'gracia {n} min', en: '{n} min grace' },
  'staff.checkin.search.ph': { es: 'Nombre, WhatsApp o email…', en: 'Name, WhatsApp or email…' },
  'staff.checkin.kbd': { es: 'Pulsa / para buscar · Enter hace check-in del primero · Esc limpia', en: 'Press / to search · Enter checks in the first · Esc clears' },
  'staff.checkin.readonly': { es: 'Tu rol puede ver la lista pero no marcar llegadas.', en: 'Your role can see the roster but cannot mark arrivals.' },
  'staff.checkin.expected': { es: 'Esperados', en: 'Expected' },
  'staff.checkin.arrived': { es: 'Llegaron', en: 'Checked in' },
  'staff.checkin.missed': { es: 'No vinieron', en: 'Did not come' },
  'staff.checkin.emptyRoster': { es: 'Nadie reservado todavía', en: 'Nobody booked yet' },
  'staff.checkin.noMatch': { es: 'Nadie en la lista coincide', en: 'Nobody on the roster matches' },
  'staff.checkin.noMatch.body': { es: 'Mira “Walk-in” a la derecha para agregar a alguien que no reservó.', en: 'See “Walk-in” on the right to add someone who did not book.' },
  'staff.checkin.checkin': { es: 'Check-in', en: 'Check in' },
  'staff.checkin.noShow': { es: 'No vino', en: 'No-show' },
  'staff.checkin.undo': { es: 'Deshacer', en: 'Undo' },
  'staff.checkin.promote': { es: 'Dar cupo', en: 'Promote' },
  'staff.checkin.noPlan': { es: 'Sin plan', en: 'No plan' },
  'staff.checkin.teachers': { es: 'Profes de hoy', en: 'Teachers today' },
  'staff.checkin.teacher.arrived': { es: 'En sala', en: 'In room' },
  'staff.checkin.teacher.expected': { es: 'Esperado', en: 'Expected' },
  'staff.checkin.walkin': { es: 'Walk-in', en: 'Walk-in' },
  'staff.checkin.walkin.body': { es: 'Busca arriba a alguien que no reservó: si ya es cliente, entra con un toque; si es nuevo, regístralo y cobra.', en: 'Search above for someone who did not book: existing customers enter in one tap; new people get registered and charged.' },
  'staff.checkin.walkin.none': { es: 'No hay clientes con ese nombre.', en: 'No customers match.' },
  'staff.checkin.walkin.add': { es: 'Entrar', en: 'Check in' },
  'staff.checkin.walkin.register': { es: 'Registrar nuevo y cobrar', en: 'Register new & pay' },

  // S-04
  'staff.register.title': { es: 'Registrar y cobrar', en: 'Register & take payment' },
  'staff.register.subtitle': { es: 'Quién es, qué compra, cómo paga. Tres pasos sin salir de la pantalla.', en: 'Who they are, what they buy, how they pay. Three steps without leaving the screen.' },
  'staff.register.noPermission': { es: 'Tu rol no puede cobrar', en: 'Your role cannot take payments' },
  'staff.register.noPermission.body': { es: 'Recepción, administración y finanzas registran cobros.', en: 'Front desk, admin and finance take payments.' },
  'staff.register.step1': { es: 'Paso 1', en: 'Step 1' },
  'staff.register.step2': { es: 'Paso 2', en: 'Step 2' },
  'staff.register.step3': { es: 'Paso 3', en: 'Step 3' },
  'staff.register.who': { es: 'Quién', en: 'Who' },
  'staff.register.what': { es: 'Qué compra', en: 'What they buy' },
  'staff.register.what.hint': { es: 'Precios del Modelo de Valor v3. Nunca se escriben en el mostrador.', en: 'Prices from the value model v3. Never typed at the desk.' },
  'staff.register.how': { es: 'Cómo paga', en: 'How they pay' },
  'staff.register.new': { es: 'Nueva persona', en: 'New person' },
  'staff.register.existing': { es: 'Ya es cliente', en: 'Existing member' },
  'staff.register.f.first': { es: 'Nombre', en: 'First name' },
  'staff.register.f.last': { es: 'Apellido', en: 'Last name' },
  'staff.register.f.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'staff.register.f.whatsapp.hint': { es: 'Recibe el recibo y los recordatorios.', en: 'Gets the receipt and reminders.' },
  'staff.register.f.email': { es: 'Email', en: 'Email' },
  'staff.register.f.emergency': { es: 'Contacto de emergencia', en: 'Emergency contact' },
  'staff.register.f.emergency.ph': { es: 'Nombre y teléfono', en: 'Name and phone' },
  'staff.register.f.birthday': { es: 'Cumpleaños', en: 'Birthday' },
  'staff.register.consent': { es: 'Acepta términos y política de datos (verbal)', en: 'Accepts terms and data policy (verbal)' },
  'staff.register.consent.hint': { es: 'Se registra con fecha, versión del documento y tu nombre ({staff}).', en: 'Recorded with timestamp, document version and your name ({staff}).' },
  'staff.register.search.ph': { es: 'Buscar por nombre, WhatsApp o email…', en: 'Search by name, WhatsApp or email…' },
  'staff.register.search.none': { es: 'No encontramos a nadie.', en: 'Nobody found.' },
  'staff.register.method.cash': { es: 'Efectivo', en: 'Cash' },
  'staff.register.method.cash.hint': { es: 'Se liquida al instante', en: 'Settles immediately' },
  'staff.register.method.datafono': { es: 'Datáfono', en: 'Card terminal' },
  'staff.register.method.datafono.hint': { es: 'Tarjeta en el mostrador', en: 'Card at the desk' },
  'staff.register.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'staff.register.method.transfer.hint': { es: 'Bancolombia / Davivienda', en: 'Bank transfer' },
  'staff.register.method.nequi': { es: 'Nequi', en: 'Nequi' },
  'staff.register.method.nequi.hint': { es: 'Pago desde el celular', en: 'Phone wallet' },
  'staff.register.method.wompi': { es: 'Link Wompi', en: 'Wompi link' },
  'staff.register.method.wompi.hint': { es: 'Queda pendiente hasta confirmar', en: 'Pending until confirmed' },
  'staff.register.wompi.note': { es: 'Marcador: el link de pago se enviará por WhatsApp cuando Wompi esté conectado. La venta queda pendiente y no activa el plan hasta que el gateway confirme.', en: 'Placeholder: the payment link will be sent by WhatsApp once Wompi is connected. The sale stays pending and does not activate the plan until the gateway confirms.' },
  'staff.register.wompi.pending': { es: 'Pago pendiente: el plan se activa cuando Wompi confirme el link.', en: 'Payment pending: the plan activates when Wompi confirms the link.' },
  'staff.register.receipt.wa': { es: 'Recibo por WhatsApp', en: 'Receipt by WhatsApp' },
  'staff.register.receipt.email': { es: 'Recibo por email', en: 'Receipt by email' },
  'staff.register.summary': { es: 'Resumen', en: 'Summary' },
  'staff.register.summary.noone': { es: 'Sin persona todavía', en: 'No person yet' },
  'staff.register.iva': { es: 'IVA {pct}%', en: 'IVA {pct}%' },
  'staff.register.iva.included': { es: 'incluido', en: 'included' },
  'staff.register.total': { es: 'Total', en: 'Total' },
  'staff.register.checkinTo': { es: 'Check-in a la clase', en: 'Check in to class' },
  'staff.register.checkinTo.hint': { es: 'Completar la venta también la deja dentro de la clase.', en: 'Completing the sale also checks them into the class.' },
  'staff.register.checkinTo.off': { es: 'Desactivado en Ajustes.', en: 'Turned off in Settings.' },
  'staff.register.checkinTo.none': { es: 'Sin check-in', en: 'No check-in' },
  'staff.register.cta': { es: 'Completar venta', en: 'Complete sale' },
  'staff.register.cta.link': { es: 'Crear link y dejar pendiente', en: 'Create link, leave pending' },
  'staff.register.audit': { es: 'Cada acción queda en el registro a nombre de {staff}.', en: 'Every action is logged under {staff}.' },
  'staff.register.done': { es: 'Venta completa', en: 'Sale complete' },
  'staff.register.done.new': { es: '{name} quedó registrada como cliente.', en: '{name} is now registered as a customer.' },
  'staff.register.done.existing': { es: 'Cobro registrado a {name}.', en: 'Payment recorded for {name}.' },
  'staff.register.done.checkedIn': { es: 'Check-in: {cls}', en: 'Checked in: {cls}' },
  'staff.register.print': { es: 'Imprimir recibo', en: 'Print receipt' },
  'staff.register.newSale': { es: 'Nueva venta', en: 'New sale' },
};
