import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'manual.title': { es: 'Manual de operaciones', en: 'Operations manual' },
  'manual.tagline': { es: 'La vida es HOY.', en: 'La vida es HOY.' },
  'manual.cover.lead': { es: 'Cómo funciona {studio} en {city}: quiénes somos, cómo se abre la puerta, cómo se cobra y qué dice el sistema. El español es la fuente; el inglés es el espejo.', en: 'How {studio} runs in {city}: who we are, how the door opens, how money is taken and what the system says. Spanish is the source; English mirrors it.' },
  'manual.cover.chapters': { es: '{n} capítulos en {parts} partes', en: '{n} chapters across {parts} parts' },
  'manual.cover.weight': { es: '{min} min de lectura · {img} capturas', en: '{min} min of reading · {img} figures' },
  'manual.part': { es: 'Parte', en: 'Part' },
  'manual.chapters': { es: 'Capítulos', en: 'Chapters' },
  'manual.summary': { es: 'Resumen', en: 'Summary' },
  'manual.search': { es: 'Buscar en el manual', en: 'Search the manual' },
  'manual.search.placeholder': { es: 'Buscar capítulo, tema o pantalla…', en: 'Search a chapter, topic or screen…' },
  'manual.search.count': { es: '{n} capítulos', en: '{n} chapters' },
  'manual.start': { es: 'Empieza por aquí', en: 'Start here' },
  'manual.start.lead': { es: 'Tres capítulos por rol: con esos ya puedes trabajar el primer día.', en: 'Three chapters per role: enough to work your first day.' },
  'manual.onThisPage': { es: 'En esta página', en: 'On this page' },
  'manual.decisions': { es: 'Decisiones pendientes', en: 'Decisions pending' },
  'manual.decisions.intro': { es: 'Todo lo que el estudio aún no ha definido, extraído automáticamente de los capítulos (bloques «DECISIÓN PENDIENTE»). Cada punto necesita una respuesta del owner; cuando se decida, se edita el capítulo y desaparece de aquí.', en: 'Everything the studio has not defined yet, extracted automatically from the chapters ("DECISION NEEDED" blocks). Each item needs an answer from the owner; once decided, edit the chapter and it disappears from this list.' },
  'manual.decisions.count': { es: '{n} decisiones pendientes', en: '{n} decisions pending' },
  'manual.decisions.none': { es: 'No hay decisiones pendientes.', en: 'No decisions pending.' },
  'manual.decisions.inChapter': { es: 'En el capítulo', en: 'In chapter' },
  'manual.placeholders.count': { es: '{n} capturas por tomar', en: '{n} screenshots to capture' },
  'manual.placeholders.total': { es: 'Quedan {n} marcadores de captura en el manual: pantallas que todavía no tienen foto.', en: '{n} capture placeholders remain in the manual: screens with no photo yet.' },
  'manual.prev': { es: 'Anterior', en: 'Previous' },
  'manual.next': { es: 'Siguiente', en: 'Next' },
  'manual.print': { es: 'Imprimir', en: 'Print' },
  'manual.role': { es: 'Para', en: 'For' },
  'manual.version': { es: 'Versión', en: 'Version' },
  'manual.updated': { es: 'Actualizado', en: 'Updated' },
  'manual.fallback': { es: 'Este capítulo aún no está traducido; se muestra la versión en español.', en: 'This chapter is not translated yet; the Spanish version is shown.' },
  'manual.notFound': { es: 'No existe ese capítulo.', en: 'No such chapter.' },
  'manual.langNote': { es: 'El español es la fuente; el inglés es un espejo. Cambia el idioma con ES/EN en la barra superior.', en: 'Spanish is the source; English mirrors it. Switch with ES/EN in the top bar.' },
  'manual.openChapter': { es: 'Abrir capítulo', en: 'Open chapter' },
};
