import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'manual.title': { es: 'Manual de operaciones', en: 'Operations manual' },
  'manual.tagline': { es: 'La vida es HOY.', en: 'La vida es HOY.' },
  'manual.cover.lead': { es: 'Cómo funciona {studio} en {city}: quiénes somos, cómo se abre la puerta, cómo se cobra y qué dice el sistema. El español es la fuente; el inglés es el espejo.', en: 'How {studio} runs in {city}: who we are, how the door opens, how money is taken and what the system says. Spanish is the source; English mirrors it.' },
  'manual.cover.chapters': { es: '{n} capítulos en {parts} partes', en: '{n} chapters across {parts} parts' },
  'manual.cover.weight': { es: '{min} min de lectura · {img} capturas', en: '{min} min of reading · {img} figures' },
  'manual.part': { es: 'Parte', en: 'Part' },
  'manual.chapters': { es: 'Capítulos', en: 'Chapters' },
  'manual.summary': { es: 'Resumen', en: 'Summary' },
  'manual.search': { es: 'Buscar en el manual', en: 'Search the manual' },
  'manual.search.placeholder': { es: 'Buscar capítulo, tema o pantalla…', en: 'Search a chapter, topic or screen…' },
  'manual.search.count': { es: '{n} capítulos', en: '{n} chapters' },
  'manual.start': { es: 'Empieza por aquí', en: 'Start here' },
  'manual.start.lead': { es: 'Tres capítulos por rol: con esos ya puedes trabajar el primer día.', en: 'Three chapters per role: enough to work your first day.' },
  'manual.onThisPage': { es: 'En esta página', en: 'On this page' },
  'manual.decisions': { es: 'Decisiones pendientes', en: 'Decisions pending' },
  'manual.decisions.intro': { es: 'Todo lo que el estudio aún no ha definido, extraído automáticamente de los capítulos (bloques «DECISIÓN PENDIENTE»). Cada punto necesita una respuesta del owner; cuando se decida, se edita el capítulo y desaparece de aquí.', en: 'Everything the studio has not defined yet, extracted automatically from the chapters ("DECISION NEEDED" blocks). Each item needs an answer from the owner; once decided, edit the chapter and it disappears from this list.' },
  'manual.decisions.count': { es: '{n} decisiones pendientes', en: '{n} decisions pending' },
  'manual.decisions.none': { es: 'No hay decisiones pendientes.', en: 'No decisions pending.' },
  'manual.decisions.inChapter': { es: 'En el capítulo', en: 'In chapter' },
  'manual.placeholders.count': { es: '{n} capturas por tomar', en: '{n} screenshots to capture' },
  'manual.placeholders.total': { es: 'Quedan {n} marcadores de captura en el manual: pantallas que todavía no tienen foto.', en: '{n} capture placeholders remain in the manual: screens with no photo yet.' },
  'manual.prev': { es: 'Anterior', en: 'Previous' },
  'manual.next': { es: 'Siguiente', en: 'Next' },
  'manual.print': { es: 'Imprimir', en: 'Print' },
  'manual.role': { es: 'Para', en: 'For' },
  'manual.version': { es: 'Versión', en: 'Version' },
  'manual.updated': { es: 'Actualizado', en: 'Updated' },
  'manual.fallback': { es: 'Este capítulo aún no está traducido; se muestra la versión en español.', en: 'This chapter is not translated yet; the Spanish version is shown.' },
  'manual.notFound': { es: 'No existe ese capítulo.', en: 'No such chapter.' },
  'manual.langNote': { es: 'El español es la fuente; el inglés es un espejo. Cambia el idioma con ES/EN en la barra superior.', en: 'Spanish is the source; English mirrors it. Switch with ES/EN in the top bar.' },
  'manual.openChapter': { es: 'Abrir capítulo', en: 'Open chapter' },
  'manual.meta.minutes': { es: 'min de lectura', en: 'min read' },
  'manual.meta.figure': { es: 'captura', en: 'figure' },
  'manual.meta.figures': { es: 'capturas', en: 'figures' },
  'manual.meta.decisions': { es: 'decisiones', en: 'decisions' },
  'manual.meta.placeholders': { es: 'por capturar', en: 'to capture' },
  // LiveBlock (src/components/organism/LiveBlock) — the live-data blocks a chapter embeds with {{…}}
  'manual.live.badge': { es: 'en vivo', en: 'live' },
  'manual.live.foot': { es: 'Datos en vivo del sistema', en: 'Live from the system' },
  'manual.live.yes': { es: 'sí', en: 'yes' },
  'manual.live.no': { es: 'no', en: 'no' },
  'manual.live.unknown': { es: 'no es una directiva que este manual sepa renderizar.', en: 'is not a directive this manual can render.' },
  'manual.live.available': { es: 'Disponibles:', en: 'Available:' },
  'manual.live.unit.hours': { es: 'horas', en: 'hours' },
  'manual.live.unit.minutes': { es: 'minutos', en: 'minutes' },
  'manual.live.unit.days': { es: 'días', en: 'days' },
  'manual.live.pricing.title': { es: 'Modelo de valor — cinco líneas de ingreso', en: 'Value model — five revenue lines' },
  'manual.live.pricing.eyebrow': { es: '{n} conceptos · src/tenant/pricing.ts', en: '{n} items · src/tenant/pricing.ts' },
  'manual.live.pricing.item': { es: 'Concepto', en: 'Item' },
  'manual.live.pricing.price': { es: 'Precio', en: 'Price' },
  'manual.live.pricing.validity': { es: 'Créditos / vigencia', en: 'Credits / validity' },
  'manual.live.pricing.class': { es: '{n} clase', en: '{n} class' },
  'manual.live.pricing.classes': { es: '{n} clases', en: '{n} classes' },
  'manual.live.pricing.days': { es: '{n} días', en: '{n} days' },
  'manual.live.pricing.renewsMonthly': { es: 'renueva cada mes', en: 'renews monthly' },
  'manual.live.pricing.renewsYearly': { es: 'renueva cada año', en: 'renews yearly' },
  'manual.live.tenant.title.hours': { es: 'Horario del estudio', en: 'Studio hours' },
  'manual.live.tenant.title.contact': { es: 'Contacto del estudio', en: 'Studio contact' },
  'manual.live.tenant.title.capacity': { es: 'Capacidad y disciplina', en: 'Capacity and discipline' },
  'manual.live.tenant.title.all': { es: 'El estudio', en: 'The studio' },
  'manual.live.tenant.source': { es: 'Ajustes › General (M-08a)', en: 'Settings › General (M-08a)' },
  'manual.live.tenant.hours': { es: 'Horario', en: 'Opening hours' },
  'manual.live.tenant.today': { es: 'Hoy', en: 'Today' },
  'manual.live.tenant.overrides': { es: 'Próximos 30 días', en: 'Next 30 days' },
  'manual.live.tenant.timezone': { es: 'Zona horaria', en: 'Time zone' },
  'manual.live.tenant.email': { es: 'Correo', en: 'Email' },
  'manual.live.tenant.address': { es: 'Dirección', en: 'Address' },
  'manual.live.tenant.city': { es: 'Ciudad', en: 'City' },
  'manual.live.tenant.mats': { es: 'Mats por clase', en: 'Mats per class' },
  'manual.live.tenant.classesPerDay': { es: 'Clases por día', en: 'Classes per day' },
  'manual.live.tenant.perPerson': { es: 'Clases por persona por día', en: 'Classes per person per day' },
  'manual.live.tenant.rooms': { es: 'Salas', en: 'Rooms' },
  'manual.live.tenant.seatsPerDay': { es: 'Cupos por día', en: 'Seats per day' },
  'manual.live.policy.title': { es: 'Políticas vigentes', en: 'Policies in force' },
  'manual.live.policy.eyebrow': { es: 'M-08a Ajustes y políticas · M-08c Nómina', en: 'M-08a Settings & policies · M-08c Payroll' },
  'manual.live.policy.current': { es: 'Valor vigente de la política', en: 'Current policy value' },
  'manual.live.policy.source.policies': { es: 'fuente: Ajustes › Políticas (M-08a)', en: 'source: Settings › Policies (M-08a)' },
  'manual.live.policy.source.payments': { es: 'fuente: Ajustes › Pagos (M-08c)', en: 'source: Settings › Payments (M-08c)' },
  'manual.live.policy.source.both': { es: 'fuente: Ajustes › Políticas (M-08a) · Pagos (M-08c)', en: 'source: Settings › Policies (M-08a) · Payments (M-08c)' },
  'manual.live.policy.cancellationHours': { es: 'Ventana de cancelación sin costo', en: 'Free cancellation window' },
  'manual.live.policy.waitlistClaimMin': { es: 'Reclamo de lista de espera', en: 'Waitlist claim window' },
  'manual.live.policy.lateGraceMin': { es: 'Tolerancia de llegada tarde', en: 'Late-arrival grace' },
  'manual.live.policy.noShowFee': { es: 'Cargo por inasistencia', en: 'No-show fee' },
  'manual.live.policy.pauseDaysPerYear': { es: 'Días de pausa por año', en: 'Pause days per year' },
  'manual.live.policy.maxPausesPerYear': { es: 'Pausas por año', en: 'Pauses per year' },
  'manual.live.policy.paymentHoldMin': { es: 'Reserva sostenida durante el pago', en: 'Booking held during payment' },
  'manual.live.policy.chargeNoticeDays': { es: 'Aviso antes de cada cobro', en: 'Notice before each charge' },
  'manual.live.policy.lockoutAttempts': { es: 'Intentos antes de bloquear', en: 'Attempts before lockout' },
  'manual.live.policy.lockoutMinutes': { es: 'Duración del bloqueo', en: 'Lockout duration' },
  'manual.live.policy.quietHours': { es: 'Horas silenciosas', en: 'Quiet hours' },
  'manual.live.policy.ivaPct': { es: 'IVA', en: 'IVA' },
  'manual.live.policy.pricesIncludeIva': { es: 'Los precios publicados incluyen IVA', en: 'Published prices include IVA' },
  'manual.live.policy.payrollCadence': { es: 'Periodicidad de la nómina de profesores', en: 'Teacher payroll cadence' },
  'manual.live.policy.payoutMethod': { es: 'Medio de pago de la nómina por defecto', en: 'Default payroll payout method' },
  'manual.live.policy.payrollSignedBy': { es: 'Quién firma el soporte de pago', en: 'Who signs the payment record' },
  'manual.live.policy.cadence.biweekly': { es: 'quincenal (1–15 · 16–fin)', en: 'biweekly (1–15 · 16–end)' },
  'manual.live.policy.cadence.monthly': { es: 'mensual', en: 'monthly' },
  'manual.live.policy.payout.transfer': { es: 'transferencia', en: 'transfer' },
  'manual.live.policy.payout.cash': { es: 'efectivo', en: 'cash' },
  'manual.live.policy.signedBy.pending': { es: 'pendiente (M-08c)', en: 'pending (M-08c)' },
  'manual.live.policy.noFee': { es: 'sin cargo', en: 'none' },
  'manual.live.tables.title': { es: 'Modelo de datos — {n} tablas', en: 'Data model — {n} tables' },
  'manual.live.table.column': { es: 'Columna', en: 'Column' },
  'manual.live.table.type': { es: 'Tipo', en: 'Type' },
  'manual.live.table.notes': { es: 'Notas', en: 'Notes' },
  'manual.live.table.rls': { es: 'Quién puede leer / escribir', en: 'Who may read / write' },
  'manual.live.table.noRls': { es: 'Esta tabla aún no tiene contrato de acceso escrito.', en: 'No access contract written yet for this table.' },
  'manual.live.roles.title': { es: 'Roles y dónde entran', en: 'Roles and where they land' },
  'manual.live.roles.role': { es: 'Rol', en: 'Role' },
  'manual.live.roles.home': { es: 'Entra en', en: 'Home' },
  'manual.live.roles.routes': { es: 'Rutas', en: 'Routes' },
  'manual.live.routes.title': { es: 'Pantallas de la superficie {surface}', en: 'Screens of the {surface} surface' },
  'manual.live.routes.eyebrow': { es: '{n} rutas · manifiesto de rutas en vivo', en: '{n} routes · live route manifest' },
  'manual.live.routes.code': { es: 'Código', en: 'Code' },
  'manual.live.routes.screen': { es: 'Pantalla', en: 'Screen' },
  'manual.live.routes.route': { es: 'Ruta', en: 'Route' },
  'manual.live.stats.title': { es: 'El estudio ahora mismo', en: 'The studio right now' },
  'manual.live.stats.eyebrow': { es: 'Contado en la capa de datos al renderizar', en: 'Counted from the data layer at render time' },
  'manual.live.stats.profiles': { es: 'Personas con perfil', en: 'People with a profile' },
  'manual.live.stats.memberships': { es: 'Membresías activas', en: 'Active memberships' },
  'manual.live.stats.week': { es: 'Clases en los próximos 7 días', en: 'Classes in the next 7 days' },
  'manual.live.stats.teachers': { es: 'Maestros activos', en: 'Active teachers' },
  'manual.live.stats.bookings': { es: 'Reservas registradas', en: 'Bookings on record' },
  'manual.live.kpi.eyebrow': { es: 'KPI · panel M-01', en: 'KPI · M-01 dashboard' },
  'manual.live.kpi.occupancy': { es: 'Ocupación', en: 'Occupancy' },
  'manual.live.kpi.occupancy.hint': { es: 'asistentes / ({mats} × clases dictadas)', en: 'attendees / ({mats} × classes taught)' },
  'manual.live.kpi.noshow': { es: 'No-show', en: 'No-show' },
  'manual.live.kpi.noshow.hint': { es: 'reservas marcadas como no-show sobre el total', en: 'bookings marked no-show over the total' },
  'manual.live.kpi.classes': { es: 'Clases dictadas', en: 'Classes taught' },
  'manual.live.kpi.classes.hint': { es: 'sesiones con estado completed', en: 'sessions with status completed' },

  // ---- 0031 · the manual as a staff LMS ----
  'manual.lens.label': { es: 'Ver el manual como…', en: 'View the manual as…' },
  'manual.lens.all': { es: 'Todo el manual', en: 'The whole manual' },
  'manual.level.required': { es: 'Obligatorio para {role}', en: 'Required for {role}' },
  'manual.level.recommended': { es: 'Recomendado para {role}', en: 'Recommended for {role}' },
  'manual.level.na': { es: 'No aplica para {role}', en: 'Not for {role}' },
  'manual.aud.label': { es: 'Para quién es este capítulo', en: 'Who this chapter is for' },
  'manual.aud.for': { es: 'Para:', en: 'For:' },
  'manual.aud.recommended': { es: 'recomendado', en: 'recommended' },
  'manual.aud.title': { es: 'Quién lee qué', en: 'Who reads what' },
  'manual.aud.chapter': { es: 'Capítulo', en: 'Chapter' },
  'manual.aud.legend': { es: '● obligatorio · ○ recomendado · – no aplica', en: '● required · ○ recommended · – n/a' },
  'manual.aud.source': { es: 'la misma tabla filtra el manual de cada rol', en: 'the same table filters each role’s manual' },
  'manual.for.label': { es: 'Para: {roles}', en: 'For: {roles}' },
  'manual.for.only': { es: 'Solo para {roles} — ábrelo si te toca', en: 'Only for {roles} — open it if it applies to you' },
  'manual.side.legend': { es: '● obligatorio · ○ recomendado · ✓ leído — para {role}', en: '● required · ○ recommended · ✓ read — for {role}' },
  'manual.lms.eyebrowOwn': { es: 'Tu manual', en: 'Your manual' },
  'manual.lms.eyebrow': { es: 'El manual de {role}', en: 'The {role} manual' },
  'manual.lms.titleOwn': { es: 'Lo que te toca leer', en: 'What you need to read' },
  'manual.lms.title': { es: 'Lo que lee {role}', en: 'What {role} reads' },
  'manual.lms.lead': { es: '{req} capítulos obligatorios y {rec} recomendados. Los demás siguen abiertos, atenuados.', en: '{req} required chapters and {rec} recommended. The rest stay open, dimmed.' },
  'manual.lms.progressOf': { es: 'Progreso de {name} (persona demo del rol).', en: 'Progress of {name} (the role’s demo person).' },
  'manual.lms.ring': { es: 'obligatorios leídos', en: 'required read' },
  'manual.lms.ringAria': { es: '{n} de {m} capítulos obligatorios leídos', en: '{n} of {m} required chapters read' },
  'manual.lms.start': { es: 'Empieza por aquí', en: 'Start here' },
  'manual.lms.required': { es: 'Obligatorio', en: 'Required' },
  'manual.lms.recommended': { es: 'Recomendado', en: 'Recommended' },
  'manual.lms.none': { es: 'Nada en esta lista.', en: 'Nothing on this list.' },
  'manual.tile.progress': { es: 'Tu avance', en: 'Your progress' },
  'manual.tile.readHint': { es: 'leídos', en: 'read' },
  'manual.tile.chapters': { es: 'Capítulos', en: 'Chapters' },
  'manual.tile.minutes': { es: '{min} min de lectura', en: '{min} min of reading' },
  'manual.tile.decisions': { es: 'Decisiones pendientes', en: 'Decisions pending' },
  'manual.tile.decisionsHint': { es: 'lo que el owner aún no define', en: 'what the owner has not defined' },
  'manual.tile.requests': { es: 'Solicitudes abiertas', en: 'Open requests' },
  'manual.tile.requestsHint': { es: 'cambios que pidió el equipo', en: 'changes the team asked for' },
  'manual.tile.sources': { es: 'Documentos fuente', en: 'Source documents' },
  'manual.tile.sourcesHint': { es: 'modelo de valor, textos y marca', en: 'value model, copy and brand' },
  'manual.read.mark': { es: 'Marcar como leído', en: 'Mark as read' },
  'manual.read.done': { es: 'Leído el {date}', en: 'Read on {date}' },
  'manual.read.short': { es: 'Leído', en: 'Read' },
  'manual.read.pending': { es: 'sin leer', en: 'not read yet' },
  'manual.read.newVersion': { es: 'Hay una versión nueva', en: 'There is a new version' },
  'manual.train.title': { es: 'Formación', en: 'Training' },
  'manual.train.titleRole': { es: 'Formación de {role}', en: '{role} training' },
  'manual.train.eyebrow': { es: 'Día 1 · Semana 1 · Mes 1', en: 'Day 1 · Week 1 · Month 1' },
  'manual.train.stage.day1': { es: 'Día 1', en: 'Day 1' },
  'manual.train.stage.week1': { es: 'Semana 1', en: 'Week 1' },
  'manual.train.stage.month1': { es: 'Mes 1', en: 'Month 1' },
  'manual.train.person': { es: 'Persona en formación', en: 'Person in training' },
  'manual.train.you': { es: 'tú', en: 'you' },
  'manual.train.yours': { es: 'Tu checklist: marca cada punto cuando lo hayas hecho; quien te entrena firma la etapa.', en: 'Your checklist: tick each item once done; your trainer signs off the stage.' },
  'manual.train.readOnly': { es: 'Checklist de {name} (solo lectura).', en: '{name}’s checklist (read-only).' },
  'manual.train.nobody': { es: 'Nadie tiene este rol todavía.', en: 'Nobody holds this role yet.' },
  'manual.train.sign': { es: 'Firmar etapa', en: 'Sign off stage' },
  'manual.train.signed': { es: 'Firmado por {name} · {date}', en: 'Signed by {name} · {date}' },
  'manual.train.signedShort': { es: 'firmado', en: 'signed' },
  'manual.train.unsigned': { es: 'Sin firmar: la firma la pone coordinación o el owner.', en: 'Not signed: coordination or the owner signs it.' },
  'manual.train.unknown': { es: 'necesita un rol con checklist.', en: 'needs a role that has a checklist.' },
  'manual.train.foot': { es: 'Se guarda por persona en HoyOS', en: 'Stored per person in HoyOS' },
  'manual.team.eyebrow': { es: 'Solo coordinación y owner', en: 'Coordination and owner only' },
  'manual.team.title': { es: 'Equipo', en: 'Team' },
  'manual.team.lead': { es: 'Cuánto lleva cada persona de su manual obligatorio y en qué etapa de formación va.', en: 'How far each person is through their required manual and which training stage they are in.' },
  'manual.team.person': { es: 'Persona', en: 'Person' },
  'manual.team.read': { es: 'Obligatorios leídos', en: 'Required read' },
  'manual.team.stage': { es: 'Formación', en: 'Training' },
  'manual.team.noPlan': { es: 'sin checklist', en: 'no checklist' },
  'manual.team.trained': { es: 'formación completa', en: 'fully trained' },
  'manual.team.stat.people': { es: 'Personas', en: 'People' },
  'manual.team.stat.avg': { es: 'Promedio leído', en: 'Average read' },
  'manual.team.stat.started': { es: 'Ya empezaron', en: 'Started' },
  'manual.team.stat.trained': { es: 'Formación completa', en: 'Fully trained' },
  'manual.edit.level.owner': { es: 'Ajustable por el owner', en: 'The owner can adjust this' },
  'manual.edit.level.coordinator': { es: 'Ajustable por coordinación', en: 'Coordination can adjust this' },
  'manual.edit.levelHint': { es: 'Esta sección es del estudio: se adapta desde aquí sin tocar el repositorio.', en: 'This section belongs to the studio: it is adapted from here without touching the repository.' },
  'manual.edit.count': { es: '{n} secciones ajustables', en: '{n} adjustable sections' },
  'manual.edit.badge': { es: 'Editado por {name} · {date}', en: 'Edited by {name} · {date}' },
  'manual.edit.original': { es: 'Ver original', en: 'See the original' },
  'manual.edit.edit': { es: 'Editar', en: 'Edit' },
  'manual.edit.history': { es: 'Historial ({n})', en: 'History ({n})' },
  'manual.edit.suggestions': { es: 'Sugerencias ({n})', en: 'Suggestions ({n})' },
  'manual.edit.suggestedBy': { es: 'Sugerido por {name} · {date}', en: 'Suggested by {name} · {date}' },
  'manual.edit.accept': { es: 'Aceptar y publicar', en: 'Accept and publish' },
  'manual.edit.dismiss': { es: 'Descartar', en: 'Dismiss' },
  'manual.edit.restore': { es: 'Restaurar original', en: 'Restore original' },
  'manual.edit.restored': { es: 'Se restauró el texto original; el historial se conserva.', en: 'The original text is back; the history is kept.' },
  'manual.edit.editLabel': { es: '{section} · {lang}', en: '{section} · {lang}' },
  'manual.edit.preview': { es: 'Así se verá', en: 'How it will look' },
  'manual.edit.empty': { es: 'La vista previa aparece mientras escribes.', en: 'The preview appears as you type.' },
  'manual.edit.note': { es: 'Por qué cambia (opcional)', en: 'Why it changes (optional)' },
  'manual.edit.notePh': { es: 'Ej.: ahora abrimos 30 min antes', en: 'E.g. we now open 30 min earlier' },
  'manual.edit.save': { es: 'Guardar', en: 'Save' },
  'manual.edit.saved': { es: 'Guardado: el manual ya muestra tu versión.', en: 'Saved: the manual now shows your version.' },
  'manual.edit.cancel': { es: 'Cancelar', en: 'Cancel' },
  'manual.edit.ai': { es: 'Reescribir con IA', en: 'Rewrite with AI' },
  'manual.edit.aiHint': { es: 'Aún no está conectado aquí; un agente ya puede hacerlo con el registro de acciones (manual.suggestEdit) y tú lo apruebas en «Sugerencias».', en: 'Not wired here yet; an agent can already do it through the actions registry (manual.suggestEdit) and you approve it under "Suggestions".' },
  'manual.edit.foot': { es: 'Editas como {role}. El markdown del repositorio no cambia: tu versión se guarda aparte, con historial, y se puede restaurar.', en: 'You are editing as {role}. The repository markdown does not change: your version is stored beside it, with history, and can be restored.' },
  'manual.edit.status.live': { es: 'publicada', en: 'live' },
  'manual.edit.status.reverted': { es: 'restaurada', en: 'reverted' },
  'manual.edit.status.suggested': { es: 'sugerida', en: 'suggested' },
  'manual.edit.status.dismissed': { es: 'descartada', en: 'dismissed' },
  'manual.policy.eyebrow': { es: 'Política del estudio', en: 'Studio policy' },
  'manual.policy.edit': { es: 'Editar: {label}', en: 'Edit: {label}' },
  'manual.policy.saved': { es: 'Política actualizada.', en: 'Policy updated.' },
  'manual.policy.updatedBy': { es: 'cambiada por {name} · {date}', en: 'changed by {name} · {date}' },
  'manual.policy.m08Edit': { es: 'Cambiar este valor', en: 'Change this value' },
  'manual.policy.m08a': { es: 'Este valor se cambia en Ajustes (M-08a).', en: 'This value is changed in Settings (M-08a).' },
  'manual.policy.m08c': { es: 'Este valor se cambia en Ajustes › Pagos (M-08c).', en: 'This value is changed in Settings › Payments (M-08c).' },
  'manual.policy.go': { es: 'Ir a Ajustes', en: 'Go to Settings' },
  'manual.req.title': { es: 'Pedir un cambio', en: 'Request a change' },
  'manual.req.lead': { es: '¿Algo no está claro, cambió o falta? Escríbelo aquí: le llega a coordinación y al owner (K-04).', en: 'Is something unclear, changed or missing? Write it here: it reaches coordination and the owner (K-04).' },
  'manual.req.section': { es: 'Sección', en: 'Section' },
  'manual.req.whole': { es: 'Todo el capítulo', en: 'The whole chapter' },
  'manual.req.what': { es: 'Qué debería decir', en: 'What it should say' },
  'manual.req.ph': { es: 'Ej.: los celulares olvidados se guardan bajo llave, no en la caja de perdidos.', en: 'E.g. forgotten phones are kept locked away, not in the lost-and-found box.' },
  'manual.req.send': { es: 'Enviar', en: 'Send' },
  'manual.req.sent': { es: 'Solicitud enviada. La verás aquí con su respuesta.', en: 'Request sent. You will see it here with its answer.' },
  'manual.req.agent': { es: 'Un agente también puede tomarla (manual.listRequests).', en: 'An agent can pick it up too (manual.listRequests).' },
  'manual.req.status.open': { es: 'abierta', en: 'open' },
  'manual.req.status.done': { es: 'resuelta', en: 'done' },
  'manual.req.status.dismissed': { es: 'descartada', en: 'dismissed' },
  'manual.req.panel': { es: 'Solicitudes del equipo', en: 'Team requests' },
  'manual.req.panelLead': { es: 'Lo que el equipo pidió cambiar en el manual. Responde, márcalo resuelto y, si toca, edita la sección desde el capítulo.', en: 'What the team asked to change in the manual. Answer, mark it done and, if needed, edit the section from the chapter.' },
  'manual.req.leadOnly': { es: 'Las solicitudes las responden coordinación y el owner. Pide un cambio desde el final de cualquier capítulo.', en: 'Coordination and the owner answer requests. Ask for a change at the end of any chapter.' },
  'manual.req.none': { es: 'No hay solicitudes abiertas.', en: 'No open requests.' },
  'manual.req.closed': { es: 'Resueltas y descartadas ({n})', en: 'Done and dismissed ({n})' },
  'manual.req.by': { es: 'Pedido por {name} · {date}', en: 'Asked by {name} · {date}' },
  'manual.req.answer': { es: 'Respuesta', en: 'Answer' },
  'manual.req.answerPh': { es: 'Qué se decidió (lo ve quien lo pidió)', en: 'What was decided (the requester sees it)' },
  'manual.req.done': { es: 'Resuelta', en: 'Done' },
  'manual.req.dismiss': { es: 'Descartar', en: 'Dismiss' },
  'manual.req.openCount': { es: '{n} solicitudes abiertas', en: '{n} open requests' },
  'manual.decisions.title': { es: 'Decisiones y solicitudes', en: 'Decisions and requests' },
  'manual.decisions.lead': { es: 'Lo que el estudio aún no ha definido y lo que el equipo pidió cambiar, en un solo lugar.', en: 'What the studio has not defined yet and what the team asked to change, in one place.' },
  'manual.source.kind.deck': { es: 'Presentación', en: 'Deck' },
  'manual.source.kind.web-copy': { es: 'Textos del sitio', en: 'Website copy' },
  'manual.source.kind.brand-manual': { es: 'Manual de marca', en: 'Brand manual' },
  'manual.source.meta': { es: '{pages} páginas · recibido {date}', en: '{pages} pages · received {date}' },
  'manual.source.viewHere': { es: 'Ver aquí', en: 'View here' },
  'manual.source.view': { es: 'Ver «{title}» aquí', en: 'View “{title}” here' },
  'manual.source.viewerTitle': { es: 'Visor de «{title}»', en: '“{title}” viewer' },
  'manual.source.fullscreen': { es: 'Pantalla completa', en: 'Fullscreen' },
  'manual.source.download': { es: 'Descargar PDF', en: 'Download PDF' },
  'manual.source.newTab': { es: 'Abrir en otra pestaña', en: 'Open in a new tab' },
  'manual.source.allSources': { es: 'Todos los documentos fuente', en: 'All source documents' },
  'manual.sources.nav': { es: 'Documentos fuente', en: 'Source documents' },
  'manual.sources.title': { es: 'Documentos fuente', en: 'Source documents' },
  'manual.sources.lead': { es: 'Los documentos del owner de donde salen el manual y el sitio. Ábrelos aquí, descárgalos o salta a los capítulos que los citan.', en: 'The owner’s documents the manual and the site are written from. Open them here, download them or jump to the chapters that cite them.' },
  'manual.sources.count': { es: '{n} documentos', en: '{n} documents' },
  'manual.sources.cited': { es: 'Citado en', en: 'Cited in' },
  'manual.sources.foot': { es: 'Índice en docs/source/index.json; archivos en public/source/. Un documento nuevo no necesita código.', en: 'Index in docs/source/index.json; files in public/source/. A new document needs no code.' },
  // audit titles for M-07 (admin.audit.<action>)
  'admin.audit.manual.read': { es: 'Capítulo del manual leído', en: 'Manual chapter read' },
  'admin.audit.manual.training.check': { es: 'Punto de formación hecho', en: 'Training item done' },
  'admin.audit.manual.training.uncheck': { es: 'Punto de formación desmarcado', en: 'Training item unticked' },
  'admin.audit.manual.training.sign': { es: 'Etapa de formación firmada', en: 'Training stage signed' },
  'admin.audit.manual.section.edit': { es: 'Sección del manual editada', en: 'Manual section edited' },
  'admin.audit.manual.section.suggest': { es: 'Edición del manual sugerida', en: 'Manual edit suggested' },
  'admin.audit.manual.section.restore': { es: 'Sección del manual restaurada', en: 'Manual section restored' },
  'admin.audit.manual.suggestion.accept': { es: 'Sugerencia del manual aceptada', en: 'Manual suggestion accepted' },
  'admin.audit.manual.suggestion.dismiss': { es: 'Sugerencia del manual descartada', en: 'Manual suggestion dismissed' },
  'admin.audit.manual.request': { es: 'Cambio al manual pedido', en: 'Manual change requested' },
  'admin.audit.manual.request.answer': { es: 'Solicitud del manual respondida', en: 'Manual request answered' },
  'admin.audit.manual.policy.edit': { es: 'Política del estudio cambiada', en: 'Studio policy changed' },
};
