/**
 * The customer module's view of the canvas specs: every code, with `layout` replaced by the real
 * section names the page renders (so the layout editor and inspector show what is on screen),
 * `data` narrowed to real table names from src/data/schema.ts, and notes on what is simulated.
 * Exported under the same name so tooling that greps `canvasSpecs['C-02']` keeps working.
 */
import { canvasSpecs as base } from '../../specs/canvasSpecs';
import { defineSpec } from '../../specs/define';
import type { PageSpec } from '../../specs/types';
import { CUSTOMER_ACTIONS } from './actions';

const ext = (code: string, patch: Partial<PageSpec>): PageSpec => {
  const b: PageSpec = base[code] ?? { code, name: { es: code, en: code }, purpose: { es: '', en: '' }, layout: [], data: [], roles: ['customer'], logic: [], integrations: [] };
  if (!base[code] && import.meta.env.DEV) console.warn(`[customer/specs] canvas code ${code} missing from canvasSpecs; using a minimal spec`);
  return defineSpec({ ...b, ...patch, notes: [...(b.notes ?? []), ...(patch.notes ?? [])] });
};

const WOMPI_NOTE = 'Wompi is simulated in src/modules/customer/payments.ts (wompiCheckout). Manual transfer/cash create pending payments the front desk settles.';

export const canvasSpecs: Record<string, PageSpec> = {
  ...base,
  'A-01': ext('A-01', { layout: ['BreathingRings + Wordmark', 'Tagline', 'LoadState', 'ContinueButton'], data: ['users', 'feature_flags'], logic: ['Breath cycle is 7 s (--dur-breath).', 'Auto-continues to /auth/sign-in after 2.8 s; a button skips the wait.'], states: ['breathing', 'reduced motion'], notes: ['Session restore is the demo session in localStorage; Supabase Auth later.'] }),
  'A-02': ext('A-02', { layout: ['Logo block', 'DemoUserPicker', 'CredentialCard (email, password)', 'Divider / OR', 'ProviderStack (Apple, Google, Biometric — disabled)', 'CreateAccountLink'], data: ['users', 'user_roles', 'audit_log'], states: ['default', 'wrong credentials: attempts left', 'locked → E-04'], notes: ['Demo mode: any demo user email signs in; 5 failed attempts route to /auth/locked (E-04).', 'Apple / Google / biometric buttons are disabled until Supabase Auth.'] }),
  'A-03': ext('A-03', { layout: ['ProgressDots', 'Heading + sub', 'FormStack (name, email, WhatsApp +57, password, birthday, emergency contact, photo)', 'ConsentRow → /site/legal', 'PrimaryButton'], data: ['users', 'profiles', 'user_roles', 'consents', 'legal_documents'], states: ['default', 'validation errors', 'duplicate email → sign-in offer', 'created'], notes: ['Inserts users + profiles + user_roles + consents rows via useData(), then SessionProvider signs in as the created row (any users id is accepted). The account lives until the mock reseeds on the next day.'] }),
  // 0030 — RETIRED. Justin asked to erase “¿Cómo quieres sentirte hoy?” from the experience: no route (the registry
  // redirects /app/intention → /app), no C-01 block, no sign-up hop, no flags. The code stays so history, docs and the
  // canvas reference still resolve. 0039 deleted the deprecated `intentions` table (nothing read or wrote it).
  'A-05': ext('A-05', { layout: [], data: [], states: ['retired (0030): /app/intention redirects to /app'], toggles: [], actions: [], notes: ['RETIRED in 0030 (0.12.0): removed from the customer experience end to end. Not routed; /app/intention redirects to /app. The intentions table was deleted in 0039.'] }),
  'C-01': ext('C-01', {
    layout: ['TopBar (logo, avatar, bell)', 'FeedbackPrompt (conditional)', 'MembershipNudge (if no plan)', 'AnnouncementCard (if active)', 'NextClassCard + countdown', 'QuickActions ×4', 'TodayList', 'StatsRow ×3', 'EventsStrip → BottomNav'],
    logic: (base['C-01']?.logic ?? []).filter((l) => !/intention/i.test(l)).concat(["Today's list is in start-time order (the A-05 intention sort was retired in 0030)."]),
    data: [...new Set([...(base['C-01']?.data ?? []), 'bookings', 'class_sessions', 'memberships', 'class_ledger', 'practice_goals', 'activity_events'])],
    notes: ['0030: the “¿Cómo quieres sentirte hoy?” card left the home; quick actions and the dock use the Icon set.', '0040: the StatsRow ×3 section (name kept for stored layouts) is the practice block — classes attended this month (by session date) + upcoming booked, weeks in a row on the goal (StreakBadge), plan balance labelled by what it is (membership → unlimited + renewal, credits → classes left + expiry), the week as WeekDots and a link to C-27. With no goal row yet it asks the weekly goal inline (GoalPicker). useMilestoneRecorder writes milestone / streak.saved events once; a newly recorded milestone shows a one-time toast.'],
  }),
  'A-06': ext('A-06', {
    layout: ['BackLink', 'LegalDocument (title, version, effective date, status badge)', 'CounselNotice', 'VersionSwitcher (when > 1 version)', 'AcceptanceReceipt + Accept', 'Body (markdown, {{policy.*}} resolved live)', 'SiblingLinks', 'PrintButton'],
    data: ['legal_documents', 'legal_acceptances', 'consents', 'tenants'],
    states: ['Published version in force', 'Draft pending counsel review', 'More than one version: switcher', 'Accepted by this member (date + channel)', 'Accepted an older version', 'Not accepted yet: accept action', 'Kind not found'],
    logic: [
      'Six kinds: terms, privacy, waiver, cancellation, refunds, house-rules. A new version is a new legal_documents row; a published row is never edited in place.',
      'The body carries {{tenant.*}} and {{policy.*}} tokens resolved at render time from src/tenant/tenant.ts + M-08 (usePolicy()), so the cancellation window on the page is the one the app enforces.',
      'legal_acceptances is append-only: user_id + document_id + version + accepted_at + channel. The in-app page shows the member the exact version they signed.',
      'Requires_acceptance marks the documents a member must accept (terms, privacy, waiver).',
    ],
    notes: [
      'Route /app/legal/:kind (customer surface) and /site/legal/:kind (public) render the same LegalDocument organism.',
      'Every version is studio-written and NOT counsel-reviewed yet: the notice says so on every render and the four documents not operationally in force keep status = draft.',
    ],
  }),
  'C-02': ext('C-02', { layout: ['ViewSwitch (Today / Week)', 'DateStrip', 'FilterBar → FilterSheet', 'ClassList → ClassRow', 'WeekGrid', 'Legend'], data: ['class_sessions', 'modalities', 'teachers', 'rooms', 'bookings', 'waitlist'], states: ['Loading: three skeleton rows', "Empty: 'No classes match' + clear-filters", 'Error: retry', 'Past days: rows read-only', 'Week view (C-02b)'], notes: ['C-02b week view is the Week segment of this page (?view=week).', 'Capacity updates live through useTable subscriptions (MockProvider change events).'] }),
  'C-02b': ext('C-02b', { layout: ['ViewSwitch (Today / Week)', 'FilterBar → FilterSheet', 'WeekGrid (Mon–Sat columns → DayChip)', 'Legend'], data: ['class_sessions', 'modalities', 'teachers', 'rooms', 'bookings'], states: ['Loading: skeleton', 'Empty day: dash in the column', 'Past days: chips dimmed', 'Booked: chip outlined'], notes: ['Rendered by SchedulePage with view=week at /app/schedule/week; on phones the six columns stack as day groups.'] }),
  'C-03': ext('C-03', { layout: ['HeroImage (placeholder)', 'TitleBlock (time, duration, room)', 'CapacityMeter', 'AboutSection', 'TeacherCard → TeacherProfile', 'PrepList → Club rules', 'StickyCTA (Reserve / Waitlist)'], data: ['class_sessions', 'modalities', 'teachers', 'rooms', 'bookings', 'waitlist'], states: ['Loading: hero shimmer', 'Cancelled class: banner + reschedule options', 'Full: CTA becomes Waitlist', 'Already booked: CTA opens the booking', 'Same-day conflict: CTA disabled with reason', 'Not found'] }),
  'C-04': ext('C-04', { layout: ['ClassSummary', 'EntitlementPicker', 'PaymentMethodRow', 'OrderSummary (subtotal, IVA, total)', 'ConfirmButton'], data: ['class_sessions', 'bookings', 'class_ledger', 'memberships', 'plans', 'payments', 'invoices'], integrations: ['WhatsApp', 'Wompi', 'Email', 'Supabase Realtime', 'DIAN e-invoicing'], notes: [WOMPI_NOTE, 'IVA 19% is computed by OrderSummary from policy.ivaRate; prices are IVA-inclusive.', 'Declined payments render E-02 inline and keep the spot held 10 minutes.', '0051: the entitlement picker offers a class from the 12-class package (class_ledger), the trial, the individual class or buying the package with this booking; no credits, no membership.'] }),
  'C-05': ext('C-05', { layout: ['WompiCard (placeholder)', 'SavedMethods (add / remove / default)', 'ElectronicMethods (card, PSE, Wompi QR)', 'ManualMethods (cash at the desk)', 'ComplianceNote'], data: ['payment_methods', 'payments', 'invoices'], states: ['Loading: rows shimmer', "Empty: 'Add a payment method'", 'Gateway down: cash at the desk only + banner', 'Expired card: inline warning', 'Saving: tokenising a new method', 'One default: every other row offers “make default”'], toggles: [{ label: 'PSE', on: true }, { label: 'Wompi QR', on: true }, { label: 'Cash at front desk', on: true }], notes: [WOMPI_NOTE, 'Saved methods are rows in payment_methods. `token_ref` is a demo placeholder produced by wompiTokenise(); the real Wompi token replaces it without changing the row shape. The PAN never reaches HoyOS.', '0051 (studio FAQ): payments are the website by card, PSE or the Wompi QR, and cash at reception. No Nequi, no Daviplata; the QR is paid each time and is not saved.'] }),
  'C-06': ext('C-06', { name: { es: 'Paquetes', en: 'Packages' }, layout: ['CurrentPackageNotice', 'PackageCards (12 classes · Santa María Tennis Club)', 'PriceNote', 'SkipLink (trial / individual class)', 'PrivateClasses (WhatsApp)', 'GiftCards → C-17', 'ConfirmDrawer'], data: ['plans', 'class_ledger', 'payments'], notes: ['Prices only from src/tenant/pricing.ts (0051 launch price list).', WOMPI_NOTE, '0051: the 12-class package lasts 3 months, can be frozen once for up to 30 days (C-07b) and is not refundable. Private classes (up to 3 people, + per extra person) are arranged on WhatsApp — nothing sold here.'] }),
  'C-07': ext('C-07', { name: { es: 'Prueba o clase individual', en: 'Trial or individual class' }, layout: ['Header · title + sub', 'PackageNotice (if classes left)', 'Eyebrow · BIENVENIDA', 'Intro line', 'PassList (trial · individual class)', 'FooterLink → C-06 · C-07b'], data: ['plans', 'payments', 'class_ledger', 'bookings'], notes: ['Each pass goes to C-04 with ?pass=<id>; the purchase and the booking happen in one confirm.', '0051: two passes — the trial class (once per person) and the individual class.'] }),
  'C-07b': ext('C-07b', { name: { es: 'Mis clases', en: 'My classes' }, layout: ['FrozenNotice (if frozen)', 'BalanceTiles (classes left · expiry)', 'FreezeRow → FreezeDrawer', 'LedgerList (purchase / booking / return / expiry)', 'PackGrid (12 classes · individual class)', 'BuyDrawer'], data: ['class_ledger', 'plans', 'payments', 'bookings'], logic: ['A package purchase adds its 12 classes with expires_at = today + 90 days.', 'Freeze once per package for up to policy.freezeMaxDays (M-08): frozen_from / frozen_until on the purchase row; the expiry moves by the frozen days and nothing can be booked while frozen.', 'Resume early: the unused frozen days come back off the expiry; the freeze still counts as used.'], notes: ['0051: was “Créditos y paquetes”. The studio sells classes, never credits; /app/credits and /app/membership redirect here.'] }),
  'C-08': ext('C-08', { layout: ['CountdownRing', 'ClassSummary', 'PrepReminder', 'ActionRow (Change / Invite)', 'AddToCalendar', 'PolicyNote'], data: ['bookings', 'class_sessions', 'modalities', 'teachers', 'rooms', 'class_ledger', 'waitlist'], logic: ['Free cancellation until T−12 h (policy.cancelWindowHours); inside the window, or a no-show, the class counts as taken.', 'Reschedule = cancel + rebook in one transaction, same entitlement, no fee outside the window.', 'Studio-side cancellation refunds automatically (E-03 state inline).', "Countdown switches to 'check in at reception' inside T−60m; check-in happens only at the front desk."], notes: ['Add to calendar downloads an .ics; share uses the Web Share API with clipboard fallback.'] }),
  'C-08b': ext('C-08b', { layout: ['Handle + title', 'PolicyLine (window from policy)', 'BookingSummary', 'MoveAction (primary)', 'CancelAction (destructive outline)', 'ReplacementList (same day, same class)', 'KeepBooking (dismiss)'], data: ['bookings', 'class_sessions', 'modalities', 'class_ledger', 'waitlist'], notes: ['Opens as a bottom Drawer over C-08 at /app/booking/:id/change.'] }),
  'C-10': ext('C-10', { layout: ['ClassLine', 'RatingScale (1–5)', 'TagChips (good / fix)', 'OptionalNote', 'AnonymousToggle', 'Submit / Skip'], data: ['reviews', 'bookings', 'class_sessions', 'teachers'], notes: ['Submit inserts a `reviews` row (rating, tags, comment, visibility), marks bookings.rated = true and recomputes teachers.rating_avg.', 'Anonymous is the default: visibility = anonymous hides who wrote it from the teacher app (S-03) while M-06 keeps the link.'] }),
  'C-11': ext('C-11', { layout: ['TabSwitch (Classes / Payments)', 'ClassHistoryList', 'PaymentList → ReceiptSheet', 'ExportButton'], data: ['bookings', 'class_sessions', 'modalities', 'teachers', 'payments', 'invoices', 'plans'], notes: ['Export downloads a JSON summary; PDF via DIAN e-invoicing later.'] }),
  'C-13': ext('C-13', { layout: ['VideoPlaceholder (studio tour)', 'CategoryList', 'ArticleView (Drawer)', 'RelatedLinks'], data: ['content_articles', 'legal_documents'], notes: ['Articles are rows in content_articles (sections rules / about), editable from M-02 without a deploy; body_md is {es,en} markdown.', 'Read receipts stay per viewer in localStorage — no table claims to own them.'] }),
  'C-14': ext('C-14', { layout: ['Header (page 1 of 2)', 'Section 01 · Tu primera vez en HOY', 'Section 02 · Reservas y horarios', 'Section 03 · Membresías y planes', 'NextPageLink → C-15'], data: ['faq_entries'], notes: ['/app/faq. Entries are faq_entries rows (group_key + page), editable from M-02; anything about prices links to /app/plans.'] }),
  'C-15': ext('C-15', { layout: ['Header (page 2 of 2) + back to C-14', 'Section 04 · El espacio', 'Section 05 · En camino', 'Section 06 · Contacto y concierge', 'ConciergeRow → WhatsApp'], data: ['faq_entries'], notes: ['/app/faq/2 (faq_entries where page = 2). Section 06 always ends with a route to a human.'] }),
  'C-16': ext('C-16', { layout: ['ContextCard (class or general)', 'ChannelRow (WhatsApp / Email / Link)', 'PassPreview', 'SentList (status)', 'RewardNote'], data: ['invites', 'class_ledger', 'class_sessions', 'profiles'], notes: ['Every send inserts an `invites` row with the member’s referral code and status sent → opened → joined → rewarded. WhatsApp/email still open outbound links.', 'The reward is a credits row (reason gift) linked from invites.reward_ledger_id; granting it is a staff/server action, never the client.'] }),
  'C-17': ext('C-17', { layout: ['HeroCard (design preview)', 'GiftPicker (individual class · 12-class package) + quantity', 'RecipientFields', 'DeliveryDate', 'MessageField (250 max)', 'DesignPicker ×4', 'OrderSummary', 'BuyCTA'], data: ['gift_cards', 'payments', 'invoices'], notes: ['0051: gift cards are an individual class or the 12-class package, bought online (quantity 1–10); the recipient redeems it at reception. Amounts come from pricing.ts (regalos family).', WOMPI_NOTE] }),
  'C-18': ext('C-18', { layout: ['Grid → TeacherCard', 'TeacherProfile (portrait, bio, classes they teach, upcoming schedule)'], data: ['teachers', 'modalities', 'class_sessions'], notes: ['/app/teachers/:id is the deep-linkable profile.'] }),
  'C-19': ext('C-19', { layout: ['Header (photo, name, membership badge)', 'EditProfile', 'MembershipRow → plan management', 'PaymentMethods', 'NotificationPrefs (push / email / WhatsApp)', 'LanguageToggle (EN / ES)', 'LeaveAReview → Google / Instagram', 'Legal links', 'SignOut / DeleteAccount'], data: ['profiles', 'users', 'memberships', 'plans', 'consents'], notes: ['Language uses the real LangToggle and persists users.locale.', 'Notification prefs write notification_prefs: each channel toggle is the master switch for that channel’s five categories; the per-category matrix lives on C-24.'] }),
  'C-20': ext('C-20', { layout: ['StatusCard (PositionRing + RuleExplainer)', 'ReleasedBanner (conditional, ClaimCountdown + ClaimButton)', 'AutoClaimToggle', 'LeaveWaitlistRow', 'PolicyNote'], data: ['waitlist', 'class_sessions', 'modalities', 'teachers', 'bookings', 'class_ledger'], notes: ['A cancellation on C-08b promotes the first waiting person to offered with a 30-minute claim_until.'] }),
  'C-21': ext('C-21', { layout: ['Step1 · Identify (WhatsApp / email)', 'Step2 · Verify (OtpInput ×6, ResendTimer)', 'Step3 · New password', 'BackToSignIn'], data: ['users', 'wa_templates'], notes: ['OTP is simulated: the demo code is shown on screen; 3 wrong codes force a resend.'] }),
  'C-22': ext('C-22', { layout: [], data: [], states: ['retired (0051): /app/membership redirects to C-07b'], toggles: [], actions: [], notes: ['RETIRED in 0051 (0.22.0): the launch price list has no membership. The memberships table stays dormant; the 12-class package freeze lives on C-07b.'] }),
  'C-23': ext('C-23', { layout: ['EventList (published, upcoming first)', 'HeroImage (placeholder)', 'WhenWhere', 'TitleBlock + hosts', 'Body', 'PriceRow (public / member)', 'CapacityMeter', 'StickyCTA · Reserve', 'BringAFriendRow → C-16', 'AddToCalendar'], data: ['events', 'event_rsvps', 'payments', 'invoices', 'teachers', 'memberships'], states: ['Loading: hero shimmer', 'Sold out: waitlist offer', 'Past: read-only with gallery', 'Cancelled: banner + refund note', 'No events published yet', 'Going: RSVP notice with cancel', 'Member price included'], notes: ['Events are `events` rows (status published) and RSVPs are `event_rsvps`; M-02 publishes them. Prices are stored per event in COP and seeded from pricing.ts.', WOMPI_NOTE + ' An event charge is an ordinary payments row with plan_id = null, linked from event_rsvps.payment_id.'] }),
  // 0019 — new code: account-level rights (Ley 1581 + App Store 5.1.1(v) + Google Play account deletion).
  'C-26': defineSpec({
    code: 'C-26',
    name: { es: 'Cuenta y datos', en: 'Account & data' },
    purpose: { es: 'Los derechos sobre la cuenta en un solo lugar: quién es el responsable del tratamiento, los consentimientos que la persona controla, una copia de sus propios datos, los documentos legales y la solicitud de eliminar la cuenta con lo que se conserva explicado en lenguaje llano.', en: 'Account-level rights in one place: who the data controller is, the consents the member controls, a copy of their own data, the legal documents and the request to delete the account, with what is kept explained in plain words.' },
    layout: ['DataController', 'ConsentToggles', 'ExportData', 'LegalLinks', 'DeleteAccount'],
    data: ['deletion_requests', 'profiles', 'users', 'notification_prefs', 'legal_acceptances', 'legal_documents', 'payments', 'invoices', 'bookings', 'audit_log', 'tenants'],
    roles: ['customer', 'teacher'],
    logic: [
      'Deleting is a request, not a client-side delete: the page inserts one deletion_requests row (status requested, channel app, optional reason) plus an audit_log row (account.deletion_request). Admin follows it in M-11; the anonymisation of profiles + users and the removal of the auth user run server-side (Supabase function) once the backend exists. Nothing on the client alters the profile.',
      'Two-step confirm: step one explains what is kept (invoices and payment history for the legal retention period, anonymised) and what ends (access, profile, notifications) and requires the "I understand" switch; step two is the destructive button. While a request is open the row is replaced by its status and a "cancel request" that flips status to cancelled (only from requested).',
      'Export builds one JSON with the member’s own rows from every table that points at their user id, plus the invoices of their payments, and logs account.export.',
      'Marketing consent is the notification_prefs marketing category per channel (WhatsApp, email); profiles.marketing_optin mirrors “any channel on”. Data-processing consent is read-only here: it shows the privacy version accepted (legal_acceptances kind privacy) and links to A-06 to accept the current one.',
      'The data controller line reads the display name from M-08 (tenants.settings) with tenant.legalName and the studio email — nothing about the studio is typed here.',
    ],
    integrations: ['Supabase Auth'],
    states: ['No request: delete row available', 'Step 1: explanation, switch off → next disabled', 'Step 2: destructive confirm', 'Request pending (requested) with cancel', 'Request processing (no cancel)', 'Privacy policy not accepted yet', 'Exporting'],
    notes: ['Reached from C-19 (Cuenta y datos) and C-25. The public counterpart with no sign-in is W-09 (/site/delete-account); the admin queue is M-11.', 'Apple App Store 5.1.1(v) and Google Play both require in-app account deletion to be discoverable; the page sits one tap under Profile and is named in the compliance checklist (docs/app-store-compliance.md).'],
  }),
  // 0040 — practice analytics, customer side. The numbers come from src/data/analytics.ts (practiceStats); this page only words them.
  'C-27': defineSpec({
    code: 'C-27',
    name: { es: 'Tu práctica', en: 'Your practice' },
    purpose: { es: 'La práctica de la persona en lenguaje llano: cuántas clases tomó esta semana y este mes, cuántas semanas seguidas lleva cumpliendo su meta, sus logros y lo que más practica, y la meta semanal que ella misma elige. Privado: nunca se compara con otras personas.', en: 'The member’s practice in plain words: how many classes they attended this week and this month, how many weeks in a row they have met their goal, their milestones and what they practise most, and the weekly goal they choose themselves. Private: never compared with anyone else.' },
    layout: ['WeekHeader', 'StreakCard', 'MonthSummary', 'History12Weeks', 'Milestones', 'Favourites', 'GoalSection'],
    data: ['bookings', 'class_sessions', 'practice_goals', 'activity_events', 'memberships', 'class_ledger', 'modalities', 'teachers'],
    roles: ['customer', 'teacher'],
    logic: [
      'A visit is a checked_in booking counted by the SESSION start date (local, America/Bogota), never by the booking created_at. "Clases tomadas este mes" = visits in the current calendar month; "reservadas próximas" = status booked with the session in the future.',
      'Weeks run Monday–Sunday. A week counts when visits ≥ the weekly goal; the current week never breaks the run and counts once met. At risk = current week not met on Saturday or Sunday.',
      'Rest week: one missed week per rolling 4 weeks is forgiven (saved) when the run is alive and there was a visit in the 4 weeks before; a saved week keeps the run but does not add. Weeks with the membership paused neither add nor break.',
      'Two missed weeks in a row, or a miss with no rest week left, resets the run; best = the longest run under the same rules. A broken run shows the best one, never a red zero.',
      'Goal 0 ("sin meta por ahora") hides the streak and the ring; counts, history and milestones stay. The goal is changed here or on C-01; each change ends the active practice_goals row and inserts a new one plus a goal.set activity event.',
      'Milestones 1 · 5 · 10 · 25 · 50 · 100 · 250 lifetime visits; C-01 writes the milestone / streak.saved events once (useMilestoneRecorder). Favourites = most-attended modality and teacher over the last 90 days.',
    ],
    integrations: [],
    states: ['No bookings ever: EmptyState with the book CTA', 'Goal set, streak alive', 'At risk (weekend, goal not met)', 'Building (no run yet, a visit this week)', 'Broken (shows the best run)', 'No goal (sin meta): no ring, no streak, counts stay', 'Rest week used / rest week available', 'Month with no-shows or late cancels (neutral tiles, shown only when > 0)'],
    notes: ['Reached from C-01 (practice block link), C-25 More and C-19 Profile (account group).', 'Same numbers as M-06 (member file) and M-12 (studio analytics): all read practiceStats().'],
  }),
  'C-24': ext('C-24', { layout: ['Header + MarkAllRead', 'TodayGroup → NotificationRow', 'EarlierGroup', 'EmptyState', 'PrefsSection (channel × category)'], data: ['notifications', 'notification_prefs'], states: ["Empty: 'nothing yet'", 'Unread: dot + heavier weight', 'Expired action: row dims, action removed', 'Offline: cached list', 'All read', 'Muted category in the prefs matrix'], notes: ['Real inbox: `notifications` rows (title/body are {es,en} JSON, deep_link routes in-app, read_at is the read receipt). Staff and automations insert; the member only updates read_at.', 'Preferences are notification_prefs rows (channel × category). No row means enabled, so only real choices are stored; C-19 toggles a whole channel.'] }),
  'C-25': ext('C-25', { layout: ['IdentityCard → C-19', 'PrimaryGroup', 'SecondaryGroup', 'SignOut'], data: ['profiles', 'memberships', 'plans', 'class_ledger'] }),
  'E-01': ext('E-01', { layout: ['Greeting', 'EmptyState (illustration, headline, CTA browse today, tour)', 'StatsPlaceholder (explanatory, not zeros)', 'AnnouncementCard'], data: ['bookings', 'memberships'], notes: ['Demo route /app/state/empty; C-01 shows this block when the person has no bookings at all.'] }),
  'E-02': ext('E-02', { layout: ['ErrorBanner (title, body, gateway reason)', 'HoldCard · countdown', 'AlternateMethods', 'ReleaseSpotLink'], data: ['payments', 'class_sessions'], notes: ['Demo route /app/state/declined; the real path is C-04 → Wompi declined (dev mode has a "simulate decline" switch).'] }),
  'E-03': ext('E-03', { layout: ['CancelBanner (reason)', 'RefundConfirmation · the class returns', 'AlternativesList → ClassRow', 'PrimaryCTA · book a replacement', 'ChannelNote'], data: ['class_sessions', 'bookings', 'class_ledger', 'modalities', 'teachers'], notes: ['Demo route /app/state/cancelled picks a cancelled session from the seed; C-08 renders the same block when the booked session is cancelled.'] }),
  'E-04': ext('E-04', { layout: ['LockNotice (title, reason, countdown)', 'PrimaryCTA · recover password → C-21', 'SecondaryCTA · WhatsApp the studio', 'SecurityNote'], data: ['users'], notes: ['Reached from A-02 after 5 failed attempts; the 15-minute countdown is local in the demo.'] }),
};

// 0025 — WebMCP actions (./actions.ts) and the widths the responsive AppShell pass was checked at (390 · 1280 · 3840,
// scratchpad captures of 2026-09-28; the full 360→3840 matrix is the screenshot pass's job).
const CHECKED_0025: Record<string, number[]> = { 'C-01': [390, 1280, 3840], 'C-02': [390, 1280, 3840], 'C-04': [390, 1280, 3840], 'C-06': [390, 1280, 3840], 'C-08': [390, 1280, 3840], 'A-02': [390, 1280, 3840], 'A-05': [390, 1280, 3840] };
// 0026 — phone calendar views and the responsive mat grid were checked at the six-width matrix (DOM audit + captures, 2026-09-28).
const CHECKED_0026: Record<string, number[]> = { 'C-02': [360, 390, 768, 1280, 1920, 3840], 'C-02b': [360, 390, 768, 1280, 1920, 3840], 'C-04': [360, 390, 768, 1280, 1920, 3840] };
for (const code of new Set([...Object.keys(CUSTOMER_ACTIONS), ...Object.keys(CHECKED_0025), ...Object.keys(CHECKED_0026)])) {
  const s = canvasSpecs[code];
  if (!s) continue;
  canvasSpecs[code] = { ...s, actions: [...(s.actions ?? []), ...(CUSTOMER_ACTIONS[code] ?? [])], checkedAt: CHECKED_0026[code] ?? CHECKED_0025[code] ?? s.checkedAt };
}
