/**
 * The customer module's view of the canvas specs: every code, with `layout` replaced by the real
 * section names the page renders (so the layout editor and inspector show what is on screen),
 * `data` narrowed to real table names from src/data/schema.ts, and notes on what is simulated.
 * Exported under the same name so tooling that greps `canvasSpecs['C-02']` keeps working.
 */
import { canvasSpecs as base } from '../../specs/canvasSpecs';
import { defineSpec } from '../../specs/define';
import type { PageSpec } from '../../specs/types';

const ext = (code: string, patch: Partial<PageSpec>): PageSpec => {
  const b: PageSpec = base[code] ?? { code, name: { es: code, en: code }, purpose: { es: '', en: '' }, layout: [], data: [], roles: ['customer'], logic: [], integrations: [] };
  if (!base[code] && import.meta.env.DEV) console.warn(`[customer/specs] canvas code ${code} missing from canvasSpecs; using a minimal spec`);
  return defineSpec({ ...b, ...patch, notes: [...(b.notes ?? []), ...(patch.notes ?? [])] });
};

const WOMPI_NOTE = 'Wompi is simulated in src/modules/customer/payments.ts (wompiCheckout). Manual transfer/cash create pending payments the front desk settles.';

export const canvasSpecs: Record<string, PageSpec> = {
  ...base,
  'A-01': ext('A-01', { layout: ['BreathingRings + Wordmark', 'Tagline', 'LoadState', 'ContinueButton'], data: ['users', 'feature_flags'], logic: ['Breath cycle is 7 s (--dur-breath).', 'Auto-continues to /auth/sign-in after 2.8 s; a button skips the wait.'], states: ['breathing', 'reduced motion'], notes: ['Session restore is the demo session in localStorage; Supabase Auth later.'] }),
  'A-02': ext('A-02', { layout: ['Logo block', 'DemoUserPicker', 'CredentialCard (email, password)', 'Divider / OR', 'ProviderStack (Apple, Google, Biometric — disabled)', 'CreateAccountLink'], data: ['users', 'user_roles', 'audit_log'], states: ['default', 'wrong credentials: attempts left', 'locked → E-04'], notes: ['Demo mode: any demo user email signs in; 5 failed attempts route to /auth/locked (E-04).', 'Apple / Google / biometric buttons are disabled until Supabase Auth.'] }),
  'A-03': ext('A-03', { layout: ['ProgressDots', 'Heading + sub', 'FormStack (name, email, WhatsApp +57, password, birthday, emergency contact, photo)', 'ConsentRow → /site/legal', 'PrimaryButton'], data: ['users', 'profiles', 'user_roles', 'consents', 'legal_documents'], states: ['default', 'validation errors', 'duplicate email → sign-in offer', 'created'], notes: ['Inserts users + profiles + user_roles + consents rows via useData(). The demo session then continues as the demo customer because SessionProvider only knows demo users (shared-change request).'] }),
  'A-05': ext('A-05', { layout: ['Question', 'MovementPicker ×4', 'Explanation', 'SkipLink'], data: ['intentions'], states: ['no intention yet', 'already answered today'] }),
  'C-02': ext('C-02', { layout: ['ViewSwitch (Today / Week)', 'DateStrip', 'FilterBar → FilterSheet', 'ClassList → ClassRow', 'WeekGrid', 'Legend'], data: ['class_sessions', 'modalities', 'teachers', 'rooms', 'bookings', 'waitlist'], states: ['Loading: three skeleton rows', "Empty: 'No classes match' + clear-filters", 'Error: retry', 'Past days: rows read-only', 'Week view (C-02b)'], notes: ['C-02b week view is the Week segment of this page (?view=week).', 'Capacity updates live through useTable subscriptions (MockProvider change events).'] }),
  'C-02b': ext('C-02b', { layout: ['ViewSwitch (Today / Week)', 'FilterBar → FilterSheet', 'WeekGrid (Mon–Sat columns → DayChip)', 'Legend'], data: ['class_sessions', 'modalities', 'teachers', 'rooms', 'bookings'], states: ['Loading: skeleton', 'Empty day: dash in the column', 'Past days: chips dimmed', 'Booked: chip outlined'], notes: ['Rendered by SchedulePage with view=week at /app/schedule/week; on phones the six columns stack as day groups.'] }),
  'C-03': ext('C-03', { layout: ['HeroImage (placeholder)', 'TitleBlock (time, duration, room)', 'CapacityMeter', 'AboutSection', 'TeacherCard → TeacherProfile', 'PrepList → Club rules', 'StickyCTA (Reserve / Waitlist)'], data: ['class_sessions', 'modalities', 'teachers', 'rooms', 'bookings', 'waitlist'], states: ['Loading: hero shimmer', 'Cancelled class: banner + reschedule options', 'Full: CTA becomes Waitlist', 'Already booked: CTA opens the booking', 'Same-day conflict: CTA disabled with reason', 'Not found'] }),
  'C-04': ext('C-04', { layout: ['ClassSummary', 'EntitlementPicker', 'PaymentMethodRow', 'OrderSummary (subtotal, IVA, total)', 'ConfirmButton'], data: ['class_sessions', 'bookings', 'credits', 'memberships', 'plans', 'payments', 'invoices'], integrations: ['WhatsApp', 'Wompi', 'Email', 'Supabase Realtime', 'DIAN e-invoicing'], notes: [WOMPI_NOTE, 'IVA 19% is computed by OrderSummary from policy.ivaRate; prices are IVA-inclusive.', 'Declined payments render E-02 inline and keep the spot held 10 minutes.'] }),
  'C-05': ext('C-05', { layout: ['WompiCard (placeholder)', 'SavedMethods', 'ElectronicMethods (card, PSE, Nequi)', 'ManualMethods (transfer instructions, cash at desk)', 'ComplianceNote'], data: ['payments', 'invoices'], notes: [WOMPI_NOTE, 'No payment_methods table yet: saved methods are derived from approved payments (shared-change request).'] }),
  'C-06': ext('C-06', { layout: ['CycleSwitch (Monthly / Yearly)', 'PlanCards', 'ComparisonNote', 'PrimaryCTA', 'SkipLink (Bienvenida passes)'], data: ['plans', 'memberships', 'payments'], notes: ['Prices only from src/tenant/pricing.ts (Modelo de Valor v3).', WOMPI_NOTE] }),
  'C-07': ext('C-07', { layout: ['Header · title + sub', 'Eyebrow · BIENVENIDA', 'Intro line', 'PassList (vertical)', 'FooterLink → C-06'], data: ['plans', 'payments', 'credits', 'bookings'], notes: ['Each pass goes to C-04 with ?pass=<id>; the purchase and the booking happen in one confirm.'] }),
  'C-07b': ext('C-07b', { name: { es: 'Créditos y paquetes', en: 'Credits & class packs' }, layout: ['BalanceHeader', 'LedgerList (earned / used / expired)', 'PackGrid (1 / 3 / 10)', 'BuyCTA'], data: ['credits', 'plans', 'payments', 'bookings'], notes: ['Pack purchase from here credits the ledger without a booking (payments + credits rows).', 'Canvas v1.5 merged C-07b into C-07; the /app/credits route keeps the ledger view under the compatibility alias.'] }),
  'C-08': ext('C-08', { layout: ['CountdownRing', 'ClassSummary', 'PrepReminder', 'ActionRow (Change / Invite)', 'AddToCalendar', 'PolicyNote'], data: ['bookings', 'class_sessions', 'modalities', 'teachers', 'rooms', 'credits', 'waitlist'], logic: [`Free cancellation until T−${2}h (policy.cancelWindowHours); inside the window the credit is forfeited.`, 'Reschedule = cancel + rebook in one transaction, same entitlement, no fee outside the window.', 'Studio-side cancellation refunds automatically (E-03 state inline).', "Countdown switches to 'Check in' inside T−60m."], notes: ['Add to calendar downloads an .ics; share uses the Web Share API with clipboard fallback.'] }),
  'C-08b': ext('C-08b', { layout: ['Handle + title', 'PolicyLine (window from policy)', 'BookingSummary', 'MoveAction (primary)', 'CancelAction (destructive outline)', 'ReplacementList (same day, same movement)', 'KeepBooking (dismiss)'], data: ['bookings', 'class_sessions', 'modalities', 'credits', 'waitlist'], notes: ['Opens as a bottom Drawer over C-08 at /app/booking/:id/change.'] }),
  'C-10': ext('C-10', { layout: ['ClassLine', 'RatingScale (1–5)', 'TagChips (good / fix)', 'OptionalNote', 'AnonymousToggle', 'Submit / Skip'], data: ['bookings', 'class_sessions', 'teachers'], notes: ['No reviews table yet: submit marks bookings.rated = true and keeps the rating locally (shared-change request).'] }),
  'C-11': ext('C-11', { layout: ['TabSwitch (Classes / Payments)', 'ClassHistoryList', 'PaymentList → ReceiptSheet', 'ExportButton'], data: ['bookings', 'class_sessions', 'modalities', 'teachers', 'payments', 'invoices', 'plans'], notes: ['Export downloads a JSON summary; PDF via DIAN e-invoicing later.'] }),
  'C-13': ext('C-13', { layout: ['VideoPlaceholder (studio tour)', 'CategoryList', 'ArticleView (Drawer)', 'RelatedLinks'], data: ['legal_documents'], notes: ['Articles live in src/modules/customer/content.ts until a content_articles table exists (shared-change request).'] }),
  'C-14': ext('C-14', { layout: ['Header (page 1 of 2)', 'Section 01 · Tu primera vez en HOY', 'Section 02 · Reservas y horarios', 'Section 03 · Membresías y planes', 'NextPageLink → C-15'], data: [], notes: ['/app/faq. Entries live in content.ts until a faq_entries table exists; anything about prices links to /app/plans.'] }),
  'C-15': ext('C-15', { layout: ['Header (page 2 of 2) + back to C-14', 'Section 04 · El espacio', 'Section 05 · En camino', 'Section 06 · Contacto y concierge', 'ConciergeRow → WhatsApp'], data: [], notes: ['/app/faq/2. Section 06 always ends with a route to a human.'] }),
  'C-16': ext('C-16', { layout: ['ContextCard (class or general)', 'ChannelRow (WhatsApp / Email / Link)', 'PassPreview', 'SentList (status)', 'RewardNote'], data: ['class_sessions', 'profiles'], notes: ['No invites table yet: sent invites are kept per user in localStorage (shared-change request). WhatsApp/email open outbound links.'] }),
  'C-17': ext('C-17', { layout: ['HeroCard (design preview)', 'AmountPicker (+ custom)', 'RecipientFields', 'DeliveryDate', 'MessageField (250 max)', 'DesignPicker ×4', 'OrderSummary', 'BuyCTA'], data: ['gift_cards', 'payments', 'invoices'], notes: ['Amounts come from pricing.ts (single / pack3 / pack10) plus a custom amount ≥ the single pass.', WOMPI_NOTE] }),
  'C-18': ext('C-18', { layout: ['Grid → TeacherCard', 'TeacherProfile (portrait, bio, classes they teach, upcoming schedule)'], data: ['teachers', 'modalities', 'class_sessions'], notes: ['/app/teachers/:id is the deep-linkable profile.'] }),
  'C-19': ext('C-19', { layout: ['Header (photo, name, membership badge)', 'EditProfile', 'MembershipRow → plan management', 'PaymentMethods', 'NotificationPrefs (push / email / WhatsApp)', 'LanguageToggle (EN / ES)', 'LeaveAReview → Google / Instagram', 'Legal links', 'SignOut / DeleteAccount'], data: ['profiles', 'users', 'memberships', 'plans', 'consents'], notes: ['Language uses the real LangToggle and persists users.locale.', 'Notification prefs are per user in localStorage until a notification_prefs table exists.'] }),
  'C-20': ext('C-20', { layout: ['StatusCard (PositionRing + RuleExplainer)', 'ReleasedBanner (conditional, ClaimCountdown + ClaimButton)', 'AutoClaimToggle', 'LeaveWaitlistRow', 'PolicyNote'], data: ['waitlist', 'class_sessions', 'modalities', 'teachers', 'bookings', 'credits'], notes: ['A cancellation on C-08b promotes the first waiting person to offered with a 30-minute claim_until.'] }),
  'C-21': ext('C-21', { layout: ['Step1 · Identify (WhatsApp / email)', 'Step2 · Verify (OtpInput ×6, ResendTimer)', 'Step3 · New password', 'BackToSignIn'], data: ['users', 'wa_templates'], notes: ['OTP is simulated: the demo code is shown on screen; 3 wrong codes force a resend.'] }),
  'C-22': ext('C-22', { layout: ['CurrentPlanCard', 'PauseRow → date picker (≤ 30 days)', 'ChangePlanRow → C-06', 'BillingHistoryRow → C-11', 'CancelRow (destructive) → reason sheet'], data: ['memberships', 'plans', 'payments', 'bookings'], logic: ['Pause up to 30 days (policy.pauseMaxDays); renewal shifts by the paused days.', 'Members are notified 3 days before a charge (policy.chargeNoticeDays).', 'Cancellation keeps access until the paid period ends; undo until then.'] }),
  'C-23': ext('C-23', { layout: ['HeroImage (placeholder)', 'WhenWhere', 'TitleBlock + hosts', 'Body', 'PriceRow (public / member)', 'CapacityMeter', 'StickyCTA · Reserve', 'BringAFriendRow → C-16', 'AddToCalendar'], data: ['teachers', 'memberships'], notes: ['No events table yet: two demo events live in content.ts and RSVPs are kept locally (shared-change request). Public price reads pricing single; members included.'] }),
  'C-24': ext('C-24', { layout: ['Header + MarkAllRead', 'TodayGroup → NotificationRow', 'EarlierGroup', 'EmptyState', 'SettingsLink → C-19'], data: ['message_log', 'waitlist', 'bookings', 'class_sessions'], notes: ['Derived inbox: message_log rows + waitlist offers + upcoming bookings. Read state per user in localStorage until a notifications table exists.'] }),
  'C-25': ext('C-25', { layout: ['IdentityCard → C-19', 'PrimaryGroup', 'SecondaryGroup', 'SignOut'], data: ['profiles', 'memberships', 'plans', 'credits'] }),
  'E-01': ext('E-01', { layout: ['Greeting', 'EmptyState (illustration, headline, CTA browse today, tour)', 'StatsPlaceholder (explanatory, not zeros)', 'AnnouncementCard'], data: ['bookings', 'memberships'], notes: ['Demo route /app/state/empty; C-01 shows this block when the person has no bookings at all.'] }),
  'E-02': ext('E-02', { layout: ['ErrorBanner (title, body, gateway reason)', 'HoldCard · countdown', 'AlternateMethods', 'ReleaseSpotLink'], data: ['payments', 'class_sessions'], notes: ['Demo route /app/state/declined; the real path is C-04 → Wompi declined (dev mode has a "simulate decline" switch).'] }),
  'E-03': ext('E-03', { layout: ['CancelBanner (reason)', 'RefundConfirmation · 1 credit', 'AlternativesList → ClassRow', 'PrimaryCTA · book a replacement', 'ChannelNote'], data: ['class_sessions', 'bookings', 'credits', 'modalities', 'teachers'], notes: ['Demo route /app/state/cancelled picks a cancelled session from the seed; C-08 renders the same block when the booked session is cancelled.'] }),
  'E-04': ext('E-04', { layout: ['LockNotice (title, reason, countdown)', 'PrimaryCTA · recover password → C-21', 'SecondaryCTA · WhatsApp the studio', 'SecurityNote'], data: ['users'], notes: ['Reached from A-02 after 5 failed attempts; the 15-minute countdown is local in the demo.'] }),
};
