import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'customer.home.greeting': { es: 'Hola, {name}', en: 'Hi, {name}' },
  'customer.home.intention.q': { es: '¿Cómo quieres sentirte hoy?', en: 'How do you want to feel today?' },
  'customer.home.intention.hint': { es: 'Tu horario de hoy se ordena según tu intención.', en: 'Today’s schedule sorts by your intention.' },
  'customer.home.intention.done': { es: 'Hoy: {mv}', en: 'Today: {mv}' },
  'customer.home.intention.change': { es: 'Cambiar', en: 'Change' },
  'customer.home.next': { es: 'Tu próxima clase', en: 'Your next class' },
  'customer.home.next.empty': { es: 'No tienes clases reservadas.', en: 'You have no booked classes.' },
  'customer.home.next.cta': { es: 'Reserva tu primera clase', en: 'Book your first class' },
  'customer.home.today': { es: 'Hoy en el club', en: 'Today at the club' },
  'customer.home.today.empty': { es: 'Hoy descansamos.', en: 'We rest today.' },
  'customer.home.stats.classes': { es: 'Clases este mes', en: 'Classes this month' },
  'customer.home.stats.streak': { es: 'Racha', en: 'Streak' },
  'customer.home.stats.credits': { es: 'Créditos', en: 'Credits' },
  'customer.home.stats.weeks': { es: '{n} sem', en: '{n} wks' },
  'customer.home.membership.nudge': { es: 'Aún no tienes plan. Empieza con una clase de prueba.', en: 'No plan yet. Start with a trial class.' },
  'customer.home.membership.cta': { es: 'Ver planes', en: 'See plans' },
  'customer.home.membership.active': { es: 'Membresía activa · renueva {date}', en: 'Active membership · renews {date}' },
  'customer.home.quick.book': { es: 'Reservar', en: 'Book' },
  'customer.home.quick.schedule': { es: 'Horario', en: 'Schedule' },
  'customer.home.quick.plans': { es: 'Planes', en: 'Plans' },
  'customer.home.quick.invite': { es: 'Invitar', en: 'Invite' },
  'customer.home.announcement': { es: 'Aviso del estudio', en: 'Studio announcement' },
  'customer.home.announcement.body': { es: 'Este sábado la clase de las 10:00 será al aire libre. Trae tu mat.', en: 'This Saturday the 10:00 class is outdoors. Bring your mat.' },
  'customer.home.view': { es: 'Ver', en: 'View' },
  'customer.home.booked': { es: 'Reservada', en: 'Booked' },
  'customer.book.ok': { es: 'Reserva confirmada', en: 'Booking confirmed' },
  'customer.book.oneADay': { es: 'Solo una clase por persona al día.', en: 'Only one class per person per day.' },
};
