import type { StringTable } from '../../i18n/types';

/** Every user-facing string of the customer app (C-xx, A-xx, E-xx). Spanish first; English always present. */
export const strings: StringTable = {
  // C-01 home
  'customer.home.greeting': { es: 'Hola, {name}', en: 'Hi, {name}' },
  'customer.home.intention.q': { es: '¿Cómo quieres sentirte hoy?', en: 'How do you want to feel today?' },
  'customer.home.intention.hint': { es: 'Tu horario de hoy se ordena según tu intención.', en: 'Today’s schedule sorts by your intention.' },
  'customer.home.intention.done': { es: 'Hoy: {mv}', en: 'Today: {mv}' },
  'customer.home.intention.change': { es: 'Cambiar', en: 'Change' },
  'customer.home.next': { es: 'Tu próxima clase', en: 'Your next class' },
  'customer.home.next.empty': { es: 'No tienes clases reservadas.', en: 'You have no booked classes.' },
  'customer.home.next.cta': { es: 'Reserva tu primera clase', en: 'Book your first class' },
  'customer.home.today': { es: 'Hoy en el club', en: 'Today at the club' },
  'customer.home.today.empty': { es: 'Hoy descansamos.', en: 'We rest today.' },
  'customer.home.stats.classes': { es: 'Clases este mes', en: 'Classes this month' },
  'customer.home.stats.streak': { es: 'Racha', en: 'Streak' },
  'customer.home.stats.credits': { es: 'Créditos', en: 'Credits' },
  'customer.home.stats.weeks': { es: '{n} sem', en: '{n} wks' },
  'customer.home.membership.nudge': { es: 'Aún no tienes plan. Empieza con una clase de prueba.', en: 'No plan yet. Start with a trial class.' },
  'customer.home.membership.cta': { es: 'Ver planes', en: 'See plans' },
  'customer.home.membership.active': { es: 'Membresía activa · renueva {date}', en: 'Active membership · renews {date}' },
  'customer.home.quick.book': { es: 'Reservar', en: 'Book' },
  'customer.home.quick.schedule': { es: 'Horario', en: 'Schedule' },
  'customer.home.quick.plans': { es: 'Planes', en: 'Plans' },
  'customer.home.quick.invite': { es: 'Invitar', en: 'Invite' },
  'customer.home.announcement': { es: 'Aviso del estudio', en: 'Studio announcement' },
  'customer.home.announcement.body': { es: 'Este sábado la clase de las 10:00 será al aire libre. Trae tu mat.', en: 'This Saturday the 10:00 class is outdoors. Bring your mat.' },
  'customer.home.view': { es: 'Ver', en: 'View' },
  'customer.home.booked': { es: 'Reservada', en: 'Booked' },
  'customer.book.ok': { es: 'Reserva confirmada', en: 'Booking confirmed' },
  'customer.book.oneADay': { es: 'Solo una clase por persona al día.', en: 'Only one class per person per day.' },
  'customer.state.demo': { es: 'Ruta de demostración del estado {code}. En el flujo real este bloque aparece dentro de la página correspondiente.', en: 'Demo route for state {code}. In the real flow this block renders inside the relevant page.' },

  // C-02 schedule
  'customer.schedule.title': { es: 'Horario', en: 'Schedule' },
  'customer.schedule.sub': { es: 'Solo en el estudio. Una clase por persona al día.', en: 'In-studio only. One class per person per day.' },
  'customer.schedule.view': { es: 'Vista', en: 'View' },
  'customer.schedule.view.today': { es: 'Día', en: 'Day' },
  'customer.schedule.view.week': { es: 'Semana', en: 'Week' },
  'customer.schedule.filters': { es: 'Filtros', en: 'Filters' },
  'customer.schedule.filter.time': { es: 'Momento del día', en: 'Time of day' },
  'customer.schedule.filter.time.all': { es: 'Todo el día', en: 'All day' },
  'customer.schedule.filter.time.morning': { es: 'Mañana', en: 'Morning' },
  'customer.schedule.filter.time.evening': { es: 'Tarde', en: 'Evening' },
  'customer.schedule.filter.modality': { es: 'Modalidad', en: 'Modality' },
  'customer.schedule.filter.teacher': { es: 'Profesor/a', en: 'Teacher' },
  'customer.schedule.filter.intention': { es: 'Intención (movimiento)', en: 'Intention (movement)' },
  'customer.schedule.filter.intention.hint': { es: 'Los cuatro movimientos del club.', en: 'The club’s four movements.' },
  'customer.schedule.clearFilters': { es: 'Quitar filtros', en: 'Clear filters' },
  'customer.schedule.apply': { es: 'Aplicar', en: 'Apply' },
  'customer.schedule.empty': { es: 'Ninguna clase coincide', en: 'No classes match' },
  'customer.schedule.empty.body': { es: 'Prueba otro día o mira la semana completa.', en: 'Try another day or look at the whole week.' },
  'customer.schedule.empty.filters': { es: 'Con estos filtros no hay clases este día.', en: 'No classes match these filters on this day.' },
  'customer.schedule.closed': { es: 'Domingo cerrado', en: 'Closed on Sunday' },
  'customer.schedule.closedShort': { es: 'Cerrado', en: 'Closed' },
  'customer.schedule.pastDay': { es: 'Clases pasadas: solo lectura.', en: 'Past classes: read-only.' },
  'customer.schedule.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'customer.schedule.done': { es: 'Terminada', en: 'Done' },
  'customer.schedule.legend': { es: 'Movimientos', en: 'Movements' },
  'customer.schedule.intentionLink': { es: 'Elegir mi intención de hoy', en: 'Pick today’s intention' },

  // C-03 class detail
  'customer.class.notFound': { es: 'Clase no encontrada', en: 'Class not found' },
  'customer.class.notFound.body': { es: 'Puede que la clase haya cambiado de fecha o ya no exista.', en: 'The class may have moved or no longer exist.' },
  'customer.class.backToSchedule': { es: 'Volver al horario', en: 'Back to schedule' },
  'customer.class.heroPlaceholder': { es: 'Foto de la clase · 16:9 (pendiente)', en: 'Class photo · 16:9 (pending)' },
  'customer.class.allLevels': { es: 'Todos los niveles', en: 'All levels' },
  'customer.class.capacityNote': { es: '{mats} mats en sala', en: '{mats} mats in the room' },
  'customer.class.about': { es: 'Sobre la clase', en: 'About the class' },
  'customer.class.intensity': { es: 'Intensidad', en: 'Intensity' },
  'customer.class.heated': { es: 'Sala caliente', en: 'Heated room' },
  'customer.class.teacher': { es: 'Profesor/a', en: 'Teacher' },
  'customer.class.prep': { es: 'Prepárate', en: 'Prepare' },
  'customer.class.prep.arrive': { es: 'Llega 10 minutos antes; la sala cierra al empezar.', en: 'Arrive 10 minutes early; the room closes at start time.' },
  'customer.class.prep.hot': { es: 'Sala caliente: toalla grande y ropa ligera.', en: 'Hot room: large towel and light clothing.' },
  'customer.class.prep.mat': { es: 'Hay mats y bloques; trae el tuyo si prefieres.', en: 'Mats and blocks are available; bring yours if you prefer.' },
  'customer.class.prep.water': { es: 'Agua: mínimo 500 ml.', en: 'Water: at least 500 ml.' },
  'customer.class.rulesLink': { es: 'Reglas del club', en: 'Club rules' },
  'customer.class.past': { es: 'Clase terminada', en: 'Class finished' },
  'customer.class.viewBooking': { es: 'Ver mi reserva', en: 'View my booking' },
  'customer.class.joinWaitlist': { es: 'Unirme a la lista de espera', en: 'Join the waitlist' },
  'customer.class.viewWaitlist': { es: 'Ver mi lista de espera', en: 'View my waitlist' },
  'customer.class.seeOther': { es: 'Ver la otra clase', en: 'See the other class' },
  'customer.class.bookAndPay': { es: 'Reservar y pagar', en: 'Book and pay' },
  'customer.class.bookTrial': { es: 'Reservar mi clase de prueba', en: 'Book my trial class' },
  'customer.class.share': { es: 'Compartir', en: 'Share' },
  'customer.class.shared': { es: 'Compartido', en: 'Shared' },
  'customer.class.linkCopied': { es: 'Enlace copiado', en: 'Link copied' },
  'customer.class.fullNote': { es: 'Clase llena. Si se libera un cupo, tendrás {min} minutos para reclamarlo.', en: 'Class full. If a spot opens you will have {min} minutes to claim it.' },

  // C-04 checkout
  'customer.checkout.title': { es: 'Reservar', en: 'Reserve' },
  'customer.checkout.claiming': { es: 'Reclamando tu cupo de la lista de espera', en: 'Claiming your waitlist spot' },
  'customer.checkout.payWith': { es: 'Pagar con', en: 'Pay with' },
  'customer.checkout.credit': { es: 'Usar un crédito', en: 'Use a credit' },
  'customer.checkout.credit.sub': { es: '{n} créditos disponibles', en: '{n} credits available' },
  'customer.checkout.membership': { es: 'Membresía', en: 'Membership' },
  'customer.checkout.membership.none': { es: 'Sin membresía activa', en: 'No active membership' },
  'customer.checkout.trialNote': { es: 'La clase de prueba es una por persona, verificada por teléfono o documento.', en: 'The trial class is one per person, verified by phone or document.' },
  'customer.checkout.packNote': { es: 'Usarás 1 crédito hoy y te quedarán {n} para usar en {days} días.', en: 'You use 1 credit today and keep {n} to use within {days} days.' },
  'customer.checkout.method': { es: 'Método de pago', en: 'Payment method' },
  'customer.checkout.manageMethods': { es: 'Gestionar', en: 'Manage' },
  'customer.checkout.simulateDecline': { es: 'Simular rechazo (dev)', en: 'Simulate decline (dev)' },
  'customer.checkout.noCharge': { es: 'Sin cargo', en: 'No charge' },
  'customer.checkout.noCharge.credit': { es: 'Se descuenta 1 crédito al confirmar; vuelve si cancelas fuera de la ventana.', en: '1 credit is deducted on confirm; it returns if you cancel outside the window.' },
  'customer.checkout.noCharge.membership': { es: 'Incluida en tu membresía.', en: 'Included in your membership.' },
  'customer.checkout.subtotal': { es: 'Subtotal', en: 'Subtotal' },
  'customer.checkout.iva': { es: 'IVA', en: 'IVA' },
  'customer.checkout.total': { es: 'Total', en: 'Total' },
  'customer.checkout.receiptNote': { es: 'Precios con IVA incluido. Recibo electrónico (DIAN) por email y WhatsApp al aprobar.', en: 'Prices include IVA. Electronic receipt (DIAN) by email and WhatsApp on approval.' },
  'customer.checkout.confirm': { es: 'Confirmar reserva', en: 'Confirm booking' },
  'customer.checkout.payWompi': { es: 'Pagar {amount} con Wompi', en: 'Pay {amount} with Wompi' },
  'customer.checkout.confirmManual': { es: 'Reservar y pagar {amount} en recepción', en: 'Book and pay {amount} at the desk' },
  'customer.checkout.policy': { es: 'Cancelación gratis hasta {h} h antes.', en: 'Free cancellation up to {h} h before.' },
  'customer.checkout.race.title': { es: 'La clase se llenó mientras reservabas', en: 'The class filled while you were booking' },
  'customer.checkout.race.body': { es: 'No se cobró nada. Puedes unirte a la lista de espera.', en: 'Nothing was charged. You can join the waitlist.' },
  'customer.checkout.unavailable': { es: 'Esta clase ya no está disponible.', en: 'This class is no longer available.' },
  'customer.checkout.pending.title': { es: 'Pendiente de pago en recepción', en: 'Pending payment at the desk' },
  'customer.checkout.pending.body': { es: 'Tu cupo queda retenido 60 minutos. Paga en recepción para confirmarlo.', en: 'Your spot is held for 60 minutes. Pay at the front desk to confirm it.' },
  'customer.checkout.success.body': { es: 'Te enviamos la confirmación por WhatsApp y email. Llega 10 minutos antes; la clase dura {min} min.', en: 'We sent the confirmation by WhatsApp and email. Arrive 10 minutes early; the class lasts {min} min.' },

  // E-02 declined
  'customer.declined.title': { es: 'El pago no pasó', en: 'The payment did not go through' },
  'customer.declined.body': { es: 'No se cobró nada ({amount}). Tu cupo sigue reservado unos minutos.', en: 'Nothing was charged ({amount}). Your spot is still held for a few minutes.' },
  'customer.declined.gateway': { es: 'Motivo del banco', en: 'Bank reason' },
  'customer.declined.hold': { es: 'retenido', en: 'held' },
  'customer.declined.hold.title': { es: 'Cupo retenido', en: 'Spot held' },
  'customer.declined.hold.body': { es: 'Guardamos tu lugar {min} minutos desde el primer intento.', en: 'We keep your place for {min} minutes from the first attempt.' },
  'customer.declined.retry': { es: 'Intentar con otro método', en: 'Try another method' },
  'customer.declined.threeStrikes': { es: 'Tres intentos rechazados: te sugerimos PSE o efectivo en recepción.', en: 'Three declines: we suggest PSE or cash at the desk.' },
  'customer.declined.release': { es: 'Liberar el cupo', en: 'Release the spot' },

  // E-03 cancelled by studio
  'customer.cancelled.title': { es: 'El estudio canceló esta clase', en: 'The studio cancelled this class' },
  'customer.cancelled.body': { es: 'Lo sentimos.', en: 'We are sorry.' },
  'customer.cancelled.reason': { es: 'Motivo: {reason}.', en: 'Reason: {reason}.' },
  'customer.cancelled.refund.credit': { es: '1 crédito volvió a tu saldo', en: '1 credit returned to your balance' },
  'customer.cancelled.refund.none': { es: 'No se descontó nada', en: 'Nothing was deducted' },
  'customer.cancelled.refund.body': { es: 'Ya está hecho; no tienes que hacer nada. No cuenta contra tu límite de cancelaciones.', en: 'Already done; nothing to do on your side. It does not count against your cancellation allowance.' },
  'customer.cancelled.alternatives': { es: 'Alternativas para el mismo día', en: 'Same-day alternatives' },
  'customer.cancelled.noAlt': { es: 'Hoy no queda otra clase con cupo', en: 'No other class with spots today' },
  'customer.cancelled.noAlt.body': { es: 'Mira el resto de la semana o únete a la lista de espera de la próxima.', en: 'Look at the rest of the week or join the next one’s waitlist.' },
  'customer.cancelled.cta': { es: 'Reservar una alternativa', en: 'Book a replacement' },
  'customer.cancelled.channels': { es: 'Te avisamos también por WhatsApp y email.', en: 'We also told you by WhatsApp and email.' },

  // E-01 empty home
  'customer.empty.title': { es: 'Tu primera clase te espera', en: 'Your first class is waiting' },
  'customer.empty.body': { es: 'Aún no tienes reservas ni historial en {name}. Mira qué hay hoy en el club y elige.', en: 'No bookings or history at {name} yet. See what is on today and pick one.' },
  'customer.empty.cta': { es: 'Ver clases de hoy', en: 'See today’s classes' },
  'customer.empty.tour': { es: 'Tour del estudio', en: 'Studio tour' },
  'customer.empty.stats': { es: 'Tus estadísticas', en: 'Your stats' },
  'customer.empty.stats.body': { es: 'Aquí verás tus clases del mes, tu racha y tus créditos después de tu primera práctica.', en: 'Your classes this month, your streak and your credits appear here after your first practice.' },
  'customer.empty.trial': { es: 'Clase de prueba', en: 'Trial class' },

  // C-05 payment methods
  'customer.pay.title': { es: 'Métodos de pago', en: 'Payment methods' },
  'customer.pay.wompi.title': { es: 'Pago con Wompi', en: 'Pay with Wompi' },
  'customer.pay.wompi.badge': { es: 'Integración pendiente', en: 'Integration pending' },
  'customer.pay.wompi.body': { es: 'Tarjetas, PSE y Nequi pasarán por Wompi. Ningún dato de tarjeta toca nuestros servidores.', en: 'Cards, PSE and Nequi will run through Wompi. No card data touches our servers.' },
  'customer.pay.wompi.cta': { es: 'Probar pago de {amount}', en: 'Test a {amount} payment' },
  'customer.pay.wompi.ok': { es: 'Aprobado (simulado) · ref. {ref}', en: 'Approved (simulated) · ref. {ref}' },
  'customer.pay.wompi.seam': { es: 'Demo: la aprobación es simulada en src/modules/customer/payments.ts.', en: 'Demo: approval is simulated in src/modules/customer/payments.ts.' },
  'customer.pay.saved': { es: 'Guardados', en: 'Saved' },
  'customer.pay.saved.empty': { es: 'Añade un método de pago', en: 'Add a payment method' },
  'customer.pay.saved.empty.body': { es: 'Se guarda tokenizado la primera vez que pagas.', en: 'It is saved tokenised the first time you pay.' },
  'customer.pay.saved.tokenised': { es: 'Tokenizado', en: 'Tokenised' },
  'customer.pay.electronic': { es: 'Electrónicos', en: 'Electronic' },
  'customer.pay.manual': { es: 'Manual', en: 'Manual' },
  'customer.pay.manual.desk': { es: 'Recepción', en: 'Front desk' },
  'customer.pay.transfer.title': { es: 'Cómo pagar por transferencia', en: 'How to pay by transfer' },
  'customer.pay.transfer.step1': { es: 'Transfiere el total a la cuenta {bank} del estudio.', en: 'Transfer the total to the studio’s {bank} account.' },
  'customer.pay.transfer.step2': { es: 'Envía el comprobante por WhatsApp a {whatsapp}.', en: 'Send the receipt by WhatsApp to {whatsapp}.' },
  'customer.pay.transfer.step3': { es: 'Recepción confirma y tu reserva pasa a pagada.', en: 'The front desk confirms and your booking becomes paid.' },
  'customer.pay.transfer.account': { es: 'Número de cuenta y NIT: se configuran en Admin → Ajustes del estudio (M-08).', en: 'Account number and NIT: configured in Admin → Studio settings (M-08).' },
  'customer.pay.comply.title': { es: 'Tus datos', en: 'Your data' },
  'customer.pay.comply.body': { es: 'Tokenización en la pasarela (PCI DSS SAQ-A), consentimiento Habeas Data (Ley 1581) antes de guardar un método, factura electrónica DIAN con NIT e IVA.', en: 'Gateway tokenisation (PCI DSS SAQ-A), Habeas Data consent (Ley 1581) before storing a method, DIAN electronic invoice with NIT and IVA.' },
  'customer.pay.method.card': { es: 'Tarjeta', en: 'Card' },
  'customer.pay.method.pse': { es: 'PSE', en: 'PSE' },
  'customer.pay.method.nequi': { es: 'Nequi', en: 'Nequi' },
  'customer.pay.method.cash': { es: 'Efectivo', en: 'Cash' },
  'customer.pay.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'customer.pay.method.gift_card': { es: 'Tarjeta de regalo', en: 'Gift card' },

  // C-06 plans
  'customer.plans.title': { es: 'Membresía', en: 'Membership' },
  'customer.plans.sub': { es: 'Acceso completo al club. Sin permanencia.', en: 'Full access to the club. No lock-in.' },
  'customer.plans.cycle': { es: 'Ciclo', en: 'Cycle' },
  'customer.plans.current': { es: 'Tu plan: {plan}', en: 'Your plan: {plan}' },
  'customer.plans.manage': { es: 'Gestionar membresía', en: 'Manage membership' },
  'customer.plans.yours': { es: 'Tu plan', en: 'Your plan' },
  'customer.plans.starts': { es: 'Inicio del plan', en: 'Plan start' },
  'customer.plans.ends': { es: 'Fin del plan', en: 'Plan end' },
  'customer.plans.change': { es: 'Cambiar a este plan', en: 'Switch to this plan' },
  'customer.plans.cta': { es: 'Empezar', en: 'Start' },
  'customer.plans.monthsFree': { es: 'Equivale a {n} meses gratis ({monthly} al mes).', en: 'Works out to {n} months free ({monthly} a month).' },
  'customer.plans.benefit.unlimited': { es: 'Todas las clases · {n} por día', en: 'Every class · {n} per day' },
  'customer.plans.benefit.pause': { es: 'Pausa hasta {days} días al año', en: 'Pause up to {days} days a year' },
  'customer.plans.benefit.guest': { es: 'Pase de invitado incluido', en: 'Guest pass included' },
  'customer.plans.benefit.events': { es: 'Precio de socio en eventos', en: 'Member price on events' },
  'customer.plans.note': { es: 'Sala de {mats} mats; reserva con tiempo. Cambios en Perfil → Membresía.', en: '{mats}-mat room; book ahead. Changes under Profile → Membership.' },
  'customer.plans.skip': { es: '¿Prefieres pagar por clase?', en: 'Prefer to pay per class?' },
  'customer.plans.skip.cta': { es: 'Pases Bienvenida', en: 'Welcome passes' },
  'customer.plans.specials': { es: '¿Un cumpleaños, un evento privado o una sesión para tu equipo? Eso lo armamos directamente contigo.', en: 'A birthday, a private event or a session for your team? That we shape directly with you.' },
  'customer.plans.specials.cta': { es: 'Escríbenos', en: 'Write to us' },
  'customer.plans.specials.wa': { es: 'Hola HOY, quiero preguntar por un especial: un evento privado o una sesión de grupo.', en: 'Hi HOY, I would like to ask about a special: a private event or a group session.' },
  'customer.plans.confirm.title': { es: 'Confirmar membresía', en: 'Confirm membership' },
  'customer.plans.confirm.note': { es: 'Te avisamos {days} días antes de cada cobro. Cancela cuando quieras.', en: 'We notify you {days} days before each charge. Cancel any time.' },
  'customer.plans.done.title': { es: 'Bienvenido al club', en: 'Welcome to the club' },
  'customer.plans.done.body': { es: 'Tu membresía está activa. Recibo enviado por email y WhatsApp.', en: 'Your membership is active. Receipt sent by email and WhatsApp.' },

  // C-07 passes
  'customer.passes.title': { es: 'Pases Bienvenida', en: 'Welcome passes' },
  'customer.passes.sub': { es: 'Para entrar sin membresía. Lo más barato primero.', en: 'The way in without a membership. Cheapest first.' },
  'customer.passes.eyebrow': { es: 'Bienvenida', en: 'Welcome' },
  'customer.passes.intro': { es: 'Cuatro opciones de una sola vez. Cada botón lleva al mismo checkout.', en: 'Four one-time options. Every button enters the same checkout.' },
  'customer.passes.credits': { es: '{n} clases', en: '{n} classes' },
  'customer.passes.validity': { es: 'válido {days} días', en: 'valid {days} days' },
  'customer.passes.cta': { es: 'Elegir clase con este pase', en: 'Pick a class with this pass' },
  'customer.passes.bookWith': { es: 'Reservar con este pase', en: 'Book with this pass' },
  'customer.passes.trialUsed': { es: 'Ya usaste tu clase de prueba. Sigue con un pase individual o un paquete.', en: 'You already used your trial class. Continue with a single pass or a pack.' },
  'customer.passes.member': { es: 'Ya tienes membresía', en: 'You already have a membership' },
  'customer.passes.member.body': { es: 'Tus clases están incluidas; no necesitas un pase.', en: 'Your classes are included; you do not need a pass.' },
  'customer.passes.footer': { es: '¿Vienes seguido?', en: 'Coming often?' },
  'customer.passes.footer.link': { es: 'Mira la membresía', en: 'See the membership' },

  // C-07b credits
  'customer.credits.title': { es: 'Créditos', en: 'Credits' },
  'customer.credits.sub': { es: 'Tu saldo y cada movimiento.', en: 'Your balance and every movement.' },
  'customer.credits.balance': { es: 'Saldo', en: 'Balance' },
  'customer.credits.membershipHint': { es: 'Incluidas con tu membresía', en: 'Included with your membership' },
  'customer.credits.expires': { es: 'Próximo vencimiento', en: 'Next expiry' },
  'customer.credits.expiringSoon': { es: 'Vence pronto', en: 'Expiring soon' },
  'customer.credits.expiringSoon.body': { es: 'Tienes créditos que vencen el {date}. Reserva antes.', en: 'You have credits expiring on {date}. Book before then.' },
  'customer.credits.topUp': { es: 'Recargar', en: 'Top up' },
  'customer.credits.ledger': { es: 'Movimientos', en: 'Ledger' },
  'customer.credits.ledger.empty': { es: 'Aún no hay movimientos', en: 'No movements yet' },
  'customer.credits.expired': { es: 'Vencido', en: 'Expired' },
  'customer.credits.until': { es: 'hasta {date}', en: 'until {date}' },
  'customer.credits.note': { es: 'Cancelar fuera de la ventana de {h} h devuelve el crédito automáticamente.', en: 'Cancelling outside the {h} h window returns the credit automatically.' },
  'customer.credits.buy.title': { es: 'Comprar créditos', en: 'Buy credits' },
  'customer.credits.done.title': { es: 'Créditos añadidos', en: 'Credits added' },
  'customer.credits.done.body': { es: '+{n} en tu saldo. Recibo enviado.', en: '+{n} to your balance. Receipt sent.' },
  'customer.credits.reason.purchase': { es: 'Compra', en: 'Purchase' },
  'customer.credits.reason.booking': { es: 'Reserva', en: 'Booking' },
  'customer.credits.reason.refund': { es: 'Devolución', en: 'Refund' },
  'customer.credits.reason.expiry': { es: 'Vencimiento', en: 'Expiry' },
  'customer.credits.reason.gift': { es: 'Regalo', en: 'Gift' },
  'customer.credits.reason.comp': { es: 'Cortesía', en: 'Comp' },
  'customer.credits.reason.cancel_return': { es: 'Cancelación (devuelto)', en: 'Cancellation (returned)' },

  // C-08 booked
  'customer.booked.notFound': { es: 'Reserva no encontrada', en: 'Booking not found' },
  'customer.booked.notFound.body': { es: 'Revisa tu historial o el horario.', en: 'Check your history or the schedule.' },
  'customer.booked.startsIn': { es: 'empieza en', en: 'starts in' },
  'customer.booked.checkin': { es: 'check-in abierto', en: 'check-in open' },
  'customer.booked.checkin.body': { es: 'Preséntate en recepción; la puerta cierra al empezar.', en: 'Check in at the front desk; the door closes at start time.' },
  'customer.booked.inProgress': { es: 'La clase está en curso', en: 'The class is in progress' },
  'customer.booked.change': { es: 'Cambiar o cancelar', en: 'Change or cancel' },
  'customer.booked.addToCalendar': { es: 'Añadir al calendario', en: 'Add to calendar' },
  'customer.booked.shareText': { es: 'Voy a {title} el {when} en {name}. ¿Vienes?', en: 'I am going to {title} on {when} at {name}. Coming?' },
  'customer.booked.policy.outside': { es: 'Cancela o cambia gratis hasta las {time} ({h} h antes)', en: 'Cancel or change free until {time} ({h} h before)' },
  'customer.booked.policy.inside': { es: 'Dentro de la ventana de {h} h: cancelar usa el crédito', en: 'Inside the {h} h window: cancelling spends the credit' },
  'customer.booked.paidWith': { es: 'pagada con {with}', en: 'paid with {with}' },
  'customer.booked.rate': { es: 'Calificar la clase', en: 'Rate the class' },
  'customer.booked.cancelled': { es: 'Reserva cancelada', en: 'Booking cancelled' },
  'customer.booked.cancelled.body': { es: 'Cancelaste fuera de la ventana; nada se descontó.', en: 'You cancelled outside the window; nothing was deducted.' },
  'customer.booked.lateCancelled': { es: 'Cancelación tardía', en: 'Late cancellation' },
  'customer.booked.lateCancelled.body': { es: 'Cancelaste dentro de la ventana; el crédito se usó.', en: 'You cancelled inside the window; the credit was spent.' },
  'customer.paidWith.membership': { es: 'membresía', en: 'membership' },
  'customer.paidWith.credit': { es: 'crédito', en: 'credit' },
  'customer.paidWith.single': { es: 'pase individual', en: 'single pass' },
  'customer.paidWith.trial': { es: 'clase de prueba', en: 'trial class' },
  'customer.paidWith.guest': { es: 'pase de invitado', en: 'guest pass' },
  'customer.paidWith.comp': { es: 'cortesía', en: 'comp' },

  // C-08b change sheet
  'customer.change.title': { es: 'Cambiar o cancelar', en: 'Change or cancel' },
  'customer.change.move.title': { es: 'Mover la reserva', en: 'Move the booking' },
  'customer.change.cancel.title': { es: 'Cancelar la reserva', en: 'Cancel the booking' },
  'customer.change.outside': { es: 'Sin costo hasta las {time}.', en: 'Free until {time}.' },
  'customer.change.inside.title': { es: 'Estás dentro de la ventana de {h} h', en: 'You are inside the {h} h window' },
  'customer.change.inside.body': { es: 'Mover sigue siendo gratis si hay cupo; cancelar usa el crédito.', en: 'Moving is still free if there is a spot; cancelling spends the credit.' },
  'customer.change.move': { es: 'Mover a otra clase de hoy', en: 'Move to another class today' },
  'customer.change.move.sub': { es: 'Conservas tu crédito y tu hábito', en: 'Keeps your credit and your habit' },
  'customer.change.drop': { es: 'Cancelar', en: 'Cancel' },
  'customer.change.drop.sub': { es: 'El crédito vuelve a tu saldo', en: 'The credit returns to your balance' },
  'customer.change.drop.sub.inside': { es: 'El crédito se usa', en: 'The credit is spent' },
  'customer.change.pick': { es: 'Elige una alternativa', en: 'Pick a replacement' },
  'customer.change.noAlt': { es: 'Hoy no hay otra clase con cupo', en: 'No other class with spots today' },
  'customer.change.noAlt.body': { es: 'Mira el resto de la semana.', en: 'Look at the rest of the week.' },
  'customer.change.move.note': { es: 'Mover = cancelar y reservar en una sola transacción, con el mismo pago.', en: 'Move = cancel and rebook in one transaction, same entitlement.' },
  'customer.change.cancel.confirm': { es: '¿Cancelar esta reserva? Tu crédito vuelve de inmediato y el cupo pasa a la lista de espera.', en: 'Cancel this booking? Your credit returns immediately and the spot goes to the waitlist.' },
  'customer.change.cancel.confirm.inside': { es: 'Estás dentro de la ventana: si cancelas ahora, tu {with} se usa igual y no vuelve. ¿Seguro?', en: 'You are inside the window: cancelling now spends your {with} and it does not return. Sure?' },
  'customer.change.cancel.cta': { es: 'Sí, cancelar la reserva', en: 'Yes, cancel the booking' },
  'customer.change.keep': { es: 'Mantener mi reserva', en: 'Keep my booking' },
  'customer.change.cancelled.ok': { es: 'Reserva cancelada.', en: 'Booking cancelled.' },
  'customer.change.cancelled.creditBack': { es: 'Reserva cancelada · tu crédito volvió a tu saldo.', en: 'Booking cancelled · your credit is back in your balance.' },
  'customer.change.cancelled.late': { es: 'Reserva cancelada dentro de la ventana · el crédito se usó.', en: 'Booking cancelled inside the window · the credit was spent.' },

  // C-20 waitlist
  'customer.waitlist.full': { es: 'Clase llena · {n} en espera', en: 'Class full · {n} waiting' },
  'customer.waitlist.rule': { es: 'Si se libera un cupo te avisamos por WhatsApp y tienes {min} minutos para reclamarlo. Entrar y salir es gratis.', en: 'If a spot opens we message you on WhatsApp and you have {min} minutes to claim it. Joining and leaving are free.' },
  'customer.waitlist.joined': { es: 'Estás en la lista', en: 'You are on the list' },
  'customer.waitlist.position': { es: 'Posición {n} de {total}', en: 'Position {n} of {total}' },
  'customer.waitlist.released': { es: 'Se liberó un cupo', en: 'A spot opened' },
  'customer.waitlist.toClaim': { es: 'para reclamar', en: 'to claim' },
  'customer.waitlist.claim': { es: 'Reclamar mi cupo', en: 'Claim my spot' },
  'customer.waitlist.claimPay': { es: 'Reclamar y pagar', en: 'Claim and pay' },
  'customer.waitlist.expired': { es: 'El cupo pasó a la siguiente persona', en: 'The spot passed to the next person' },
  'customer.waitlist.expired.body': { es: 'La ventana de reclamo terminó. Puedes volver a la lista.', en: 'The claim window ended. You can rejoin the list.' },
  'customer.waitlist.rejoin': { es: 'Volver a la lista', en: 'Rejoin' },
  'customer.waitlist.spotsOpen': { es: 'Hay {n} cupos libres', en: '{n} spots are open' },
  'customer.waitlist.started': { es: 'La clase ya empezó', en: 'The class already started' },
  'customer.waitlist.started.body': { es: 'La lista de espera se cerró.', en: 'The waitlist is closed.' },
  'customer.waitlist.autoClaim': { es: 'Reclamar automáticamente', en: 'Auto-claim' },
  'customer.waitlist.autoClaim.body': { es: 'Usa un crédito o tu membresía en el momento en que se libere el cupo.', en: 'Uses a credit or your membership the moment the spot is offered.' },
  'customer.waitlist.leave': { es: 'Salir de la lista', en: 'Leave the waitlist' },
  'customer.waitlist.leave.sub': { es: 'Gratis, sin cargos', en: 'Free, no charges' },
  'customer.waitlist.policy': { es: 'La promoción es estricta por posición. Recepción puede ajustar con motivo registrado. Ventana de {min} min.', en: 'Promotion is strictly by position. The front desk can override with a logged reason. {min}-minute window.' },
  'customer.waitlist.devRelease': { es: 'Simular cupo liberado (dev)', en: 'Simulate released spot (dev)' },

  // C-10 rate
  'customer.rate.title': { es: 'Califica tu clase', en: 'Rate your class' },
  'customer.rate.prompt': { es: '¿Cómo estuvo?', en: 'How was it?' },
  'customer.rate.sub': { es: 'Cinco segundos. Puedes saltarlo.', en: 'Five seconds. You can skip it.' },
  'customer.rate.star.1': { es: 'Mal', en: 'Poor' },
  'customer.rate.star.2': { es: 'Regular', en: 'Meh' },
  'customer.rate.star.3': { es: 'Bien', en: 'Fine' },
  'customer.rate.star.4': { es: 'Muy bien', en: 'Very good' },
  'customer.rate.star.5': { es: 'Excelente', en: 'Excellent' },
  'customer.rate.good': { es: 'Lo que estuvo bien', en: 'What was good' },
  'customer.rate.fix': { es: 'Lo que mejoraría', en: 'What could improve' },
  'customer.rate.tag.music': { es: 'Música', en: 'Music' },
  'customer.rate.tag.heat': { es: 'Temperatura', en: 'Heat' },
  'customer.rate.tag.pace': { es: 'Ritmo', en: 'Pace' },
  'customer.rate.tag.clarity': { es: 'Claridad', en: 'Clarity' },
  'customer.rate.tag.crowded': { es: 'Sala llena', en: 'Crowded' },
  'customer.rate.tag.late': { es: 'Empezó tarde', en: 'Started late' },
  'customer.rate.tag.tooHard': { es: 'Muy exigente', en: 'Too hard' },
  'customer.rate.tag.tooEasy': { es: 'Muy suave', en: 'Too easy' },
  'customer.rate.note': { es: 'Algo más (opcional)', en: 'Anything else (optional)' },
  'customer.rate.anonymous': { es: 'Enviar como anónimo', en: 'Send anonymously' },
  'customer.rate.submit': { es: 'Enviar', en: 'Send' },
  'customer.rate.skip': { es: 'Saltar', en: 'Skip' },
  'customer.rate.privacy': { es: 'Los profesores ven promedios anónimos. Menos de 3 estrellas abre un seguimiento con coordinación.', en: 'Teachers see anonymous aggregates. Under 3 stars opens a follow-up with the coordinator.' },
  'customer.rate.thanks': { es: 'Gracias', en: 'Thank you' },
  'customer.rate.thanks.body': { es: 'Tu opinión ya está con el equipo.', en: 'Your feedback is with the team.' },
  'customer.rate.public': { es: 'Dejar una reseña pública', en: 'Leave a public review' },

  // C-11 history
  'customer.history.title': { es: 'Historial', en: 'History' },
  'customer.history.sub': { es: 'Clases y pagos, con recibos.', en: 'Classes and payments, with receipts.' },
  'customer.history.export': { es: 'Exportar', en: 'Export' },
  'customer.history.classes': { es: 'Clases', en: 'Classes' },
  'customer.history.payments': { es: 'Pagos', en: 'Payments' },
  'customer.history.empty': { es: 'Tu primera clase te espera', en: 'Your first class is waiting' },
  'customer.history.empty.body': { es: 'Aquí aparecerán tus clases pasadas, incluidas las canceladas.', en: 'Your past classes appear here, cancelled ones included.' },
  'customer.history.payments.empty': { es: 'Aún no hay pagos', en: 'No payments yet' },
  'customer.history.otherCharge': { es: 'Otro cargo', en: 'Other charge' },
  'customer.history.note': { es: 'Canceladas y no asistidas se marcan, no se ocultan. Facturas electrónicas DIAN cuando aplique.', en: 'Cancelled and no-show classes are marked, not hidden. DIAN electronic invoices where applicable.' },
  'customer.history.receipt': { es: 'Recibo', en: 'Receipt' },
  'customer.history.receipt.number': { es: 'Número', en: 'Number' },
  'customer.history.receipt.date': { es: 'Fecha', en: 'Date' },
  'customer.history.receipt.concept': { es: 'Concepto', en: 'Item' },
  'customer.history.receipt.method': { es: 'Método', en: 'Method' },
  'customer.history.receipt.dian': { es: 'Factura electrónica DIAN con NIT e IVA cuando el estudio la emita; PDF próximamente.', en: 'DIAN electronic invoice with NIT and IVA when the studio issues it; PDF coming.' },
  'customer.history.status.booked': { es: 'Reservada', en: 'Booked' },
  'customer.history.status.checked_in': { es: 'Asistió', en: 'Attended' },
  'customer.history.status.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'customer.history.status.no_show': { es: 'No asistió', en: 'No-show' },
  'customer.history.status.late_cancel': { es: 'Cancelación tardía', en: 'Late cancel' },
  'customer.history.pay.pending': { es: 'Pendiente', en: 'Pending' },
  'customer.history.pay.approved': { es: 'Aprobado', en: 'Approved' },
  'customer.history.pay.declined': { es: 'Rechazado', en: 'Declined' },
  'customer.history.pay.refunded': { es: 'Reembolsado', en: 'Refunded' },
  'customer.history.pay.voided': { es: 'Anulado', en: 'Voided' },

  // C-13 rules
  'customer.rules.title': { es: 'Reglas del club', en: 'Club rules' },
  'customer.rules.sub': { es: 'Lo que mantiene la sala segura y agradable.', en: 'What keeps the room safe and pleasant.' },
  'customer.rules.read': { es: 'Leído', en: 'Read' },
  'customer.rules.required': { es: 'Importante', en: 'Important' },
  'customer.rules.checklist': { es: 'Lista', en: 'Checklist' },
  'customer.rules.gotIt': { es: 'Entendido', en: 'Got it' },
  'customer.rules.note': { es: 'Los videos son marcadores hasta que el estudio grabe el material.', en: 'Videos are placeholders until the studio supplies footage.' },

  // C-14 / C-15 FAQ
  'customer.faq.title': { es: 'Preguntas frecuentes', en: 'FAQ' },
  'customer.faq.page': { es: 'Página {n} de {total}', en: 'Page {n} of {total}' },
  'customer.faq.plansLink': { es: 'Ver planes', en: 'See plans' },
  'customer.faq.next': { es: 'Siguiente: el espacio, cómo llegar y contacto', en: 'Next: the space, getting here and contact' },
  'customer.faq.concierge': { es: '¿No está tu pregunta? Una persona te responde.', en: 'Question not here? A person answers.' },

  // C-16 invite
  'customer.invite.title': { es: 'Invita a un amigo', en: 'Invite a friend' },
  'customer.invite.sub': { es: 'Un pase de prueba por persona invitada, por WhatsApp, email o enlace.', en: 'One trial pass per invited person, by WhatsApp, email or link.' },
  'customer.invite.pass': { es: 'Pase de invitado', en: 'Guest pass' },
  'customer.invite.pass.title': { es: 'Una clase de regalo', en: 'One class, on us' },
  'customer.invite.pass.valid': { es: 'Válido {days} días · una vez por persona', en: 'Valid {days} days · once per person' },
  'customer.invite.to': { es: 'Para (opcional)', en: 'To (optional)' },
  'customer.invite.to.hint': { es: 'Número de WhatsApp o correo. Si lo dejas vacío, eliges el contacto en la app.', en: 'WhatsApp number or email. Leave empty to pick the contact in the app.' },
  'customer.invite.link': { es: 'Enlace', en: 'Link' },
  'customer.invite.sent': { es: 'Invitación enviada', en: 'Invite sent' },
  'customer.invite.subject': { es: 'Te invito a una clase en {studio}', en: 'I am inviting you to a class at {studio}' },
  'customer.invite.text.general': { es: 'Soy {name}. Te regalo una clase en {studio}: entra con este enlace.', en: 'It is {name}. Here is a free class at {studio}: use this link.' },
  'customer.invite.text.class': { es: 'Soy {name}. Ven conmigo a {title} el {when} en {studio}: tu primera clase va por mi cuenta.', en: 'It is {name}. Join me at {title} on {when} at {studio}: your first class is on me.' },
  'customer.invite.sentList': { es: 'Enviadas', en: 'Sent' },
  'customer.invite.sentList.empty': { es: 'Aún no has invitado a nadie.', en: 'You have not invited anyone yet.' },
  'customer.invite.status.sent': { es: 'Enviada', en: 'Sent' },
  'customer.invite.status.opened': { es: 'Abierta', en: 'Opened' },
  'customer.invite.reward': { es: 'Cuando tu invitado asiste, el estudio puede acreditarte una clase (configurable).', en: 'When your guest attends, the studio may credit you a class (configurable).' },

  // C-17 gift
  'customer.gift.title': { es: 'Tarjeta de regalo', en: 'Gift card' },
  'customer.gift.sub': { es: 'Regala bienestar: monto, destinatario, fecha y mensaje.', en: 'Gift wellness: amount, recipient, date and message.' },
  'customer.gift.preview': { es: 'Vista previa de la tarjeta', en: 'Card preview' },
  'customer.gift.for': { es: 'Para {name}', en: 'For {name}' },
  'customer.gift.amount': { es: 'Monto', en: 'Amount' },
  'customer.gift.custom': { es: 'Otro monto', en: 'Custom amount' },
  'customer.gift.min': { es: 'Mínimo {amount}.', en: 'Minimum {amount}.' },
  'customer.gift.to': { es: 'Para quién', en: 'Recipient' },
  'customer.gift.contact': { es: 'WhatsApp o correo', en: 'WhatsApp or email' },
  'customer.gift.contact.hint': { es: 'Ahí llega la tarjeta.', en: 'Where the card arrives.' },
  'customer.gift.contact.err': { es: 'Escribe un WhatsApp válido o un correo.', en: 'Enter a valid WhatsApp number or email.' },
  'customer.gift.delivery': { es: 'Entrega', en: 'Delivery' },
  'customer.gift.date': { es: 'Fecha de entrega', en: 'Delivery date' },
  'customer.gift.date.hint': { es: 'Se envía a las 8:00 de ese día por email y WhatsApp.', en: 'Sent at 8:00 that day by email and WhatsApp.' },
  'customer.gift.date.past': { es: 'La fecha no puede ser pasada.', en: 'The date cannot be in the past.' },
  'customer.gift.message': { es: 'Mensaje', en: 'Message' },
  'customer.gift.design': { es: 'Diseño', en: 'Design' },
  'customer.gift.note': { es: 'Se convierte en créditos en la cuenta de quien lo recibe en {studio}. Sin cargo por servicio.', en: 'Converts to credits on the recipient’s {studio} account. No service fee.' },
  'customer.gift.cta': { es: 'Regalar {amount}', en: 'Gift {amount}' },
  'customer.gift.done.title': { es: 'Regalo programado', en: 'Gift scheduled' },
  'customer.gift.done.body': { es: 'Código {code} para {name}. Se entrega el {date} a las 8:00. Recibo enviado.', en: 'Code {code} for {name}. Delivered on {date} at 8:00. Receipt sent.' },

  // C-18 teachers
  'customer.teachers.title': { es: 'Profesores', en: 'Teachers' },
  'customer.teachers.sub': { es: 'Elige a la persona, no solo la hora.', en: 'Choose the person, not just the time slot.' },
  'customer.teachers.notFound': { es: 'Profesor no encontrado', en: 'Teacher not found' },
  'customer.teachers.portrait': { es: 'Retrato del profesor (pendiente)', en: 'Teacher portrait (pending)' },
  'customer.teachers.teaches': { es: 'Enseña', en: 'Teaches' },
  'customer.teachers.upcoming': { es: 'Próximas clases', en: 'Upcoming classes' },
  'customer.teachers.upcoming.empty': { es: 'Sin clases programadas esta semana.', en: 'No classes scheduled this week.' },
  'customer.teachers.ratingsNote': { es: 'Las valoraciones son privadas hasta que el estudio las active.', en: 'Ratings stay private until the studio enables them.' },

  // C-19 profile
  'customer.profile.title': { es: 'Perfil', en: 'Profile' },
  'customer.profile.changePhoto': { es: 'Cambiar foto', en: 'Change photo' },
  'customer.profile.photoTooBig': { es: 'La foto debe pesar menos de 1,5 MB.', en: 'The photo must be under 1.5 MB.' },
  'customer.profile.noPlan': { es: 'Sin plan', en: 'No plan' },
  'customer.profile.whatsapp.verify': { es: 'Verificar WhatsApp', en: 'Verify WhatsApp' },
  'customer.profile.whatsapp.verified': { es: 'WhatsApp verificado.', en: 'WhatsApp verified.' },
  'customer.profile.edit': { es: 'Editar perfil', en: 'Edit profile' },
  'customer.profile.saved': { es: 'Guardado.', en: 'Saved.' },
  'customer.profile.account': { es: 'Cuenta', en: 'Account' },
  'customer.profile.pay.sub': { es: 'Tarjetas, PSE, Nequi, transferencia', en: 'Cards, PSE, Nequi, transfer' },
  'customer.profile.notifications': { es: 'Notificaciones', en: 'Notifications' },
  'customer.profile.notif.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.profile.notif.whatsapp.sub': { es: 'Recordatorios, cupos liberados, cancelaciones', en: 'Reminders, released spots, cancellations' },
  'customer.profile.notif.push': { es: 'Push', en: 'Push' },
  'customer.profile.notif.push.sub': { es: 'En este dispositivo', en: 'On this device' },
  'customer.profile.notif.email': { es: 'Email', en: 'Email' },
  'customer.profile.notif.email.sub': { es: 'Recibos y resúmenes', en: 'Receipts and summaries' },
  'customer.profile.language': { es: 'Idioma', en: 'Language' },
  'customer.profile.language.sub': { es: 'Por cuenta, no por dispositivo', en: 'Per account, not per device' },
  'customer.profile.review': { es: 'Deja una reseña', en: 'Leave a review' },
  'customer.profile.review.google': { es: 'Google', en: 'Google' },
  'customer.profile.review.instagram': { es: 'Instagram', en: 'Instagram' },
  'customer.profile.legal': { es: 'Legal', en: 'Legal' },
  'customer.profile.legal.terms': { es: 'Términos y condiciones', en: 'Terms and conditions' },
  'customer.profile.legal.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },
  'customer.profile.legal.law': { es: 'Ley 1581 de 2012 · Habeas Data', en: 'Ley 1581 de 2012 · Habeas Data' },
  'customer.profile.signOut': { es: 'Cerrar sesión', en: 'Sign out' },
  'customer.profile.delete': { es: 'Eliminar mi cuenta', en: 'Delete my account' },
  'customer.profile.delete.sub': { es: '30 días para recuperarla', en: '30-day recovery window' },
  'customer.profile.delete.confirm.title': { es: '¿Eliminar tu cuenta?', en: 'Delete your account?' },
  'customer.profile.delete.confirm.body': { es: 'Tendrás 30 días para recuperarla escribiendo al estudio. Después se borran tus datos conforme a la Ley 1581.', en: 'You have 30 days to recover it by contacting the studio. After that your data is erased under Ley 1581.' },
  'customer.profile.delete.cta': { es: 'Eliminar cuenta', en: 'Delete account' },

  // forms (shared by C-19, A-03, C-21, C-17)
  'customer.form.required': { es: 'Este campo es obligatorio.', en: 'This field is required.' },
  'customer.form.name': { es: 'Nombre', en: 'Name' },
  'customer.form.first': { es: 'Nombre', en: 'First name' },
  'customer.form.last': { es: 'Apellido', en: 'Last name' },
  'customer.form.email': { es: 'Correo', en: 'Email' },
  'customer.form.email.err': { es: 'Escribe un correo válido.', en: 'Enter a valid email.' },
  'customer.form.phone': { es: 'Teléfono', en: 'Phone' },
  'customer.form.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.form.whatsapp.hint': { es: 'Colombia +57 por defecto. Ahí llegan recordatorios y cancelaciones.', en: 'Colombia +57 by default. Reminders and cancellations go here.' },
  'customer.form.password': { es: 'Contraseña', en: 'Password' },
  'customer.form.password.hint': { es: 'Mínimo 8 caracteres. Sin reglas de composición.', en: 'At least 8 characters. No composition rules.' },
  'customer.form.password.err': { es: 'Mínimo 8 caracteres.', en: 'At least 8 characters.' },
  'customer.form.strength.0': { es: 'Muy corta', en: 'Too short' },
  'customer.form.strength.1': { es: 'Débil', en: 'Weak' },
  'customer.form.strength.2': { es: 'Aceptable', en: 'Okay' },
  'customer.form.strength.3': { es: 'Fuerte', en: 'Strong' },
  'customer.form.birthday': { es: 'Cumpleaños (opcional)', en: 'Birthday (optional)' },
  'customer.form.birthday.hint': { es: 'Para felicitarte.', en: 'So we can wish you well.' },
  'customer.form.emergency': { es: 'Contacto de emergencia', en: 'Emergency contact' },
  'customer.form.photo': { es: 'Foto de perfil', en: 'Profile photo' },
  'customer.form.photo.hint': { es: 'Ayuda a recepción a reconocerte. Puedes añadirla después.', en: 'Helps the front desk recognise you. You can add it later.' },
  'customer.form.photo.pick': { es: 'Tomar o elegir', en: 'Take or choose' },
  'customer.form.optional': { es: 'Opcional', en: 'Optional' },

  // C-22 membership
  'customer.membership.title': { es: 'Membresía', en: 'Membership' },
  'customer.membership.none': { es: 'Aún no tienes membresía', en: 'No membership yet' },
  'customer.membership.none.body': { es: 'Elige un plan o sigue pagando por clase.', en: 'Pick a plan or keep paying per class.' },
  'customer.membership.current': { es: 'Plan actual', en: 'Current plan' },
  'customer.membership.renews': { es: 'Renueva {date}', en: 'Renews {date}' },
  'customer.membership.notice': { es: 'Te avisamos {days} días antes de cada cobro.', en: 'We notify you {days} days before each charge.' },
  'customer.membership.usage': { es: 'Clases este mes', en: 'Classes this month' },
  'customer.membership.usage.hint': { es: 'Reservadas y asistidas', en: 'Booked and attended' },
  'customer.membership.since': { es: 'Socio desde', en: 'Member since' },
  'customer.membership.pause': { es: 'Pausar membresía', en: 'Pause membership' },
  'customer.membership.pause.sub': { es: 'Hasta {days} días; la renovación se corre', en: 'Up to {days} days; renewal shifts' },
  'customer.membership.pause.body': { es: 'Hasta {days} días al año. No se cobra mientras está en pausa y la fecha de renovación se corre esos días.', en: 'Up to {days} days a year. No charge while paused and the renewal date shifts by those days.' },
  'customer.membership.pause.days': { es: 'Duración', en: 'Duration' },
  'customer.membership.pause.option': { es: '{n} días', en: '{n} days' },
  'customer.membership.pause.preview': { es: 'En pausa hasta el {until}. Nueva renovación: {renews}.', en: 'Paused until {until}. New renewal: {renews}.' },
  'customer.membership.pause.cta': { es: 'Pausar', en: 'Pause' },
  'customer.membership.paused.ok': { es: 'Membresía en pausa hasta el {date}.', en: 'Membership paused until {date}.' },
  'customer.membership.paused.title': { es: 'Membresía en pausa', en: 'Membership paused' },
  'customer.membership.paused.body': { es: 'Se reanuda el {date}. Puedes reanudarla antes.', en: 'Resumes on {date}. You can resume earlier.' },
  'customer.membership.resume': { es: 'Reanudar', en: 'Resume' },
  'customer.membership.resumed': { es: 'Membresía reanudada.', en: 'Membership resumed.' },
  'customer.membership.change': { es: 'Cambiar de plan', en: 'Change plan' },
  'customer.membership.change.sub': { es: 'Aplica en el próximo ciclo', en: 'Applies next cycle' },
  'customer.membership.billing': { es: 'Historial de pagos', en: 'Billing history' },
  'customer.membership.billing.sub': { es: 'Recibos y facturas', en: 'Receipts and invoices' },
  'customer.membership.cancel': { es: 'Cancelar membresía', en: 'Cancel membership' },
  'customer.membership.cancel.sub': { es: 'Conservas el acceso hasta el fin del periodo', en: 'You keep access until the period ends' },
  'customer.membership.cancel.body': { es: 'Tu acceso continúa hasta el {date}. Conservas créditos e historial y puedes deshacerlo hasta entonces.', en: 'Your access continues until {date}. You keep credits and history and can undo until then.' },
  'customer.membership.cancel.reason': { es: 'Motivo (nos ayuda a mejorar)', en: 'Reason (helps us improve)' },
  'customer.membership.cancel.cta': { es: 'Cancelar al final del periodo', en: 'Cancel at period end' },
  'customer.membership.cancelled.ok': { es: 'Cancelación programada para el {date}.', en: 'Cancellation scheduled for {date}.' },
  'customer.membership.pendingCancel.title': { es: 'Cancelación programada', en: 'Cancellation scheduled' },
  'customer.membership.pendingCancel.body': { es: 'Tu acceso termina el {date}.', en: 'Your access ends on {date}.' },
  'customer.membership.undo': { es: 'Deshacer', en: 'Undo' },
  'customer.membership.undone': { es: 'Cancelación deshecha.', en: 'Cancellation undone.' },
  'customer.membership.reason.price': { es: 'Precio', en: 'Price' },
  'customer.membership.reason.schedule': { es: 'Horario', en: 'Schedule' },
  'customer.membership.reason.moving': { es: 'Me mudo', en: 'Moving' },
  'customer.membership.reason.injury': { es: 'Lesión o salud', en: 'Injury or health' },
  'customer.membership.reason.other': { es: 'Otro', en: 'Other' },
  'customer.membership.status.active': { es: 'Activa', en: 'Active' },
  'customer.membership.status.paused': { es: 'En pausa', en: 'Paused' },
  'customer.membership.status.past_due': { es: 'Pago pendiente', en: 'Payment due' },
  'customer.membership.status.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'customer.membership.status.expired': { es: 'Vencida', en: 'Expired' },

  // C-23 events
  'customer.events.title': { es: 'Eventos', en: 'Events' },
  'customer.events.sub': { es: 'Baños de sonido, talleres y retiros.', en: 'Sound baths, workshops and retreats.' },
  'customer.events.spots': { es: 'cupos', en: 'spots' },
  'customer.events.notFound': { es: 'Evento no encontrado', en: 'Event not found' },
  'customer.events.photo': { es: 'Foto del evento · 4:5 (pendiente)', en: 'Event photo · 4:5 (pending)' },
  'customer.events.host': { es: 'Con {name}', en: 'With {name}' },
  'customer.events.price.public': { es: 'Precio general', en: 'Public price' },
  'customer.events.price.member': { es: 'Socios', en: 'Members' },
  'customer.events.bring': { es: 'Qué traer', en: 'What to bring' },
  'customer.events.friend': { es: 'Traer a un amigo', en: 'Bring a friend' },
  'customer.events.friend.sub': { es: 'Pase de invitado', en: 'Guest pass' },
  'customer.events.rsvp': { es: 'Reservar mi lugar', en: 'Reserve my place' },
  'customer.events.soldOut': { es: 'Agotado · lista de espera pronto', en: 'Sold out · waitlist soon' },
  'customer.events.going': { es: 'Vas a este evento', en: 'You are going' },
  'customer.events.going.body': { es: 'Te enviamos la confirmación por WhatsApp y email.', en: 'Confirmation sent by WhatsApp and email.' },
  'customer.events.cancel': { es: 'Cancelar', en: 'Cancel' },
  'customer.events.memberIncluded': { es: 'Incluido en tu membresía', en: 'Included in your membership' },
  'customer.events.policy': { es: 'Los eventos no consumen créditos de clase y tienen su propia política de cancelación.', en: 'Events do not consume class credits and have their own cancellation policy.' },

  // C-24 notifications
  'customer.notifications.title': { es: 'Notificaciones', en: 'Notifications' },
  'customer.notifications.unread': { es: '{n} sin leer', en: '{n} unread' },
  'customer.notifications.markAll': { es: 'Marcar todo como leído', en: 'Mark all read' },
  'customer.notifications.today': { es: 'Hoy', en: 'Today' },
  'customer.notifications.earlier': { es: 'Antes', en: 'Earlier' },
  'customer.notifications.empty': { es: 'Nada todavía', en: 'Nothing yet' },
  'customer.notifications.empty.body': { es: 'Aquí verás lo que el estudio te envía por WhatsApp, email o push.', en: 'Everything the studio sends you by WhatsApp, email or push appears here.' },
  'customer.notifications.retention': { es: 'Se conservan 90 días', en: 'Kept for 90 days' },

  // C-25 more
  'customer.more.planPrompt': { es: 'Elegir plan', en: 'Pick a plan' },
  'customer.more.plans.sub': { es: 'Membresía y pases Bienvenida', en: 'Membership and Welcome passes' },
  'customer.more.rules.sub': { es: 'Sala caliente · etiqueta · tour', en: 'Hot room · etiquette · tour' },
  'customer.more.whatsapp': { es: 'Escribir al estudio', en: 'WhatsApp the studio' },
  'customer.more.whatsapp.text': { es: 'Hola, soy {name}. Tengo una pregunta:', en: 'Hi, it is {name}. I have a question:' },
  'customer.more.email': { es: 'Correo al estudio', en: 'Email the studio' },
  'customer.more.states': { es: 'Estados de ejemplo (dev)', en: 'Sample states (dev)' },
  'customer.more.authFlow': { es: 'Flujo de acceso', en: 'Auth flow' },

  // A-05 intention
  'customer.intention.enraiza': { es: 'Tierra, centro, fuerza tranquila.', en: 'Ground, centre, quiet strength.' },
  'customer.intention.fluye': { es: 'Movimiento continuo, respiración.', en: 'Continuous movement, breath.' },
  'customer.intention.arde': { es: 'Calor, sudor, foco.', en: 'Heat, sweat, focus.' },
  'customer.intention.libera': { es: 'Soltar, quietud, descanso.', en: 'Release, stillness, rest.' },
  'customer.intention.skip': { es: 'Hoy no, gracias', en: 'Not today, thanks' },

  // A-01 splash
  'customer.splash.line1': { es: 'La vida es', en: 'Life is' },
  'customer.splash.line2': { es: 'Un oasis en ti', en: 'An oasis within' },
  'customer.splash.loading': { es: 'Restaurando tu sesión…', en: 'Restoring your session…' },
  'customer.splash.ready': { es: 'Listo', en: 'Ready' },
  'customer.splash.continue': { es: 'Continuar', en: 'Continue' },

  // A-02 sign in
  'customer.signin.title': { es: 'Entrar', en: 'Sign in' },
  'customer.signin.sub': { es: 'Demo: elige un usuario o escribe su correo. La autenticación real llega con Supabase Auth.', en: 'Demo: pick a user or type their email. Real authentication arrives with Supabase Auth.' },
  'customer.signin.demo': { es: 'Usuarios demo', en: 'Demo users' },
  'customer.signin.emailHint': { es: 'Cualquier correo de usuario demo; cualquier contraseña.', en: 'Any demo user email; any password.' },
  'customer.signin.cta': { es: 'Entrar', en: 'Sign in' },
  'customer.signin.forgot': { es: 'Olvidé mi contraseña', en: 'Forgot my password' },
  'customer.signin.wrong': { es: 'Correo o contraseña incorrectos. Te quedan {n} intentos.', en: 'Wrong email or password. {n} attempts left.' },
  'customer.signin.or': { es: 'o', en: 'or' },
  'customer.signin.apple': { es: 'Continuar con Apple', en: 'Continue with Apple' },
  'customer.signin.google': { es: 'Continuar con Google', en: 'Continue with Google' },
  'customer.signin.biometric': { es: 'Desbloqueo biométrico', en: 'Biometric unlock' },
  'customer.signin.providersNote': { es: 'Llegan con Supabase Auth.', en: 'Coming with Supabase Auth.' },
  'customer.signin.new': { es: '¿Primera vez?', en: 'First time?' },
  'customer.signin.create': { es: 'Crear cuenta', en: 'Create account' },

  // A-03 sign up
  'customer.signup.title': { es: 'Crear cuenta', en: 'Create account' },
  'customer.signup.sub': { es: 'Lo mínimo que el estudio necesita. Dos minutos.', en: 'The minimum the studio needs. Two minutes.' },
  'customer.signup.step': { es: 'Paso {n} de {total}', en: 'Step {n} of {total}' },
  'customer.signup.emergency.why': { es: 'Lo pedimos ahora para que exista desde tu primera clase.', en: 'We ask now so it exists from your first class.' },
  'customer.signup.consent': { es: 'Acepto los', en: 'I accept the' },
  'customer.signup.and': { es: 'y la', en: 'and the' },
  'customer.signup.consent.err': { es: 'Necesitamos tu consentimiento para continuar.', en: 'We need your consent to continue.' },
  'customer.signup.dup': { es: 'Ya existe una cuenta con ese correo o WhatsApp', en: 'An account with that email or WhatsApp already exists' },
  'customer.signup.dup.body': { es: 'Entra con ella o recupera la contraseña.', en: 'Sign in with it or recover the password.' },
  'customer.signup.cta': { es: 'Continuar', en: 'Continue' },
  'customer.signup.have': { es: '¿Ya tienes cuenta?', en: 'Already have an account?' },

  // C-21 password reset
  'customer.reset.back': { es: 'Volver a entrar', en: 'Back to sign in' },
  'customer.reset.title': { es: 'Recuperar acceso', en: 'Recover access' },
  'customer.reset.sub': { es: 'Te enviamos un código de 6 dígitos por WhatsApp; email como alternativa.', en: 'We send a 6-digit code by WhatsApp; email as a fallback.' },
  'customer.reset.channel': { es: 'Canal', en: 'Channel' },
  'customer.reset.send': { es: 'Enviar código', en: 'Send code' },
  'customer.reset.privacy': { es: 'Si la cuenta existe, recibirás el código. El mensaje es igual en ambos casos.', en: 'If the account exists you will receive the code. The message is identical either way.' },
  'customer.reset.otp.title': { es: 'Escribe el código', en: 'Enter the code' },
  'customer.reset.otp.sub': { es: 'Enviado a {to}. Vale {min} minutos y se usa una vez.', en: 'Sent to {to}. Valid {min} minutes, single use.' },
  'customer.reset.demoCode': { es: 'Demo: el código es {code}.', en: 'Demo: the code is {code}.' },
  'customer.reset.codeInvalidated': { es: 'Tres intentos fallidos: el código se invalidó. Pide uno nuevo.', en: 'Three wrong attempts: the code was invalidated. Request a new one.' },
  'customer.reset.wrong': { es: 'Código incorrecto. Te quedan {n} intentos.', en: 'Wrong code. {n} attempts left.' },
  'customer.reset.resend': { es: 'Reenviar código', en: 'Resend code' },
  'customer.reset.resendIn': { es: 'Reenviar en {s} s', en: 'Resend in {s} s' },
  'customer.reset.useEmail': { es: 'Usar email en su lugar', en: 'Use email instead' },
  'customer.reset.useWhatsapp': { es: 'Usar WhatsApp en su lugar', en: 'Use WhatsApp instead' },
  'customer.reset.new.title': { es: 'Nueva contraseña', en: 'New password' },
  'customer.reset.save': { es: 'Guardar y entrar', en: 'Save and sign in' },
  'customer.reset.signOutOthers': { es: 'Al guardar, cerramos la sesión en tus otros dispositivos.', en: 'Saving signs you out on your other devices.' },
  'customer.reset.done.title': { es: 'Contraseña actualizada', en: 'Password updated' },
  'customer.reset.done.body': { es: 'Ya puedes entrar con la nueva contraseña.', en: 'You can now sign in with the new password.' },

  // E-04 locked
  'customer.locked.title': { es: 'Acceso en pausa', en: 'Sign-in paused' },
  'customer.locked.body': { es: 'Tras {n} intentos fallidos pausamos el acceso {min} minutos y avisamos por email al titular de la cuenta.', en: 'After {n} failed attempts we pause sign-in for {min} minutes and email the account holder.' },
  'customer.locked.wait': { es: 'para reintentar', en: 'to retry' },
  'customer.locked.recover': { es: 'Recuperar contraseña', en: 'Recover password' },
  'customer.locked.whatsapp': { es: 'Escribir al estudio', en: 'WhatsApp the studio' },
  'customer.locked.whatsappText': { es: 'Hola, no puedo entrar a mi cuenta.', en: 'Hi, I cannot sign in to my account.' },
  'customer.locked.security': { es: 'La recuperación no está limitada por esta pausa. El contador es del servidor: reinstalar la app no lo reinicia.', en: 'Recovery is not rate-limited by this pause. The countdown is server-side: reinstalling the app does not reset it.' },

  // 0008 · notifications table (C-24) + prefs
  'customer.notifications.open': { es: 'Abrir', en: 'Open' },
  'customer.notifications.via.in_app': { es: 'en la app', en: 'in app' },
  'customer.notifications.via.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.notifications.via.email': { es: 'Email', en: 'Email' },
  'customer.notifications.via.push': { es: 'Push', en: 'Push' },
  'customer.notifications.prefs.title': { es: 'Preferencias', en: 'Preferences' },
  'customer.notifications.prefs.sub': { es: 'Elige por canal qué quieres recibir. Lo importante de tus reservas siempre llega a esta bandeja.', en: 'Choose per channel what you want to receive. Anything critical about your bookings always reaches this inbox.' },
  'customer.notifications.prefs.byCategory': { es: 'Ajusta por canal y categoría', en: 'Tune by channel and category' },
  'customer.notifications.prefs.note': { es: 'Guardamos solo lo que cambias; lo demás queda activo.', en: 'We store only what you change; everything else stays on.' },
  'customer.notifications.channel.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.notifications.channel.email': { es: 'Email', en: 'Email' },
  'customer.notifications.channel.push': { es: 'Push', en: 'Push' },
  'customer.notifications.cat.bookings': { es: 'Reservas', en: 'Bookings' },
  'customer.notifications.cat.bookings.sub': { es: 'Confirmaciones, cambios y recordatorios de clase.', en: 'Confirmations, changes and class reminders.' },
  'customer.notifications.cat.waitlist': { es: 'Lista de espera', en: 'Waitlist' },
  'customer.notifications.cat.waitlist.sub': { es: 'Cuando se libera un cupo tuyo.', en: 'When a spot opens for you.' },
  'customer.notifications.cat.payments': { es: 'Pagos', en: 'Payments' },
  'customer.notifications.cat.payments.sub': { es: 'Recibos, cobros próximos y pagos rechazados.', en: 'Receipts, upcoming charges and declined payments.' },
  'customer.notifications.cat.events': { es: 'Eventos', en: 'Events' },
  'customer.notifications.cat.events.sub': { es: 'Talleres y baños de sonido nuevos.', en: 'New workshops and sound baths.' },
  'customer.notifications.cat.marketing': { es: 'Novedades', en: 'News' },
  'customer.notifications.cat.marketing.sub': { es: 'Noticias del club y promociones. Nunca afecta tus reservas.', en: 'Club news and offers. Never affects your bookings.' },
  // 0008 · invites table (C-16)
  'customer.invite.status.joined': { es: 'Se unió', en: 'Joined' },
  'customer.invite.status.rewarded': { es: 'Clase acreditada', en: 'Class credited' },
  'customer.invite.channel.whatsapp': { es: 'Enviada por WhatsApp', en: 'Sent by WhatsApp' },
  'customer.invite.channel.email': { es: 'Enviada por email', en: 'Sent by email' },
  'customer.invite.channel.link': { es: 'Enlace compartido', en: 'Link shared' },
  // 0008 · payment_methods table (C-05)
  'customer.pay.add': { es: 'Guardar', en: 'Save' },
  'customer.pay.saved.default': { es: 'Predeterminado', en: 'Default' },
  'customer.pay.saved.makeDefault': { es: 'Usar por defecto', en: 'Make default' },
  'customer.pay.saved.remove': { es: 'Quitar método', en: 'Remove method' },
  'customer.pay.saved.expires': { es: 'Vence {date}', en: 'Expires {date}' },
  'customer.pay.kind.card': { es: 'Tarjeta', en: 'Card' },
  'customer.pay.kind.pse': { es: 'PSE · débito bancario', en: 'PSE · bank debit' },
  'customer.pay.kind.nequi': { es: 'Nequi · billetera', en: 'Nequi · wallet' },
  'customer.pay.kind.transfer': { es: 'Transferencia', en: 'Transfer' },
  'customer.pay.kind.cash': { es: 'Efectivo', en: 'Cash' },
  // 0008 · events + content tables (C-23, C-14/C-15)
  'customer.events.empty': { es: 'Aún no hay eventos', en: 'No events yet' },
  'customer.events.empty.body': { es: 'El estudio publica talleres y baños de sonido aquí.', en: 'The studio publishes workshops and sound baths here.' },
  'customer.faq.empty': { es: 'Sin preguntas publicadas', en: 'No published questions' },
  'customer.faq.empty.body': { es: 'El estudio está preparando esta sección.', en: 'The studio is preparing this section.' },
  // 0012 · A-06 legal library (site + in-app) and the media slots
  'customer.legal.title': { es: 'Legal', en: 'Legal' },
  'customer.legal.kind.terms': { es: 'Términos y condiciones', en: 'Terms & conditions' },
  'customer.legal.kind.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },
  'customer.legal.kind.waiver': { es: 'Exoneración y declaración de salud', en: 'Waiver & health declaration' },
  'customer.legal.kind.cancellation': { es: 'Política de cancelaciones', en: 'Cancellation policy' },
  'customer.legal.kind.refunds': { es: 'Política de reembolsos', en: 'Refund policy' },
  'customer.legal.kind.house-rules': { es: 'Reglas de casa', en: 'House rules' },
  'customer.legal.status.published': { es: 'Vigente', en: 'In force' },
  'customer.legal.status.draft': { es: 'Borrador', en: 'Draft' },
  'customer.legal.effective': { es: 'Vigente desde el {date}', en: 'In force since {date}' },
  'customer.legal.effective.draft': { es: 'Propuesta para el {date}', en: 'Proposed for {date}' },
  'customer.legal.counsel': { es: 'Texto redactado por el estudio y pendiente de revisión por abogado. Cita la Ley 1581 de 2012 (datos personales) y la Ley 1480 de 2011 (consumidor); no reemplaza asesoría legal.', en: 'Written by the studio and pending counsel review. It cites Ley 1581 de 2012 (personal data) and Ley 1480 de 2011 (consumer law); it is not legal advice.' },
  'customer.legal.versions': { es: 'Versiones', en: 'Versions' },
  'customer.legal.accepted': { es: 'Aceptaste esta versión el {date} ({channel}).', en: 'You accepted this version on {date} ({channel}).' },
  'customer.legal.acceptedOther': { es: 'Aceptaste la versión {v} el {date}. Esta versión es distinta.', en: 'You accepted version {v} on {date}. This version is a different one.' },
  'customer.legal.notAccepted': { es: 'Todavía no has aceptado este documento.', en: 'You have not accepted this document yet.' },
  'customer.legal.accept': { es: 'Aceptar esta versión', en: 'Accept this version' },
  'customer.legal.channel.app': { es: 'en la app', en: 'in the app' },
  'customer.legal.channel.website': { es: 'en la web', en: 'on the website' },
  'customer.legal.channel.front_desk': { es: 'en recepción', en: 'at the front desk' },
  'customer.legal.channel.import': { es: 'registro anterior', en: 'earlier record' },
  'customer.legal.others': { es: 'Otros documentos:', en: 'Other documents:' },
  'customer.legal.print': { es: 'Imprimir o guardar en PDF', en: 'Print or save as PDF' },
  'customer.legal.liveNumbers': { es: 'Los números salen de la configuración del estudio', en: 'The numbers come from the studio settings' },
  'customer.legal.notFound': { es: 'Documento no encontrado', en: 'Document not found' },
  'customer.legal.notFound.body': { es: 'Puede que el enlace sea antiguo. Los documentos vigentes están en Más → Legal.', en: 'The link may be old. The documents in force are under More → Legal.' },
  'customer.legal.token.pending': { es: '(pendiente)', en: '(pending)' },
  'customer.legal.token.noShowFee': { es: ' y se cobra la tarifa de no-show de {amount}', en: ' and the {amount} no-show fee is charged' },
  'customer.media.pending': { es: 'arte pendiente', en: 'art pending' },
  'customer.media.brief': { es: 'Encargo: {brief}', en: 'Brief: {brief}' },
};
