import type { StringTable } from '../../i18n/types';

/** Every user-facing string of the customer app (C-xx, A-xx, E-xx). Spanish first; English always present. */
export const strings: StringTable = {
  // C-01 home
  'customer.home.greeting': { es: 'Hola, {name}', en: 'Hi, {name}' },
  'customer.home.next': { es: 'Tu próxima clase', en: 'Your next class' },
  'customer.home.next.empty': { es: 'No tienes clases reservadas.', en: 'You have no booked classes.' },
  'customer.home.next.cta': { es: 'Reserva tu primera clase', en: 'Book your first class' },
  'customer.home.today': { es: 'Hoy en el club', en: 'Today at the club' },
  'customer.home.today.empty': { es: 'Hoy descansamos.', en: 'We rest today.' },
  // C-01 practice block (0040): every label says what is counted; "racha" never stands alone as a headline (research §5.8).
  'customer.home.stats.title': { es: 'Tu práctica', en: 'Your practice' },
  'customer.home.stats.classes': { es: 'Clases tomadas este mes', en: 'Classes attended this month' },
  'customer.home.stats.upcoming.one': { es: '{n} reservada próxima', en: '{n} upcoming booked' },
  'customer.home.stats.upcoming.other': { es: '{n} reservadas próximas', en: '{n} upcoming booked' },
  'customer.home.stats.upcoming.none': { es: 'Sin reservas próximas', en: 'Nothing booked yet' },
  'customer.home.stats.streak': { es: 'Semanas seguidas', en: 'Weeks in a row' },
  'customer.home.stats.weeks.one': { es: 'semana', en: 'week' },
  'customer.home.stats.weeks.other': { es: 'semanas', en: 'weeks' },
  'customer.home.stats.best': { es: 'Mejor', en: 'Best' },
  'customer.home.stats.hint.alive': { es: 'Meta: {target} por semana', en: 'Goal: {target} a week' },
  'customer.home.stats.hint.atRisk.one': { es: 'Te falta {n} esta semana', en: '{n} to go this week' },
  'customer.home.stats.hint.atRisk.other': { es: 'Te faltan {n} esta semana', en: '{n} to go this week' },
  'customer.home.stats.hint.building': { es: 'Empieza una racha esta semana', en: 'Start a streak this week' },
  'customer.home.stats.hint.best.one': { es: 'Tu mejor racha: {n} semana', en: 'Your best run: {n} week' },
  'customer.home.stats.hint.best.other': { es: 'Tu mejor racha: {n} semanas', en: 'Your best run: {n} weeks' },
  'customer.home.stats.membership': { es: 'Membresía', en: 'Membership' },
  'customer.home.stats.unlimited': { es: 'Ilimitada', en: 'Unlimited' },
  'customer.home.stats.renews': { es: 'Renueva {date}', en: 'Renews {date}' },
  'customer.home.stats.paused': { es: 'En pausa', en: 'Paused' },
  'customer.home.stats.pausedUntil': { es: 'Hasta {date}', en: 'Until {date}' },
  'customer.home.stats.package': { es: 'Clases en tu paquete', en: 'Classes in your package' },
  'customer.home.stats.frozenUntil': { es: 'Congelado hasta {date}', en: 'Frozen until {date}' },
  'customer.home.stats.expires': { es: 'Vence {date}', en: 'Expires {date}' },
  'customer.home.stats.noPlan': { es: 'Sin plan activo', en: 'No active plan' },
  'customer.home.stats.week': { es: '{attended} de {target} esta semana', en: '{attended} of {target} this week' },
  'customer.home.stats.weekNoGoal.one': { es: '{n} clase esta semana', en: '{n} class this week' },
  'customer.home.stats.weekNoGoal.other': { es: '{n} clases esta semana', en: '{n} classes this week' },
  'customer.home.stats.more': { es: 'Ver tu práctica', en: 'See your practice' },
  'customer.home.goal.title': { es: '¿Cuántas veces por semana quieres practicar?', en: 'How many times a week do you want to practise?' },
  'customer.home.goal.hint': { es: 'Solo para tu seguimiento; puedes cambiarla cuando quieras.', en: 'Just for your own tracking; change it whenever you like.' },
  'customer.home.milestone': { es: '¡Clase número {n}!', en: 'Class number {n}!' },
  // C-27 Tu práctica (0040)
  'customer.practice.title': { es: 'Tu práctica', en: 'Your practice' },
  'customer.practice.sub': { es: 'Tus clases, tus semanas y tu meta.', en: 'Your classes, your weeks and your goal.' },
  'customer.practice.goal.perWeek': { es: 'por semana', en: 'a week' },
  'customer.practice.goal.none': { es: 'Sin meta por ahora', en: 'No goal for now' },
  'customer.practice.goal.suggested': { es: 'Sugerido', en: 'Suggested' },
  'customer.practice.goal.group': { es: 'Tu meta semanal', en: 'Your weekly goal' },
  'customer.practice.goal.saved': { es: 'Meta guardada: {n} por semana', en: 'Goal saved: {n} a week' },
  'customer.practice.goal.cleared': { es: 'Sin meta por ahora. Tus clases se siguen contando.', en: 'No goal for now. Your classes still count.' },
  'customer.practice.goal.title': { es: 'Tu meta semanal', en: 'Your weekly goal' },
  'customer.practice.goal.current': { es: 'Ahora: {n} por semana', en: 'Now: {n} a week' },
  'customer.practice.goal.currentNone': { es: 'Ahora: sin meta', en: 'Now: no goal' },
  'customer.practice.goal.suggestedLine': { es: 'Según tus últimas semanas te sugerimos {n} por semana.', en: 'Based on your recent weeks we suggest {n} a week.' },
  'customer.practice.privacy': { es: 'Solo tú y el equipo del estudio ven esto; nunca se compara con otras personas.', en: 'Only you and the studio team see this; it is never compared with anyone else.' },
  'customer.practice.week.initials': { es: 'L,M,X,J,V,S,D', en: 'M,T,W,T,F,S,S' },
  'customer.practice.week.title': { es: 'Esta semana', en: 'This week' },
  'customer.practice.week.noGoal': { es: 'Sin meta · elige una abajo', en: 'No goal · pick one below' },
  'customer.practice.week.met': { es: 'Meta de la semana cumplida', en: 'Weekly goal met' },
  'customer.practice.week.ring': { es: '{attended} de {target} clases esta semana', en: '{attended} of {target} classes this week' },
  'customer.practice.streak.title': { es: 'Semanas seguidas cumpliendo tu meta', en: 'Weeks in a row on your goal' },
  'customer.practice.streak.rule': { es: 'Una semana cuenta cuando llegas a tu meta. Si una semana no llegas, la primera de cada cuatro no rompe la racha.', en: 'A week counts when you reach your goal. If you fall short one week, the first miss in any four weeks does not break your run.' },
  'customer.practice.streak.pause': { es: 'Las semanas con tu paquete congelado no suman ni rompen.', en: 'Weeks with your package frozen neither add nor break.' },
  'customer.practice.streak.saved': { es: 'Semana de descanso usada: {date}', en: 'Rest week used: {date}' },
  'customer.practice.streak.grace': { es: 'Descanso disponible', en: 'Rest week available' },
  'customer.practice.streak.noGoal': { es: 'Elige una meta semanal abajo para contar semanas seguidas. Tus clases se cuentan igual.', en: 'Pick a weekly goal below to count weeks in a row. Your classes count either way.' },
  'customer.practice.month.title': { es: 'Este mes · {month}', en: 'This month · {month}' },
  'customer.practice.month.upcoming': { es: 'Reservadas próximas', en: 'Upcoming booked' },
  'customer.practice.month.minutes': { es: 'Minutos de práctica', en: 'Minutes practised' },
  'customer.practice.month.noShows': { es: 'Reservas sin asistir', en: 'Booked, not attended' },
  'customer.practice.month.lateCancels': { es: 'Cancelaciones tardías', en: 'Late cancellations' },
  'customer.practice.history.title': { es: 'Últimas {n} semanas', en: 'Last {n} weeks' },
  'customer.practice.history.goal': { es: 'meta {n}', en: 'goal {n}' },
  'customer.practice.history.rest': { es: 'descanso', en: 'rest week' },
  'customer.practice.history.paused': { es: 'pausa', en: 'paused' },
  'customer.practice.history.now': { es: 'esta semana', en: 'this week' },
  'customer.practice.milestones.title': { es: 'Logros', en: 'Milestones' },
  'customer.practice.milestones.reached': { es: 'Alcanzados', en: 'Reached' },
  'customer.practice.milestones.next': { es: 'Próximo', en: 'Next' },
  'customer.practice.milestones.remaining.one': { es: 'Falta {n}', en: '{n} to go' },
  'customer.practice.milestones.remaining.other': { es: 'Faltan {n}', en: '{n} to go' },
  'customer.practice.classes.one': { es: '{n} clase', en: '{n} class' },
  'customer.practice.classes.other': { es: '{n} clases', en: '{n} classes' },
  'customer.practice.milestones.first': { es: 'Primera clase: {date}', en: 'First class: {date}' },
  'customer.practice.milestones.total.one': { es: '{n} clase en total', en: '{n} class in total' },
  'customer.practice.milestones.total.other': { es: '{n} clases en total', en: '{n} classes in total' },
  'customer.practice.fav.title': { es: 'Lo que más practicas', en: 'What you practise most' },
  'customer.practice.fav.window': { es: 'Últimos 90 días', en: 'Last 90 days' },
  'customer.practice.fav.modality': { es: 'Tipo de clase favorito', en: 'Favourite class type' },
  'customer.practice.fav.teacher': { es: 'Profe con quien más practicas', en: 'Teacher you practise with most' },
  'customer.practice.fav.variety.one': { es: '{n} tipo de clase probado', en: '{n} class type tried' },
  'customer.practice.fav.variety.other': { es: '{n} tipos de clase probados', en: '{n} class types tried' },
  'customer.practice.fav.empty': { es: 'Aún no hay clases en los últimos 90 días.', en: 'No classes in the last 90 days yet.' },
  'customer.practice.fav.explore': { es: 'Explorar el horario', en: 'Explore the schedule' },
  'customer.practice.empty.title': { es: 'Tu práctica empieza con tu primera clase', en: 'Your practice starts with your first class' },
  'customer.practice.empty.body': { es: 'Cuando tomes clases, aquí verás tus semanas, tu meta y tus logros.', en: 'Once you take classes, your weeks, your goal and your milestones show here.' },
  'customer.practice.more.sub': { es: 'Semanas seguidas, meta y logros', en: 'Weeks in a row, goal and milestones' },
  'customer.home.membership.nudge': { es: 'Aún no tienes paquete. Empieza con una clase de prueba.', en: 'No package yet. Start with a trial class.' },
  'customer.home.membership.cta': { es: 'Ver planes', en: 'See plans' },
  'customer.home.membership.active': { es: 'Membresía activa · renueva {date}', en: 'Active membership · renews {date}' },
  'customer.home.quick.book': { es: 'Reservar', en: 'Book' },
  'customer.home.quick.schedule': { es: 'Horario', en: 'Schedule' },
  'customer.home.quick.plans': { es: 'Planes', en: 'Plans' },
  'customer.home.quick.invite': { es: 'Invitar', en: 'Invite' },
  'customer.home.announcement': { es: 'Aviso del estudio', en: 'Studio announcement' },
  'customer.home.announcement.body': { es: 'Este sábado la clase de las 10:00 será al aire libre. Trae tu mat.', en: 'This Saturday the 10:00 class is outdoors. Bring your mat.' },
  'customer.home.view': { es: 'Ver', en: 'View' },
  'customer.home.booked': { es: 'Reservada', en: 'Booked' },
  'customer.book.ok': { es: 'Reserva confirmada', en: 'Booking confirmed' },
  'customer.book.oneADay': { es: 'Solo una clase por persona al día.', en: 'Only one class per person per day.' },
  'customer.state.demo': { es: 'Ruta de demostración del estado {code}. En el flujo real este bloque aparece dentro de la página correspondiente.', en: 'Demo route for state {code}. In the real flow this block renders inside the relevant page.' },

  // C-02 schedule
  'customer.schedule.title': { es: 'Horario', en: 'Schedule' },
  'customer.schedule.sub': { es: 'Solo en el estudio. Una clase por persona al día.', en: 'In-studio only. One class per person per day.' },
  'customer.schedule.view': { es: 'Vista', en: 'View' },
  'customer.schedule.view.today': { es: 'Día', en: 'Day' },
  'customer.schedule.view.week': { es: 'Semana', en: 'Week' },
  'customer.schedule.filters': { es: 'Filtros', en: 'Filters' },
  'customer.schedule.filter.time': { es: 'Momento del día', en: 'Time of day' },
  'customer.schedule.filter.time.all': { es: 'Todo el día', en: 'All day' },
  'customer.schedule.filter.time.morning': { es: 'Mañana', en: 'Morning' },
  'customer.schedule.filter.time.evening': { es: 'Tarde', en: 'Evening' },
  'customer.schedule.filter.modality': { es: 'Clase', en: 'Class' },
  'customer.schedule.filter.teacher': { es: 'Profesor/a', en: 'Teacher' },
  'customer.schedule.clearFilters': { es: 'Quitar filtros', en: 'Clear filters' },
  'customer.schedule.apply': { es: 'Aplicar', en: 'Apply' },
  'customer.schedule.empty': { es: 'Ninguna clase coincide', en: 'No classes match' },
  'customer.schedule.empty.body': { es: 'Prueba otro día o mira la semana completa.', en: 'Try another day or look at the whole week.' },
  'customer.schedule.empty.filters': { es: 'Con estos filtros no hay clases este día.', en: 'No classes match these filters on this day.' },
  'customer.schedule.closed': { es: 'Domingo cerrado', en: 'Closed on Sunday' },
  'customer.schedule.closedShort': { es: 'Cerrado', en: 'Closed' },
  'customer.schedule.pastDay': { es: 'Clases pasadas: solo lectura.', en: 'Past classes: read-only.' },
  'customer.schedule.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'customer.schedule.done': { es: 'Terminada', en: 'Done' },
  'customer.schedule.legend': { es: 'Clases', en: 'Classes' },

  // C-03 class detail
  'customer.class.notFound': { es: 'Clase no encontrada', en: 'Class not found' },
  'customer.class.notFound.body': { es: 'Puede que la clase haya cambiado de fecha o ya no exista.', en: 'The class may have moved or no longer exist.' },
  'customer.class.backToSchedule': { es: 'Volver al horario', en: 'Back to schedule' },
  'customer.class.heroPlaceholder': { es: 'Foto de la clase · 16:9 (pendiente)', en: 'Class photo · 16:9 (pending)' },
  'customer.class.allLevels': { es: 'Todos los niveles', en: 'All levels' },
  'customer.class.capacityNote': { es: '{mats} mats en sala', en: '{mats} mats in the room' },
  'customer.class.about': { es: 'Sobre la clase', en: 'About the class' },
  'customer.class.intensity': { es: 'Intensidad', en: 'Intensity' },
  'customer.class.heated': { es: 'Sala caliente', en: 'Heated room' },
  'customer.class.teacher': { es: 'Profesor/a', en: 'Teacher' },
  'customer.class.prep': { es: 'Prepárate', en: 'Prepare' },
  'customer.class.prep.arrive': { es: 'Llega 10 minutos antes; la sala cierra al empezar.', en: 'Arrive 10 minutes early; the room closes at start time.' },
  'customer.class.prep.hot': { es: 'Sala caliente: toalla grande y ropa ligera.', en: 'Hot room: large towel and light clothing.' },
  'customer.class.prep.mat': { es: 'Nosotros ponemos el mat y todos los implementos.', en: 'We provide the mat and all the props.' },
  'customer.class.prep.water': { es: 'Si quieres, trae una toalla pequeña y tu botella; después de clase está la zona de hidratación.', en: 'If you like, bring a small towel and your bottle; the hydration zone is there after class.' },
  'customer.class.rulesLink': { es: 'Reglas del club', en: 'Club rules' },
  'customer.class.past': { es: 'Clase terminada', en: 'Class finished' },
  'customer.class.viewBooking': { es: 'Ver mi reserva', en: 'View my booking' },
  'customer.class.joinWaitlist': { es: 'Unirme a la lista de espera', en: 'Join the waitlist' },
  'customer.class.viewWaitlist': { es: 'Ver mi lista de espera', en: 'View my waitlist' },
  'customer.class.seeOther': { es: 'Ver la otra clase', en: 'See the other class' },
  'customer.class.bookAndPay': { es: 'Reservar y pagar', en: 'Book and pay' },
  'customer.class.bookTrial': { es: 'Reservar mi clase de prueba', en: 'Book my trial class' },
  'customer.class.share': { es: 'Compartir', en: 'Share' },
  'customer.class.shared': { es: 'Compartido', en: 'Shared' },
  'customer.class.linkCopied': { es: 'Enlace copiado', en: 'Link copied' },
  'customer.class.fullNote': { es: 'Clase llena. Si se libera un cupo, tendrás {min} minutos para reclamarlo.', en: 'Class full. If a spot opens you will have {min} minutes to claim it.' },

  // C-04 checkout
  'customer.checkout.title': { es: 'Reservar', en: 'Reserve' },
  'customer.checkout.claiming': { es: 'Reclamando tu cupo de la lista de espera', en: 'Claiming your waitlist spot' },
  'customer.checkout.payWith': { es: 'Pagar con', en: 'Pay with' },
  'customer.checkout.package': { es: 'Una clase de tu paquete', en: 'A class from your package' },
  'customer.checkout.package.sub': { es: '{n} clases disponibles', en: '{n} classes available' },
  'customer.checkout.trialNote': { es: 'La clase de prueba es una por persona, verificada por teléfono o documento.', en: 'The trial class is one per person, verified by phone or document.' },
  'customer.checkout.packNote': { es: 'Usarás 1 clase hoy y te quedarán {n} para usar en {months} meses.', en: 'You use 1 class today and keep {n} to use within {months} months.' },
  'customer.checkout.method': { es: 'Método de pago', en: 'Payment method' },
  'customer.checkout.manageMethods': { es: 'Gestionar', en: 'Manage' },
  'customer.checkout.simulateDecline': { es: 'Simular rechazo (dev)', en: 'Simulate decline (dev)' },
  'customer.checkout.noCharge': { es: 'Sin cargo', en: 'No charge' },
  'customer.checkout.noCharge.package': { es: 'Se descuenta 1 clase de tu paquete al confirmar; vuelve si cancelas más de {h} h antes.', en: '1 class comes off your package on confirm; it returns if you cancel more than {h} h before.' },
  'customer.checkout.subtotal': { es: 'Subtotal', en: 'Subtotal' },
  'customer.checkout.iva': { es: 'IVA', en: 'IVA' },
  'customer.checkout.total': { es: 'Total', en: 'Total' },
  'customer.checkout.receiptNote': { es: 'Precios con IVA incluido. Recibo electrónico (DIAN) por email y WhatsApp al aprobar.', en: 'Prices include IVA. Electronic receipt (DIAN) by email and WhatsApp on approval.' },
  'customer.checkout.confirm': { es: 'Confirmar reserva', en: 'Confirm booking' },
  'customer.checkout.payWompi': { es: 'Pagar {amount} con Wompi', en: 'Pay {amount} with Wompi' },
  'customer.checkout.confirmManual': { es: 'Reservar y pagar {amount} en recepción', en: 'Book and pay {amount} at the desk' },
  'customer.checkout.policy': { es: 'Cancelación gratis hasta {h} h antes.', en: 'Free cancellation up to {h} h before.' },
  'customer.checkout.race.title': { es: 'La clase se llenó mientras reservabas', en: 'The class filled while you were booking' },
  'customer.checkout.race.body': { es: 'No se cobró nada. Puedes unirte a la lista de espera.', en: 'Nothing was charged. You can join the waitlist.' },
  'customer.checkout.unavailable': { es: 'Esta clase ya no está disponible.', en: 'This class is no longer available.' },
  'customer.checkout.pending.title': { es: 'Pendiente de pago en recepción', en: 'Pending payment at the desk' },
  'customer.checkout.pending.body': { es: 'Tu cupo queda retenido 60 minutos. Paga en recepción para confirmarlo.', en: 'Your spot is held for 60 minutes. Pay at the front desk to confirm it.' },
  'customer.checkout.success.body': { es: 'Te enviamos la confirmación por WhatsApp y email. Llega 10 minutos antes; la clase dura {min} min.', en: 'We sent the confirmation by WhatsApp and email. Arrive 10 minutes early; the class lasts {min} min.' },

  // E-02 declined
  'customer.declined.title': { es: 'El pago no pasó', en: 'The payment did not go through' },
  'customer.declined.body': { es: 'No se cobró nada ({amount}). Tu cupo sigue reservado unos minutos.', en: 'Nothing was charged ({amount}). Your spot is still held for a few minutes.' },
  'customer.declined.gateway': { es: 'Motivo del banco', en: 'Bank reason' },
  'customer.declined.hold': { es: 'retenido', en: 'held' },
  'customer.declined.hold.title': { es: 'Cupo retenido', en: 'Spot held' },
  'customer.declined.hold.body': { es: 'Guardamos tu lugar {min} minutos desde el primer intento.', en: 'We keep your place for {min} minutes from the first attempt.' },
  'customer.declined.retry': { es: 'Intentar con otro método', en: 'Try another method' },
  'customer.declined.threeStrikes': { es: 'Tres intentos rechazados: te sugerimos PSE, el QR de Wompi o pagar en recepción.', en: 'Three declines: we suggest PSE, the Wompi QR or paying at the front desk.' },
  'customer.declined.release': { es: 'Liberar el cupo', en: 'Release the spot' },

  // E-03 cancelled by studio
  'customer.cancelled.title': { es: 'El estudio canceló esta clase', en: 'The studio cancelled this class' },
  'customer.cancelled.body': { es: 'Lo sentimos.', en: 'We are sorry.' },
  'customer.cancelled.reason': { es: 'Motivo: {reason}.', en: 'Reason: {reason}.' },
  'customer.cancelled.refund.credit': { es: 'La clase volvió a tu paquete', en: 'The class went back to your package' },
  'customer.cancelled.refund.none': { es: 'No se descontó nada', en: 'Nothing was deducted' },
  'customer.cancelled.refund.body': { es: 'Ya está hecho; no tienes que hacer nada. No cuenta contra tu límite de cancelaciones.', en: 'Already done; nothing to do on your side. It does not count against your cancellation allowance.' },
  'customer.cancelled.alternatives': { es: 'Alternativas para el mismo día', en: 'Same-day alternatives' },
  'customer.cancelled.noAlt': { es: 'Hoy no queda otra clase con cupo', en: 'No other class with spots today' },
  'customer.cancelled.noAlt.body': { es: 'Mira el resto de la semana o únete a la lista de espera de la próxima.', en: 'Look at the rest of the week or join the next one’s waitlist.' },
  'customer.cancelled.cta': { es: 'Reservar una alternativa', en: 'Book a replacement' },
  'customer.cancelled.channels': { es: 'Te avisamos también por WhatsApp y email.', en: 'We also told you by WhatsApp and email.' },

  // E-01 empty home
  'customer.empty.title': { es: 'Tu primera clase te espera', en: 'Your first class is waiting' },
  'customer.empty.body': { es: 'Aún no tienes reservas ni historial en {name}. Mira qué hay hoy en el club y elige.', en: 'No bookings or history at {name} yet. See what is on today and pick one.' },
  'customer.empty.cta': { es: 'Ver clases de hoy', en: 'See today’s classes' },
  'customer.empty.tour': { es: 'Tour del estudio', en: 'Studio tour' },
  'customer.empty.stats': { es: 'Tus estadísticas', en: 'Your stats' },
  'customer.empty.stats.body': { es: 'Después de tu primera clase verás aquí las clases tomadas este mes, tus semanas seguidas cumpliendo tu meta y las clases que te quedan en tu plan.', en: 'After your first class you will see the classes you attended this month, your weeks in a row on your goal and the classes left on your plan here.' },
  'customer.empty.trial': { es: 'Clase de prueba', en: 'Trial class' },

  // C-05 payment methods
  'customer.pay.title': { es: 'Métodos de pago', en: 'Payment methods' },
  'customer.pay.wompi.title': { es: 'Pago con Wompi', en: 'Pay with Wompi' },
  'customer.pay.wompi.badge': { es: 'Integración pendiente', en: 'Integration pending' },
  'customer.pay.wompi.body': { es: 'En la web pagas con tarjeta, PSE o el código QR de Wompi. Ningún dato de tarjeta toca nuestros servidores.', en: 'On the web you pay by card, PSE or the Wompi QR code. No card data touches our servers.' },
  'customer.pay.wompi.cta': { es: 'Probar pago de {amount}', en: 'Test a {amount} payment' },
  'customer.pay.wompi.ok': { es: 'Aprobado (simulado) · ref. {ref}', en: 'Approved (simulated) · ref. {ref}' },
  'customer.pay.wompi.seam': { es: 'Demo: la aprobación es simulada en src/modules/customer/payments.ts.', en: 'Demo: approval is simulated in src/modules/customer/payments.ts.' },
  'customer.pay.saved': { es: 'Guardados', en: 'Saved' },
  'customer.pay.saved.empty': { es: 'Añade un método de pago', en: 'Add a payment method' },
  'customer.pay.saved.empty.body': { es: 'Se guarda tokenizado la primera vez que pagas.', en: 'It is saved tokenised the first time you pay.' },
  'customer.pay.saved.tokenised': { es: 'Tokenizado', en: 'Tokenised' },
  'customer.pay.qr.each': { es: 'Se paga en cada compra', en: 'Paid on each purchase' },
  'customer.pay.electronic': { es: 'Electrónicos', en: 'Electronic' },
  'customer.pay.manual': { es: 'Manual', en: 'Manual' },
  'customer.pay.manual.desk': { es: 'Recepción', en: 'Front desk' },
  'customer.pay.comply.title': { es: 'Tus datos', en: 'Your data' },
  'customer.pay.comply.body': { es: 'Tokenización en la pasarela (PCI DSS SAQ-A), consentimiento Habeas Data (Ley 1581) antes de guardar un método, factura electrónica DIAN con NIT e IVA.', en: 'Gateway tokenisation (PCI DSS SAQ-A), Habeas Data consent (Ley 1581) before storing a method, DIAN electronic invoice with NIT and IVA.' },
  'customer.pay.method.card': { es: 'Tarjeta', en: 'Card' },
  'customer.pay.method.pse': { es: 'PSE', en: 'PSE' },
  'customer.pay.method.qr': { es: 'QR de Wompi', en: 'Wompi QR' },
  'customer.pay.method.cash': { es: 'Efectivo', en: 'Cash' },
  'customer.pay.method.transfer': { es: 'Transferencia', en: 'Transfer' },
  'customer.pay.method.gift_card': { es: 'Tarjeta de regalo', en: 'Gift card' },

  // C-06 plans
  'customer.plans.title': { es: 'Paquetes', en: 'Packages' },
  'customer.plans.sub': { es: '12 clases para usar en 3 meses. Sin permanencia, sin créditos.', en: '12 classes to use within 3 months. No lock-in, no credits.' },
  'customer.plans.current': { es: 'Tu paquete: {plan}', en: 'Your package: {plan}' },
  'customer.plans.left': { es: 'Te quedan {n} clases.', en: 'You have {n} classes left.' },
  'customer.plans.manage': { es: 'Ver mis clases', en: 'See my classes' },
  'customer.plans.starts': { es: 'Compra', en: 'Bought' },
  'customer.plans.ends': { es: 'Vence', en: 'Expires' },
  'customer.plans.cta': { es: 'Comprar paquete', en: 'Buy the package' },
  'customer.plans.note': { es: 'Sala de {mats} mats; reserva con tiempo. Tus clases y el congelamiento están en Más → Mis clases.', en: '{mats}-mat room; book ahead. Your classes and the freeze are under More → My classes.' },
  'customer.plans.skip': { es: '¿Prefieres pagar por clase?', en: 'Prefer to pay per class?' },
  'customer.plans.skip.cta': { es: 'Prueba o clase individual', en: 'Trial or individual class' },
  'customer.plans.specials.cta': { es: 'Escríbenos', en: 'Write to us' },
  'customer.plans.specials.wa': { es: 'Hola HOY, quiero preguntar por un especial: un evento privado o una sesión de grupo.', en: 'Hi HOY, I would like to ask about a special: a private event or a group session.' },
  'customer.plans.confirm.title': { es: 'Confirmar paquete', en: 'Confirm package' },
  'customer.plans.confirm.note': { es: 'Tus 12 clases vencen en {months} meses desde hoy. Puedes congelarlo una vez. No es reembolsable.', en: 'Your 12 classes expire {months} months from today. You can freeze it once. Not refundable.' },
  'customer.plans.done.title': { es: 'Paquete activo', en: 'Package active' },
  'customer.plans.done.body': { es: 'Tienes {n} clases para reservar. Recibo enviado por email y WhatsApp.', en: 'You have {n} classes to book. Receipt sent by email and WhatsApp.' },
  'customer.plans.benefit.classes': { es: '{n} clases, cualquier clase del horario', en: '{n} classes, any class on the schedule' },
  'customer.plans.benefit.validity': { es: 'Vence a los {months} meses de la compra', en: 'Expires {months} months after purchase' },
  'customer.plans.benefit.freeze': { es: 'Congélalo una vez, hasta {days} días', en: 'Freeze it once, up to {days} days' },
  'customer.plans.benefit.noRefund': { es: 'No es reembolsable', en: 'Not refundable' },
  'customer.plans.benefit.affiliates': { es: 'Precio para afiliados del Santa María Tennis Club; recepción verifica tu afiliación.', en: 'Price for Santa María Tennis Club members; the front desk checks your membership.' },
  'customer.plans.private.title': { es: 'Clases privadas', en: 'Private classes' },
  'customer.plans.gift': { es: '¿Quieres regalar una clase o un paquete?', en: 'Want to give a class or a package?' },
  'customer.plans.gift.cta': { es: 'Tarjetas de regalo', en: 'Gift cards' },

  // C-07 passes
  'customer.passes.title': { es: 'Clase de prueba o individual', en: 'Trial or individual class' },
  'customer.passes.sub': { es: 'Paga una clase a la vez.', en: 'Pay one class at a time.' },
  'customer.passes.eyebrow': { es: 'Para empezar', en: 'To start' },
  'customer.passes.intro': { es: 'Dos opciones de una sola vez. Cada botón lleva al mismo checkout.', en: 'Two one-time options. Every button enters the same checkout.' },
  'customer.passes.cta': { es: 'Elegir clase con este pase', en: 'Pick a class with this pass' },
  'customer.passes.bookWith': { es: 'Reservar con este pase', en: 'Book with this pass' },
  'customer.passes.trialUsed': { es: 'Ya usaste tu clase de prueba. Sigue con una clase individual o el paquete de 12.', en: 'You already used your trial class. Continue with an individual class or the 12-class package.' },
  'customer.passes.footer': { es: '¿Vienes seguido?', en: 'Coming often?' },
  'customer.passes.footer.link': { es: 'Mira el paquete de 12 clases', en: 'See the 12-class package' },
  'customer.passes.package': { es: 'Tienes {n} clases en tu paquete', en: 'You have {n} classes in your package' },
  'customer.passes.package.body': { es: 'No necesitas pagar otra clase: resérvala con tu paquete.', en: 'No need to pay for another class: book it with your package.' },

  // C-07b Mis clases (0051)
  'customer.classes.title': { es: 'Mis clases', en: 'My classes' },
  'customer.classes.sub': { es: 'Tu paquete, las clases que te quedan y cada movimiento.', en: 'Your package, the classes you have left and every movement.' },
  'customer.classes.package': { es: 'Paquete de 12 clases', en: '12-class package' },
  'customer.classes.package.none': { es: 'Aún no tienes paquete', en: 'No package yet' },
  'customer.classes.package.none.body': { es: 'El paquete de 12 clases dura {months} meses y lo puedes congelar una vez.', en: 'The 12-class package lasts {months} months and you can freeze it once.' },
  'customer.classes.balance': { es: 'Clases restantes', en: 'Classes left' },
  'customer.classes.expires': { es: 'Vencen el', en: 'Expire on' },
  'customer.classes.expiringSoon': { es: 'Vence pronto', en: 'Expiring soon' },
  'customer.classes.expiringSoon.body': { es: 'Tus clases vencen el {date}. Resérvalas antes.', en: 'Your classes expire on {date}. Book them before then.' },
  'customer.classes.frozen.title': { es: 'Paquete congelado', en: 'Package frozen' },
  'customer.classes.frozen.body': { es: 'Congelado hasta el {date}. Mientras tanto no puedes reservar con él; puedes reanudarlo antes.', en: 'Frozen until {date}. You cannot book with it meanwhile; you can resume it earlier.' },
  'customer.classes.frozen.badge': { es: 'Congelado', en: 'Frozen' },
  'customer.classes.resume': { es: 'Reanudar', en: 'Resume' },
  'customer.classes.resumed': { es: 'Paquete reanudado. Los días que no usaste vuelven a la fecha de vencimiento.', en: 'Package resumed. The days you did not use come back off the expiry date.' },
  'customer.classes.freeze': { es: 'Congelar el paquete', en: 'Freeze the package' },
  'customer.classes.freeze.sub': { es: 'Una vez por paquete, hasta {days} días', en: 'Once per package, up to {days} days' },
  'customer.classes.freeze.used': { es: 'Ya usaste el congelamiento de este paquete', en: 'You already used this package’s freeze' },
  'customer.classes.freeze.body': { es: 'Puedes congelar tu paquete una sola vez, hasta {days} días. La fecha de vencimiento se corre los mismos días.', en: 'You can freeze your package once, for up to {days} days. The expiry date moves by the same days.' },
  'customer.classes.freeze.days': { es: 'Duración', en: 'Duration' },
  'customer.classes.freeze.option': { es: '{n} días', en: '{n} days' },
  'customer.classes.freeze.preview': { es: 'Congelado hasta el {until}. Nuevo vencimiento: {expires}.', en: 'Frozen until {until}. New expiry: {expires}.' },
  'customer.classes.freeze.cta': { es: 'Congelar', en: 'Freeze' },
  'customer.classes.freeze.ok': { es: 'Paquete congelado hasta el {date}.', en: 'Package frozen until {date}.' },
  'customer.classes.topUp': { es: 'Comprar clases', en: 'Buy classes' },
  'customer.classes.topUp.note': { es: 'Precios con IVA incluido. Las clases no son reembolsables.', en: 'Prices include IVA. Classes are not refundable.' },
  'customer.classes.ledger': { es: 'Movimientos', en: 'Movements' },
  'customer.classes.ledger.empty': { es: 'Aún no hay movimientos', en: 'No movements yet' },
  'customer.classes.reason.purchase': { es: 'Compra', en: 'Purchase' },
  'customer.classes.reason.booking': { es: 'Reserva', en: 'Booking' },
  'customer.classes.reason.refund': { es: 'Devolución', en: 'Refund' },
  'customer.classes.reason.expiry': { es: 'Vencimiento', en: 'Expiry' },
  'customer.classes.reason.gift': { es: 'Regalo', en: 'Gift' },
  'customer.classes.reason.comp': { es: 'Cortesía', en: 'Comp' },
  'customer.classes.reason.cancel_return': { es: 'Cancelación (devuelta)', en: 'Cancellation (returned)' },
  'customer.classes.reason.reschedule': { es: 'Cambio de clase', en: 'Class change' },
  'customer.classes.frozenRange': { es: 'congelado {from} – {to}', en: 'frozen {from} – {to}' },
  'customer.classes.expired': { es: 'Vencido', en: 'Expired' },
  'customer.classes.until': { es: 'hasta {date}', en: 'until {date}' },
  'customer.classes.note': { es: 'Cancelar más de {h} h antes devuelve la clase a tu paquete. Dentro de ese plazo, o si no llegas, la clase se cuenta como tomada.', en: 'Cancelling more than {h} h before puts the class back in your package. Inside that window, or if you do not show up, the class counts as taken.' },
  'customer.classes.buy.title': { es: 'Comprar clases', en: 'Buy classes' },
  'customer.classes.done.title': { es: 'Clases añadidas', en: 'Classes added' },
  'customer.classes.done.body': { es: '+{n} en tu paquete. Recibo enviado.', en: '+{n} in your package. Receipt sent.' },

  // C-08 booked
  'customer.booked.notFound': { es: 'Reserva no encontrada', en: 'Booking not found' },
  'customer.booked.notFound.body': { es: 'Revisa tu historial o el horario.', en: 'Check your history or the schedule.' },
  'customer.booked.startsIn': { es: 'empieza en', en: 'starts in' },
  'customer.booked.checkin': { es: 'check-in en recepción', en: 'check in at reception' },
  'customer.booked.checkin.body': { es: 'El check-in se hace solo en recepción, al llegar. Llega 10 minutos antes.', en: 'Check-in happens only at the front desk, when you arrive. Arrive 10 minutes early.' },
  'customer.booked.inProgress': { es: 'La clase está en curso', en: 'The class is in progress' },
  'customer.booked.change': { es: 'Cambiar o cancelar', en: 'Change or cancel' },
  'customer.booked.addToCalendar': { es: 'Añadir al calendario', en: 'Add to calendar' },
  'customer.booked.shareText': { es: 'Voy a {title} el {when} en {name}. ¿Vienes?', en: 'I am going to {title} on {when} at {name}. Coming?' },
  'customer.booked.policy.outside': { es: 'Cancela o cambia gratis hasta las {time} ({h} h antes)', en: 'Cancel or change free until {time} ({h} h before)' },
  'customer.booked.policy.inside': { es: 'Dentro de la ventana de {h} h: cancelar usa la clase', en: 'Inside the {h} h window: cancelling uses the class' },
  'customer.booked.paidWith': { es: 'pagada con {with}', en: 'paid with {with}' },
  'customer.booked.rate': { es: 'Calificar la clase', en: 'Rate the class' },
  'customer.booked.cancelled': { es: 'Reserva cancelada', en: 'Booking cancelled' },
  'customer.booked.cancelled.body': { es: 'Cancelaste fuera de la ventana; nada se descontó.', en: 'You cancelled outside the window; nothing was deducted.' },
  'customer.booked.lateCancelled': { es: 'Cancelación tardía', en: 'Late cancellation' },
  'customer.booked.lateCancelled.body': { es: 'Cancelaste dentro de la ventana; la clase se usó.', en: 'You cancelled inside the window; the class was used.' },
  'customer.paidWith.membership': { es: 'membresía', en: 'membership' },
  'customer.paidWith.package': { es: 'paquete', en: 'package' },
  'customer.paidWith.single': { es: 'clase individual', en: 'individual class' },
  'customer.paidWith.trial': { es: 'clase de prueba', en: 'trial class' },
  'customer.paidWith.guest': { es: 'invitado', en: 'guest' },
  'customer.paidWith.comp': { es: 'cortesía', en: 'comp' },

  // C-08b change sheet
  'customer.change.title': { es: 'Cambiar o cancelar', en: 'Change or cancel' },
  'customer.change.move.title': { es: 'Mover la reserva', en: 'Move the booking' },
  'customer.change.cancel.title': { es: 'Cancelar la reserva', en: 'Cancel the booking' },
  'customer.change.outside': { es: 'Sin costo hasta las {time}.', en: 'Free until {time}.' },
  'customer.change.inside.title': { es: 'Estás dentro de la ventana de {h} h', en: 'You are inside the {h} h window' },
  'customer.change.inside.body': { es: 'Mover sigue siendo gratis si hay cupo; cancelar usa la clase.', en: 'Moving is still free if there is a spot; cancelling uses the class.' },
  'customer.change.move': { es: 'Mover a otra clase de hoy', en: 'Move to another class today' },
  'customer.change.move.sub': { es: 'Conservas tu clase y tu hábito', en: 'Keeps your class and your habit' },
  'customer.change.drop': { es: 'Cancelar', en: 'Cancel' },
  'customer.change.drop.sub': { es: 'La clase vuelve a tu paquete', en: 'The class goes back to your package' },
  'customer.change.drop.sub.inside': { es: 'La clase se usa', en: 'The class is used' },
  'customer.change.pick': { es: 'Elige una alternativa', en: 'Pick a replacement' },
  'customer.change.noAlt': { es: 'Hoy no hay otra clase con cupo', en: 'No other class with spots today' },
  'customer.change.noAlt.body': { es: 'Mira el resto de la semana.', en: 'Look at the rest of the week.' },
  'customer.change.move.note': { es: 'Mover = cancelar y reservar en una sola transacción, con el mismo pago.', en: 'Move = cancel and rebook in one transaction, same entitlement.' },
  'customer.change.cancel.confirm': { es: '¿Cancelar esta reserva? Tu clase vuelve de inmediato y el cupo pasa a la lista de espera.', en: 'Cancel this booking? Your class comes back immediately and the spot goes to the waitlist.' },
  'customer.change.cancel.confirm.inside': { es: 'Estás dentro de la ventana: si cancelas ahora, tu {with} se usa igual y no vuelve. ¿Seguro?', en: 'You are inside the window: cancelling now spends your {with} and it does not return. Sure?' },
  'customer.change.cancel.cta': { es: 'Sí, cancelar la reserva', en: 'Yes, cancel the booking' },
  'customer.change.keep': { es: 'Mantener mi reserva', en: 'Keep my booking' },
  'customer.change.cancelled.ok': { es: 'Reserva cancelada.', en: 'Booking cancelled.' },
  'customer.change.cancelled.creditBack': { es: 'Reserva cancelada · tu clase volvió a tu paquete.', en: 'Booking cancelled · your class is back in your package.' },
  'customer.change.cancelled.late': { es: 'Reserva cancelada dentro de la ventana · la clase se usó.', en: 'Booking cancelled inside the window · the class was used.' },

  // C-20 waitlist
  'customer.waitlist.full': { es: 'Clase llena · {n} en espera', en: 'Class full · {n} waiting' },
  'customer.waitlist.rule': { es: 'Si se libera un cupo te avisamos por WhatsApp y tienes {min} minutos para reclamarlo. Entrar y salir es gratis.', en: 'If a spot opens we message you on WhatsApp and you have {min} minutes to claim it. Joining and leaving are free.' },
  'customer.waitlist.joined': { es: 'Estás en la lista', en: 'You are on the list' },
  'customer.waitlist.position': { es: 'Posición {n} de {total}', en: 'Position {n} of {total}' },
  'customer.waitlist.released': { es: 'Se liberó un cupo', en: 'A spot opened' },
  'customer.waitlist.toClaim': { es: 'para reclamar', en: 'to claim' },
  'customer.waitlist.claim': { es: 'Reclamar mi cupo', en: 'Claim my spot' },
  'customer.waitlist.claimPay': { es: 'Reclamar y pagar', en: 'Claim and pay' },
  'customer.waitlist.expired': { es: 'El cupo pasó a la siguiente persona', en: 'The spot passed to the next person' },
  'customer.waitlist.expired.body': { es: 'La ventana de reclamo terminó. Puedes volver a la lista.', en: 'The claim window ended. You can rejoin the list.' },
  'customer.waitlist.rejoin': { es: 'Volver a la lista', en: 'Rejoin' },
  'customer.waitlist.spotsOpen': { es: 'Hay {n} cupos libres', en: '{n} spots are open' },
  'customer.waitlist.started': { es: 'La clase ya empezó', en: 'The class already started' },
  'customer.waitlist.started.body': { es: 'La lista de espera se cerró.', en: 'The waitlist is closed.' },
  'customer.waitlist.autoClaim': { es: 'Reclamar automáticamente', en: 'Auto-claim' },
  'customer.waitlist.autoClaim.body': { es: 'Usa una clase de tu paquete en el momento en que se libere el cupo.', en: 'Uses a class from your package the moment the spot is offered.' },
  'customer.waitlist.leave': { es: 'Salir de la lista', en: 'Leave the waitlist' },
  'customer.waitlist.leave.sub': { es: 'Gratis, sin cargos', en: 'Free, no charges' },
  'customer.waitlist.policy': { es: 'La promoción es estricta por posición. Recepción puede ajustar con motivo registrado. Ventana de {min} min.', en: 'Promotion is strictly by position. The front desk can override with a logged reason. {min}-minute window.' },
  'customer.waitlist.devRelease': { es: 'Simular cupo liberado (dev)', en: 'Simulate released spot (dev)' },

  // C-10 rate
  'customer.rate.title': { es: 'Califica tu clase', en: 'Rate your class' },
  'customer.rate.prompt': { es: '¿Cómo estuvo?', en: 'How was it?' },
  'customer.rate.sub': { es: 'Cinco segundos. Puedes saltarlo.', en: 'Five seconds. You can skip it.' },
  'customer.rate.star.1': { es: 'Mal', en: 'Poor' },
  'customer.rate.star.2': { es: 'Regular', en: 'Meh' },
  'customer.rate.star.3': { es: 'Bien', en: 'Fine' },
  'customer.rate.star.4': { es: 'Muy bien', en: 'Very good' },
  'customer.rate.star.5': { es: 'Excelente', en: 'Excellent' },
  'customer.rate.good': { es: 'Lo que estuvo bien', en: 'What was good' },
  'customer.rate.fix': { es: 'Lo que mejoraría', en: 'What could improve' },
  'customer.rate.tag.music': { es: 'Música', en: 'Music' },
  'customer.rate.tag.heat': { es: 'Temperatura', en: 'Heat' },
  'customer.rate.tag.pace': { es: 'Ritmo', en: 'Pace' },
  'customer.rate.tag.clarity': { es: 'Claridad', en: 'Clarity' },
  'customer.rate.tag.crowded': { es: 'Sala llena', en: 'Crowded' },
  'customer.rate.tag.late': { es: 'Empezó tarde', en: 'Started late' },
  'customer.rate.tag.tooHard': { es: 'Muy exigente', en: 'Too hard' },
  'customer.rate.tag.tooEasy': { es: 'Muy suave', en: 'Too easy' },
  'customer.rate.note': { es: 'Algo más (opcional)', en: 'Anything else (optional)' },
  'customer.rate.anonymous': { es: 'Enviar como anónimo', en: 'Send anonymously' },
  'customer.rate.submit': { es: 'Enviar', en: 'Send' },
  'customer.rate.skip': { es: 'Saltar', en: 'Skip' },
  'customer.rate.privacy': { es: 'Los profesores ven promedios anónimos. Menos de 3 estrellas abre un seguimiento con coordinación.', en: 'Teachers see anonymous aggregates. Under 3 stars opens a follow-up with the coordinator.' },
  'customer.rate.thanks': { es: 'Gracias', en: 'Thank you' },
  'customer.rate.thanks.body': { es: 'Tu opinión ya está con el equipo.', en: 'Your feedback is with the team.' },
  'customer.rate.public': { es: 'Dejar una reseña pública', en: 'Leave a public review' },

  // C-11 history
  'customer.history.title': { es: 'Historial', en: 'History' },
  'customer.history.sub': { es: 'Clases y pagos, con recibos.', en: 'Classes and payments, with receipts.' },
  'customer.history.export': { es: 'Exportar', en: 'Export' },
  'customer.history.classes': { es: 'Clases', en: 'Classes' },
  'customer.history.payments': { es: 'Pagos', en: 'Payments' },
  'customer.history.empty': { es: 'Tu primera clase te espera', en: 'Your first class is waiting' },
  'customer.history.empty.body': { es: 'Aquí aparecerán tus clases pasadas, incluidas las canceladas.', en: 'Your past classes appear here, cancelled ones included.' },
  'customer.history.payments.empty': { es: 'Aún no hay pagos', en: 'No payments yet' },
  'customer.history.otherCharge': { es: 'Otro cargo', en: 'Other charge' },
  'customer.history.note': { es: 'Canceladas y no asistidas se marcan, no se ocultan. Facturas electrónicas DIAN cuando aplique.', en: 'Cancelled and no-show classes are marked, not hidden. DIAN electronic invoices where applicable.' },
  'customer.history.receipt': { es: 'Recibo', en: 'Receipt' },
  'customer.history.receipt.number': { es: 'Número', en: 'Number' },
  'customer.history.receipt.date': { es: 'Fecha', en: 'Date' },
  'customer.history.receipt.concept': { es: 'Concepto', en: 'Item' },
  'customer.history.receipt.method': { es: 'Método', en: 'Method' },
  'customer.history.receipt.dian': { es: 'Factura electrónica DIAN con NIT e IVA cuando el estudio la emita; PDF próximamente.', en: 'DIAN electronic invoice with NIT and IVA when the studio issues it; PDF coming.' },
  'customer.history.status.booked': { es: 'Reservada', en: 'Booked' },
  'customer.history.status.checked_in': { es: 'Asistió', en: 'Attended' },
  'customer.history.status.cancelled': { es: 'Cancelada', en: 'Cancelled' },
  'customer.history.status.no_show': { es: 'No asistió', en: 'No-show' },
  'customer.history.status.late_cancel': { es: 'Cancelación tardía', en: 'Late cancel' },
  'customer.history.pay.pending': { es: 'Pendiente', en: 'Pending' },
  'customer.history.pay.approved': { es: 'Aprobado', en: 'Approved' },
  'customer.history.pay.declined': { es: 'Rechazado', en: 'Declined' },
  'customer.history.pay.refunded': { es: 'Reembolsado', en: 'Refunded' },
  'customer.history.pay.voided': { es: 'Anulado', en: 'Voided' },

  // C-13 rules
  'customer.rules.title': { es: 'Reglas del club', en: 'Club rules' },
  'customer.rules.sub': { es: 'Lo que mantiene la sala segura y agradable.', en: 'What keeps the room safe and pleasant.' },
  'customer.rules.read': { es: 'Leído', en: 'Read' },
  'customer.rules.required': { es: 'Importante', en: 'Important' },
  'customer.rules.checklist': { es: 'Lista', en: 'Checklist' },
  'customer.rules.gotIt': { es: 'Entendido', en: 'Got it' },
  'customer.rules.note': { es: 'Los videos son marcadores hasta que el estudio grabe el material.', en: 'Videos are placeholders until the studio supplies footage.' },

  // C-14 / C-15 FAQ
  'customer.faq.title': { es: 'Preguntas frecuentes', en: 'FAQ' },
  'customer.faq.page': { es: 'Página {n} de {total}', en: 'Page {n} of {total}' },
  'customer.faq.plansLink': { es: 'Ver planes', en: 'See plans' },
  'customer.faq.next': { es: 'Siguiente: el espacio, cómo llegar y contacto', en: 'Next: the space, getting here and contact' },
  'customer.faq.concierge': { es: '¿No está tu pregunta? Una persona te responde.', en: 'Question not here? A person answers.' },

  // C-16 invite
  'customer.invite.title': { es: 'Invita a un amigo', en: 'Invite a friend' },
  'customer.invite.sub': { es: 'Un pase de prueba por persona invitada, por WhatsApp, email o enlace.', en: 'One trial pass per invited person, by WhatsApp, email or link.' },
  'customer.invite.pass': { es: 'Pase de invitado', en: 'Guest pass' },
  'customer.invite.pass.title': { es: 'Una clase de regalo', en: 'One class, on us' },
  'customer.invite.pass.valid': { es: 'Válido {days} días · una vez por persona', en: 'Valid {days} days · once per person' },
  'customer.invite.to': { es: 'Para (opcional)', en: 'To (optional)' },
  'customer.invite.to.hint': { es: 'Número de WhatsApp o correo. Si lo dejas vacío, eliges el contacto en la app.', en: 'WhatsApp number or email. Leave empty to pick the contact in the app.' },
  'customer.invite.link': { es: 'Enlace', en: 'Link' },
  'customer.invite.sent': { es: 'Invitación enviada', en: 'Invite sent' },
  'customer.invite.subject': { es: 'Te invito a una clase en {studio}', en: 'I am inviting you to a class at {studio}' },
  'customer.invite.text.general': { es: 'Soy {name}. Te regalo una clase en {studio}: entra con este enlace.', en: 'It is {name}. Here is a free class at {studio}: use this link.' },
  'customer.invite.text.class': { es: 'Soy {name}. Ven conmigo a {title} el {when} en {studio}: tu primera clase va por mi cuenta.', en: 'It is {name}. Join me at {title} on {when} at {studio}: your first class is on me.' },
  'customer.invite.sentList': { es: 'Enviadas', en: 'Sent' },
  'customer.invite.sentList.empty': { es: 'Aún no has invitado a nadie.', en: 'You have not invited anyone yet.' },
  'customer.invite.status.sent': { es: 'Enviada', en: 'Sent' },
  'customer.invite.status.opened': { es: 'Abierta', en: 'Opened' },
  'customer.invite.reward': { es: 'Cuando tu invitado asiste, el estudio puede regalarte una clase (configurable).', en: 'When your guest attends, the studio may give you a class (configurable).' },

  // C-17 gift
  'customer.gift.title': { es: 'Tarjeta de regalo', en: 'Gift card' },
  'customer.gift.sub': { es: 'Regala una clase o el paquete de 12: destinatario, fecha y mensaje.', en: 'Give a class or the 12-class package: recipient, date and message.' },
  'customer.gift.preview': { es: 'Vista previa de la tarjeta', en: 'Card preview' },
  'customer.gift.for': { es: 'Para {name}', en: 'For {name}' },
  'customer.gift.amount': { es: 'Qué regalas', en: 'What you give' },
  'customer.gift.qty': { es: 'Cantidad', en: 'Quantity' },
  'customer.gift.qty.less': { es: 'Una menos', en: 'One fewer' },
  'customer.gift.qty.more': { es: 'Una más', en: 'One more' },
  'customer.gift.qty.err': { es: 'Elige entre 1 y {max} tarjetas.', en: 'Choose between 1 and {max} cards.' },
  'customer.gift.qty.hint': { es: 'Cada tarjeta lleva su propio código y se redime en recepción.', en: 'Each card has its own code and is redeemed at the front desk.' },
  'customer.gift.to': { es: 'Para quién', en: 'Recipient' },
  'customer.gift.contact': { es: 'WhatsApp o correo', en: 'WhatsApp or email' },
  'customer.gift.contact.hint': { es: 'Ahí llega la tarjeta.', en: 'Where the card arrives.' },
  'customer.gift.contact.err': { es: 'Escribe un WhatsApp válido o un correo.', en: 'Enter a valid WhatsApp number or email.' },
  'customer.gift.delivery': { es: 'Entrega', en: 'Delivery' },
  'customer.gift.date': { es: 'Fecha de entrega', en: 'Delivery date' },
  'customer.gift.date.hint': { es: 'Se envía a las 8:00 de ese día por email y WhatsApp.', en: 'Sent at 8:00 that day by email and WhatsApp.' },
  'customer.gift.date.past': { es: 'La fecha no puede ser pasada.', en: 'The date cannot be in the past.' },
  'customer.gift.message': { es: 'Mensaje', en: 'Message' },
  'customer.gift.design': { es: 'Diseño', en: 'Design' },
  'customer.gift.note': { es: 'Quien la recibe la redime en recepción de {studio}. Sin cargo por servicio.', en: 'The recipient redeems it at the {studio} front desk. No service fee.' },
  'customer.gift.cta': { es: 'Regalar {amount}', en: 'Gift {amount}' },
  'customer.gift.done.title': { es: 'Regalo programado', en: 'Gift scheduled' },
  'customer.gift.done.body': { es: 'Código {code} para {name}. Se entrega el {date} a las 8:00. Recibo enviado.', en: 'Code {code} for {name}. Delivered on {date} at 8:00. Receipt sent.' },

  // C-18 teachers
  'customer.teachers.title': { es: 'Profesores', en: 'Teachers' },
  'customer.teachers.sub': { es: 'Elige a la persona, no solo la hora.', en: 'Choose the person, not just the time slot.' },
  'customer.teachers.notFound': { es: 'Profesor no encontrado', en: 'Teacher not found' },
  'customer.teachers.portrait': { es: 'Retrato del profesor (pendiente)', en: 'Teacher portrait (pending)' },
  'customer.teachers.teaches': { es: 'Enseña', en: 'Teaches' },
  'customer.teachers.upcoming': { es: 'Próximas clases', en: 'Upcoming classes' },
  'customer.teachers.upcoming.empty': { es: 'Sin clases programadas esta semana.', en: 'No classes scheduled this week.' },
  'customer.teachers.ratingsNote': { es: 'Las valoraciones son privadas hasta que el estudio las active.', en: 'Ratings stay private until the studio enables them.' },

  // C-19 profile
  'customer.profile.title': { es: 'Perfil', en: 'Profile' },
  'customer.profile.changePhoto': { es: 'Cambiar foto', en: 'Change photo' },
  'customer.profile.photoTooBig': { es: 'La foto debe pesar menos de 1,5 MB.', en: 'The photo must be under 1.5 MB.' },
  'customer.profile.noPlan': { es: 'Sin plan', en: 'No plan' },
  'customer.profile.whatsapp.verify': { es: 'Verificar WhatsApp', en: 'Verify WhatsApp' },
  'customer.profile.whatsapp.verified': { es: 'WhatsApp verificado.', en: 'WhatsApp verified.' },
  'customer.profile.edit': { es: 'Editar perfil', en: 'Edit profile' },
  'customer.profile.saved': { es: 'Guardado.', en: 'Saved.' },
  'customer.profile.account': { es: 'Cuenta', en: 'Account' },
  'customer.profile.pay.sub': { es: 'Tarjeta, PSE, QR de Wompi', en: 'Card, PSE, Wompi QR' },
  'customer.profile.notifications': { es: 'Notificaciones', en: 'Notifications' },
  'customer.profile.notif.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.profile.notif.whatsapp.sub': { es: 'Recordatorios, cupos liberados, cancelaciones', en: 'Reminders, released spots, cancellations' },
  'customer.profile.notif.push': { es: 'Push', en: 'Push' },
  'customer.profile.notif.push.sub': { es: 'En este dispositivo', en: 'On this device' },
  'customer.profile.notif.email': { es: 'Email', en: 'Email' },
  'customer.profile.notif.email.sub': { es: 'Recibos y resúmenes', en: 'Receipts and summaries' },
  'customer.profile.language': { es: 'Idioma', en: 'Language' },
  'customer.profile.language.sub': { es: 'Por cuenta, no por dispositivo', en: 'Per account, not per device' },
  'customer.profile.review': { es: 'Deja una reseña', en: 'Leave a review' },
  'customer.profile.review.google': { es: 'Google', en: 'Google' },
  'customer.profile.review.instagram': { es: 'Instagram', en: 'Instagram' },
  'customer.profile.legal': { es: 'Legal', en: 'Legal' },
  'customer.profile.legal.terms': { es: 'Términos y condiciones', en: 'Terms and conditions' },
  'customer.profile.legal.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },
  'customer.profile.legal.law': { es: 'Ley 1581 de 2012 · Habeas Data', en: 'Ley 1581 de 2012 · Habeas Data' },
  'customer.profile.signOut': { es: 'Cerrar sesión', en: 'Sign out' },
  'customer.profile.delete': { es: 'Eliminar mi cuenta', en: 'Delete my account' },
  'customer.profile.delete.sub': { es: 'Se solicita en Cuenta y datos; lo financiero se conserva', en: 'Requested under Account & data; financial records are kept' },
  'customer.profile.delete.confirm.title': { es: '¿Eliminar tu cuenta?', en: 'Delete your account?' },

  // forms (shared by C-19, A-03, C-21, C-17)
  'customer.form.required': { es: 'Este campo es obligatorio.', en: 'This field is required.' },
  'customer.form.name': { es: 'Nombre', en: 'Name' },
  'customer.form.first': { es: 'Nombre', en: 'First name' },
  'customer.form.last': { es: 'Apellido', en: 'Last name' },
  'customer.form.email': { es: 'Correo', en: 'Email' },
  'customer.form.email.err': { es: 'Escribe un correo válido.', en: 'Enter a valid email.' },
  'customer.form.phone': { es: 'Teléfono', en: 'Phone' },
  'customer.form.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.form.whatsapp.hint': { es: 'Colombia {dial} por defecto. Ahí llegan recordatorios y cancelaciones.', en: 'Colombia {dial} by default. Reminders and cancellations go here.' },
  'customer.form.password': { es: 'Contraseña', en: 'Password' },
  'customer.form.password.hint': { es: 'Mínimo 8 caracteres. Sin reglas de composición.', en: 'At least 8 characters. No composition rules.' },
  'customer.form.password.err': { es: 'Mínimo 8 caracteres.', en: 'At least 8 characters.' },
  'customer.form.strength.0': { es: 'Muy corta', en: 'Too short' },
  'customer.form.strength.1': { es: 'Débil', en: 'Weak' },
  'customer.form.strength.2': { es: 'Aceptable', en: 'Okay' },
  'customer.form.strength.3': { es: 'Fuerte', en: 'Strong' },
  'customer.form.birthday': { es: 'Cumpleaños (opcional)', en: 'Birthday (optional)' },
  'customer.form.birthday.hint': { es: 'Para felicitarte.', en: 'So we can wish you well.' },
  'customer.form.emergency': { es: 'Contacto de emergencia', en: 'Emergency contact' },
  'customer.form.photo': { es: 'Foto de perfil', en: 'Profile photo' },
  'customer.form.photo.hint': { es: 'Ayuda a recepción a reconocerte. Puedes añadirla después.', en: 'Helps the front desk recognise you. You can add it later.' },
  'customer.form.photo.pick': { es: 'Tomar o elegir', en: 'Take or choose' },
  'customer.form.optional': { es: 'Opcional', en: 'Optional' },


  // C-23 events
  'customer.events.title': { es: 'Eventos', en: 'Events' },
  'customer.events.sub': { es: 'Baños de sonido, talleres y retiros.', en: 'Sound baths, workshops and retreats.' },
  'customer.events.spots': { es: 'cupos', en: 'spots' },
  'customer.events.notFound': { es: 'Evento no encontrado', en: 'Event not found' },
  'customer.events.photo': { es: 'Foto del evento · 4:5 (pendiente)', en: 'Event photo · 4:5 (pending)' },
  'customer.events.host': { es: 'Con {name}', en: 'With {name}' },
  'customer.events.price.public': { es: 'Precio general', en: 'Public price' },
  'customer.events.price.member': { es: 'Socios', en: 'Members' },
  'customer.events.bring': { es: 'Qué traer', en: 'What to bring' },
  'customer.events.friend': { es: 'Traer a un amigo', en: 'Bring a friend' },
  'customer.events.friend.sub': { es: 'Pase de invitado', en: 'Guest pass' },
  'customer.events.rsvp': { es: 'Reservar mi lugar', en: 'Reserve my place' },
  'customer.events.soldOut': { es: 'Agotado · lista de espera pronto', en: 'Sold out · waitlist soon' },
  'customer.events.going': { es: 'Vas a este evento', en: 'You are going' },
  'customer.events.going.body': { es: 'Te enviamos la confirmación por WhatsApp y email.', en: 'Confirmation sent by WhatsApp and email.' },
  'customer.events.cancel': { es: 'Cancelar', en: 'Cancel' },
  'customer.events.memberIncluded': { es: 'Incluido en tu membresía', en: 'Included in your membership' },
  'customer.events.policy': { es: 'Los eventos no consumen clases de tu paquete y tienen su propia política de cancelación.', en: 'Events do not use classes from your package and have their own cancellation policy.' },

  // C-24 notifications
  'customer.notifications.title': { es: 'Notificaciones', en: 'Notifications' },
  'customer.notifications.unread': { es: '{n} sin leer', en: '{n} unread' },
  'customer.notifications.markAll': { es: 'Marcar todo como leído', en: 'Mark all read' },
  'customer.notifications.today': { es: 'Hoy', en: 'Today' },
  'customer.notifications.earlier': { es: 'Antes', en: 'Earlier' },
  'customer.notifications.empty': { es: 'Nada todavía', en: 'Nothing yet' },
  'customer.notifications.empty.body': { es: 'Aquí verás lo que el estudio te envía por WhatsApp, email o push.', en: 'Everything the studio sends you by WhatsApp, email or push appears here.' },
  'customer.notifications.retention': { es: 'Se conservan 90 días', en: 'Kept for 90 days' },

  // C-25 more
  'customer.more.planPrompt': { es: 'Elegir plan', en: 'Pick a plan' },
  'customer.more.plans.sub': { es: 'Paquete de 12 clases, prueba e individual', en: '12-class package, trial and individual' },
  'customer.more.classes.sub': { es: 'Tu paquete, vencimiento y congelamiento', en: 'Your package, expiry and freeze' },
  'customer.more.rules.sub': { es: 'Qué traer · etiqueta · tour', en: 'What to bring · etiquette · tour' },
  'customer.more.whatsapp': { es: 'Escribir al estudio', en: 'WhatsApp the studio' },
  'customer.more.whatsapp.text': { es: 'Hola, soy {name}. Tengo una pregunta:', en: 'Hi, it is {name}. I have a question:' },
  'customer.more.whatsapp.textAnon': { es: 'Hola. Tengo una pregunta:', en: 'Hi. I have a question:' },
  'customer.more.visit': { es: 'Cómo llegar', en: 'Getting here' },
  'customer.more.hours': { es: 'Horario', en: 'Opening hours' },
  'customer.more.email': { es: 'Correo al estudio', en: 'Email the studio' },
  'customer.more.states': { es: 'Estados de ejemplo (dev)', en: 'Sample states (dev)' },
  'customer.more.authFlow': { es: 'Flujo de acceso', en: 'Auth flow' },


  // A-01 splash
  'customer.splash.line1': { es: 'La vida es', en: 'Life is' },
  'customer.splash.line2': { es: 'Un oasis en ti', en: 'An oasis within' },
  'customer.splash.loading': { es: 'Restaurando tu sesión…', en: 'Restoring your session…' },
  'customer.splash.ready': { es: 'Listo', en: 'Ready' },
  'customer.splash.continue': { es: 'Continuar', en: 'Continue' },

  // A-02 sign in
  'customer.signin.title': { es: 'Entrar', en: 'Sign in' },
  'customer.signin.sub': { es: 'Demo: elige un usuario o escribe su correo. La autenticación real llega con Supabase Auth.', en: 'Demo: pick a user or type their email. Real authentication arrives with Supabase Auth.' },
  'customer.signin.demo': { es: 'Usuarios demo', en: 'Demo users' },
  'customer.signin.emailHint': { es: 'Cualquier correo de usuario demo; cualquier contraseña.', en: 'Any demo user email; any password.' },
  'customer.signin.cta': { es: 'Entrar', en: 'Sign in' },
  'customer.signin.forgot': { es: 'Olvidé mi contraseña', en: 'Forgot my password' },
  'customer.signin.wrong': { es: 'Correo o contraseña incorrectos. Te quedan {n} intentos.', en: 'Wrong email or password. {n} attempts left.' },
  'customer.signin.or': { es: 'o', en: 'or' },
  'customer.signin.apple': { es: 'Continuar con Apple', en: 'Continue with Apple' },
  'customer.signin.google': { es: 'Continuar con Google', en: 'Continue with Google' },
  'customer.signin.biometric': { es: 'Desbloqueo biométrico', en: 'Biometric unlock' },
  'customer.signin.providersNote': { es: 'Llegan con Supabase Auth.', en: 'Coming with Supabase Auth.' },
  'customer.signin.new': { es: '¿Primera vez?', en: 'First time?' },
  'customer.signin.create': { es: 'Crear cuenta', en: 'Create account' },

  // A-03 sign up
  'customer.signup.title': { es: 'Crear cuenta', en: 'Create account' },
  'customer.signup.sub': { es: 'Lo mínimo que el estudio necesita. Dos minutos.', en: 'The minimum the studio needs. Two minutes.' },
  'customer.signup.step': { es: 'Paso {n} de {total}', en: 'Step {n} of {total}' },
  'customer.signup.emergency.why': { es: 'Lo pedimos ahora para que exista desde tu primera clase.', en: 'We ask now so it exists from your first class.' },
  'customer.signup.consent': { es: 'Acepto los', en: 'I accept the' },
  'customer.signup.and': { es: 'y la', en: 'and the' },
  'customer.signup.consent.err': { es: 'Necesitamos tu consentimiento para continuar.', en: 'We need your consent to continue.' },
  'customer.signup.dup': { es: 'Ya existe una cuenta con ese correo o WhatsApp', en: 'An account with that email or WhatsApp already exists' },
  'customer.signup.dup.body': { es: 'Entra con ella o recupera la contraseña.', en: 'Sign in with it or recover the password.' },
  'customer.signup.cta': { es: 'Continuar', en: 'Continue' },
  'customer.signup.have': { es: '¿Ya tienes cuenta?', en: 'Already have an account?' },

  // C-21 password reset
  'customer.reset.back': { es: 'Volver a entrar', en: 'Back to sign in' },
  'customer.reset.title': { es: 'Recuperar acceso', en: 'Recover access' },
  'customer.reset.sub': { es: 'Te enviamos un código de 6 dígitos por WhatsApp; email como alternativa.', en: 'We send a 6-digit code by WhatsApp; email as a fallback.' },
  'customer.reset.channel': { es: 'Canal', en: 'Channel' },
  'customer.reset.send': { es: 'Enviar código', en: 'Send code' },
  'customer.reset.privacy': { es: 'Si la cuenta existe, recibirás el código. El mensaje es igual en ambos casos.', en: 'If the account exists you will receive the code. The message is identical either way.' },
  'customer.reset.otp.title': { es: 'Escribe el código', en: 'Enter the code' },
  'customer.reset.otp.sub': { es: 'Enviado a {to}. Vale {min} minutos y se usa una vez.', en: 'Sent to {to}. Valid {min} minutes, single use.' },
  'customer.reset.demoCode': { es: 'Demo: el código es {code}.', en: 'Demo: the code is {code}.' },
  'customer.reset.codeInvalidated': { es: 'Tres intentos fallidos: el código se invalidó. Pide uno nuevo.', en: 'Three wrong attempts: the code was invalidated. Request a new one.' },
  'customer.reset.wrong': { es: 'Código incorrecto. Te quedan {n} intentos.', en: 'Wrong code. {n} attempts left.' },
  'customer.reset.resend': { es: 'Reenviar código', en: 'Resend code' },
  'customer.reset.resendIn': { es: 'Reenviar en {s} s', en: 'Resend in {s} s' },
  'customer.reset.useEmail': { es: 'Usar email en su lugar', en: 'Use email instead' },
  'customer.reset.useWhatsapp': { es: 'Usar WhatsApp en su lugar', en: 'Use WhatsApp instead' },
  'customer.reset.new.title': { es: 'Nueva contraseña', en: 'New password' },
  'customer.reset.save': { es: 'Guardar y entrar', en: 'Save and sign in' },
  'customer.reset.signOutOthers': { es: 'Al guardar, cerramos la sesión en tus otros dispositivos.', en: 'Saving signs you out on your other devices.' },
  'customer.reset.done.title': { es: 'Contraseña actualizada', en: 'Password updated' },
  'customer.reset.done.body': { es: 'Ya puedes entrar con la nueva contraseña.', en: 'You can now sign in with the new password.' },

  // E-04 locked
  'customer.locked.title': { es: 'Acceso en pausa', en: 'Sign-in paused' },
  'customer.locked.body': { es: 'Tras {n} intentos fallidos pausamos el acceso {min} minutos y avisamos por email al titular de la cuenta.', en: 'After {n} failed attempts we pause sign-in for {min} minutes and email the account holder.' },
  'customer.locked.wait': { es: 'para reintentar', en: 'to retry' },
  'customer.locked.recover': { es: 'Recuperar contraseña', en: 'Recover password' },
  'customer.locked.whatsapp': { es: 'Escribir al estudio', en: 'WhatsApp the studio' },
  'customer.locked.whatsappText': { es: 'Hola, no puedo entrar a mi cuenta.', en: 'Hi, I cannot sign in to my account.' },
  'customer.locked.security': { es: 'La recuperación no está limitada por esta pausa. El contador es del servidor: reinstalar la app no lo reinicia.', en: 'Recovery is not rate-limited by this pause. The countdown is server-side: reinstalling the app does not reset it.' },

  // 0008 · notifications table (C-24) + prefs
  'customer.notifications.open': { es: 'Abrir', en: 'Open' },
  'customer.notifications.via.in_app': { es: 'en la app', en: 'in app' },
  'customer.notifications.via.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.notifications.via.email': { es: 'Email', en: 'Email' },
  'customer.notifications.via.push': { es: 'Push', en: 'Push' },
  'customer.notifications.prefs.title': { es: 'Preferencias', en: 'Preferences' },
  'customer.notifications.prefs.sub': { es: 'Elige por canal qué quieres recibir. Lo importante de tus reservas siempre llega a esta bandeja.', en: 'Choose per channel what you want to receive. Anything critical about your bookings always reaches this inbox.' },
  'customer.notifications.prefs.byCategory': { es: 'Ajusta por canal y categoría', en: 'Tune by channel and category' },
  'customer.notifications.prefs.note': { es: 'Guardamos solo lo que cambias; lo demás queda activo.', en: 'We store only what you change; everything else stays on.' },
  'customer.notifications.channel.whatsapp': { es: 'WhatsApp', en: 'WhatsApp' },
  'customer.notifications.channel.email': { es: 'Email', en: 'Email' },
  'customer.notifications.channel.push': { es: 'Push', en: 'Push' },
  'customer.notifications.cat.bookings': { es: 'Reservas', en: 'Bookings' },
  'customer.notifications.cat.bookings.sub': { es: 'Confirmaciones, cambios y recordatorios de clase.', en: 'Confirmations, changes and class reminders.' },
  'customer.notifications.cat.waitlist': { es: 'Lista de espera', en: 'Waitlist' },
  'customer.notifications.cat.waitlist.sub': { es: 'Cuando se libera un cupo tuyo.', en: 'When a spot opens for you.' },
  'customer.notifications.cat.payments': { es: 'Pagos', en: 'Payments' },
  'customer.notifications.cat.payments.sub': { es: 'Recibos, cobros próximos y pagos rechazados.', en: 'Receipts, upcoming charges and declined payments.' },
  'customer.notifications.cat.events': { es: 'Eventos', en: 'Events' },
  'customer.notifications.cat.events.sub': { es: 'Talleres y baños de sonido nuevos.', en: 'New workshops and sound baths.' },
  'customer.notifications.cat.marketing': { es: 'Novedades', en: 'News' },
  'customer.notifications.cat.marketing.sub': { es: 'Noticias del club y promociones. Nunca afecta tus reservas.', en: 'Club news and offers. Never affects your bookings.' },
  // 0008 · invites table (C-16)
  'customer.invite.status.joined': { es: 'Se unió', en: 'Joined' },
  'customer.invite.status.rewarded': { es: 'Clase regalada', en: 'Class given' },
  'customer.invite.channel.whatsapp': { es: 'Enviada por WhatsApp', en: 'Sent by WhatsApp' },
  'customer.invite.channel.email': { es: 'Enviada por email', en: 'Sent by email' },
  'customer.invite.channel.link': { es: 'Enlace compartido', en: 'Link shared' },
  // 0008 · payment_methods table (C-05)
  'customer.pay.add': { es: 'Guardar', en: 'Save' },
  'customer.pay.saved.default': { es: 'Predeterminado', en: 'Default' },
  'customer.pay.saved.makeDefault': { es: 'Usar por defecto', en: 'Make default' },
  'customer.pay.saved.remove': { es: 'Quitar método', en: 'Remove method' },
  'customer.pay.saved.expires': { es: 'Vence {date}', en: 'Expires {date}' },
  'customer.pay.kind.card': { es: 'Tarjeta', en: 'Card' },
  'customer.pay.kind.pse': { es: 'PSE · débito bancario', en: 'PSE · bank debit' },
  'customer.pay.kind.transfer': { es: 'Transferencia', en: 'Transfer' },
  'customer.pay.kind.cash': { es: 'Efectivo', en: 'Cash' },
  // 0008 · events + content tables (C-23, C-14/C-15)
  'customer.events.empty': { es: 'Aún no hay eventos', en: 'No events yet' },
  'customer.events.empty.body': { es: 'El estudio publica talleres y baños de sonido aquí.', en: 'The studio publishes workshops and sound baths here.' },
  'customer.faq.empty': { es: 'Sin preguntas publicadas', en: 'No published questions' },
  'customer.faq.empty.body': { es: 'El estudio está preparando esta sección.', en: 'The studio is preparing this section.' },
  // 0012 · A-06 legal library (site + in-app) and the media slots
  'customer.legal.kind.terms': { es: 'Términos y condiciones', en: 'Terms & conditions' },
  'customer.legal.kind.privacy': { es: 'Política de privacidad', en: 'Privacy policy' },
  'customer.legal.kind.waiver': { es: 'Exoneración y declaración de salud', en: 'Waiver & health declaration' },
  'customer.legal.kind.cancellation': { es: 'Política de cancelaciones', en: 'Cancellation policy' },
  'customer.legal.kind.refunds': { es: 'Política de reembolsos', en: 'Refund policy' },
  'customer.legal.kind.house-rules': { es: 'Reglas de casa', en: 'House rules' },
  'customer.legal.status.published': { es: 'Vigente', en: 'In force' },
  'customer.legal.status.draft': { es: 'Borrador', en: 'Draft' },
  'customer.legal.effective': { es: 'Vigente desde el {date}', en: 'In force since {date}' },
  'customer.legal.effective.draft': { es: 'Propuesta para el {date}', en: 'Proposed for {date}' },
  'customer.legal.counsel': { es: 'Texto redactado por el estudio y pendiente de revisión por abogado. Cita la Ley 1581 de 2012 (datos personales) y la Ley 1480 de 2011 (consumidor); no reemplaza asesoría legal.', en: 'Written by the studio and pending counsel review. It cites Ley 1581 de 2012 (personal data) and Ley 1480 de 2011 (consumer law); it is not legal advice.' },
  'customer.legal.versions': { es: 'Versiones', en: 'Versions' },
  'customer.legal.accepted': { es: 'Aceptaste esta versión el {date} ({channel}).', en: 'You accepted this version on {date} ({channel}).' },
  'customer.legal.acceptedOther': { es: 'Aceptaste la versión {v} el {date}. Esta versión es distinta.', en: 'You accepted version {v} on {date}. This version is a different one.' },
  'customer.legal.notAccepted': { es: 'Todavía no has aceptado este documento.', en: 'You have not accepted this document yet.' },
  'customer.legal.accept': { es: 'Aceptar esta versión', en: 'Accept this version' },
  'customer.legal.channel.app': { es: 'en la app', en: 'in the app' },
  'customer.legal.channel.website': { es: 'en la web', en: 'on the website' },
  'customer.legal.channel.front_desk': { es: 'en recepción', en: 'at the front desk' },
  'customer.legal.channel.import': { es: 'registro anterior', en: 'earlier record' },
  'customer.legal.others': { es: 'Otros documentos:', en: 'Other documents:' },
  'customer.legal.print': { es: 'Imprimir o guardar en PDF', en: 'Print or save as PDF' },
  'customer.legal.liveNumbers': { es: 'Los números salen de la configuración del estudio', en: 'The numbers come from the studio settings' },
  'customer.legal.notFound': { es: 'Documento no encontrado', en: 'Document not found' },
  'customer.legal.notFound.body': { es: 'Puede que el enlace sea antiguo. Los documentos vigentes están en Más → Legal.', en: 'The link may be old. The documents in force are under More → Legal.' },
  'customer.legal.token.pending': { es: '(pendiente)', en: '(pending)' },
  'customer.legal.token.noShowFee': { es: ' y se cobra la tarifa de no-show de {amount}', en: ' and the {amount} no-show fee is charged' },
  'customer.media.pending': { es: 'arte pendiente', en: 'art pending' },

  // C-26 Cuenta y datos (0019)
  'customer.account.title': { es: 'Cuenta y datos', en: 'Account & data' },
  'customer.account.sub': { es: 'Tus derechos sobre tu información: verla, llevártela, decidir y borrar.', en: 'Your rights over your information: see it, take it with you, decide and delete.' },
  'customer.account.consents': { es: 'Consentimientos', en: 'Consents' },
  'customer.account.consent.marketingWa': { es: 'Novedades por WhatsApp', en: 'News on WhatsApp' },
  'customer.account.consent.marketingEmail': { es: 'Novedades por email', en: 'News by email' },
  'customer.account.consent.marketing.sub': { es: 'Eventos, talleres y promociones. Lo transaccional (reservas, pagos) siempre llega.', en: 'Events, workshops and offers. Transactional messages (bookings, payments) always arrive.' },
  'customer.account.consent.processing': { es: 'Tratamiento de datos', en: 'Data processing' },
  'customer.account.consent.processing.on': { es: 'Aceptaste la política de privacidad v{v} el {date}', en: 'You accepted the privacy policy v{v} on {date}' },
  'customer.account.consent.processing.off': { es: 'Todavía no has aceptado la política de privacidad vigente', en: 'You have not accepted the current privacy policy yet' },
  'customer.legal.notAccepted.short': { es: 'Pendiente', en: 'Pending' },
  'customer.account.export': { es: 'Una copia de tus datos', en: 'A copy of your data' },
  'customer.account.export.body': { es: 'Descarga en un archivo JSON todo lo que el estudio guarda de ti: perfil, reservas, pagos y facturas, clases de tus paquetes, consentimientos, notificaciones y preferencias. Es tuyo.', en: 'Download a JSON file with everything the studio keeps about you: profile, bookings, payments and invoices, the classes of your packages, consents, notifications and preferences. It is yours.' },
  'customer.account.export.cta': { es: 'Descargar mis datos', en: 'Download my data' },
  'customer.account.export.done': { es: 'Listo: tu archivo se está descargando.', en: 'Done: your file is downloading.' },
  'customer.account.delete': { es: 'Eliminar la cuenta', en: 'Delete the account' },
  'customer.account.delete.sub': { es: 'Dos pasos. Te explicamos qué se conserva antes de confirmar.', en: 'Two steps. We explain what is kept before you confirm.' },
  'customer.account.delete.what': { es: 'Qué pasa al eliminar tu cuenta', en: 'What happens when you delete your account' },
  'customer.account.delete.what.body': { es: 'Tu perfil se anonimiza (nombre, foto, cumpleaños, contacto de emergencia y notas desaparecen), tus notificaciones se borran y pierdes el acceso a la app. Lo que la ley nos obliga a conservar se queda, sin tu nombre.', en: 'Your profile is anonymised (name, photo, birthday, emergency contact and notes go away), your notifications are deleted and you lose access to the app. What the law obliges us to keep stays, without your name.' },
  'customer.account.delete.keep.invoices': { es: 'Se conservan: las facturas y el historial de pagos, por el plazo de conservación contable que exige la ley, ligados a un identificador anónimo.', en: 'Kept: invoices and payment history, for the accounting retention period the law requires, linked to an anonymous identifier.' },
  'customer.account.delete.keep.profile': { es: 'Se anonimiza: tu perfil y tu cuenta de acceso. Nadie del estudio podrá volver a asociar esos pagos contigo.', en: 'Anonymised: your profile and your login account. Nobody at the studio can link those payments back to you.' },
  'customer.account.delete.keep.access': { es: 'Termina: el acceso a la app, las reservas futuras (se cancelan) y las clases que te queden en tu paquete.', en: 'Ends: access to the app, future bookings (cancelled) and any classes left in your package.' },
  'customer.account.delete.keep.time': { es: 'Tiempo: el estudio procesa la solicitud en máximo quince días hábiles y te confirma por correo. Hasta entonces puedes cancelarla aquí.', en: 'Timing: the studio processes the request within fifteen business days at most and confirms by email. Until then you can cancel it here.' },
  'customer.account.delete.reason': { es: 'Motivo (opcional)', en: 'Reason (optional)' },
  'customer.account.delete.reason.ph': { es: 'Nos ayuda a mejorar. No es obligatorio.', en: 'It helps us improve. Not required.' },
  'customer.account.delete.understood': { es: 'Entiendo qué se conserva y qué termina', en: 'I understand what is kept and what ends' },
  'customer.account.delete.next': { es: 'Continuar', en: 'Continue' },
  'customer.account.delete.confirm2.title': { es: 'Última confirmación', en: 'Last confirmation' },
  'customer.account.delete.confirm2.body': { es: 'Vas a pedirle a {name} que elimine tu cuenta. Es la última confirmación.', en: 'You are about to ask {name} to delete your account. This is the last confirmation.' },
  'customer.account.delete.cta': { es: 'Sí, solicitar la eliminación', en: 'Yes, request the deletion' },
  'customer.account.delete.sent': { es: 'Solicitud recibida. Te confirmamos por correo cuando esté hecha.', en: 'Request received. We confirm by email once it is done.' },
  'customer.account.delete.cancelled': { es: 'Solicitud cancelada. Tu cuenta sigue como estaba.', en: 'Request cancelled. Your account stays as it was.' },
  'customer.account.delete.requestedOn': { es: 'Solicitada el {date}', en: 'Requested on {date}' },
  'customer.account.delete.pending.body': { es: 'Tu solicitud está en cola. El estudio la procesa en máximo quince días hábiles; mientras tanto puedes seguir usando la app o cancelarla.', en: 'Your request is queued. The studio processes it within fifteen business days at most; meanwhile you can keep using the app or cancel it.' },
  'customer.account.delete.processing.body': { es: 'El estudio ya está procesando tu solicitud. Ya no se puede cancelar desde aquí; si cambiaste de idea, escríbenos.', en: 'The studio is already processing your request. It can no longer be cancelled from here; if you changed your mind, write to us.' },
  'customer.account.delete.retention': { es: 'Las facturas y el historial de pagos se conservan anonimizados por obligación legal; el perfil y el acceso se eliminan.', en: 'Invoices and payment history are kept anonymised by legal obligation; the profile and the access are removed.' },
  'customer.account.delete.cancel': { es: 'Cancelar la solicitud', en: 'Cancel the request' },
  'customer.account.status.requested': { es: 'Pendiente', en: 'Pending' },
  'customer.account.status.processing': { es: 'En proceso', en: 'Processing' },
  'customer.account.status.done': { es: 'Hecha', en: 'Done' },
  'customer.account.status.cancelled': { es: 'Cancelada', en: 'Cancelled' },
};
