import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'hub.title': { es: 'Hub de pruebas', en: 'Testing hub' },
  'hub.subtitle': { es: 'Elige una experiencia. Todo lo que ves usa datos demo; nada es real todavía.', en: 'Pick an experience. Everything here runs on demo data; nothing is real yet.' },
  'hub.session': { es: 'Estás probando como', en: 'You are testing as' },
  'hub.card.website': { es: 'Sitio web', en: 'Website' },
  'hub.card.website.body': { es: 'Lo que ve cualquiera antes de entrar: filosofía, modalidades, horario, profesores, planes, contacto.', en: 'What anyone sees before signing in: philosophy, modalities, schedule, teachers, plans, contact.' },
  'hub.card.customer': { es: 'App de clientes', en: 'Customer app' },
  'hub.card.customer.body': { es: 'Móvil primero. Inicio con intención del día, clases de hoy, reservas y planes.', en: 'Mobile first. Home with daily intention, today’s classes, bookings and plans.' },
  'hub.card.teacher': { es: 'App de profesores', en: 'Teacher app' },
  'hub.card.teacher.body': { es: 'Mis clases, asistencia y nómina.', en: 'My classes, attendance and payroll.' },
  'hub.card.staff': { es: 'Staff y administración', en: 'Staff & admin' },
  'hub.card.staff.body': { es: 'Escritorio primero. Elige el rol para ver su experiencia.', en: 'Desktop first. Pick the role to see its experience.' },
  'hub.card.manual': { es: 'Manual de operaciones', en: 'Operations manual' },
  'hub.card.manual.body': { es: 'Cómo funciona el club en persona y en el software, por rol.', en: 'How the club runs in person and in software, by role.' },
  'hub.card.docs': { es: 'Documentación y changelog', en: 'Documentation & changelog' },
  'hub.card.docs.body': { es: 'Cada prompt, cada respuesta, cada cambio. Con capturas.', en: 'Every prompt, every response, every change. With screenshots.' },
  'hub.card.dev': { es: 'Desarrollo', en: 'Developer' },
  'hub.card.dev.body': { es: 'Tokens, biblioteca de componentes, specs, tablas y editor de layout.', en: 'Tokens, component library, specs, tables and layout editor.' },
  'hub.open': { es: 'Abrir', en: 'Open' },
  'hub.signin': { es: 'Entrar o crear cuenta', en: 'Sign in or create an account' },
  'hub.enterAs': { es: 'Entrar como {name}', en: 'Enter as {name}' },
  'hub.devHint': { es: 'Con modo dev activo, cada página muestra un chip “spec” y Ctrl+. abre el inspector.', en: 'With dev mode on, every page shows a “spec” chip and Ctrl+. opens the inspector.' },
  'hub.wireframe': { es: 'Wireframe', en: 'Wireframe' },
  'hub.dev.tokens': { es: 'Tokens (D-01)', en: 'Tokens (D-01)' },
  'hub.dev.components': { es: 'Componentes (D-02)', en: 'Components (D-02)' },
  'hub.dev.specs': { es: 'Specs', en: 'Specs' },
  'hub.dev.tables': { es: 'Tablas (M-03)', en: 'Tables (M-03)' },
  'hub.dev.layout': { es: 'Editor de layout', en: 'Layout editor' },
  'hub.dev.kb': { es: 'Kanban y changelog (K-01)', en: 'Kanban & changelog (K-01)' },
  'hub.footer': { es: 'HoyOS v0 · pruebas privadas · datos demo', en: 'HoyOS v0 · private testing · demo data' },
};
