import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import type { StringTable } from '../../i18n/types';
import { EVERYONE } from '../../auth/roles';
import { DocsBrowser } from './DocsBrowser';
import { docsSpec } from './specs';

export const strings: StringTable = {
  'docs.title': { es: 'Documentación', en: 'Documentation' },
  'docs.all': { es: 'Todos', en: 'All' },
  'docs.group.changelog': { es: 'Changelog', en: 'Changelog' },
  'docs.group.prompts': { es: 'Registro de prompts', en: 'Prompt log' },
  'docs.group.screenshots': { es: 'Capturas', en: 'Screenshots' },
  'docs.kanban.intro': { es: 'Un carril por equipo; columnas Backlog / Doing / Done. Se edita en docs/kanban.md en el mismo turno que el trabajo.', en: 'One lane per team; Backlog / Doing / Done columns. Edited in docs/kanban.md in the same turn as the work.' },
  'docs.kanban.general': { es: 'General', en: 'General' },
  'docs.changelog.intro': { es: '{n} entradas, la más reciente primero. Formato K-01: versión, fecha, intención, decisión, alternativa rechazada, archivos.', en: '{n} entries, newest first. K-01 format: version, date, intent, decision, alternative rejected, files.' },
  'docs.prompts.intro': { es: '{n} prompts, el más reciente primero. Cada uno guarda el texto exacto y la respuesta.', en: '{n} prompts, newest first. Each keeps the exact text and the response.' },
  'docs.prompts.prompt': { es: 'Prompt', en: 'Prompt' },
  'docs.prompts.response': { es: 'Respuesta', en: 'Response' },
  'docs.prompts.noResponse': { es: 'Sin sección de respuesta todavía.', en: 'No response section yet.' },
  'docs.screenshots.intro': { es: 'Generadas con npm run screenshots en docs/screenshots/<código>/<idioma>-<ancho>[-dark].jpg.', en: 'Generated by npm run screenshots into docs/screenshots/<code>/<lang>-<width>[-dark].jpg.' },
  'docs.screenshots.empty': { es: 'Aún no hay capturas. Ejecuta npm run screenshots al final de la sesión y haz commit de los PNG.', en: 'No screenshots yet. Run npm run screenshots at the end of the session and commit the PNGs.' },
};
const el = () => h(DocsBrowser);

export const routes: RouteDef[] = [
  { path: '/docs', element: el(), spec: docsSpec, roles: EVERYONE, surface: 'docs', layout: 'desktop', nav: { labelKey: 'core.nav.docs', icon: '❡', order: 1 } },
  { path: '/docs/*', element: el(), spec: docsSpec, roles: EVERYONE, surface: 'docs', layout: 'desktop' },
];
