import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'teacher.home.title': { es: 'Mis clases', en: 'My classes' },
  'teacher.home.notLinked': { es: 'Este usuario no está vinculado a un perfil de profesor. Elige uno para revisar la app.', en: 'This user is not linked to a teacher profile. Pick one to review the app.' },
  'teacher.home.viewAs': { es: 'Ver como profesor', en: 'View as teacher' },
  'teacher.home.next': { es: 'Próxima clase', en: 'Next class' },
  'teacher.home.noNext': { es: 'No tienes clases próximas', en: 'No upcoming classes' },
  'teacher.home.noNext.body': { es: 'Cuando coordinación te asigne una clase aparecerá aquí.', en: 'When the coordinator assigns you a class it will show here.' },
  'teacher.home.openRoster': { es: 'Abrir lista', en: 'Open roster' },
  'teacher.home.arrived': { es: '{n} llegaron', en: '{n} arrived' },
  'teacher.home.arrivedOf': { es: '{n} de {total} llegaron', en: '{n} of {total} arrived' },
  'teacher.home.today': { es: 'Clases hoy', en: 'Classes today' },
  'teacher.home.taughtMonth': { es: 'Dictadas este mes', en: 'Taught this month' },
  'teacher.home.payroll': { es: 'Nómina estimada', en: 'Estimated payroll' },
  'teacher.home.payroll.hint': { es: 'clases dictadas × tarifa', en: 'classes taught × rate' },
  'teacher.home.emptyToday': { es: 'Hoy no dictas. Buen día para practicar.', en: 'No classes today. Good day to practise.' },
  'teacher.home.week': { es: 'Próximos 7 días', en: 'Next 7 days' },
  'teacher.home.empty': { es: 'No tienes más clases esta semana.', en: 'No more classes this week.' },
  'teacher.home.sub': { es: 'Pedir reemplazo', en: 'Request substitute' },
  'teacher.home.sub.body': { es: 'Coordinación recibe la solicitud por WhatsApp y busca quién cubra la clase.', en: 'The coordinator gets the request on WhatsApp and finds cover.' },
  'teacher.home.sub.class': { es: 'Clase', en: 'Class' },
  'teacher.home.sub.reason': { es: 'Motivo', en: 'Reason' },
  'teacher.home.sub.rule': { es: 'Avisa con 12 h de antelación cuando puedas', en: 'Give 12 h notice when you can' },
  'teacher.home.sub.send': { es: 'Enviar solicitud', en: 'Send request' },
  'teacher.home.sub.sent': { es: 'Solicitud enviada', en: 'Request sent' },
  'teacher.home.sub.sent.body': { es: 'Quedó en el registro de actividad. Coordinación te confirma por WhatsApp.', en: 'Logged in the activity log. The coordinator confirms on WhatsApp.' },

  'teacher.class.notFound': { es: 'Clase no encontrada', en: 'Class not found' },
  'teacher.class.notFound.body': { es: 'Puede haber sido eliminada o el enlace es antiguo.', en: 'It may have been removed or the link is old.' },
  'teacher.class.present': { es: '{n} de {total} presentes', en: '{n} of {total} present' },
  'teacher.class.window.open': { es: 'Asistencia abierta', en: 'Attendance open' },
  'teacher.class.window.locked': { es: 'Asistencia bloqueada', en: 'Attendance locked' },
  'teacher.class.window.rule': { es: 'Se marca de 15 min antes hasta 2 h después. Luego, coordinación.', en: 'Mark from 15 min before to 2 h after. Later, ask the coordinator.' },
  'teacher.class.window.override': { es: 'Fuera de ventana: estás marcando como coordinación.', en: 'Outside the window: you are marking as coordinator.' },
  'teacher.class.locked.early': { es: 'Aún no abre: 15 min antes de la clase.', en: 'Not open yet: 15 min before class.' },
  'teacher.class.locked.late': { es: 'Cerró 2 h después de la clase. Pide a coordinación.', en: 'Closed 2 h after class. Ask the coordinator.' },
  'teacher.class.locked.notMine': { es: 'Esta clase la dicta otro profesor.', en: 'Another teacher runs this class.' },
  'teacher.class.markAll': { es: 'Todos presentes', en: 'All present' },
  'teacher.class.complete': { es: 'Cerrar clase', en: 'Close class' },
  'teacher.class.roster': { es: 'Lista', en: 'Roster' },
  'teacher.class.emptyRoster': { es: 'Nadie reservado todavía', en: 'Nobody booked yet' },
  'teacher.class.present.mark': { es: 'Presente', en: 'Present' },
  'teacher.class.absent.mark': { es: 'Ausente', en: 'Absent' },
  'teacher.class.notes': { es: 'Notas de la clase', en: 'Class notes' },
  'teacher.class.notes.ph': { es: '¿Cómo estuvo? Lesiones, energía, música…', en: 'How did it go? Injuries, energy, music…' },
  'teacher.class.notes.hint': { es: 'Internas. Coordinación las ve en el registro.', en: 'Internal. The coordinator sees them in the log.' },
  'teacher.class.notes.add': { es: 'Guardar nota', en: 'Save note' },
  'teacher.class.notes.empty': { es: 'Sin notas todavía.', en: 'No notes yet.' },

  'teacher.payroll.title': { es: 'Nómina', en: 'Payroll' },
  'teacher.payroll.classes': { es: 'Clases dictadas', en: 'Classes taught' },
  'teacher.payroll.subs': { es: '{n} reemplazos', en: '{n} substitutions' },
  'teacher.payroll.rate': { es: 'Tarifa por clase', en: 'Rate per class' },
  'teacher.payroll.total': { es: 'Total del mes', en: 'Month total' },
  'teacher.payroll.total.period': { es: 'Total de la quincena', en: 'Period total' },
  'teacher.payroll.closes': { es: 'cierra el {date}', en: 'run closes {date}' },
  'teacher.payroll.empty': { es: 'Sin clases dictadas este mes', en: 'No classes taught this month' },
  'teacher.payroll.empty.body': { es: 'Solo cuentan las clases cerradas (completadas).', en: 'Only closed (completed) classes count.' },
  'teacher.payroll.sub': { es: 'Reemplazo', en: 'Substitution' },
  'teacher.payroll.students': { es: '{n} alumnos', en: '{n} students' },

  'teacher.profile.title': { es: 'Mi perfil', en: 'My profile' },
  'teacher.profile.name': { es: 'Nombre público', en: 'Public name' },
  'teacher.profile.photo': { es: 'La foto la sube coordinación desde Contenido (marcador hasta tener las fotos reales).', en: 'The coordinator uploads photos from Content (placeholder until real assets land).' },
  'teacher.profile.bio': { es: 'Bio', en: 'Bio' },
  'teacher.profile.bio.en.hint': { es: 'Opcional: si falta, se usa el español.', en: 'Optional: Spanish is used when missing.' },
  'teacher.profile.specialties': { es: 'Especialidades', en: 'Specialties' },
  'teacher.profile.rate': { es: 'Tarifa por clase', en: 'Rate per class' },
  'teacher.profile.rate.readonly': { es: 'Solo lectura', en: 'Read only' },
  'teacher.profile.preview': { es: 'Así te ven en la web y la app', en: 'How the website and app show you' },
  'teacher.profile.review': { es: 'Los cambios pasan por coordinación antes de publicarse.', en: 'Changes go through the coordinator before publishing.' },
  'teacher.profile.saved': { es: 'Enviado a revisión.', en: 'Sent for review.' },
  'teacher.profile.submit': { es: 'Enviar cambios', en: 'Submit changes' },

  'teacher.class.reviews': { es: 'Reseñas de esta clase', en: 'Reviews of this class' },
  'teacher.class.reviews.count': { es: '{n} reseñas', en: '{n} reviews' },
  'teacher.class.reviews.none': { es: 'Sin reseñas todavía', en: 'No reviews yet' },
  'teacher.class.reviews.note': { es: 'Promedio de las reseñas de los alumnos (C-10). Solo lectura y anónimo salvo que el alumno firme.', en: 'Average of the students’ reviews (C-10). Read-only and anonymous unless the student signs it.' },
  // 0012 · S-03 payroll reads payroll_runs / payroll_lines
  'teacher.payroll.state.estimate': { es: 'Estimado', en: 'Estimate' },
  'teacher.payroll.state.estimate.body': { es: 'Finanzas todavía no genera la corrida del mes. Este total sale de tus clases cerradas × tu tarifa.', en: 'Finance has not generated this month’s run yet. This total comes from your closed classes × your rate.' },
  'teacher.payroll.state.draft': { es: 'Borrador', en: 'Draft' },
  'teacher.payroll.state.draft.body': { es: 'La corrida existe y está en revisión de finanzas. Puede cambiar con bonos o ajustes.', en: 'The run exists and finance is reviewing it. It can still change with bonuses or adjustments.' },
  'teacher.payroll.state.approved': { es: 'Aprobada', en: 'Approved' },
  'teacher.payroll.state.approved.body': { es: 'Aprobada por finanzas. El pago sale en los próximos días.', en: 'Approved by finance. Payment goes out in the next few days.' },
  'teacher.payroll.state.paid': { es: 'Pagada', en: 'Paid' },
  'teacher.payroll.state.paid.body': { es: 'Liquidada. Si algo no cuadra, escríbenos: la corrección va como ajuste en la siguiente.', en: 'Settled. If something is off, write to us: the correction goes as an adjustment in the next run.' },
  'teacher.payroll.rate.hint': { es: 'la fija coordinación', en: 'set by the coordinator' },
  'teacher.payroll.paidOn': { es: 'pagada el {date}', en: 'paid {date}' },
  'teacher.payroll.breakdown': { es: 'Clase por clase', en: 'Class by class' },
  'teacher.payroll.fromTimetable': { es: 'Clase del horario', en: 'Timetable class' },
  'teacher.payroll.kind.bonus': { es: 'Bono', en: 'Bonus' },
  'teacher.payroll.kind.adjustment': { es: 'Ajuste', en: 'Adjustment' },
  'teacher.payroll.kind.class': { es: 'Clase', en: 'Class' },
  'teacher.payroll.kind.manual': { es: 'Especial', en: 'Special' },
  'teacher.payroll.manual.hint': { es: 'pago acordado con recepción por un Especial (evento privado, clase privada, sesión de grupo)', en: 'payout agreed with the desk for a Special (private event, private class, group session)' },
  'teacher.home.specials': { es: 'Especiales', en: 'Specials' },
  'teacher.home.specials.hint': { es: 'Salas reservadas contigo fuera del horario: eventos privados, clases privadas, sesiones de grupo. El pago aparece en Nómina como línea "Especial".', en: 'Rooms booked with you outside the timetable: private events, private classes, group sessions. The payout shows in Payroll as an "Especial" line.' },
  'teacher.home.specials.empty': { es: 'No tienes especiales reservados.', en: 'No specials booked with you.' },
  'teacher.home.specials.payout': { es: 'pago {amount}', en: 'payout {amount}' },
  'teacher.home.specials.unpaid': { es: 'pago por definir', en: 'payout to be set' },
  'teacher.payroll.method': { es: 'Cómo te pagamos', en: 'How you get paid' },
  'teacher.payroll.method.on': { es: 'Cuenta registrada: {brand} {last4}.', en: 'Account on file: {brand} {last4}.' },
  'teacher.payroll.method.none': { es: 'No tienes una cuenta registrada. Pídele a finanzas que la registre para recibir por dispersión.', en: 'You have no account on file. Ask finance to register it so you can be paid by dispersion.' },
  'teacher.payroll.method.run': { es: 'Esta corrida se paga por {method}.', en: 'This run is paid by {method}.' },
  'teacher.payroll.method.hint': { es: 'El medio se decide cuando finanzas cierra la corrida.', en: 'The method is decided when finance closes the run.' },
  'teacher.payroll.methodKind.wompi': { es: 'Wompi', en: 'Wompi' },
  'teacher.payroll.methodKind.transfer': { es: 'transferencia', en: 'transfer' },
  'teacher.payroll.methodKind.cash': { es: 'efectivo', en: 'cash' },
  'teacher.payroll.methodKind.card': { es: 'tarjeta', en: 'card' },
  'teacher.payroll.methodKind.pse': { es: 'PSE', en: 'PSE' },
  'teacher.payroll.methodKind.nequi': { es: 'Nequi', en: 'Nequi' },
  'teacher.payroll.history': { es: 'Corridas anteriores', en: 'Earlier runs' },
  'teacher.payroll.historyLine': { es: '{n} clases', en: '{n} classes' },
  'teacher.payroll.download': { es: 'Descargar extracto (PDF)', en: 'Download statement (PDF)' },
  'teacher.payroll.ask': { es: 'Preguntar por este extracto', en: 'Ask about this statement' },
  'teacher.payroll.ask.text': { es: 'Hola, tengo una pregunta sobre mi nómina de {period} (total {total}).', en: 'Hi, I have a question about my {period} payroll (total {total}).' },
  'teacher.payroll.runBy': { es: 'La nómina la corre finanzas del estudio · Wompi simulado', en: 'Payroll is run by the studio’s finance team · Wompi simulated' },
};
