/**
 * The hub map contract — schema `hoy.hub-map/1`.
 *
 * One machine-readable description of everything HoyOS has, by role and by device, published at
 * `{baseUrl}hub-map.json` (generated by `scripts/gen-hub-map.mjs` on every build). Other hosts — the
 * aluzina studio OS, the between-gigs company OS and hoy's own testing hub — read it and draw the hub
 * through their own lens. Pure types: no React, no runtime code. Documented in
 * `docs/reference/hub-map.md`; a breaking change bumps the schema id to `hoy.hub-map/2`.
 */
export type Bi = { es: string; en: string };
/** How a host should draw the page: phone = app screen 390x844; tablet 768x1024; desktop 1280x800; page = a tall scrolling website page (390 wide, full length); sheet = a document/markdown page (docs, manual). */
export type HubDevice = 'phone' | 'tablet' | 'desktop' | 'page' | 'sheet';
export type HubBand = 'outside' | 'team' | 'build';
export type HubLensId = 'aluzina' | 'between-gigs' | 'standalone';
export type ThumbKey = 'es-phone' | 'en-phone' | 'es-desktop' | 'en-desktop' | 'es-phone-dark' | 'en-phone-dark' | 'es-desktop-dark' | 'en-desktop-dark';
export type ShotKey = 'es-390' | 'en-390' | 'es-1280' | 'en-1280' | 'es-390-full' | 'en-390-full';
/** URLs relative to `product.baseUrl`. A key is present only when the file is published. */
export interface HubShots { thumbs: Partial<Record<ThumbKey, string>>; full: Partial<Record<ShotKey, string>>; }
export interface HubRole {
  /** hoy Role id: customer | public | teacher | front_desk | coordinator | finance | admin | super_admin | maintenance */
  id: string;
  label: Bi; description: Bi;
  /** outside = customers/public/teachers, team = staff/admin, build = docs/dev */
  band: HubBand;
  /** ROLE_HOME route */
  home: string;
  /** The role's primary device. */
  device: HubDevice;
  demoUser?: { id: string; firstName: string };
  /** Figure look hint for hosts: 'customer' | 'teacher' | 'frontdesk' | 'coordinator' | 'finance' | 'admin' | 'superadmin' | 'public' | 'maintenance' */
  look: string;
  /** Two desk props from this vocabulary: laptop phone clipboard tape contract calculator plans ruler sketchbook pencils samples swatches board stamp hardhat tablet book keys mug rating */
  props: [string, string];
}
/** One per hub card (the 13 HUB_SURFACES) — the thing a role "enters". */
export interface HubExperience {
  id: string; code: string; label: Bi; purpose: Bi;
  /** Owning role (mat) + every role allowed in. */
  roleId: string; roles: string[];
  /** `url` = baseUrl + '#' + route */
  band: HubBand; device: HubDevice; route: string; url: string;
  featured?: boolean; secondary?: { label: Bi; route: string };
  /** Every page code inside this experience, in nav order. */
  pageCodes: string[];
  /** Of the experience's entry page. */
  shots: HubShots;
}
/** A sub-mat: the group a page sits in inside its experience (e.g. the customer app's Book / Pay / Account / Sign in). `order` sorts groups within an experience, ascending. Ids are stable across releases; labels are copy. */
export interface HubGroup { id: string; label: Bi; order: number; }
/** Every route that has a code (one entry per code; `route` is the code's first route). */
export interface HubPage {
  code: string; route: string; name: Bi; purpose: Bi; surface: string; roles: string[];
  experienceId: string; device: HubDevice; status: 'built' | 'stub'; actions: string[]; shots: HubShots;
  /** Since 0028, additive: the sub-mat this page belongs to inside its experience. Absent only if a host reads an older file. */
  group?: HubGroup;
}
export interface HubTool { id: string; code: string; label: Bi; purpose: Bi; route: string; url: string; device: 'desktop'; shots: HubShots; }
export interface HubLensHint { title: Bi; framing: Bi; groupBy: 'role' | 'experience' | 'surface'; showTools: boolean; entry: string; }
export interface HubMap {
  schema: 'hoy.hub-map/1'; generatedAt: string;
  product: { id: 'hoy'; name: Bi; tagline: Bi; version: string; baseUrl: string; hubRoute: string; brand: { accent: string; wordmark?: string } };
  /** pattern: '{baseUrl}#{route}?as={role}&lang={lang}&theme={theme}&dev=0&live=0' — exactly what src/app/frameSession.ts frameUrl() produces; hosts substitute and iframe it. */
  embed: { pattern: string; note: Bi };
  roles: HubRole[]; experiences: HubExperience[]; pages: HubPage[]; tools: HubTool[];
  lenses: Record<HubLensId, HubLensHint>;
}
